/*
 Highcharts JS v8.1.0 (2020-05-12)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(n){c(n);c.Highcharts=n;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function n(c,f,h,k){c.hasOwnProperty(f)||(c[f]=k.apply(null,h))}c=c?c._modules:{};n(c,"annotations/eventEmitterMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,f){var h=f.addEvent,k=f.fireEvent,
d=f.inArray,b=f.objectEach,x=f.pick,B=f.removeEvent;return{addEvents:function(){var a=this,e=function(e){h(e,"mousedown",function(g){a.onMouseDown(g)})};e(this.graphic.element);(a.labels||[]).forEach(function(a){a.options.useHTML&&a.graphic.text&&e(a.graphic.text.element)});b(a.options.events,function(e,g){var l=function(l){"click"===g&&a.cancelClick||e.call(a,a.chart.pointer.normalize(l),a.target)};if(-1===d(g,a.nonDOMEvents||[]))a.graphic.on(g,l);else h(a,g,l)});if(a.options.draggable&&(h(a,"drag",
a.onDrag),!a.graphic.renderer.styledMode)){var q={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[a.options.draggable]};a.graphic.css(q);(a.labels||[]).forEach(function(a){a.options.useHTML&&a.graphic.text&&a.graphic.text.css(q)})}a.isUpdating||k(a,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(a){var e=this,b=e.chart.pointer;a.preventDefault&&a.preventDefault();if(2!==a.button){a=
b.normalize(a);var d=a.chartX;var g=a.chartY;e.cancelClick=!1;e.chart.hasDraggedAnnotation=!0;e.removeDrag=h(c.doc,"mousemove",function(a){e.hasDragged=!0;a=b.normalize(a);a.prevChartX=d;a.prevChartY=g;k(e,"drag",a);d=a.chartX;g=a.chartY});e.removeMouseUp=h(c.doc,"mouseup",function(a){e.cancelClick=e.hasDragged;e.hasDragged=!1;e.chart.hasDraggedAnnotation=!1;k(x(e.target,e),"afterUpdate");e.onMouseUp(a)})}},onMouseUp:function(a){var e=this.chart;a=this.target||this;var b=e.options.annotations;e=e.annotations.indexOf(a);
this.removeDocEvents();b[e]=a.options},onDrag:function(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop)){var e=this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(e.y=0);"y"===this.options.draggable&&(e.x=0);this.points.length?this.translate(e.x,e.y):(this.shapes.forEach(function(a){a.translate(e.x,e.y)}),this.labels.forEach(function(a){a.translate(e.x,e.y)}));this.redraw(!1)}},mouseMoveToRadians:function(a,e,b){var d=a.prevChartY-b,g=a.prevChartX-
e;b=a.chartY-b;a=a.chartX-e;this.chart.inverted&&(e=g,g=d,d=e,e=a,a=b,b=e);return Math.atan2(b,a)-Math.atan2(d,g)},mouseMoveToTranslation:function(a){var e=a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;if(this.chart.inverted){var b=a;a=e;e=b}return{x:e,y:a}},mouseMoveToScale:function(a,e,b){e=(a.chartX-e||1)/(a.prevChartX-e||1);a=(a.chartY-b||1)/(a.prevChartY-b||1);this.chart.inverted&&(b=a,a=e,e=b);return{x:e,y:a}},destroy:function(){this.removeDocEvents();B(this);this.hcEvents=null}}});n(c,"annotations/ControlPoint.js",
[c["parts/Utilities.js"],c["annotations/eventEmitterMixin.js"]],function(c,f){var h=c.merge,k=c.pick;return function(){function d(b,d,c,a){this.addEvents=f.addEvents;this.graphic=void 0;this.mouseMoveToRadians=f.mouseMoveToRadians;this.mouseMoveToScale=f.mouseMoveToScale;this.mouseMoveToTranslation=f.mouseMoveToTranslation;this.onDrag=f.onDrag;this.onMouseDown=f.onMouseDown;this.onMouseUp=f.onMouseUp;this.removeDocEvents=f.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=b;this.target=d;this.options=
c;this.index=k(c.index,a)}d.prototype.setVisibility=function(b){this.graphic.attr("visibility",b?"visible":"hidden");this.options.visible=b};d.prototype.render=function(){var b=this.chart,d=this.options;this.graphic=b.renderer.symbol(d.symbol,0,0,d.width,d.height).add(b.controlPointsGroup).css(d.style);this.setVisibility(d.visible);this.addEvents()};d.prototype.redraw=function(b){this.graphic[b?"animate":"attr"](this.options.positioner.call(this,this.target))};d.prototype.destroy=function(){f.destroy.call(this);
this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};d.prototype.update=function(b){var d=this.chart,c=this.target,a=this.index;b=h(!0,this.options,b);this.destroy();this.constructor(d,c,b,a);this.render(d.controlPointsGroup);this.redraw()};return d}()});n(c,"annotations/MockPoint.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,f){var h=f.defined,k=f.fireEvent;return function(){function d(b,d,f){this.y=this.x=this.plotY=this.plotX=this.isInside=
void 0;this.mock=!0;this.series={visible:!0,chart:b,getPlotBox:c.Series.prototype.getPlotBox};this.target=d||null;this.options=f;this.applyOptions(this.getOptions())}d.fromPoint=function(b){return new d(b.series.chart,null,{x:b.x,y:b.y,xAxis:b.series.xAxis,yAxis:b.series.yAxis})};d.pointToPixels=function(b,d){var c=b.series,a=c.chart,e=b.plotX,f=b.plotY;a.inverted&&(b.mock?(e=b.plotY,f=b.plotX):(e=a.plotWidth-b.plotY,f=a.plotHeight-b.plotX));c&&!d&&(b=c.getPlotBox(),e+=b.translateX,f+=b.translateY);
return{x:e,y:f}};d.pointToOptions=function(b){return{x:b.x,y:b.y,xAxis:b.series.xAxis,yAxis:b.series.yAxis}};d.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};d.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};d.prototype.applyOptions=function(b){this.command=b.command;this.setAxis(b,"x");this.setAxis(b,"y");this.refresh()};d.prototype.setAxis=function(b,d){d+="Axis";b=b[d];var f=this.series.chart;this.series[d]=
b instanceof c.Axis?b:h(b)?f[d][b]||f.get(b):null};d.prototype.toAnchor=function(){var b=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(b[0]=this.plotY,b[1]=this.plotX);return b};d.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};d.prototype.isInsidePlot=function(){var b=this.plotX,d=this.plotY,c=this.series.xAxis,a=this.series.yAxis,e={x:b,y:d,isInsidePlot:!0};c&&(e.isInsidePlot=h(b)&&0<=b&&b<=c.len);a&&(e.isInsidePlot=e.isInsidePlot&&h(d)&&0<=d&&d<=a.len);k(this.series.chart,
"afterIsInsidePlot",e);return e.isInsidePlot};d.prototype.refresh=function(){var b=this.series,d=b.xAxis;b=b.yAxis;var c=this.getOptions();d?(this.x=c.x,this.plotX=d.toPixels(c.x,!0)):(this.x=null,this.plotX=c.x);b?(this.y=c.y,this.plotY=b.toPixels(c.y,!0)):(this.y=null,this.plotY=c.y);this.isInside=this.isInsidePlot()};d.prototype.translate=function(b,d,c,a){this.hasDynamicOptions()||(this.plotX+=c,this.plotY+=a,this.refreshOptions())};d.prototype.scale=function(b,d,c,a){if(!this.hasDynamicOptions()){var e=
this.plotY*a;this.plotX=(1-c)*b+this.plotX*c;this.plotY=(1-a)*d+e;this.refreshOptions()}};d.prototype.rotate=function(b,d,c){if(!this.hasDynamicOptions()){var a=Math.cos(c);c=Math.sin(c);var e=this.plotX,f=this.plotY;e-=b;f-=d;this.plotX=e*a-f*c+b;this.plotY=e*c+f*a+d;this.refreshOptions()}};d.prototype.refreshOptions=function(){var b=this.series,d=b.xAxis;b=b.yAxis;this.x=this.options.x=d?this.options.x=d.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=b?b.toValue(this.plotY,!0):this.plotY};
return d}()});n(c,"annotations/controllable/controllableMixin.js",[c["annotations/ControlPoint.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,f,h,k){var d=k.isObject,b=k.isString,x=k.merge,u=k.splat;return{init:function(a,e,b){this.annotation=a;this.chart=a.chart;this.options=e;this.points=[];this.controlPoints=[];this.index=b;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var a=
this.options;return a.points||a.point&&u(a.point)},attrsFromOptions:function(a){var e=this.constructor.attrsMap,b={},d,g=this.chart.styledMode;for(d in a){var l=e[d];!l||g&&-1!==["fill","stroke","stroke-width"].indexOf(l)||(b[l]=a[d])}return b},anchor:function(a){var e=a.series.getPlotBox();a=a.mock?a.toAnchor():h.prototype.getAnchor.call({chart:a.series.chart},a);a={x:a[0]+(this.options.x||0),y:a[1]+(this.options.y||0),height:a[2]||0,width:a[3]||0};return{relativePosition:a,absolutePosition:x(a,
{x:a.x+e.translateX,y:a.y+e.translateY})}},point:function(a,e){if(a&&a.series)return a;e&&null!==e.series||(d(a)?e=new f(this.chart,this,a):b(a)?e=this.chart.get(a)||null:"function"===typeof a&&(e=a.call(e,this),e=e.series?e:new f(this.chart,this,a)));return e},linkPoints:function(){var a=this.getPointsOptions(),e=this.points,b=a&&a.length||0,d;for(d=0;d<b;d++){var g=this.point(a[d],e[d]);if(!g){e.length=0;return}g.mock&&g.refresh();e[d]=g}return e},addControlPoints:function(){var a=this.options.controlPoints;
(a||[]).forEach(function(e,b){e=x(this.options.controlPointOptions,e);e.index||(e.index=b);a[b]=e;this.controlPoints.push(new c(this.chart,this,e))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(a){this.controlPoints.forEach(function(a){a.render()})},redraw:function(a){this.controlPoints.forEach(function(b){b.redraw(a)})},transform:function(a,b,d,c,g){if(this.chart.inverted){var l=b;b=d;d=l}this.points.forEach(function(l,e){this.transformPoint(a,b,d,c,g,e)},this)},transformPoint:function(a,
b,d,c,g,l){var e=this.points[l];e.mock||(e=this.points[l]=f.fromPoint(e));e[a](b,d,c,g)},translate:function(a,b){this.transform("translate",null,null,a,b)},translatePoint:function(a,b,d){this.transformPoint("translate",null,null,a,b,d)},translateShape:function(a,b){var d=this.annotation.chart,e=this.annotation.userOptions,g=d.annotations.indexOf(this.annotation);d=d.options.annotations[g];this.translatePoint(a,b,0);d[this.collection][this.index].point=this.options.point;e[this.collection][this.index].point=
this.options.point},rotate:function(a,b,d){this.transform("rotate",a,b,d)},scale:function(a,b,d,c){this.transform("scale",a,b,d,c)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(b){b.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=
null)},update:function(a){var b=this.annotation;a=x(!0,this.options,a);var d=this.graphic.parentGroup;this.destroy();this.constructor(b,a);this.render(d);this.redraw()}}});n(c,"annotations/controllable/markerMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,f){var h=f.addEvent,k=f.defined,d=f.merge,b=f.objectEach,x=f.uniqueKey,u={arrow:{tagName:"marker",render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},
"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};c.SVGRenderer.prototype.addMarker=function(a,b){var e={id:a},c={stroke:b.color||"none",fill:b.color||"rgba(0, 0, 0, 0.75)"};e.children=b.children.map(function(a){return d(c,a)});b=this.definition(d(!0,{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},b,e));b.id=a;return b};f=function(a){return function(b){this.attr(a,
"url(#"+b+")")}};f={markerEndSetter:f("marker-end"),markerStartSetter:f("marker-start"),setItemMarkers:function(a){var b=a.options,c=a.chart,f=c.options.defs,g=b.fill,l=k(g)&&"none"!==g?g:b.stroke;["markerStart","markerEnd"].forEach(function(g){var e=b[g],p;if(e){for(p in f){var t=f[p];if(e===t.id&&"marker"===t.tagName){var m=t;break}}m&&(e=a[g]=c.renderer.addMarker((b.id||x())+"-"+m.id,d(m,{color:l})),a.attr(g,e.attr("id")))}})}};h(c.Chart,"afterGetContainer",function(){this.options.defs=d(u,this.options.defs||
{});b(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return f});n(c,"annotations/controllable/ControllablePath.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/controllable/markerMixin.js"],c["parts/Utilities.js"]],function(c,f,h,k){var d=k.extend;k=k.merge;var b="rgba(192,192,192,"+(f.svg?.0001:.002)+")";f=function(b,d,a){this.init(b,d,a);this.collection="shapes"};f.attrsMap={dashStyle:"dashstyle",
strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};k(!0,f.prototype,c,{type:"path",setMarkers:h.setItemMarkers,toD:function(){var b=this.options.d;if(b)return"function"===typeof b?b.call(this):b;b=this.points;var d=b.length,a=d,c=b[0],f=a&&this.anchor(c).absolutePosition,h=0,g=[];if(f)for(g.push(["M",f.x,f.y]);++h<d&&a;)c=b[h],a=c.command||"L",f=this.anchor(c).absolutePosition,"M"===a?g.push([a,f.x,f.y]):"L"===a?g.push([a,f.x,f.y]):"Z"===a&&g.push([a]),a=c.series.visible;return a?
this.chart.renderer.crispLine(g,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return c.shouldBeDrawn.call(this)||!!this.options.d},render:function(f){var k=this.options,a=this.attrsFromOptions(k);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(a).add(f);k.className&&this.graphic.addClass(k.className);this.tracker=this.annotation.chart.renderer.path([["M",0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(f);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",
stroke:b,fill:b,"stroke-width":this.graphic.strokeWidth()+2*k.snap});c.render.call(this);d(this.graphic,{markerStartSetter:h.markerStartSetter,markerEndSetter:h.markerEndSetter});this.setMarkers(this)},redraw:function(b){var d=this.toD(),a=b?"animate":"attr";d?(this.graphic[a]({d:d}),this.tracker[a]({d:d})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=!!d;c.redraw.call(this,b)}});return f});n(c,"annotations/controllable/ControllableRect.js",
[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],c["parts/Utilities.js"]],function(c,f,h){h=h.merge;var k=function(d,b,c){this.init(d,b,c);this.collection="shapes"};k.attrsMap=h(f.attrsMap,{width:"width",height:"height"});h(!0,k.prototype,c,{type:"rect",translate:c.translateShape,render:function(d){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(b).add(d);c.render.call(this)},redraw:function(d){var b=
this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[d?"animate":"attr"]({x:b.x,y:b.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,d)}});return k});n(c,"annotations/controllable/ControllableCircle.js",[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],c["parts/Utilities.js"]],function(c,f,h){h=h.merge;var k=function(d,b,c){this.init(d,b,c);this.collection="shapes"};
k.attrsMap=h(f.attrsMap,{r:"r"});h(!0,k.prototype,c,{type:"circle",translate:c.translateShape,render:function(d){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(b).add(d);c.render.call(this)},redraw:function(d){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[d?"animate":"attr"]({x:b.x,y:b.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,d)},setRadius:function(d){this.options.r=
d}});return k});n(c,"annotations/controllable/ControllableLabel.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,f,h,k,d){var b=d.extend,x=d.format,u=d.isNumber,a=d.merge,e=d.pick,q=function(a,g,b){this.init(a,g,b);this.collection="labels"};q.shapesWithoutBackground=["connector"];q.alignedPosition=function(a,b){var g=a.align,d=a.verticalAlign,c=(b.x||0)+(a.x||0),e=(b.y||0)+(a.y||0),
f,h;"right"===g?f=1:"center"===g&&(f=2);f&&(c+=(b.width-(a.width||0))/f);"bottom"===d?h=1:"middle"===d&&(h=2);h&&(e+=(b.height-(a.height||0))/h);return{x:Math.round(c),y:Math.round(e)}};q.justifiedOptions=function(a,b,d,c){var g=d.align,l=d.verticalAlign,e=b.box?0:b.padding||0,f=b.getBBox();b={align:g,verticalAlign:l,x:d.x,y:d.y,width:b.width,height:b.height};d=c.x-a.plotLeft;var p=c.y-a.plotTop;c=d+e;0>c&&("right"===g?b.align="left":b.x=-c);c=d+f.width-e;c>a.plotWidth&&("left"===g?b.align="right":
b.x=a.plotWidth-c);c=p+e;0>c&&("bottom"===l?b.verticalAlign="top":b.y=-c);c=p+f.height-e;c>a.plotHeight&&("top"===l?b.verticalAlign="bottom":b.y=a.plotHeight-c);return b};q.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};a(!0,q.prototype,c,{translatePoint:function(a,b){c.translatePoint.call(this,a,b,0)},translate:function(a,b){var g=this.annotation.chart,d=this.annotation.userOptions,c=g.annotations.indexOf(this.annotation);
c=g.options.annotations[c];g.inverted&&(g=a,a=b,b=g);this.options.x+=a;this.options.y+=b;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=this.options.y;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y},render:function(a){var b=this.options,d=this.attrsFromOptions(b),e=b.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(d).add(a);this.annotation.chart.styledMode||
("contrast"===e.color&&(e.color=this.annotation.chart.renderer.getContrast(-1<q.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;c.render.call(this)},redraw:function(b){var a=this.options,d=this.text||a.format||a.text,e=this.graphic,f=this.points[0];e.attr({text:d?x(d,f.getLabelConfig(),this.annotation.chart):a.formatter.call(f,this)});a=this.anchor(f);
(d=this.position(a))?(e.alignAttr=d,d.anchorX=a.absolutePosition.x,d.anchorY=a.absolutePosition.y,e[b?"animate":"attr"](d)):e.attr({x:0,y:-9999});e.placed=!!d;c.redraw.call(this,b)},anchor:function(){var a=c.anchor.apply(this,arguments),b=this.options.x||0,d=this.options.y||0;a.absolutePosition.x-=b;a.absolutePosition.y-=d;a.relativePosition.x-=b;a.relativePosition.y-=d;return a},position:function(a){var d=this.graphic,c=this.annotation.chart,f=this.points[0],r=this.options,w=a.absolutePosition,t=
a.relativePosition;if(a=f.series.visible&&h.prototype.isInsidePlot.call(f)){if(r.distance)var m=k.prototype.getPosition.call({chart:c,distance:e(r.distance,16)},d.width,d.height,{plotX:t.x,plotY:t.y,negative:f.negative,ttBelow:f.ttBelow,h:t.height||t.width});else r.positioner?m=r.positioner.call(this):(f={x:w.x,y:w.y,width:0,height:0},m=q.alignedPosition(b(r,{width:d.width,height:d.height}),f),"justify"===this.options.overflow&&(m=q.alignedPosition(q.justifiedOptions(c,d,r,m),f)));r.crop&&(r=m.x-
c.plotLeft,f=m.y-c.plotTop,a=c.isInsidePlot(r,f)&&c.isInsidePlot(r+d.width,f+d.height))}return a?m:null}});f.SVGRenderer.prototype.symbols.connector=function(a,b,d,c,e){var g=e&&e.anchorX;e=e&&e.anchorY;var f=d/2;if(u(g)&&u(e)){var l=[["M",g,e]];var v=b-e;0>v&&(v=-c-v);v<d&&(f=g<a+d/2?v:d-v);e>b+c?l.push(["L",a+f,b+c]):e<b?l.push(["L",a+f,b]):g<a?l.push(["L",a,b+c/2]):g>a+d&&l.push(["L",a+d,b+c/2])}return l||[]};return q});n(c,"annotations/controllable/ControllableImage.js",[c["annotations/controllable/ControllableLabel.js"],
c["annotations/controllable/controllableMixin.js"],c["parts/Utilities.js"]],function(c,f,h){h=h.merge;var k=function(d,b,c){this.init(d,b,c);this.collection="shapes"};k.attrsMap={width:"width",height:"height",zIndex:"zIndex"};h(!0,k.prototype,f,{type:"image",translate:f.translateShape,render:function(d){var b=this.attrsFromOptions(this.options),c=this.options;this.graphic=this.annotation.chart.renderer.image(c.src,0,-9E9,c.width,c.height).attr(b).add(d);this.graphic.width=c.width;this.graphic.height=
c.height;f.render.call(this)},redraw:function(d){var b=this.anchor(this.points[0]);if(b=c.prototype.position.call(this,b))this.graphic[d?"animate":"attr"]({x:b.x,y:b.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b;f.redraw.call(this,d)}});return k});n(c,"annotations/annotations.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableRect.js"],c["annotations/controllable/ControllableCircle.js"],
c["annotations/controllable/ControllablePath.js"],c["annotations/controllable/ControllableImage.js"],c["annotations/controllable/ControllableLabel.js"],c["annotations/eventEmitterMixin.js"],c["annotations/MockPoint.js"],c["annotations/ControlPoint.js"]],function(c,f,h,k,d,b,n,B,a,e,q){var u=f.addEvent,g=f.defined,l=f.destroyObjectProperties,p=f.erase,r=f.extend,w=f.find,t=f.fireEvent,m=f.merge,v=f.pick,C=f.splat;f=f.wrap;var z=c.Chart.prototype,y=function(){function c(a,b){this.annotation=void 0;
this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=m(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)}c.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();
this.addLabels();this.setLabelCollector()};c.prototype.getLabelsAndShapesOptions=function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=C(b[d]).map(function(b,c){return m(a[d][c],b)}))});return c};c.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);m(!0,this.options.shapes[b],a.options)},this)};c.prototype.addLabels=function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);m(!0,this.options.labels[b],a.options)},
this)};c.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};c.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]};c.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,
y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};c.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};c.prototype.setOptions=function(a){this.options=m(this.defaultOptions,a)};c.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());
this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);h.redraw.call(this,a)};c.prototype.redrawItems=function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)};c.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};c.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);
this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();h.render.call(this)};c.prototype.setVisibility=function(a){var b=this.options;a=v(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};c.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};
h.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};c.prototype.destroy=function(){var b=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;p(b.labelCollectors,this.labelCollector);a.destroy.call(this);h.destroy.call(this);l(this,b)};c.prototype.remove=function(){return this.chart.removeAnnotation(this)};c.prototype.update=function(a,b){var c=this.chart,d=this.getLabelsAndShapesOptions(this.userOptions,
a),g=c.annotations.indexOf(this);a=m(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.constructor(c,a);c.options.annotations[g]=a;this.isUpdating=!0;v(b,!0)&&c.redraw();t(this,"afterUpdate");this.isUpdating=!1};c.prototype.initShape=function(a,b){a=m(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new c.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b};c.prototype.initLabel=function(a,b){a=m(this.options.labelOptions,
{controlPointOptions:this.options.controlPointOptions},a);b=new B(this,a,b);b.itemType="label";this.labels.push(b);return b};c.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(v(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};c.prototype.adjustVisibility=function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():
c.hide()};c.prototype.destroyItem=function(a){p(this[a.itemType+"s"],a);a.destroy()};c.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};c.ControlPoint=q;c.MockPoint=e;c.shapesMap={rect:k,circle:d,path:b,image:n};c.types={};return c}();m(!0,y.prototype,h,a,m(y.prototype,{nonDOMEvents:["add","afterUpdate","drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",
borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return g(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},
events:{},zIndex:6}}));c.extendAnnotation=function(a,b,c,d){b=b||y;m(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=m(a.prototype.defaultOptions,d||{})};r(z,{initAnnotation:function(a){a=new (y.types[a.type]||y)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);v(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:w(b,function(b){return b.options.id===
a});c&&(t(c,"remove"),p(this.options.annotations,c.options),p(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});z.collectionsWithUpdate.push("annotations");z.collectionsWithInit.annotations=[z.addAnnotation];z.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();
a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();u(a,"redraw",a.drawAnnotations);u(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});f(c.Pointer.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))});return c.Annotation=y});n(c,"mixins/navigation.js",[],function(){return{initUpdate:function(c){c.navigation||(c.navigation=
{updates:[],update:function(c,h){this.updates.forEach(function(f){f.update.call(f.context,c,h)})}})},addUpdate:function(c,f){f.navigation||this.initUpdate(f);f.navigation.updates.push({update:c,context:f})}}});n(c,"annotations/navigationBindings.js",[c["annotations/annotations.src.js"],c["mixins/navigation.js"],c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,f,h,k){function d(b){var c=b.prototype.defaultOptions.events&&b.prototype.defaultOptions.events.click;l(!0,b.prototype.defaultOptions.events,
{click:function(b){var d=this,g=d.chart.navigationBindings,e=g.activeAnnotation;c&&c.click.call(d,b);e!==d?(g.deselectAnnotation(),g.activeAnnotation=d,d.setControlPointsVisibility(!0),a(g,"showPopup",{annotation:d,formType:"annotation-toolbar",options:g.annotationToFields(d),onSubmit:function(a){var b={};"remove"===a.actionType?(g.activeAnnotation=!1,g.chart.removeAnnotation(d)):(g.fieldsToOptions(a.fields,b),g.deselectAnnotation(),a=b.typeOptions,"measure"===d.options.type&&(a.crosshairY.enabled=
0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),d.update(b))}})):(g.deselectAnnotation(),a(g,"closePopup"));b.activeAnnotation=!0}})}var b=k.addEvent,n=k.attr,u=k.format,a=k.fireEvent,e=k.isArray,q=k.isFunction,A=k.isNumber,g=k.isObject,l=k.merge,p=k.objectEach,r=k.pick,w=h.doc,t=h.win,m=function(){function c(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=w.getElementsByClassName(this.options.bindingsClassName||
"")}c.prototype.initEvents=function(){var a=this,c=a.chart,d=a.container,g=a.options;a.boundClassNames={};p(g.bindings||{},function(b){a.boundClassNames[b.className]=b});[].forEach.call(d,function(c){a.eventsToUnbind.push(b(c,"click",function(b){var d=a.getButtonEvents(c,b);d&&a.bindingsButtonClick(d.button,d.events,b)}))});p(g.events||{},function(c,d){q(c)&&a.eventsToUnbind.push(b(a,d,c))});a.eventsToUnbind.push(b(c.container,"click",function(b){!c.cancelClick&&c.isInsidePlot(b.chartX-c.plotLeft,
b.chartY-c.plotTop)&&a.bindingsChartClick(this,b)}));a.eventsToUnbind.push(b(c.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))};c.prototype.initUpdate=function(){var a=this;f.addUpdate(function(b){a.update(b)},this.chart)};c.prototype.bindingsButtonClick=function(b,c,d){var g=this.chart;this.selectedButtonElement&&(a(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&g.removeAnnotation(this.currentUserDetails),
this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=c;this.selectedButtonElement=b;a(this,"selectButton",{button:b});c.init&&c.init.call(this,b,d);(c.start||c.steps)&&g.renderer.boxWrapper.addClass("highcharts-draw-mode")};c.prototype.bindingsChartClick=function(b,c){b=this.chart;var d=this.selectedButton;b=b.renderer.boxWrapper;var g;if(g=this.activeAnnotation&&!c.activeAnnotation&&c.target.parentNode){a:{g=c.target;var e=t.Element.prototype,f=e.matches||e.msMatchesSelector||e.webkitMatchesSelector,
l=null;if(e.closest)l=e.closest.call(g,".highcharts-popup");else{do{if(f.call(g,".highcharts-popup"))break a;g=g.parentElement||g.parentNode}while(null!==g&&1===g.nodeType)}g=l}g=!g}g&&(a(this,"closePopup"),this.deselectAnnotation());d&&d.start&&(this.nextEvent?(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,d.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]:(a(this,"deselectButton",{button:this.selectedButtonElement}),b.removeClass("highcharts-draw-mode"),
d.end&&d.end.call(this,c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=d.start.call(this,c),d.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]):(a(this,"deselectButton",{button:this.selectedButtonElement}),b.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,d.end&&d.end.call(this,c,this.currentUserDetails))))};c.prototype.bindingsContainerMouseMove=function(a,
b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};c.prototype.fieldsToOptions=function(a,b){p(a,function(a,c){var d=parseFloat(a),g=c.split("."),e=b,f=g.length-1;!A(d)||a.match(/px/g)||c.match(/format/g)||(a=d);""!==a&&"undefined"!==a&&g.forEach(function(b,c){var d=r(g[c+1],"");f===c?e[b]=a:(e[b]||(e[b]=d.match(/\d/g)?[]:{}),e=e[b])})});return b};c.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=
!1)};c.prototype.annotationToFields=function(a){function b(c,d,f,h){if(f&&-1===t.indexOf(d)&&(0<=(f.indexOf&&f.indexOf(d))||f[d]||!0===f))if(e(c))h[d]=[],c.forEach(function(a,c){g(a)?(h[d][c]={},p(a,function(a,g){b(a,g,l[d],h[d][c])})):b(a,0,l[d],h[d])});else if(g(c)){var k={};e(h)?(h.push(k),k[d]={},k=k[d]):h[d]=k;p(c,function(a,c){b(a,c,0===d?f:l[d],k)})}else"format"===d?h[d]=[u(c,a.labels[0].points[0]).toString(),"text"]:e(h)?h.push([c,v(c)]):h[d]=[c,v(c)]}var d=a.options,f=c.annotationsEditable,
l=f.nestedOptions,v=this.utils.getFieldType,h=r(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),t=c.annotationsNonEditable[d.langKey]||[],k={langKey:d.langKey,type:h};p(d,function(a,c){"typeOptions"===c?(k[c]={},p(d[c],function(a,d){b(a,d,l,k[c],!0)})):b(a,c,f[h],k)});return k};c.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var d;c&&((d=n(c,"class"))&&(b=b.concat(d.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,
c!==a););return b};c.prototype.getButtonEvents=function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d};c.prototype.update=function(a){this.options=l(!0,this.options,a);this.removeEvents();this.initEvents()};c.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};c.prototype.destroy=function(){this.removeEvents()};c.annotationsEditable={nestedOptions:{labelOptions:["style",
"format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],
label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:[]};c.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};return c}();m.prototype.utils={updateRectSize:function(a,b){var c=b.chart,d=b.options.typeOptions,g=c.pointer.getCoordinates(a);a=g.xAxis[0].value-d.point.x;d=d.point.y-g.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?
d:a,height:c.inverted?a:d}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};h.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new m(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};b(h.Chart,"load",function(){this.initNavigationBindings()});b(h.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});
b(m,"deselectButton",function(){this.selectedButtonElement=null});b(c,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});h.Annotation&&(d(c),p(c.types,function(a){d(a)}));h.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",
labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=
this.chart.options.navigation;return this.chart.addAnnotation(l({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5}]},b.annotationsOptions,b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,d=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var g=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(g?c-a.chartX:d-a.chartX,2)+Math.pow(g?
d-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a);a=this.chart.options.navigation;var c=b.xAxis[0].value;b=b.yAxis[0].value;return this.chart.addAnnotation(l({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b}]}]},a.annotationsOptions,a.bindings.rectangleAnnotation.annotationsOptions))},
steps:[function(a,b){var c=b.options.shapes[0].points,d=this.chart.pointer.getCoordinates(a);a=d.xAxis[0].value;d=d.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=d;c[3].y=d;b.update({shapes:[{points:c}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(l({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,
y:a.yAxis[0].value},overflow:"none",crop:!0}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return m});n(c,"annotations/popup.js",[c["annotations/navigationBindings.js"],c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,f,h){var k=h.addEvent,d=h.createElement,b=h.defined,n=h.isArray,u=h.isObject,a=h.isString,e=h.objectEach,q=h.pick;h=h.wrap;var A=/\d/g;h(f.Pointer.prototype,"onContainerMouseDown",function(b,c){var d=c.target&&c.target.className;
a(d)&&0<=d.indexOf("highcharts-popup-field")||b.apply(this,Array.prototype.slice.call(arguments,1))});f.Popup=function(a,b){this.init(a,b)};f.Popup.prototype={init:function(a,b){this.container=d("div",{className:"highcharts-popup"},null,a);this.lang=this.getLangpack();this.iconsURL=b;this.addCloseBtn()},addCloseBtn:function(){var a=this;var b=d("div",{className:"highcharts-popup-close"},null,this.container);b.style["background-image"]="url("+this.iconsURL+"close.svg)";["click","touchstart"].forEach(function(c){k(b,
c,function(){a.closePopup()})})},addColsContainer:function(a){var b=d("div",{className:"highcharts-popup-lhs-col"},null,a);a=d("div",{className:"highcharts-popup-rhs-col"},null,a);d("div",{className:"highcharts-popup-rhs-col-wrapper"},null,a);return{lhsCol:b,rhsCol:a}},addInput:function(a,b,c,e){var g=a.split(".");g=g[g.length-1];var f=this.lang;b="highcharts-"+b+"-"+g;b.match(A)||d("label",{innerHTML:f[g]||g,htmlFor:b},null,c);d("input",{name:b,value:e[0],type:e[1],className:"highcharts-popup-field"},
null,c).setAttribute("highcharts-data-name",a)},addButton:function(a,b,c,e,f){var g=this,l=this.closePopup,h=this.getFields;var p=d("button",{innerHTML:b},null,a);["click","touchstart"].forEach(function(a){k(p,a,function(){l.call(g);return e(h(f,c))})});return p},getFields:function(a,b){var c=a.querySelectorAll("input"),d=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var g,e;var f={actionType:b,linkedTo:d&&
d.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){e=a.getAttribute("highcharts-data-name");(g=a.getAttribute("highcharts-data-series-id"))?f.seriesId=a.value:e?f.fields[e]=a.value:f.type=a.value});a&&(f.fields["params.volumeSeriesID"]=a.getAttribute("value"));return f},showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),
a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,d){this.popup=b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,d);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,d);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d);"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0)},getLangpack:function(){return f.getOptions().lang.navigation.popup},
annotations:{addToolbar:function(a,b,c){var e=this,g=this.lang,f=this.popup.container,l=this.showForm;-1===f.className.indexOf("highcharts-annotation-toolbar")&&(f.className+=" highcharts-annotation-toolbar");f.style.top=a.plotTop+10+"px";d("span",{innerHTML:q(g[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type)},null,f);var h=this.addButton(f,g.removeButton||"remove","remove",c,f);h.className+=" highcharts-annotation-remove-button";h.style["background-image"]="url("+this.iconsURL+"destroy.svg)";h=
this.addButton(f,g.editButton||"edit","edit",function(){l.call(e,"annotation-edit",a,b,c)},f);h.className+=" highcharts-annotation-edit-button";h.style["background-image"]="url("+this.iconsURL+"edit.svg)"},addForm:function(a,b,c,e){var g=this.popup.container,f=this.lang;d("h2",{innerHTML:f[b.langKey]||b.langKey,className:"highcharts-popup-main-title"},null,g);var l=d("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,g);var h=d("div",{className:"highcharts-popup-bottom-row"},
null,g);this.annotations.addFormFields.call(this,l,a,"",b,[],!0);this.addButton(h,e?f.addButton||"add":f.saveButton||"save",e?"add":"save",c,g)},addFormFields:function(a,b,c,f,h,k){var g=this,l=this.annotations.addFormFields,p=this.addInput,r=this.lang,t,w;e(f,function(d,e){t=""!==c?c+"."+e:e;u(d)&&(!n(d)||n(d)&&u(d[0])?(w=r[e]||e,w.match(A)||h.push([!0,w,a]),l.call(g,a,b,t,d,h,!1)):h.push([g,t,"annotation",a,d]))});k&&(h=h.sort(function(a){return a[1].match(/format/g)?-1:1}),h.forEach(function(a){!0===
a[0]?d("span",{className:"highcharts-annotation-title",innerHTML:a[1]},null,a[2]):p.apply(a[0],a.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,e=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var f=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.addButton||"add","add",c,f);this.addColsContainer(b[1]);d.addIndicatorList.call(this,
a,b[1],"edit");f=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.saveButton||"save","edit",c,f);this.addButton(f,e.removeButton||"remove","remove",c,f)},addIndicatorList:function(a,b,c){var f=this,g=b.querySelectorAll(".highcharts-popup-lhs-col")[0];b=b.querySelectorAll(".highcharts-popup-rhs-col")[0];var h="edit"===c,l=h?a.series:a.options.plotOptions,p=this.indicators.addFormFields,n;var q=d("ul",{className:"highcharts-indicator-list"},null,g);var u=b.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];
e(l,function(b,c){var e=b.options;if(b.params||e&&e.params){var g=f.indicators.getNameType(b,c),r=g.type;n=d("li",{className:"highcharts-indicator-list",innerHTML:g.name},null,q);["click","touchstart"].forEach(function(c){k(n,c,function(){p.call(f,a,h?b:l[r],g.type,u);h&&b.options&&d("input",{type:"hidden",name:"highcharts-id-"+r,value:b.options.id},null,u).setAttribute("highcharts-data-series-id",b.options.id)})})}});0<q.childNodes.length&&q.childNodes[0].click()},getNameType:function(a,b){var c=
a.options,d=f.seriesTypes;d=d[b]&&d[b].prototype.nameBase||b.toUpperCase();c&&c.type&&(b=a.options.type,d=a.name);return{name:d,type:b}},listAllSeries:function(a,c,e,f,h){a="highcharts-"+c+"-type-"+a;var g;d("label",{innerHTML:this.lang[c]||c,htmlFor:a},null,f);var l=d("select",{name:a,className:"highcharts-popup-field"},null,f);l.setAttribute("id","highcharts-select-"+c);e.series.forEach(function(a){g=a.options;!g.params&&g.id&&"highcharts-navigator-series"!==g.id&&d("option",{innerHTML:g.name||
g.id,value:g.id},null,l)});b(h)&&(l.value=h)},addFormFields:function(a,b,c,e){var f=b.params||b.options.params,g=this.indicators.getNameType;e.innerHTML="";d("h3",{className:"highcharts-indicator-title",innerHTML:g(b,c).name},null,e);d("input",{type:"hidden",name:"highcharts-type-"+c,value:c},null,e);this.indicators.listAllSeries.call(this,c,"series",a,e,b.linkedParent&&f.volumeSeriesID);f.volumeSeriesID&&this.indicators.listAllSeries.call(this,c,"volume",a,e,b.linkedParent&&b.linkedParent.options.id);
this.indicators.addParamInputs.call(this,a,"params",f,c,e)},addParamInputs:function(a,b,c,d,f){var g=this,h=this.indicators.addParamInputs,l=this.addInput,k;e(c,function(c,e){k=b+"."+e;u(c)?h.call(g,a,k,c,d,f):"params.volumeSeriesID"!==k&&l.call(g,k,d,f,[c,"text"])})},getAmount:function(){var a=0;e(this.series,function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,
"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(a,b){var c=this.popup.container,e="highcharts-tab-item",f=this.lang;0===b&&(e+=" highcharts-tab-disabled");b=d("span",{innerHTML:f[a+"Button"]||a,className:e},null,c);b.setAttribute("highcharts-data-tab-type",a);return b},addContentItem:function(){return d("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=
this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,e){c=d.getAttribute("highcharts-data-tab-type");"edit"===c&&0===a||["click","touchstart"].forEach(function(a){k(d,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,e)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,
b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),a[c].classList.remove("highcharts-tab-item-show")}}};k(c,"showPopup",function(a){this.popup||(this.popup=new f.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.1.0/gfx/stock-icons/"));this.popup.showForm(a.formType,
this.chart,a.options,a.onSubmit)});k(c,"closePopup",function(){this.popup&&this.popup.closePopup()})});n(c,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map