/*
 Highcharts JS v8.1.0 (2020-05-12)

 Exporting module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/exporting",["highcharts"],function(n){e(n);e.Highcharts=n;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function n(e,g,m,k){e.hasOwnProperty(g)||(e[g]=k.apply(null,m))}e=e?e._modules:{};n(e,"modules/full-screen.src.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,g){var m=g.addEvent;g=e.Chart;var k=function(){function g(f){this.chart=
f;this.isOpen=!1;f=f.renderTo;this.browserProps||("function"===typeof f.requestFullscreen?this.browserProps={fullscreenChange:"fullscreenchange",requestFullscreen:"requestFullscreen",exitFullscreen:"exitFullscreen"}:f.mozRequestFullScreen?this.browserProps={fullscreenChange:"mozfullscreenchange",requestFullscreen:"mozRequestFullScreen",exitFullscreen:"mozCancelFullScreen"}:f.webkitRequestFullScreen?this.browserProps={fullscreenChange:"webkitfullscreenchange",requestFullscreen:"webkitRequestFullScreen",
exitFullscreen:"webkitExitFullscreen"}:f.msRequestFullscreen&&(this.browserProps={fullscreenChange:"MSFullscreenChange",requestFullscreen:"msRequestFullscreen",exitFullscreen:"msExitFullscreen"}))}g.prototype.close=function(){var f=this.chart;if(this.isOpen&&this.browserProps&&f.container.ownerDocument instanceof Document)f.container.ownerDocument[this.browserProps.exitFullscreen]();this.unbindFullscreenEvent&&this.unbindFullscreenEvent();this.isOpen=!1;this.setButtonText()};g.prototype.open=function(){var f=
this,g=f.chart;if(f.browserProps){f.unbindFullscreenEvent=m(g.container.ownerDocument,f.browserProps.fullscreenChange,function(){f.isOpen?(f.isOpen=!1,f.close()):(f.isOpen=!0,f.setButtonText())});var e=g.renderTo[f.browserProps.requestFullscreen]();if(e)e["catch"](function(){alert("Full screen is not supported inside a frame.")});m(g,"destroy",f.unbindFullscreenEvent)}};g.prototype.setButtonText=function(){var f,g=this.chart,e=g.exportDivElements,k=g.options.exporting,m=null===(f=null===k||void 0===
k?void 0:k.buttons)||void 0===f?void 0:f.contextButton.menuItems;f=g.options.lang;(null===k||void 0===k?0:k.menuItemDefinitions)&&(null===f||void 0===f?0:f.exitFullscreen)&&f.viewFullscreen&&m&&e&&e.length&&(e[m.indexOf("viewFullscreen")].innerHTML=this.isOpen?f.exitFullscreen:k.menuItemDefinitions.viewFullscreen.text||f.viewFullscreen)};g.prototype.toggle=function(){this.isOpen?this.close():this.open()};return g}();e.Fullscreen=k;m(g,"beforeRender",function(){this.fullscreen=new e.Fullscreen(this)});
return e.Fullscreen});n(e,"mixins/navigation.js",[],function(){return{initUpdate:function(e){e.navigation||(e.navigation={updates:[],update:function(g,e){this.updates.forEach(function(k){k.update.call(k.context,g,e)})}})},addUpdate:function(e,g){g.navigation||this.initUpdate(g);g.navigation.updates.push({update:e,context:g})}}});n(e,"modules/exporting.src.js",[e["mixins/navigation.js"],e["parts/Globals.js"],e["parts/SVGRenderer.js"],e["parts/Utilities.js"]],function(e,g,m,k){var n=k.addEvent,f=k.css,
r=k.createElement,D=k.discardElement,t=k.extend,I=k.find,A=k.fireEvent,J=k.isObject,p=k.merge,E=k.objectEach,u=k.pick,K=k.removeEvent,L=k.uniqueKey,y=g.defaultOptions,w=g.doc,B=g.Chart,M=g.isTouchDevice,z=g.win,G=z.navigator.userAgent,H=g.Renderer.prototype.symbols,N=/Edge\/|Trident\/|MSIE /.test(G),O=/firefox/i.test(G);t(y.lang,{viewFullscreen:"View in full screen",exitFullscreen:"Exit from full screen",printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",
downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});y.navigation||(y.navigation={});p(!0,y.navigation,{buttonOptions:{theme:{},symbolSize:14,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,verticalAlign:"top",width:24}});p(!0,y.navigation,{menuStyle:{border:"1px solid #999999",background:"#ffffff",padding:"5px 0"},menuItemStyle:{padding:"0.5em 1em",color:"#333333",background:"none",fontSize:M?"14px":"11px",transition:"background 250ms, color 250ms"},
menuItemHoverStyle:{background:"#335cad",color:"#ffffff"},buttonOptions:{symbolFill:"#666666",symbolStroke:"#666666",symbolStrokeWidth:3,theme:{padding:5}}});y.exporting={type:"image/png",url:"https://export.highcharts.com/",printMaxWidth:780,scale:2,buttons:{contextButton:{className:"highcharts-contextbutton",menuClassName:"highcharts-contextmenu",symbol:"menu",titleKey:"contextButtonTitle",menuItems:"viewFullscreen printChart separator downloadPNG downloadJPEG downloadPDF downloadSVG".split(" ")}},
menuItemDefinitions:{viewFullscreen:{textKey:"viewFullscreen",onclick:function(){this.fullscreen.toggle()}},printChart:{textKey:"printChart",onclick:function(){this.print()}},separator:{separator:!0},downloadPNG:{textKey:"downloadPNG",onclick:function(){this.exportChart()}},downloadJPEG:{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},downloadPDF:{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},downloadSVG:{textKey:"downloadSVG",
onclick:function(){this.exportChart({type:"image/svg+xml"})}}}};g.post=function(a,b,c){var d=r("form",p({method:"post",action:a,enctype:"multipart/form-data"},c),{display:"none"},w.body);E(b,function(a,b){r("input",{type:"hidden",name:b,value:a},null,d)});d.submit();D(d)};g.isSafari&&g.win.matchMedia("print").addListener(function(a){g.printingChart&&(a.matches?g.printingChart.beforePrint():g.printingChart.afterPrint())});t(B.prototype,{sanitizeSVG:function(a,b){var c=a.indexOf("</svg>")+6,d=a.substr(c);
a=a.substr(0,c);b&&b.exporting&&b.exporting.allowHTML&&d&&(d='<foreignObject x="0" y="0" width="'+b.chart.width+'" height="'+b.chart.height+'"><body xmlns="http://www.w3.org/1999/xhtml">'+d+"</body></foreignObject>",a=a.replace("</svg>",d+"</svg>"));a=a.replace(/zIndex="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\(("|&quot;)(.*?)("|&quot;);?\)/g,"url($2)").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ (|NS[0-9]+:)href=/g,
" xlink:href=").replace(/\n/," ").replace(/(fill|stroke)="rgba\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\.]+)\)"/g,'$1="rgb($2)" $1-opacity="$3"').replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad");this.ieSanitizeSVG&&(a=this.ieSanitizeSVG(a));return a},getChartHTML:function(){this.styledMode&&this.inlineStyles();return this.container.innerHTML},getSVG:function(a){var b,c=p(this.options,a);c.plotOptions=p(this.userOptions.plotOptions,a&&a.plotOptions);c.time=p(this.userOptions.time,a&&a.time);var d=r("div",
null,{position:"absolute",top:"-9999em",width:this.chartWidth+"px",height:this.chartHeight+"px"},w.body);var e=this.renderTo.style.width;var f=this.renderTo.style.height;e=c.exporting.sourceWidth||c.chart.width||/px$/.test(e)&&parseInt(e,10)||(c.isGantt?800:600);f=c.exporting.sourceHeight||c.chart.height||/px$/.test(f)&&parseInt(f,10)||400;t(c.chart,{animation:!1,renderTo:d,forExport:!0,renderer:"SVGRenderer",width:e,height:f});c.exporting.enabled=!1;delete c.data;c.series=[];this.series.forEach(function(a){b=
p(a.userOptions,{animation:!1,enableMouseTracking:!1,showCheckbox:!1,visible:a.visible});b.isInternal||c.series.push(b)});this.axes.forEach(function(a){a.userOptions.internalKey||(a.userOptions.internalKey=L())});var k=new g.Chart(c,this.callback);a&&["xAxis","yAxis","series"].forEach(function(b){var d={};a[b]&&(d[b]=a[b],k.update(d))});this.axes.forEach(function(a){var b=I(k.axes,function(b){return b.options.internalKey===a.userOptions.internalKey}),d=a.getExtremes(),c=d.userMin;d=d.userMax;b&&("undefined"!==
typeof c&&c!==b.min||"undefined"!==typeof d&&d!==b.max)&&b.setExtremes(c,d,!0,!1)});e=k.getChartHTML();A(this,"getSVG",{chartCopy:k});e=this.sanitizeSVG(e,c);c=null;k.destroy();D(d);return e},getSVGForExport:function(a,b){var c=this.options.exporting;return this.getSVG(p({chart:{borderRadius:0}},c.chartOptions,b,{exporting:{sourceWidth:a&&a.sourceWidth||c.sourceWidth,sourceHeight:a&&a.sourceHeight||c.sourceHeight}}))},getFilename:function(){var a=this.userOptions.title&&this.userOptions.title.text,
b=this.options.exporting.filename;if(b)return b.replace(/\//g,"-");"string"===typeof a&&(b=a.toLowerCase().replace(/<\/?[^>]+(>|$)/g,"").replace(/[\s_]+/g,"-").replace(/[^a-z0-9\-]/g,"").replace(/^[\-]+/g,"").replace(/[\-]+/g,"-").substr(0,24).replace(/[\-]+$/g,""));if(!b||5>b.length)b="chart";return b},exportChart:function(a,b){b=this.getSVGForExport(a,b);a=p(this.options.exporting,a);g.post(a.url,{filename:a.filename?a.filename.replace(/\//g,"-"):this.getFilename(),type:a.type,width:a.width||0,
scale:a.scale,svg:b},a.formAttributes)},moveContainers:function(a){(this.fixedDiv?[this.fixedDiv,this.scrollingContainer]:[this.container]).forEach(function(b){a.appendChild(b)})},beforePrint:function(){var a=w.body,b=this.options.exporting.printMaxWidth,c={childNodes:a.childNodes,origDisplay:[],resetParams:void 0};this.isPrinting=!0;this.pointer.reset(null,0);A(this,"beforePrint");b&&this.chartWidth>b&&(c.resetParams=[this.options.chart.width,void 0,!1],this.setSize(b,void 0,!1));[].forEach.call(c.childNodes,
function(a,b){1===a.nodeType&&(c.origDisplay[b]=a.style.display,a.style.display="none")});this.moveContainers(a);this.printReverseInfo=c},afterPrint:function(){if(this.printReverseInfo){var a=this.printReverseInfo.childNodes,b=this.printReverseInfo.origDisplay,c=this.printReverseInfo.resetParams;this.moveContainers(this.renderTo);[].forEach.call(a,function(a,c){1===a.nodeType&&(a.style.display=b[c]||"")});this.isPrinting=!1;c&&this.setSize.apply(this,c);delete this.printReverseInfo;delete g.printingChart;
A(this,"afterPrint")}},print:function(){var a=this;a.isPrinting||(g.printingChart=a,g.isSafari||a.beforePrint(),setTimeout(function(){z.focus();z.print();g.isSafari||setTimeout(function(){a.afterPrint()},1E3)},1))},contextMenu:function(a,b,c,d,e,g,F){var h=this,C=h.options.navigation,p=h.chartWidth,x=h.chartHeight,q="cache-"+a,l=h[q],v=Math.max(e,g);if(!l){h.exportContextMenu=h[q]=l=r("div",{className:a},{position:"absolute",zIndex:1E3,padding:v+"px",pointerEvents:"auto"},h.fixedDiv||h.container);
var m=r("ul",{className:"highcharts-menu"},{listStyle:"none",margin:0,padding:0},l);h.styledMode||f(m,t({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},C.menuStyle));l.hideMenu=function(){f(l,{display:"none"});F&&F.setState(0);h.openMenu=!1;f(h.renderTo,{overflow:"hidden"});k.clearTimeout(l.hideTimer);A(h,"exportMenuHidden")};h.exportEvents.push(n(l,"mouseleave",function(){l.hideTimer=z.setTimeout(l.hideMenu,500)}),n(l,"mouseenter",function(){k.clearTimeout(l.hideTimer)}),
n(w,"mouseup",function(b){h.pointer.inClass(b.target,a)||l.hideMenu()}),n(l,"click",function(){h.openMenu&&l.hideMenu()}));b.forEach(function(a){"string"===typeof a&&(a=h.options.exporting.menuItemDefinitions[a]);if(J(a,!0)){if(a.separator)var b=r("hr",null,null,m);else b=r("li",{className:"highcharts-menu-item",onclick:function(b){b&&b.stopPropagation();l.hideMenu();a.onclick&&a.onclick.apply(h,arguments)},innerHTML:a.text||h.options.lang[a.textKey]},null,m),h.styledMode||(b.onmouseover=function(){f(this,
C.menuItemHoverStyle)},b.onmouseout=function(){f(this,C.menuItemStyle)},f(b,t({cursor:"pointer"},C.menuItemStyle)));h.exportDivElements.push(b)}});h.exportDivElements.push(m,l);h.exportMenuWidth=l.offsetWidth;h.exportMenuHeight=l.offsetHeight}b={display:"block"};c+h.exportMenuWidth>p?b.right=p-c-e-v+"px":b.left=c-v+"px";d+g+h.exportMenuHeight>x&&"top"!==F.alignOptions.verticalAlign?b.bottom=x-d-v+"px":b.top=d+g-v+"px";f(l,b);f(h.renderTo,{overflow:""});h.openMenu=!0;A(h,"exportMenuShown")},addButton:function(a){var b=
this,c=b.renderer,d=p(b.options.navigation.buttonOptions,a),e=d.onclick,g=d.menuItems,f=d.symbolSize||12;b.btnCount||(b.btnCount=0);b.exportDivElements||(b.exportDivElements=[],b.exportSVGElements=[]);if(!1!==d.enabled){var h=d.theme,k=h.states,m=k&&k.hover;k=k&&k.select;var x;b.styledMode||(h.fill=u(h.fill,"#ffffff"),h.stroke=u(h.stroke,"none"));delete h.states;e?x=function(a){a&&a.stopPropagation();e.call(b,a)}:g&&(x=function(a){a&&a.stopPropagation();b.contextMenu(q.menuClassName,g,q.translateX,
q.translateY,q.width,q.height,q);q.setState(2)});d.text&&d.symbol?h.paddingLeft=u(h.paddingLeft,25):d.text||t(h,{width:d.width,height:d.height,padding:0});b.styledMode||(h["stroke-linecap"]="round",h.fill=u(h.fill,"#ffffff"),h.stroke=u(h.stroke,"none"));var q=c.button(d.text,0,0,x,h,m,k).addClass(a.className).attr({title:u(b.options.lang[d._titleKey||d.titleKey],"")});q.menuClassName=a.menuClassName||"highcharts-menu-"+b.btnCount++;if(d.symbol){var l=c.symbol(d.symbol,d.symbolX-f/2,d.symbolY-f/2,
f,f,{width:f,height:f}).addClass("highcharts-button-symbol").attr({zIndex:1}).add(q);b.styledMode||l.attr({stroke:d.symbolStroke,fill:d.symbolFill,"stroke-width":d.symbolStrokeWidth||1})}q.add(b.exportingGroup).align(t(d,{width:q.width,x:u(d.x,b.buttonOffset)}),!0,"spacingBox");b.buttonOffset+=(q.width+d.buttonSpacing)*("right"===d.align?-1:1);b.exportSVGElements.push(q,l)}},destroyExport:function(a){var b=a?a.target:this;a=b.exportSVGElements;var c=b.exportDivElements,d=b.exportEvents,e;a&&(a.forEach(function(a,
d){a&&(a.onclick=a.ontouchstart=null,e="cache-"+a.menuClassName,b[e]&&delete b[e],b.exportSVGElements[d]=a.destroy())}),a.length=0);b.exportingGroup&&(b.exportingGroup.destroy(),delete b.exportingGroup);c&&(c.forEach(function(a,d){k.clearTimeout(a.hideTimer);K(a,"mouseleave");b.exportDivElements[d]=a.onmouseout=a.onmouseover=a.ontouchstart=a.onclick=null;D(a)}),c.length=0);d&&(d.forEach(function(a){a()}),d.length=0)}});m.prototype.inlineToAttributes="fill stroke strokeLinecap strokeLinejoin strokeWidth textAnchor x y".split(" ");
m.prototype.inlineBlacklist=[/-/,/^(clipPath|cssText|d|height|width)$/,/^font$/,/[lL]ogical(Width|Height)$/,/perspective/,/TapHighlightColor/,/^transition/,/^length$/];m.prototype.unstyledElements=["clipPath","defs","desc"];B.prototype.inlineStyles=function(){function a(a){return a.replace(/([A-Z])/g,function(a,b){return"-"+b.toLowerCase()})}function b(c){function f(b,f){v=u=!1;if(g){for(r=g.length;r--&&!u;)u=g[r].test(f);v=!u}"transform"===f&&"none"===b&&(v=!0);for(r=e.length;r--&&!v;)v=e[r].test(f)||
"function"===typeof b;v||y[f]===b&&"svg"!==c.nodeName||h[c.nodeName][f]===b||(-1!==d.indexOf(f)?c.setAttribute(a(f),b):l+=a(f)+":"+b+";")}var l="",v,u,r;if(1===c.nodeType&&-1===k.indexOf(c.nodeName)){var t=z.getComputedStyle(c,null);var y="svg"===c.nodeName?{}:z.getComputedStyle(c.parentNode,null);if(!h[c.nodeName]){m=n.getElementsByTagName("svg")[0];var w=n.createElementNS(c.namespaceURI,c.nodeName);m.appendChild(w);h[c.nodeName]=p(z.getComputedStyle(w,null));"text"===c.nodeName&&delete h.text.fill;
m.removeChild(w)}if(O||N)for(var x in t)f(t[x],x);else E(t,f);l&&(t=c.getAttribute("style"),c.setAttribute("style",(t?t+";":"")+l));"svg"===c.nodeName&&c.setAttribute("stroke-width","1px");"text"!==c.nodeName&&[].forEach.call(c.children||c.childNodes,b)}}var c=this.renderer,d=c.inlineToAttributes,e=c.inlineBlacklist,g=c.inlineWhitelist,k=c.unstyledElements,h={},m;c=w.createElement("iframe");f(c,{width:"1px",height:"1px",visibility:"hidden"});w.body.appendChild(c);var n=c.contentWindow.document;n.open();
n.write('<svg xmlns="http://www.w3.org/2000/svg"></svg>');n.close();b(this.container.querySelector("svg"));m.parentNode.removeChild(m)};H.menu=function(a,b,c,d){return[["M",a,b+2.5],["L",a+c,b+2.5],["M",a,b+d/2+.5],["L",a+c,b+d/2+.5],["M",a,b+d-1.5],["L",a+c,b+d-1.5]]};H.menuball=function(a,b,c,d){a=[];d=d/3-2;return a=a.concat(this.circle(c-d,b,d,d),this.circle(c-d,b+d+4,d,d),this.circle(c-d,b+2*(d+4),d,d))};B.prototype.renderExporting=function(){var a=this,b=a.options.exporting,c=b.buttons,d=a.isDirtyExporting||
!a.exportSVGElements;a.buttonOffset=0;a.isDirtyExporting&&a.destroyExport();d&&!1!==b.enabled&&(a.exportEvents=[],a.exportingGroup=a.exportingGroup||a.renderer.g("exporting-group").attr({zIndex:3}).add(),E(c,function(b){a.addButton(b)}),a.isDirtyExporting=!1);n(a,"destroy",a.destroyExport)};n(B,"init",function(){var a=this;a.exporting={update:function(b,c){a.isDirtyExporting=!0;p(!0,a.options.exporting,b);u(c,!0)&&a.redraw()}};e.addUpdate(function(b,c){a.isDirtyExporting=!0;p(!0,a.options.navigation,
b);u(c,!0)&&a.redraw()},a)});B.prototype.callbacks.push(function(a){a.renderExporting();n(a,"redraw",a.renderExporting)})});n(e,"masters/modules/exporting.src.js",[],function(){})});
//# sourceMappingURL=exporting.js.map