/*
 Highmaps JS v8.1.0 (2020-05-12)

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(p){b(p);b.Highcharts=p;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function p(b,q,m,g){b.hasOwnProperty(q)||(b[q]=g.apply(null,m))}b=b?b._modules:{};p(b,"parts-map/ColorSeriesMixin.js",[b["parts/Globals.js"]],function(b){b.colorPointMixin={setVisible:function(b){var m=this,g=b?"show":
"hide";m.visible=m.options.visible=!!b;["graphic","dataLabel"].forEach(function(b){if(m[b])m[b][g]()})}};b.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var b=this,m=this.options.nullColor,g=this.colorAxis,x=this.colorKey;(this.data.length?this.data:this.points).forEach(function(r){var h=r.getNestedProperty(x);if(h=r.options.color||(r.isNull||null===r.value?m:g&&"undefined"!==typeof h?g.toColor(h,r):r.color||b.color))r.color=h})}}});p(b,"parts-map/ColorAxis.js",
[b["parts/Axis.js"],b["parts/Color.js"],b["parts/Globals.js"],b["parts/Legend.js"],b["mixins/legend-symbol.js"],b["parts/Point.js"],b["parts/Utilities.js"]],function(b,q,m,g,p,r,h){var x=this&&this.__extends||function(){var a=function(c,d){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,c){d.__proto__=c}||function(d,c){for(var k in c)c.hasOwnProperty(k)&&(d[k]=c[k])};return a(c,d)};return function(c,d){function k(){this.constructor=c}a(c,d);c.prototype=null===d?Object.create(d):
(k.prototype=d.prototype,new k)}}(),v=q.parse;q=h.addEvent;var B=h.erase,z=h.extend,w=h.Fx,y=h.isNumber,a=h.merge,f=h.pick,D=h.splat;"";h=m.Chart;var A=m.Series,n=m.colorPointMixin,e=m.noop;z(A.prototype,m.colorSeriesMixin);z(r.prototype,n);h.prototype.collectionsWithUpdate.push("colorAxis");h.prototype.collectionsWithInit.colorAxis=[h.prototype.addColorAxis];var l=function(b){function c(d,k){var c=b.call(this,d,k)||this;c.beforePadding=!1;c.chart=void 0;c.coll="colorAxis";c.dataClasses=void 0;c.legendItem=
void 0;c.legendItems=void 0;c.name="";c.options=void 0;c.stops=void 0;c.visible=!0;c.init(d,k);return c}x(c,b);c.buildOptions=function(d,c,b){d=d.options.legend||{};var k=b.layout?"vertical"!==b.layout:"vertical"!==d.layout;return a(c,{side:k?2:1,reversed:!k},b,{opposite:!k,showEmpty:!1,title:null,visible:d.enabled&&(b?!1!==b.visible:!0)})};c.prototype.init=function(d,k){var a=c.buildOptions(d,c.defaultOptions,k);this.coll="colorAxis";b.prototype.init.call(this,d,a);k.dataClasses&&this.initDataClasses(k);
this.initStops();this.horiz=!a.opposite;this.zoomEnabled=!1};c.prototype.initDataClasses=function(d){var c=this.chart,b,t=0,f=c.options.chart.colorCount,e=this.options,l=d.dataClasses.length;this.dataClasses=b=[];this.legendItems=[];d.dataClasses.forEach(function(d,k){d=a(d);b.push(d);if(c.styledMode||!d.color)"category"===e.dataClassColor?(c.styledMode||(k=c.options.colors,f=k.length,d.color=k[t]),d.colorIndex=t,t++,t===f&&(t=0)):d.color=v(e.minColor).tweenTo(v(e.maxColor),2>l?.5:k/(l-1))})};c.prototype.hasData=
function(){return!!(this.tickPositions||[]).length};c.prototype.setTickPositions=function(){if(!this.dataClasses)return b.prototype.setTickPositions.call(this)};c.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(d){d.color=v(d[1])})};c.prototype.setOptions=function(d){b.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker};c.prototype.setAxisSize=function(){var d=this.legendSymbol,
k=this.chart,a=k.options.legend||{},t,b;d?(this.left=a=d.attr("x"),this.top=t=d.attr("y"),this.width=b=d.attr("width"),this.height=d=d.attr("height"),this.right=k.chartWidth-a-b,this.bottom=k.chartHeight-t-d,this.len=this.horiz?b:d,this.pos=this.horiz?a:t):this.len=(this.horiz?a.symbolWidth:a.symbolHeight)||c.defaultLegendLength};c.prototype.normalizedValue=function(d){this.logarithmic&&(d=this.logarithmic.log2lin(d));return 1-(this.max-d)/(this.max-this.min||1)};c.prototype.toColor=function(d,c){var k=
this.dataClasses,a=this.stops,b;if(k)for(b=k.length;b--;){var f=k[b];var e=f.from;a=f.to;if(("undefined"===typeof e||d>=e)&&("undefined"===typeof a||d<=a)){var l=f.color;c&&(c.dataClass=b,c.colorIndex=f.colorIndex);break}}else{d=this.normalizedValue(d);for(b=a.length;b--&&!(d>a[b][0]););e=a[b]||a[b+1];a=a[b+1]||e;d=1-(a[0]-d)/(a[0]-e[0]||1);l=e.color.tweenTo(a.color,d)}return l};c.prototype.getOffset=function(){var d=this.legendGroup,c=this.chart.axisOffset[this.side];d&&(this.axisParent=d,b.prototype.getOffset.call(this),
this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=c)};c.prototype.setLegendColor=function(){var d=this.reversed,c=d?1:0;d=d?0:1;c=this.horiz?[c,0,d,0]:[0,d,0,c];this.legendColor={linearGradient:{x1:c[0],y1:c[1],x2:c[2],y2:c[3]},stops:this.stops}};c.prototype.drawLegendSymbol=function(d,a){var b=d.padding,k=d.options,e=this.horiz,l=f(k.symbolWidth,e?c.defaultLegendLength:12),u=f(k.symbolHeight,e?12:c.defaultLegendLength),n=f(k.labelPadding,e?16:
30);k=f(k.itemDistance,10);this.setLegendColor();a.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,l,u).attr({zIndex:1}).add(a.legendGroup);this.legendItemWidth=l+b+(e?k:n);this.legendItemHeight=u+b+(e?n:0)};c.prototype.setState=function(c){this.series.forEach(function(d){d.setState(c)})};c.prototype.setVisible=function(){};c.prototype.getSeriesExtremes=function(){var c=this.series,a=c.length,b;this.dataMin=Infinity;for(this.dataMax=-Infinity;a--;){var e=c[a];var l=e.colorKey=f(e.options.colorKey,
e.colorKey,e.pointValKey,e.zoneAxis,"y");var u=e.pointArrayMap;var n=e[l+"Min"]&&e[l+"Max"];if(e[l+"Data"])var h=e[l+"Data"];else if(u){h=[];u=u.indexOf(l);var g=e.yData;if(0<=u&&g)for(b=0;b<g.length;b++)h.push(f(g[b][u],g[b]))}else h=e.yData;n?(e.minColorValue=e[l+"Min"],e.maxColorValue=e[l+"Max"]):(h=A.prototype.getExtremes.call(e,h),e.minColorValue=h.dataMin,e.maxColorValue=h.dataMax);"undefined"!==typeof e.minColorValue&&(this.dataMin=Math.min(this.dataMin,e.minColorValue),this.dataMax=Math.max(this.dataMax,
e.maxColorValue));n||A.prototype.applyExtremes.call(e)}};c.prototype.drawCrosshair=function(c,a){var d=a&&a.plotX,e=a&&a.plotY,k=this.pos,f=this.len;if(a){var l=this.toPixels(a.getNestedProperty(a.series.colorKey));l<k?l=k-2:l>k+f&&(l=k+f+2);a.plotX=l;a.plotY=this.len-l;b.prototype.drawCrosshair.call(this,c,a);a.plotX=d;a.plotY=e;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&
this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};c.prototype.getPlotLinePath=function(c){var a=c.translatedValue;return y(a)?this.horiz?[["M",a-4,this.top-6],["L",a+4,this.top-6],["L",a,this.top],["Z"]]:[["M",this.left,a],["L",this.left-6,a+6],["L",this.left-6,a-6],["Z"]]:b.prototype.getPlotLinePath.call(this,c)};c.prototype.update=function(d,e){var f=this.chart,k=f.legend,l=c.buildOptions(f,{},d);this.series.forEach(function(c){c.isDirtyData=!0});(d.dataClasses&&k.allItems||this.dataClasses)&&
this.destroyItems();f.options[this.coll]=a(this.userOptions,l);b.prototype.update.call(this,l,e);this.legendItem&&(this.setLegendColor(),k.colorizeItem(this,!0))};c.prototype.destroyItems=function(){var c=this.chart;this.legendItem?c.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(a){c.legend.destroyItem(a)});c.isDirtyLegend=!0};c.prototype.remove=function(c){this.destroyItems();b.prototype.remove.call(this,c)};c.prototype.getDataClassLegendSymbols=function(){var c=this,
a=c.chart,b=c.legendItems,f=a.options.legend,l=f.valueDecimals,u=f.valueSuffix||"",n;b.length||c.dataClasses.forEach(function(d,f){var k=!0,h=d.from,g=d.to,t=a.numberFormatter;n="";"undefined"===typeof h?n="< ":"undefined"===typeof g&&(n="> ");"undefined"!==typeof h&&(n+=t(h,l)+u);"undefined"!==typeof h&&"undefined"!==typeof g&&(n+=" - ");"undefined"!==typeof g&&(n+=t(g,l)+u);b.push(z({chart:a,name:n,options:{},drawLegendSymbol:p.drawRectangle,visible:!0,setState:e,isDataClass:!0,setVisible:function(){k=
c.visible=!k;c.series.forEach(function(c){c.points.forEach(function(c){c.dataClass===f&&c.setVisible(k)})});a.legend.colorizeItem(this,k)}},d))});return b};c.defaultLegendLength=200;c.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0};c.keepProps=["legendGroup",
"legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return c}(b);Array.prototype.push.apply(b.keepProps,l.keepProps);m.ColorAxis=l;["fill","stroke"].forEach(function(a){w.prototype[a+"Setter"]=function(){this.elem.attr(a,v(this.start).tweenTo(v(this.end),this.pos),null,!0)}});q(h,"afterGetAxes",function(){var a=this,c=a.options;this.colorAxis=[];c.colorAxis&&(c.colorAxis=D(c.colorAxis),c.colorAxis.forEach(function(c,b){c.index=b;new l(a,c)}))});q(A,"bindAxes",function(){var a=this.axisTypes;
a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]});q(g,"afterGetAllItems",function(a){var c=[],d,b;(this.chart.colorAxis||[]).forEach(function(b){(d=b.options)&&d.showInLegend&&(d.dataClasses&&d.visible?c=c.concat(b.getDataClassLegendSymbols()):d.visible&&c.push(b),b.series.forEach(function(c){if(!c.options.showInLegend||d.dataClasses)"point"===c.options.legendType?c.points.forEach(function(c){B(a.allItems,c)}):B(a.allItems,c)}))});for(b=c.length;b--;)a.allItems.unshift(c[b])});
q(g,"afterColorizeItem",function(a){a.visible&&a.item.legendColor&&a.item.legendSymbol.attr({fill:a.item.legendColor})});q(g,"afterUpdate",function(){var a=this.chart.colorAxis;a&&a.forEach(function(c,a,b){c.update({},b)})});q(A,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return l});p(b,"parts-map/ColorMapSeriesMixin.js",[b["parts/Globals.js"],b["parts/Point.js"],b["parts/Utilities.js"]],function(b,q,m){var g=m.defined;
m=b.noop;var x=b.seriesTypes;b.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(b){q.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})}};b.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:m,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:x.column.prototype.pointAttribs,
colorAttribs:function(b){var h={};g(b.color)&&(h[this.colorProp||"fill"]=b.color);return h}}});p(b,"parts-map/HeatmapSeries.js",[b["parts/Globals.js"],b["mixins/legend-symbol.js"],b["parts/SVGRenderer.js"],b["parts/Utilities.js"]],function(b,q,m,g){var p=g.clamp,r=g.extend,h=g.fireEvent,x=g.isNumber,v=g.merge,C=g.pick;g=g.seriesType;"";var z=b.colorMapPointMixin,w=b.Series,y=m.prototype.symbols;g("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},
inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},v(b.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){w.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=C(a.pointRange,
a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;r(y,{ellipse:y.circle,rect:y.square})},getSymbol:w.prototype.getSymbol,setClip:function(a){var b=this.chart;w.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?b[this.sharedClipKey]:b.clipRect)},translate:function(){var a=this.options,b=a.marker&&a.marker.symbol||"",g=y[b]?b:"rect";a=this.options;var m=-1!==["circle","square"].indexOf(g);this.generatePoints();this.points.forEach(function(a){var e=
a.getCellAttributes(),f={x:Math.min(e.x1,e.x2),y:Math.min(e.y1,e.y2),width:Math.max(Math.abs(e.x2-e.x1),0),height:Math.max(Math.abs(e.y2-e.y1),0)};var h=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(m){var c=Math.abs(f.width-f.height);f.x=Math.min(e.x1,e.x2)+(f.width<f.height?0:c/2);f.y=Math.min(e.y1,e.y2)+(f.width<f.height?c/2:0);f.width=f.height=Math.min(f.width,f.height)}c={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:v(!0,f,{d:y[g](f.x,
f.y,f.width,f.height)})};h&&(a.marker={width:f.width,height:f.height});r(a,c)});h(this,"afterTranslate")},pointAttribs:function(a,f){var h=w.prototype.pointAttribs.call(this,a,f),g=this.options||{},n=this.chart.options.plotOptions||{},e=n.series||{},l=n.heatmap||{};n=g.borderColor||l.borderColor||e.borderColor;e=g.borderWidth||l.borderWidth||e.borderWidth||h["stroke-width"];h.stroke=a&&a.marker&&a.marker.lineColor||g.marker&&g.marker.lineColor||n||this.color;h["stroke-width"]=e;f&&(a=v(g.states[f],
g.marker&&g.marker.states[f],a.options.states&&a.options.states[f]||{}),f=a.brightness,h.fill=a.color||b.color(h.fill).brighten(f||0).get(),h.stroke=a.lineColor);return h},markerAttribs:function(a,b){var f=a.marker||{},h=this.options.marker||{},g=a.shapeArgs||{},e={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var l=h.states[b]||{};var m=f.states&&f.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){e[a[0]]=(m[a[0]]||l[a[0]]||g[a[0]])+(m[a[0]+"Plus"]||l[a[0]+"Plus"]||0);e[a[1]]=
g[a[1]]+(g[a[0]]-e[a[0]])/2})}return b?e:g},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)w.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return w.prototype.getValidPoints.call(this,a,b,!0)},getBox:b.noop,drawLegendSymbol:q.drawRectangle,alignDataLabel:b.seriesTypes.column.prototype.alignDataLabel,
getExtremes:function(){var a=w.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;x(b)&&(this.valueMin=b);x(a)&&(this.valueMax=a);return w.prototype.getExtremes.call(this)}}),v(z,{applyOptions:function(a,f){a=b.Point.prototype.applyOptions.call(this,a,f);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-
a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]},getCellAttributes:function(){var a=this.series,b=a.options,g=(b.colsize||1)/2,h=(b.rowsize||1)/2,n=a.xAxis,e=a.yAxis,l=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var m=C(this.pointPadding,b.pointPadding,0),c={x1:p(Math.round(n.len-(n.translate(this.x-g,!1,!0,!1,!0,-a)||0)),-n.len,2*n.len),x2:p(Math.round(n.len-(n.translate(this.x+g,!1,!0,!1,!0,-a)||0)),-n.len,2*n.len),y1:p(Math.round(e.translate(this.y-
h,!1,!0,!1,!0)||0),-e.len,2*e.len),y2:p(Math.round(e.translate(this.y+h,!1,!0,!1,!0)||0),-e.len,2*e.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var d=a+"1",e=a+"2",f=Math.abs(c[d]-c[e]),g=l&&l.lineWidth||0,h=Math.abs(c[d]+c[e])/2;l[b]&&l[b]<f&&(c[d]=h-l[b]/2-g/2,c[e]=h+l[b]/2+g/2);m&&("y"===a&&(d=e,e=a+"1"),c[d]+=m,c[e]-=m)});return c}}));""});p(b,"masters/modules/heatmap.src.js",[],function(){})});
//# sourceMappingURL=heatmap.js.map