/*
 Highcharts JS v8.1.0 (2020-05-12)

 Item series type for Highcharts

 (c) 2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/item-series",["highcharts"],function(d){b(d);b.Highcharts=d;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function d(b,c,d,D){b.hasOwnProperty(c)||(b[c]=D.apply(null,d))}b=b?b._modules:{};d(b,"modules/item-series.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,c){var d=c.defined,D=c.extend,F=c.fireEvent,
B=c.isNumber,G=c.merge,H=c.objectEach,I=c.pick;c=c.seriesType;var m=b.seriesTypes.pie.prototype.pointClass.prototype;c("item","pie",{endAngle:void 0,innerSize:"40%",itemPadding:.1,layout:"vertical",marker:G(b.defaultOptions.plotOptions.line.marker,{radius:null}),rows:void 0,crisp:!1,showInLegend:!0,startAngle:void 0},{markerAttribs:void 0,translate:function(){this.slots||(this.slots=[]);B(this.options.startAngle)&&B(this.options.endAngle)?(b.seriesTypes.pie.prototype.translate.call(this),this.slots=
this.getSlots()):(this.generatePoints(),F(this,"afterTranslate"))},getSlots:function(){function a(a){0<C&&(a.row.colCount--,C--)}for(var b=this.center,c=b[2],d=b[3],r,n=this.slots,t,y,u,v,w,f,l,x,h=0,p,z=this.endAngleRad-this.startAngleRad,q=Number.MAX_VALUE,A,e,k,g=this.options.rows,m=(c-d)/c,E=0===z%(2*Math.PI);q>this.total+(e&&E?e.length:0);)for(A=q,q=n.length=0,e=k,k=[],h++,p=c/h/2,g?(d=(p-g)/p*c,0<=d?p=g:(d=0,m=1)):p=Math.floor(p*m),r=p;0<r;r--)u=(d+r/p*(c-d-h))/2,v=z*u,w=Math.ceil(v/h),k.push({rowRadius:u,
rowLength:v,colCount:w}),q+=w+1;if(e){for(var C=A-this.total-(E?e.length:0);0<C;)e.map(function(a){return{angle:a.colCount/a.rowLength,row:a}}).sort(function(a,b){return b.angle-a.angle}).slice(0,Math.min(C,Math.ceil(e.length/2))).forEach(a);e.forEach(function(a){var c=a.rowRadius;f=(a=a.colCount)?z/a:0;for(x=0;x<=a;x+=1)l=this.startAngleRad+x*f,t=b[0]+Math.cos(l)*c,y=b[1]+Math.sin(l)*c,n.push({x:t,y:y,angle:l})},this);n.sort(function(a,b){return a.angle-b.angle});this.itemSize=h;return n}},getRows:function(){var a=
this.options.rows;if(!a){var b=this.chart.plotWidth/this.chart.plotHeight;a=Math.sqrt(this.total);if(1<b)for(a=Math.ceil(a);0<a;){var c=this.total/a;if(c/a>b)break;a--}else for(a=Math.floor(a);a<this.total;){c=this.total/a;if(c/a<b)break;a++}}return a},drawPoints:function(){var a=this,b=this.options,c=a.chart.renderer,m=b.marker,r=this.borderWidth%2?.5:1,n=0,t=this.getRows(),y=Math.ceil(this.total/t),u=this.chart.plotWidth/y,v=this.chart.plotHeight/t,w=this.itemSize||Math.min(u,v);this.points.forEach(function(f){var l,
x,h=f.marker||{},p=h.symbol||m.symbol;h=I(h.radius,m.radius);var z=d(h)?2*h:w,q=z*b.itemPadding,A;f.graphics=l=f.graphics||{};a.chart.styledMode||(x=a.pointAttribs(f,f.selected&&"select"));if(!f.isNull&&f.visible){f.graphic||(f.graphic=c.g("point").add(a.group));for(var e=0;e<f.y;e++){if(a.center&&a.slots){var k=a.slots.shift();var g=k.x-w/2;k=k.y-w/2}else"horizontal"===b.layout?(g=n%y*u,k=v*Math.floor(n/y)):(g=u*Math.floor(n/t),k=n%t*v);g+=q;k+=q;var B=A=Math.round(z-2*q);a.options.crisp&&(g=Math.round(g)-
r,k=Math.round(k)+r);g={x:g,y:k,width:A,height:B};"undefined"!==typeof h&&(g.r=h);l[e]?l[e].animate(g):l[e]=c.symbol(p,null,null,null,null,{backgroundSize:"within"}).attr(D(g,x)).add(f.graphic);l[e].isActive=!0;n++}}H(l,function(a,b){a.isActive?a.isActive=!1:(a.destroy(),delete l[b])})})},drawDataLabels:function(){this.center&&this.slots?b.seriesTypes.pie.prototype.drawDataLabels.call(this):this.points.forEach(function(a){a.destroyElements({dataLabel:1})})},animate:function(a){a?this.group.attr({opacity:0}):
this.group.animate({opacity:1},this.options.animation)}},{connectorShapes:m.connectorShapes,getConnectorPath:m.getConnectorPath,setVisible:m.setVisible,getTranslate:m.getTranslate});""});d(b,"masters/modules/item-series.src.js",[],function(){})});
//# sourceMappingURL=item-series.js.map