/*
 Highmaps JS v8.1.0 (2020-05-12)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(y){a(y);a.Highcharts=y;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function y(a,h,q,m){a.hasOwnProperty(h)||(a[h]=m.apply(null,q))}a=a?a._modules:{};y(a,"parts-map/MapAxis.js",[a["parts/Axis.js"],a["parts/Utilities.js"]],function(a,h){var q=h.addEvent,m=h.pick,f=function(){return function(f){this.axis=
f}}();h=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");q(a,"init",function(){this.mapAxis||(this.mapAxis=new f(this))});q(a,"getSeriesExtremes",function(){if(this.mapAxis){var f=[];this.isXAxis&&(this.series.forEach(function(a,u){a.useMapGeometry&&(f[u]=a.xData,a.xData=[])}),this.mapAxis.seriesXData=f)}});q(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var f=this.mapAxis.seriesXData||[],a;if(this.isXAxis){var u=m(this.dataMin,Number.MAX_VALUE);var c=m(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(n,w){n.useMapGeometry&&(u=Math.min(u,m(n.minX,u)),c=Math.max(c,m(n.maxX,c)),n.xData=f[w],a=!0)});a&&(this.dataMin=u,this.dataMax=c);this.mapAxis.seriesXData=void 0}}});q(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var f=this.chart,a=f.plotWidth/f.plotHeight;f=f.xAxis[0];var u;"yAxis"===this.coll&&"undefined"!==typeof f.transA&&this.series.forEach(function(c){c.preserveAspectRatio&&(u=!0)});if(u&&(this.transA=f.transA=Math.min(this.transA,
f.transA),a/=(f.max-f.min)/(this.max-this.min),a=1>a?this:f,f=(a.max-a.min)*a.transA,a.mapAxis.pixelPadding=a.len-f,a.minPixelPadding=a.mapAxis.pixelPadding/2,f=a.mapAxis.fixTo)){f=f[1]-a.toValue(f[0],!0);f*=a.transA;if(Math.abs(f)>a.minPixelPadding||a.min===a.dataMin&&a.max===a.dataMax)f=0;a.minPixelPadding-=f}}});q(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();h.compose(a);return h});y(a,"parts-map/ColorSeriesMixin.js",[a["parts/Globals.js"]],function(a){a.colorPointMixin=
{setVisible:function(a){var h=this,m=a?"show":"hide";h.visible=h.options.visible=!!a;["graphic","dataLabel"].forEach(function(f){if(h[f])h[f][m]()})}};a.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,z=this.options.nullColor,m=this.colorAxis,f=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var D=h.getNestedProperty(f);if(D=h.options.color||(h.isNull||null===h.value?z:m&&"undefined"!==typeof D?m.toColor(D,h):h.color||a.color))h.color=
D})}}});y(a,"parts-map/ColorAxis.js",[a["parts/Axis.js"],a["parts/Color.js"],a["parts/Globals.js"],a["parts/Legend.js"],a["mixins/legend-symbol.js"],a["parts/Point.js"],a["parts/Utilities.js"]],function(a,h,q,m,f,D,B){var z=this&&this.__extends||function(){var b=function(d,r){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,d){b.__proto__=d}||function(b,d){for(var r in d)d.hasOwnProperty(r)&&(b[r]=d[r])};return b(d,r)};return function(d,r){function v(){this.constructor=d}b(d,r);
d.prototype=null===r?Object.create(r):(v.prototype=r.prototype,new v)}}(),x=h.parse;h=B.addEvent;var u=B.erase,c=B.extend,n=B.Fx,w=B.isNumber,g=B.merge,l=B.pick,A=B.splat;"";B=q.Chart;var p=q.Series,k=q.colorPointMixin,e=q.noop;c(p.prototype,q.colorSeriesMixin);c(D.prototype,k);B.prototype.collectionsWithUpdate.push("colorAxis");B.prototype.collectionsWithInit.colorAxis=[B.prototype.addColorAxis];var b=function(b){function d(d,v){var r=b.call(this,d,v)||this;r.beforePadding=!1;r.chart=void 0;r.coll=
"colorAxis";r.dataClasses=void 0;r.legendItem=void 0;r.legendItems=void 0;r.name="";r.options=void 0;r.stops=void 0;r.visible=!0;r.init(d,v);return r}z(d,b);d.buildOptions=function(b,d,c){b=b.options.legend||{};var r=c.layout?"vertical"!==c.layout:"vertical"!==b.layout;return g(d,{side:r?2:1,reversed:!r},c,{opposite:!r,showEmpty:!1,title:null,visible:b.enabled&&(c?!1!==c.visible:!0)})};d.prototype.init=function(r,c){var v=d.buildOptions(r,d.defaultOptions,c);this.coll="colorAxis";b.prototype.init.call(this,
r,v);c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=!v.opposite;this.zoomEnabled=!1};d.prototype.initDataClasses=function(b){var d=this.chart,r,c=0,e=d.options.chart.colorCount,k=this.options,t=b.dataClasses.length;this.dataClasses=r=[];this.legendItems=[];b.dataClasses.forEach(function(b,v){b=g(b);r.push(b);if(d.styledMode||!b.color)"category"===k.dataClassColor?(d.styledMode||(v=d.options.colors,e=v.length,b.color=v[c]),b.colorIndex=c,c++,c===e&&(c=0)):b.color=x(k.minColor).tweenTo(x(k.maxColor),
2>t?.5:v/(t-1))})};d.prototype.hasData=function(){return!!(this.tickPositions||[]).length};d.prototype.setTickPositions=function(){if(!this.dataClasses)return b.prototype.setTickPositions.call(this)};d.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=x(b[1])})};d.prototype.setOptions=function(d){b.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker};d.prototype.setAxisSize=
function(){var b=this.legendSymbol,c=this.chart,e=c.options.legend||{},k,t;b?(this.left=e=b.attr("x"),this.top=k=b.attr("y"),this.width=t=b.attr("width"),this.height=b=b.attr("height"),this.right=c.chartWidth-e-t,this.bottom=c.chartHeight-k-b,this.len=this.horiz?t:b,this.pos=this.horiz?e:k):this.len=(this.horiz?e.symbolWidth:e.symbolHeight)||d.defaultLegendLength};d.prototype.normalizedValue=function(b){this.logarithmic&&(b=this.logarithmic.log2lin(b));return 1-(this.max-b)/(this.max-this.min||1)};
d.prototype.toColor=function(b,d){var c=this.dataClasses,e=this.stops,v;if(c)for(v=c.length;v--;){var r=c[v];var k=r.from;e=r.to;if(("undefined"===typeof k||b>=k)&&("undefined"===typeof e||b<=e)){var t=r.color;d&&(d.dataClass=v,d.colorIndex=r.colorIndex);break}}else{b=this.normalizedValue(b);for(v=e.length;v--&&!(b>e[v][0]););k=e[v]||e[v+1];e=e[v+1]||k;b=1-(e[0]-b)/(e[0]-k[0]||1);t=k.color.tweenTo(e.color,b)}return t};d.prototype.getOffset=function(){var d=this.legendGroup,c=this.chart.axisOffset[this.side];
d&&(this.axisParent=d,b.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=c)};d.prototype.setLegendColor=function(){var b=this.reversed,d=b?1:0;b=b?0:1;d=this.horiz?[d,0,b,0]:[0,b,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};d.prototype.drawLegendSymbol=function(b,c){var e=b.padding,v=b.options,r=this.horiz,k=l(v.symbolWidth,r?d.defaultLegendLength:12),t=l(v.symbolHeight,
r?12:d.defaultLegendLength),g=l(v.labelPadding,r?16:30);v=l(v.itemDistance,10);this.setLegendColor();c.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,k,t).attr({zIndex:1}).add(c.legendGroup);this.legendItemWidth=k+e+(r?v:g);this.legendItemHeight=t+e+(r?g:0)};d.prototype.setState=function(b){this.series.forEach(function(d){d.setState(b)})};d.prototype.setVisible=function(){};d.prototype.getSeriesExtremes=function(){var b=this.series,d=b.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var e=
b[d];var k=e.colorKey=l(e.options.colorKey,e.colorKey,e.pointValKey,e.zoneAxis,"y");var t=e.pointArrayMap;var g=e[k+"Min"]&&e[k+"Max"];if(e[k+"Data"])var a=e[k+"Data"];else if(t){a=[];t=t.indexOf(k);var f=e.yData;if(0<=t&&f)for(c=0;c<f.length;c++)a.push(l(f[c][t],f[c]))}else a=e.yData;g?(e.minColorValue=e[k+"Min"],e.maxColorValue=e[k+"Max"]):(a=p.prototype.getExtremes.call(e,a),e.minColorValue=a.dataMin,e.maxColorValue=a.dataMax);"undefined"!==typeof e.minColorValue&&(this.dataMin=Math.min(this.dataMin,
e.minColorValue),this.dataMax=Math.max(this.dataMax,e.maxColorValue));g||p.prototype.applyExtremes.call(e)}};d.prototype.drawCrosshair=function(d,e){var c=e&&e.plotX,k=e&&e.plotY,r=this.pos,v=this.len;if(e){var t=this.toPixels(e.getNestedProperty(e.series.colorKey));t<r?t=r-2:t>r+v&&(t=r+v+2);e.plotX=t;e.plotY=this.len-t;b.prototype.drawCrosshair.call(this,d,e);e.plotX=c;e.plotY=k;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),
this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};d.prototype.getPlotLinePath=function(d){var e=d.translatedValue;return w(e)?this.horiz?[["M",e-4,this.top-6],["L",e+4,this.top-6],["L",e,this.top],["Z"]]:[["M",this.left,e],["L",this.left-6,e+6],["L",this.left-6,e-6],["Z"]]:b.prototype.getPlotLinePath.call(this,d)};d.prototype.update=function(e,c){var k=this.chart,r=k.legend,t=d.buildOptions(k,{},e);this.series.forEach(function(b){b.isDirtyData=
!0});(e.dataClasses&&r.allItems||this.dataClasses)&&this.destroyItems();k.options[this.coll]=g(this.userOptions,t);b.prototype.update.call(this,t,c);this.legendItem&&(this.setLegendColor(),r.colorizeItem(this,!0))};d.prototype.destroyItems=function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(d){b.legend.destroyItem(d)});b.isDirtyLegend=!0};d.prototype.remove=function(d){this.destroyItems();b.prototype.remove.call(this,d)};d.prototype.getDataClassLegendSymbols=
function(){var b=this,d=b.chart,k=b.legendItems,t=d.options.legend,a=t.valueDecimals,g=t.valueSuffix||"",n;k.length||b.dataClasses.forEach(function(t,r){var v=!0,l=t.from,p=t.to,A=d.numberFormatter;n="";"undefined"===typeof l?n="< ":"undefined"===typeof p&&(n="> ");"undefined"!==typeof l&&(n+=A(l,a)+g);"undefined"!==typeof l&&"undefined"!==typeof p&&(n+=" - ");"undefined"!==typeof p&&(n+=A(p,a)+g);k.push(c({chart:d,name:n,options:{},drawLegendSymbol:f.drawRectangle,visible:!0,setState:e,isDataClass:!0,
setVisible:function(){v=b.visible=!v;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===r&&b.setVisible(v)})});d.legend.colorizeItem(this,v)}},t))});return k};d.defaultLegendLength=200;d.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0};
d.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return d}(a);Array.prototype.push.apply(a.keepProps,b.keepProps);q.ColorAxis=b;["fill","stroke"].forEach(function(b){n.prototype[b+"Setter"]=function(){this.elem.attr(b,x(this.start).tweenTo(x(this.end),this.pos),null,!0)}});h(B,"afterGetAxes",function(){var d=this,e=d.options;this.colorAxis=[];e.colorAxis&&(e.colorAxis=A(e.colorAxis),e.colorAxis.forEach(function(e,c){e.index=c;new b(d,e)}))});h(p,"bindAxes",
function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});h(m,"afterGetAllItems",function(b){var d=[],e,c;(this.chart.colorAxis||[]).forEach(function(c){(e=c.options)&&e.showInLegend&&(e.dataClasses&&e.visible?d=d.concat(c.getDataClassLegendSymbols()):e.visible&&d.push(c),c.series.forEach(function(d){if(!d.options.showInLegend||e.dataClasses)"point"===d.options.legendType?d.points.forEach(function(d){u(b.allItems,d)}):u(b.allItems,d)}))});for(c=
d.length;c--;)b.allItems.unshift(d[c])});h(m,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});h(m,"afterUpdate",function(){var b=this.chart.colorAxis;b&&b.forEach(function(b,d,e){b.update({},e)})});h(p,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});return b});y(a,"parts-map/ColorMapSeriesMixin.js",[a["parts/Globals.js"],a["parts/Point.js"],a["parts/Utilities.js"]],
function(a,h,q){var m=q.defined;q=a.noop;var f=a.seriesTypes;a.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){h.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}};a.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:q,parallelArrays:["x","y","value"],colorKey:"value",
pointAttribs:f.column.prototype.pointAttribs,colorAttribs:function(a){var f={};m(a.color)&&(f[this.colorProp||"fill"]=a.color);return f}}});y(a,"parts-map/MapNavigation.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,h){function q(c){c&&(c.preventDefault&&c.preventDefault(),c.stopPropagation&&c.stopPropagation(),c.cancelBubble=!0)}function m(c){this.init(c)}var f=h.addEvent,D=h.extend,z=h.merge,C=h.objectEach,x=h.pick;h=a.Chart;var u=a.doc;m.prototype.init=function(c){this.chart=c;
c.mapNavButtons=[]};m.prototype.update=function(c){var a=this.chart,w=a.options.mapNavigation,g,l,A,p,k,e=function(b){this.handler.call(a,b);q(b)},b=a.mapNavButtons;c&&(w=a.options.mapNavigation=z(a.options.mapNavigation,c));for(;b.length;)b.pop().destroy();x(w.enableButtons,w.enabled)&&!a.renderer.forExport&&C(w.buttons,function(d,c){g=z(w.buttonOptions,d);a.styledMode||(l=g.theme,l.style=z(g.theme.style,g.style),p=(A=l.states)&&A.hover,k=A&&A.select);d=a.renderer.button(g.text,0,0,e,l,p,k,0,"zoomIn"===
c?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[c]).attr({width:g.width,height:g.height,title:a.options.lang[c],padding:g.padding,zIndex:5}).add();d.handler=g.onclick;f(d.element,"dblclick",q);b.push(d);var t=g,v=f(a,"load",function(){d.align(D(t,{width:d.width,height:2*d.height}),null,t.alignTo);v()})});this.updateEvents(w)};m.prototype.updateEvents=function(c){var a=this.chart;x(c.enableDoubleClickZoom,c.enabled)||c.enableDoubleClickZoomTo?
this.unbindDblClick=this.unbindDblClick||f(a.container,"dblclick",function(c){a.pointer.onContainerDblClick(c)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());x(c.enableMouseWheelZoom,c.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||f(a.container,"undefined"===typeof u.onmousewheel?"DOMMouseScroll":"mousewheel",function(c){a.pointer.onContainerMouseWheel(c);q(c);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};D(h.prototype,{fitToBox:function(c,
a){[["x","width"],["y","height"]].forEach(function(f){var g=f[0];f=f[1];c[g]+c[f]>a[g]+a[f]&&(c[f]>a[f]?(c[f]=a[f],c[g]=a[g]):c[g]=a[g]+a[f]-c[f]);c[f]>a[f]&&(c[f]=a[f]);c[g]<a[g]&&(c[g]=a[g])});return c},mapZoom:function(c,a,f,g,l){var n=this.xAxis[0],p=n.max-n.min,k=x(a,n.min+p/2),e=p*c;p=this.yAxis[0];var b=p.max-p.min,d=x(f,p.min+b/2);b*=c;k=this.fitToBox({x:k-e*(g?(g-n.pos)/n.len:.5),y:d-b*(l?(l-p.pos)/p.len:.5),width:e,height:b},{x:n.dataMin,y:p.dataMin,width:n.dataMax-n.dataMin,height:p.dataMax-
p.dataMin});e=k.x<=n.dataMin&&k.width>=n.dataMax-n.dataMin&&k.y<=p.dataMin&&k.height>=p.dataMax-p.dataMin;g&&n.mapAxis&&(n.mapAxis.fixTo=[g-n.pos,a]);l&&p.mapAxis&&(p.mapAxis.fixTo=[l-p.pos,f]);"undefined"===typeof c||e?(n.setExtremes(void 0,void 0,!1),p.setExtremes(void 0,void 0,!1)):(n.setExtremes(k.x,k.x+k.width,!1),p.setExtremes(k.y,k.y+k.height,!1));this.redraw()}});f(h,"beforeRender",function(){this.mapNavigation=new m(this);this.mapNavigation.update()});a.MapNavigation=m});y(a,"parts-map/MapPointer.js",
[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,h){var q=h.extend,m=h.pick;h=h.wrap;a=a.Pointer;q(a.prototype,{onContainerDblClick:function(a){var f=this.chart;a=this.normalize(a);f.options.mapNavigation.enableDoubleClickZoomTo?f.pointer.inClass(a.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(.5,f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var f=
this.chart;a=this.normalize(a);var h=a.detail||-(a.wheelDelta/120);f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(Math.pow(f.options.mapNavigation.mouseWheelSensitivity,h),f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)}});h(a.prototype,"zoomOption",function(a){var f=this.chart.options.mapNavigation;m(f.enableTouchZoom,f.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});h(a.prototype,"pinchTranslate",function(a,
h,m,q,z,u,c){a.call(this,h,m,q,z,u,c);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=q.scaleX>q.scaleY,this.pinchTranslateDirection(!a,h,m,q,z,u,c,a?q.scaleX:q.scaleY))})});y(a,"parts-map/MapSeries.js",[a["parts/Globals.js"],a["mixins/legend-symbol.js"],a["parts/Point.js"],a["parts/SVGRenderer.js"],a["parts/Utilities.js"]],function(a,h,q,m,f){var z=f.extend,B=f.fireEvent,C=f.getNestedProperty,x=f.isArray,u=f.isNumber,c=f.merge,n=f.objectEach,w=f.pick,g=f.seriesType,l=f.splat,A=a.colorMapPointMixin,
p=a.noop,k=a.Series,e=a.seriesTypes;g("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},
c(a.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:p,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(b){b=k.prototype.setOptions.call(this,b);var d=b.joinBy;null===d&&(d="_i");d=this.joinBy=l(d);d[1]||(d[1]=d[0]);return b},getBox:function(b){var d=Number.MAX_VALUE,e=-d,c=d,k=-d,f=d,g=d,n=this.xAxis,l=this.yAxis,p;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path?b.path=a.splitPath(b.path):"M"===b.path[0]&&
(b.path=m.prototype.pathToSegments(b.path));var t=b.path||[],v=-d,r=d,n=-d,l=d,h=b.properties;b._foundBox||(t.forEach(function(b){var d=b[b.length-2];b=b[b.length-1];"number"===typeof d&&"number"===typeof b&&(r=Math.min(r,d),v=Math.max(v,d),l=Math.min(l,b),n=Math.max(n,b))}),b._midX=r+(v-r)*w(b.middleX,h&&h["hc-middle-x"],.5),b._midY=l+(n-l)*w(b.middleY,h&&h["hc-middle-y"],.5),b._maxX=v,b._minX=r,b._maxY=n,b._minY=l,b.labelrank=w(b.labelrank,(v-r)*(n-l)),b._foundBox=!0);e=Math.max(e,b._maxX);c=Math.min(c,
b._minX);k=Math.max(k,b._maxY);f=Math.min(f,b._minY);g=Math.min(b._maxX-b._minX,b._maxY-b._minY,g);p=!0}});p&&(this.minY=Math.min(f,w(this.minY,d)),this.maxY=Math.max(k,w(this.maxY,-d)),this.minX=Math.min(c,w(this.minX,d)),this.maxX=Math.max(e,w(this.maxX,-d)),n&&"undefined"===typeof n.options.minRange&&(n.minRange=Math.min(5*g,(this.maxX-this.minX)/5,n.minRange||d)),l&&"undefined"===typeof l.options.minRange&&(l.minRange=Math.min(5*g,(this.maxY-this.minY)/5,l.minRange||d)))},hasData:function(){return!!this.processedXData.length},
getExtremes:function(){var b=k.prototype.getExtremes.call(this,this.valueData),d=b.dataMin;b=b.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);u(d)&&(this.valueMin=d);u(b)&&(this.valueMax=b);return{dataMin:this.minY,dataMax:this.maxY}},translatePath:function(b){var d=this.xAxis,e=this.yAxis,c=d.min,a=d.transA,k=d.minPixelPadding,f=e.min,g=e.transA,n=e.minPixelPadding,l=[];b&&b.forEach(function(b){"M"===b[0]?l.push(["M",(b[1]-(c||0))*a+k,(b[2]-(f||0))*g+n]):"L"===b[0]?
l.push(["L",(b[1]-(c||0))*a+k,(b[2]-(f||0))*g+n]):"C"===b[0]?l.push(["C",(b[1]-(c||0))*a+k,(b[2]-(f||0))*g+n,(b[3]-(c||0))*a+k,(b[4]-(f||0))*g+n,(b[5]-(c||0))*a+k,(b[6]-(f||0))*g+n]):"Q"===b[0]?l.push(["Q",(b[1]-(c||0))*a+k,(b[2]-(f||0))*g+n,(b[3]-(c||0))*a+k,(b[4]-(f||0))*g+n]):"Z"===b[0]&&l.push(["Z"])});return l},setData:function(b,d,e,f){var g=this.options,t=this.chart.options.chart,r=t&&t.map,l=g.mapData,p=this.joinBy,h=g.keys||this.pointArrayMap,A=[],m={},w=this.chart.mapTransforms;!l&&r&&(l=
"string"===typeof r?a.maps[r]:r);b&&b.forEach(function(d,e){var c=0;if(u(d))b[e]={value:d};else if(x(d)){b[e]={};!g.keys&&d.length>h.length&&"string"===typeof d[0]&&(b[e]["hc-key"]=d[0],++c);for(var a=0;a<h.length;++a,++c)h[a]&&"undefined"!==typeof d[c]&&(0<h[a].indexOf(".")?q.prototype.setNestedProperty(b[e],d[c],h[a]):b[e][h[a]]=d[c])}p&&"_i"===p[0]&&(b[e]._i=e)});this.getBox(b);(this.chart.mapTransforms=w=t&&t.mapTransforms||l&&l["hc-transform"]||w)&&n(w,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),
b.sinAngle=Math.sin(b.rotation))});if(l){"FeatureCollection"===l.type&&(this.mapTitle=l.title,l=a.geojson(l,this.type,this));this.mapData=l;this.mapMap={};for(w=0;w<l.length;w++)t=l[w],r=t.properties,t._i=w,p[0]&&r&&r[p[0]]&&(t[p[0]]=r[p[0]]),m[t[p[0]]]=t;this.mapMap=m;if(b&&p[1]){var z=p[1];b.forEach(function(b){b=C(z,b);m[b]&&A.push(m[b])})}if(g.allAreas){this.getBox(l);b=b||[];if(p[1]){var D=p[1];b.forEach(function(b){A.push(C(D,b))})}A="|"+A.map(function(b){return b&&b[p[0]]}).join("|")+"|";l.forEach(function(d){p[0]&&
-1!==A.indexOf("|"+d[p[0]]+"|")||(b.push(c(d,{value:null})),f=!1)})}else this.getBox(A)}k.prototype.setData.call(this,b,d,e,f)},drawGraph:p,drawDataLabels:p,doFullTranslate:function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var b=this,d=b.xAxis,e=b.yAxis,c=b.doFullTranslate();b.generatePoints();b.data.forEach(function(a){u(a._midX)&&u(a._midY)&&(a.plotX=d.toPixels(a._midX,!0),a.plotY=e.toPixels(a._midY,!0));c&&(a.shapeType="path",
a.shapeArgs={d:b.translatePath(a.path)})});B(b,"afterTranslate")},pointAttribs:function(b,d){d=b.series.chart.styledMode?this.colorAttribs(b):e.column.prototype.pointAttribs.call(this,b,d);d["stroke-width"]=w(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return d},drawPoints:function(){var b=this,d=b.xAxis,c=b.yAxis,a=b.group,k=b.chart,f=k.renderer,g=this.baseTrans;b.transformGroup||(b.transformGroup=f.g().attr({scaleX:1,scaleY:1}).add(a),b.transformGroup.survive=
!0);if(b.doFullTranslate())k.hasRendered&&!k.styledMode&&b.points.forEach(function(d){d.shapeArgs&&(d.shapeArgs.fill=b.pointAttribs(d,d.state).fill)}),b.group=b.transformGroup,e.column.prototype.drawPoints.apply(b),b.group=a,b.points.forEach(function(d){if(d.graphic){var e="";d.name&&(e+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(e+=" highcharts-key-"+d.properties["hc-key"].toLowerCase());e&&d.graphic.addClass(e);k.styledMode&&d.graphic.css(b.pointAttribs(d,
d.selected&&"select"||void 0))}}),this.baseTrans={originX:d.min-d.minPixelPadding/d.transA,originY:c.min-c.minPixelPadding/c.transA+(c.reversed?0:c.len/c.transA),transAX:d.transA,transAY:c.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1});else{var l=d.transA/g.transAX;var n=c.transA/g.transAY;var p=d.toPixels(g.originX,!0);var h=c.toPixels(g.originY,!0);.99<l&&1.01>l&&.99<n&&1.01>n&&(n=l=1,p=Math.round(p),h=Math.round(h));var u=this.transformGroup;if(k.renderer.globalAnimation){var A=
u.attr("translateX");var m=u.attr("translateY");var q=u.attr("scaleX");var z=u.attr("scaleY");u.attr({animator:0}).animate({animator:1},{step:function(b,d){u.attr({translateX:A+(p-A)*d.pos,translateY:m+(h-m)*d.pos,scaleX:q+(l-q)*d.pos,scaleY:z+(n-z)*d.pos})}})}else u.attr({translateX:p,translateY:h,scaleX:l,scaleY:n})}k.styledMode||a.element.setAttribute("stroke-width",w(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(l||1));this.drawMapDataLabels()},drawMapDataLabels:function(){k.prototype.drawDataLabels.call(this);
this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var b=this,d=k.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?setTimeout(function(){d.call(b)}):d.call(b)},animate:function(b){var d=this.options.animation,e=this.group,c=this.xAxis,a=this.yAxis,k=c.pos,f=a.pos;this.chart.renderer.isSVG&&(!0===d&&(d={duration:1E3}),b?e.attr({translateX:k+c.len/2,translateY:f+a.len/2,scaleX:.001,scaleY:.001}):e.animate({translateX:k,translateY:f,scaleX:1,scaleY:1},d))},
animateDrilldown:function(b){var d=this.chart.plotBox,e=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],c=e.bBox,a=this.chart.options.drilldown.animation;b||(b=Math.min(c.width/d.width,c.height/d.height),e.shapeArgs={scaleX:b,scaleY:b,translateX:c.x,translateY:c.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(e.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},a)}))},drawLegendSymbol:h.drawRectangle,animateDrillupFrom:function(b){e.column.prototype.animateDrillupFrom.call(this,
b)},animateDrillupTo:function(b){e.column.prototype.animateDrillupTo.call(this,b)}}),z({applyOptions:function(b,d){var e=this.series;b=q.prototype.applyOptions.call(this,b,d);d=e.joinBy;e.mapData&&e.mapMap&&(d=q.prototype.getNestedProperty.call(b,d[1]),(d="undefined"!==typeof d&&e.mapMap[d])?(e.xyFromShape&&(b.x=d._midX,b.y=d._midY),z(b,d)):b.value=b.value||null);return b},onMouseOver:function(b){f.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)q.prototype.onMouseOver.call(this,
b);else this.series.onMouseOut(b)},zoomTo:function(){var b=this.series;b.xAxis.setExtremes(this._minX,this._maxX,!1);b.yAxis.setExtremes(this._minY,this._maxY,!1);b.chart.redraw()}},A));""});y(a,"parts-map/MapLineSeries.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,h){h=h.seriesType;var q=a.seriesTypes;h("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,f){a=q.map.prototype.pointAttribs.call(this,
a,f);a.fill=this.options.fillColor;return a},drawLegendSymbol:q.line.prototype.drawLegendSymbol});""});y(a,"parts-map/MapPointSeries.js",[a["parts/Globals.js"]],function(a){var h=a.merge,q=a.Point,m=a.Series;a=a.seriesType;a("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){m.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},
{applyOptions:function(a,m){a="undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?h(a,this.series.chart.fromLatLonToPoint(a)):a;return q.prototype.applyOptions.call(this,a,m)}});""});y(a,"parts-more/BubbleLegend.js",[a["parts/Chart.js"],a["parts/Color.js"],a["parts/Globals.js"],a["parts/Legend.js"],a["parts/Utilities.js"]],function(a,h,q,m,f){var z=h.parse;h=f.addEvent;var B=f.arrayMax,C=f.arrayMin,x=f.isNumber,u=f.merge,c=f.objectEach,n=f.pick,w=f.stableSort,g=f.wrap;"";var l=q.Series,A=q.noop,
p=q.setOptions;p({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});p=
function(){function a(e,b){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=A;this.init(e,b)}a.prototype.init=function(e,b){this.options=e;this.visible=!0;this.chart=b.chart;this.legend=b};a.prototype.addToLegend=function(e){e.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(e){var b=
this.chart,d=this.options,a=n(e.options.itemDistance,20),c=d.ranges;var k=d.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(d.labels.style.fontSize.toString()+"px");c&&c.length&&x(c[0].value)?(w(c,function(b,d){return d.value-b.value}),this.ranges=c,this.setOptions(),this.render(),b=this.getMaxLabelSize(),c=this.ranges[0].radius,e=2*c,k=k-c+b.width,k=0<k?k:0,this.maxLabel=b,this.movementX="left"===d.labels.align?k:0,this.legendItemWidth=e+k+a,this.legendItemHeight=e+this.fontMetrics.h/2):
e.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,b=this.options,d=this.chart.series[b.seriesIndex],c=this.legend.baseline,k={"z-index":b.zIndex,"stroke-width":b.borderWidth},g={"z-index":b.zIndex,"stroke-width":b.connectorWidth},f=this.getLabelStyles(),l=d.options.marker.fillOpacity,p=this.chart.styledMode;a.forEach(function(e,t){p||(k.stroke=n(e.borderColor,b.borderColor,d.color),k.fill=n(e.color,b.color,1!==l?z(d.color).setOpacity(l).get("rgba"):d.color),
g.stroke=n(e.connectorColor,b.connectorColor,d.color));a[t].radius=this.getRangeRadius(e.value);a[t]=u(a[t],{center:a[0].radius-a[t].radius+c});p||u(!0,a[t],{bubbleStyle:u(!1,k),connectorStyle:u(!1,g),labelStyle:f})},this)};a.prototype.getLabelStyles=function(){var a=this.options,b={},d="left"===a.labels.align,k=this.legend.options.rtl;c(a.labels.style,function(d,a){"color"!==a&&"fontSize"!==a&&"z-index"!==a&&(b[a]=d)});return u(!1,b,{"font-size":a.labels.style.fontSize,fill:n(a.labels.style.color,
"#000000"),"z-index":a.zIndex,align:k||d?"right":"left"})};a.prototype.getRangeRadius=function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,b=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=
0;this.legendSymbol.translateY=0;this.ranges.forEach(function(d){d.value>=b&&this.renderRange(d)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var b=this.options,d=b.labels,c=this.chart.renderer,e=this.symbols,k=e.labels,g=a.center,f=Math.abs(a.radius),l=b.connectorDistance||0,n=d.align,p=d.style.fontSize;l=this.legend.options.rtl||"left"===n?-l:l;d=b.connectorWidth;var h=this.ranges[0].radius||
0,u=g-f-b.borderWidth/2+d/2;p=p/2-(this.fontMetrics.h-p)/2;var A=c.styledMode;"center"===n&&(l=0,b.connectorDistance=0,a.labelStyle.align="center");n=u+b.labels.y;var m=h+l+b.labels.x;e.bubbleItems.push(c.circle(h,g+((u%1?1:.5)-(d%2?0:.5)),f).attr(A?{}:a.bubbleStyle).addClass((A?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendSymbol));e.connectors.push(c.path(c.crispLine([["M",h,u],["L",h+l,u]],b.connectorWidth)).attr(A?{}:
a.connectorStyle).addClass((A?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendSymbol));a=c.text(this.formatLabel(a),m,n+p).attr(A?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);k.push(a);a.placed=!0;a.alignAttr={x:m,y:n+p}};a.prototype.getMaxLabelSize=function(){var a,b;this.symbols.labels.forEach(function(d){b=d.getBBox(!0);a=a?b.width>a.width?b:a:
b});return a||{}};a.prototype.formatLabel=function(a){var b=this.options,d=b.labels.formatter;b=b.labels.format;var c=this.chart.numberFormatter;return b?f.format(b,a):d?d.call(a):c(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),b.labels.forEach(function(a,c){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[c].show():b.connectors[c].hide()}))};a.prototype.getRanges=function(){var a=
this.legend.bubbleLegend,b=a.options.ranges,d,c=Number.MAX_VALUE,k=-Number.MAX_VALUE;a.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(d=b.zData.filter(x),d.length&&(c=n(b.options.zMin,Math.min(c,Math.max(C(d),!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),k=n(b.options.zMax,Math.max(k,B(d)))))});var g=c===k?[{value:k}]:[{value:c},{value:(c+k)/2},{value:k,autoRanges:!0}];b.length&&b[0].radius&&g.reverse();g.forEach(function(a,d){b&&b[d]&&(g[d]=u(!1,b[d],a))});
return g};a.prototype.predictBubbleSizes=function(){var a=this.chart,b=this.fontMetrics,d=a.legend.options,c="horizontal"===d.layout,k=c?a.legend.lastLineHeight:0,g=a.plotSizeX,f=a.plotSizeY,l=a.series[this.options.seriesIndex];a=Math.ceil(l.minPxSize);var n=Math.ceil(l.maxPxSize);l=l.options.maxSize;var p=Math.min(f,g);if(d.floating||!/%$/.test(l))b=n;else if(l=parseFloat(l),b=(p+k-b.h/2)*l/100/(l/100+1),c&&f-b>=g||!c&&g-b>=f)b=n;return[a,Math.ceil(b)]};a.prototype.updateRanges=function(a,b){var d=
this.legend.options.bubbleLegend;d.minSize=a;d.maxSize=b;d.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())};return a}();h(m,"afterGetAllItems",function(a){var c=this.bubbleLegend,b=this.options,d=b.bubbleLegend,k=this.chart.getVisibleBubbleSeriesIndex();c&&c.ranges&&c.ranges.length&&(d.ranges.length&&
(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(c));0<=k&&b.enabled&&d.enabled&&(d.seriesIndex=k,this.bubbleLegend=new q.BubbleLegend(d,this),this.bubbleLegend.addToLegend(a.allItems))});a.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,c=0;c<a.length;){if(a[c]&&a[c].isBubble&&a[c].visible&&a[c].zData.length)return c;c++}return-1};m.prototype.getLinesHeights=function(){var a=this.allItems,c=[],b=a.length,d,g=0;for(d=0;d<b;d++)if(a[d].legendItemHeight&&(a[d].itemHeight=
a[d].legendItemHeight),a[d]===a[b-1]||a[d+1]&&a[d]._legendItemPos[1]!==a[d+1]._legendItemPos[1]){c.push({height:0});var l=c[c.length-1];for(g;g<=d;g++)a[g].itemHeight>l.height&&(l.height=a[g].itemHeight);l.step=d}return c};m.prototype.retranslateItems=function(a){var c,b,d,k=this.options.rtl,g=0;this.allItems.forEach(function(e,l){c=e.legendGroup.translateX;b=e._legendItemPos[1];if((d=e.movementX)||k&&e.ranges)d=k?c-e.options.maxSize/2:c+d,e.legendGroup.attr({translateX:d});l>a[g].step&&g++;e.legendGroup.attr({translateY:Math.round(b+
a[g].height/2)});e._legendItemPos[1]=b+a[g].height/2})};h(l,"legendItemClick",function(){var a=this.chart,c=this.visible,b=this.chart.legend;b&&b.bubbleLegend&&(this.visible=!c,this.ignoreSeries=c,a=0<=a.getVisibleBubbleSeriesIndex(),b.bubbleLegend.visible!==a&&(b.update({bubbleLegend:{enabled:a}}),b.bubbleLegend.visible=a),this.visible=c)});g(a.prototype,"drawChartBox",function(a,e,b){var d=this.legend,g=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&
g){var k=d.bubbleLegend.options;g=d.bubbleLegend.predictBubbleSizes();d.bubbleLegend.updateRanges(g[0],g[1]);k.placed||(d.group.placed=!1,d.allItems.forEach(function(b){b.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();k.placed||(b.setScale(),b.updateNames(),c(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});k.placed=!0;this.getMargins();a.call(this,e,b);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else a.call(this,
e,b),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))});q.BubbleLegend=p;return q.BubbleLegend});y(a,"parts-more/BubbleSeries.js",[a["parts/Globals.js"],a["parts/Color.js"],a["parts/Point.js"],a["parts/Utilities.js"]],function(a,h,q,m){var f=h.parse,z=m.arrayMax,B=m.arrayMin,C=m.clamp,x=m.extend,u=m.isNumber,c=m.pick,n=m.pInt;h=m.seriesType;m=a.Axis;var w=a.noop,g=a.Series,l=a.seriesTypes;h("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},
inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,
isBubble:!0,pointAttribs:function(a,c){var k=this.options.marker.fillOpacity;a=g.prototype.pointAttribs.call(this,a,c);1!==k&&(a.fill=f(a.fill).setOpacity(k).get("rgba"));return a},getRadii:function(a,c,g){var e=this.zData,b=this.yData,d=g.minPxSize,k=g.maxPxSize,l=[];var f=0;for(g=e.length;f<g;f++){var n=e[f];l.push(this.getRadius(a,c,d,k,n,b[f]))}this.radii=l},getRadius:function(a,c,g,e,b,d){var k=this.options,l="width"!==k.sizeBy,f=k.zThreshold,n=c-a,p=.5;if(null===d||null===b)return null;if(u(b)){k.sizeByAbsoluteValue&&
(b=Math.abs(b-f),n=Math.max(c-f,Math.abs(a-f)),a=0);if(b<a)return g/2-1;0<n&&(p=(b-a)/n)}l&&0<=p&&(p=Math.sqrt(p));return Math.ceil(g+p*(e-g))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var c=a.graphic;if(c&&c.width){var e={x:c.x,y:c.y,width:c.width,height:c.height};c.attr({x:a.plotX,y:a.plotY,width:1,height:1});c.animate(e,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,
c=this.data,g=this.radii;l.scatter.prototype.translate.call(this);for(a=c.length;a--;){var e=c[a];var b=g?g[a]:0;u(b)&&b>=this.minPxSize/2?(e.marker=x(e.marker,{radius:b,width:2*b,height:2*b}),e.dlBox={x:e.plotX-b,y:e.plotY-b,width:2*b,height:2*b}):e.shapeArgs=e.plotY=e.dlBox=void 0}},alignDataLabel:l.column.prototype.alignDataLabel,buildKDTree:w,applyZones:w},{haloPath:function(a){return q.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});m.prototype.beforePadding=
function(){var a=this,g=this.len,l=this.chart,e=0,b=g,d=this.isXAxis,f=d?"xData":"yData",h=this.min,m={},w=Math.min(l.plotWidth,l.plotHeight),q=Number.MAX_VALUE,x=-Number.MAX_VALUE,D=this.max-h,y=g/D,E=[];this.series.forEach(function(b){var e=b.options;!b.bubblePadding||!b.visible&&l.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,E.push(b),d&&(["minSize","maxSize"].forEach(function(b){var a=e[b],c=/%$/.test(a);a=n(a);m[b]=c?w*a/100:a}),b.minPxSize=m.minSize,b.maxPxSize=Math.max(m.maxSize,
m.minSize),b=b.zData.filter(u),b.length&&(q=c(e.zMin,C(B(b),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,q)),x=c(e.zMax,Math.max(x,z(b))))))});E.forEach(function(c){var g=c[f],l=g.length;d&&c.getRadii(q,x,c);if(0<D)for(;l--;)if(u(g[l])&&a.dataMin<=g[l]&&g[l]<=a.max){var k=c.radii?c.radii[l]:0;e=Math.min((g[l]-h)*y-k,e);b=Math.max((g[l]-h)*y+k,b)}});E.length&&0<D&&!this.logarithmic&&(b-=g,y*=(g+Math.max(0,e)-Math.min(b,g))/g,[["min","userMin",e],["max","userMax",b]].forEach(function(b){"undefined"===
typeof c(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/y)}))};""});y(a,"parts-map/MapBubbleSeries.js",[a["parts/Globals.js"],a["parts/Point.js"],a["parts/Utilities.js"]],function(a,h,q){var m=q.merge;q=q.seriesType;var f=a.seriesTypes;f.bubble&&q("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:f.map.prototype.getMapData,getBox:f.map.prototype.getBox,setData:f.map.prototype.setData,setOptions:f.map.prototype.setOptions},
{applyOptions:function(a,q){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?h.prototype.applyOptions.call(this,m(a,this.series.chart.fromLatLonToPoint(a)),q):f.map.prototype.pointClass.prototype.applyOptions.call(this,a,q)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});y(a,"parts-map/HeatmapSeries.js",[a["parts/Globals.js"],a["mixins/legend-symbol.js"],a["parts/SVGRenderer.js"],a["parts/Utilities.js"]],function(a,h,q,m){var f=m.clamp,z=m.extend,B=m.fireEvent,
y=m.isNumber,x=m.merge,u=m.pick;m=m.seriesType;"";var c=a.colorMapPointMixin,n=a.Series,w=q.prototype.symbols;m("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,
brightness:.2}}},x(a.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){n.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=u(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;z(w,{ellipse:w.circle,rect:w.square})},getSymbol:n.prototype.getSymbol,setClip:function(a){var c=this.chart;n.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&
this.sharedClipKey?c[this.sharedClipKey]:c.clipRect)},translate:function(){var a=this.options,c=a.marker&&a.marker.symbol||"",f=w[c]?c:"rect";a=this.options;var n=-1!==["circle","square"].indexOf(f);this.generatePoints();this.points.forEach(function(a){var e=a.getCellAttributes(),b={x:Math.min(e.x1,e.x2),y:Math.min(e.y1,e.y2),width:Math.max(Math.abs(e.x2-e.x1),0),height:Math.max(Math.abs(e.y2-e.y1),0)};var d=a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");if(n){var g=Math.abs(b.width-
b.height);b.x=Math.min(e.x1,e.x2)+(b.width<b.height?0:g/2);b.y=Math.min(e.y1,e.y2)+(b.width<b.height?g/2:0);b.width=b.height=Math.min(b.width,b.height)}g={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:x(!0,b,{d:w[f](b.x,b.y,b.width,b.height)})};d&&(a.marker={width:b.width,height:b.height});z(a,g)});B(this,"afterTranslate")},pointAttribs:function(c,l){var g=n.prototype.pointAttribs.call(this,c,l),f=this.options||{},k=this.chart.options.plotOptions||{},e=k.series||
{},b=k.heatmap||{};k=f.borderColor||b.borderColor||e.borderColor;e=f.borderWidth||b.borderWidth||e.borderWidth||g["stroke-width"];g.stroke=c&&c.marker&&c.marker.lineColor||f.marker&&f.marker.lineColor||k||this.color;g["stroke-width"]=e;l&&(c=x(f.states[l],f.marker&&f.marker.states[l],c.options.states&&c.options.states[l]||{}),l=c.brightness,g.fill=c.color||a.color(g.fill).brighten(l||0).get(),g.stroke=c.lineColor);return g},markerAttribs:function(a,c){var g=a.marker||{},f=this.options.marker||{},
l=a.shapeArgs||{},e={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(c){var b=f.states[c]||{};var d=g.states&&g.states[c]||{};[["width","x"],["height","y"]].forEach(function(a){e[a[0]]=(d[a[0]]||b[a[0]]||l[a[0]])+(d[a[0]+"Plus"]||b[a[0]+"Plus"]||0);e[a[1]]=l[a[1]]+(l[a[0]]-e[a[0]])/2})}return c?e:l},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)n.prototype.drawPoints.call(this),this.points.forEach(function(c){c.graphic&&c.graphic[a.chart.styledMode?"css":
"animate"](a.colorAttribs(c))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,c){return n.prototype.getValidPoints.call(this,a,c,!0)},getBox:a.noop,drawLegendSymbol:h.drawRectangle,alignDataLabel:a.seriesTypes.column.prototype.alignDataLabel,getExtremes:function(){var a=n.prototype.getExtremes.call(this,this.valueData),c=a.dataMin;a=a.dataMax;y(c)&&(this.valueMin=c);y(a)&&(this.valueMax=a);return n.prototype.getExtremes.call(this)}}),x(c,{applyOptions:function(c,
f){c=a.Point.prototype.applyOptions.call(this,c,f);c.formatPrefix=c.isNull||null===c.value?"null":"point";return c},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]},getCellAttributes:function(){var a=this.series,c=a.options,n=(c.colsize||1)/2,h=(c.rowsize||1)/2,k=a.xAxis,e=a.yAxis,b=this.options.marker||a.options.marker;
a=a.pointPlacementToXValue();var d=u(this.pointPadding,c.pointPadding,0),m={x1:f(Math.round(k.len-(k.translate(this.x-n,!1,!0,!1,!0,-a)||0)),-k.len,2*k.len),x2:f(Math.round(k.len-(k.translate(this.x+n,!1,!0,!1,!0,-a)||0)),-k.len,2*k.len),y1:f(Math.round(e.translate(this.y-h,!1,!0,!1,!0)||0),-e.len,2*e.len),y2:f(Math.round(e.translate(this.y+h,!1,!0,!1,!0)||0),-e.len,2*e.len)};[["width","x"],["height","y"]].forEach(function(a){var c=a[0];a=a[1];var e=a+"1",f=a+"2",g=Math.abs(m[e]-m[f]),n=b&&b.lineWidth||
0,k=Math.abs(m[e]+m[f])/2;b[c]&&b[c]<g&&(m[e]=k-b[c]/2-n/2,m[f]=k+b[c]/2+n/2);d&&("y"===a&&(e=f,f=a+"1"),m[e]+=d,m[f]-=d)});return m}}));""});y(a,"parts-map/GeoJSON.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,h){function q(a,c){var f,h=!1,g=a.x,l=a.y;a=0;for(f=c.length-1;a<c.length;f=a++){var m=c[a][1]>l;var p=c[f][1]>l;m!==p&&g<(c[f][0]-c[a][0])*(l-c[a][1])/(c[f][1]-c[a][1])+c[a][0]&&(h=!h)}return h}var m=h.error,f=h.extend,z=h.format,y=h.merge;h=h.wrap;var C=a.Chart,x=a.win;C.prototype.transformFromLatLon=
function(a,c){var f,h=(null===(f=this.userOptions.chart)||void 0===f?void 0:f.proj4)||x.proj4;if(!h)return m(21,!1,this),{x:0,y:null};a=h(c.crs,[a.lon,a.lat]);f=c.cosAngle||c.rotation&&Math.cos(c.rotation);h=c.sinAngle||c.rotation&&Math.sin(c.rotation);a=c.rotation?[a[0]*f+a[1]*h,-a[0]*h+a[1]*f]:a;return{x:((a[0]-(c.xoffset||0))*(c.scale||1)+(c.xpan||0))*(c.jsonres||1)+(c.jsonmarginX||0),y:(((c.yoffset||0)-a[1])*(c.scale||1)+(c.ypan||0))*(c.jsonres||1)-(c.jsonmarginY||0)}};C.prototype.transformToLatLon=
function(a,c){if("undefined"===typeof x.proj4)m(21,!1,this);else{a={x:((a.x-(c.jsonmarginX||0))/(c.jsonres||1)-(c.xpan||0))/(c.scale||1)+(c.xoffset||0),y:((-a.y-(c.jsonmarginY||0))/(c.jsonres||1)+(c.ypan||0))/(c.scale||1)+(c.yoffset||0)};var f=c.cosAngle||c.rotation&&Math.cos(c.rotation),h=c.sinAngle||c.rotation&&Math.sin(c.rotation);c=x.proj4(c.crs,"WGS84",c.rotation?{x:a.x*f+a.y*-h,y:a.x*h+a.y*f}:a);return{lat:c.y,lon:c.x}}};C.prototype.fromPointToLatLon=function(a){var c=this.mapTransforms,f;if(c){for(f in c)if(Object.hasOwnProperty.call(c,
f)&&c[f].hitZone&&q({x:a.x,y:-a.y},c[f].hitZone.coordinates[0]))return this.transformToLatLon(a,c[f]);return this.transformToLatLon(a,c["default"])}m(22,!1,this)};C.prototype.fromLatLonToPoint=function(a){var c=this.mapTransforms,f;if(!c)return m(22,!1,this),{x:0,y:null};for(f in c)if(Object.hasOwnProperty.call(c,f)&&c[f].hitZone){var h=this.transformFromLatLon(a,c[f]);if(q({x:h.x,y:-h.y},c[f].hitZone.coordinates[0]))return h}return this.transformFromLatLon(a,c["default"])};a.geojson=function(a,c,
h){var n=[],g=[],l=function(a){a.forEach(function(a,c){0===c?g.push(["M",a[0],-a[1]]):g.push(["L",a[0],-a[1]])})};c=c||"map";a.features.forEach(function(a){var h=a.geometry,k=h.type;h=h.coordinates;a=a.properties;var e;g=[];"map"===c||"mapbubble"===c?("Polygon"===k?(h.forEach(l),g.push(["Z"])):"MultiPolygon"===k&&(h.forEach(function(a){a.forEach(l)}),g.push(["Z"])),g.length&&(e={path:g})):"mapline"===c?("LineString"===k?l(h):"MultiLineString"===k&&h.forEach(l),g.length&&(e={path:g})):"mappoint"===
c&&"Point"===k&&(e={x:h[0],y:-h[1]});e&&n.push(f(e,{name:a.name||a.NAME,properties:a}))});h&&a.copyrightShort&&(h.chart.mapCredits=z(h.chart.options.credits.mapText,{geojson:a}),h.chart.mapCreditsFull=z(h.chart.options.credits.mapTextFull,{geojson:a}));return n};h(C.prototype,"addCredits",function(a,c){c=y(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});y(a,"parts-map/Map.js",[a["parts/Chart.js"],
a["parts/Globals.js"],a["parts/SVGRenderer.js"],a["parts/Utilities.js"]],function(a,h,q,m){function f(a,f,h,g,l,m,p,k){return[["M",a+l,f],["L",a+h-m,f],["C",a+h-m/2,f,a+h,f+m/2,a+h,f+m],["L",a+h,f+g-p],["C",a+h,f+g-p/2,a+h-p/2,f+g,a+h-p,f+g],["L",a+k,f+g],["C",a+k/2,f+g,a,f+g-k/2,a,f+g-k],["L",a,f+l],["C",a,f+l/2,a+l/2,f,a+l,f],["Z"]]}var y=m.extend,z=m.merge,C=m.pick;m=h.defaultOptions;var x=h.Renderer,u=h.VMLRenderer;y(m.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});m.mapNavigation={buttonOptions:{alignTo:"plotBox",
align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};h.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));
return q.prototype.pathToSegments(a)};h.maps={};q.prototype.symbols.topbutton=function(a,h,m,g,l){return f(a-1,h-1,m,g,l.r,l.r,0,0)};q.prototype.symbols.bottombutton=function(a,h,m,g,l){return f(a-1,h-1,m,g,0,0,l.r,l.r)};x===u&&["topbutton","bottombutton"].forEach(function(a){u.prototype.symbols[a]=q.prototype.symbols[a]});h.Map=h.mapChart=function(c,f,m){var g="string"===typeof c||c.nodeName,l=arguments[g?1:0],n=l,p={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},k=h.getOptions().credits;
var e=l.series;l.series=null;l=z({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:C(k.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:C(k.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:p,yAxis:z(p,{reversed:!0})},l,{chart:{inverted:!1,alignTicks:!1}});l.series=n.series=e;return g?new a(c,l,m):new a(l,f)}});y(a,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map