/*
 Highstock JS v8.1.0 (2020-05-12)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?(p["default"]=p,module.exports=p):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(J){p(J);p.Highcharts=J;return p}):p("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(p){function J(p,n,y,u){p.hasOwnProperty(n)||(p[n]=u.apply(null,y))}p=p?p._modules:{};J(p,"parts/NavigatorAxis.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n){var y=p.isTouchDevice,u=n.addEvent,C=n.correctFloat,
h=n.defined,q=n.isNumber,A=n.pick,d=function(){function d(d){this.axis=d}d.prototype.destroy=function(){this.axis=void 0};d.prototype.toFixedRange=function(d,D,x,v){var w=this.axis,r=w.chart;r=r&&r.fixedRange;var l=(w.pointRange||0)/2;d=A(x,w.translate(d,!0,!w.horiz));D=A(v,w.translate(D,!0,!w.horiz));w=r&&(D-d)/r;h(x)||(d=C(d+l));h(v)||(D=C(D-l));.7<w&&1.3>w&&(v?d=D-r:D=d+r);q(d)&&q(D)||(d=D=void 0);return{min:d,max:D}};return d}();return function(){function q(){}q.compose=function(q){q.keepProps.push("navigatorAxis");
u(q,"init",function(){this.navigatorAxis||(this.navigatorAxis=new d(this))});u(q,"zoom",function(d){var x=this.chart.options,v=x.navigator,w=this.navigatorAxis,r=x.chart.pinchType,l=x.rangeSelector;x=x.chart.zoomType;this.isXAxis&&(v&&v.enabled||l&&l.enabled)&&("y"===x?d.zoomed=!1:(!y&&"xy"===x||y&&"xy"===r)&&this.options.range&&(v=w.previousZoom,h(d.newMin)?w.previousZoom=[this.min,this.max]:v&&(d.newMin=v[0],d.newMax=v[1],w.previousZoom=void 0)));"undefined"!==typeof d.zoomed&&d.preventDefault()})};
q.AdditionsClass=d;return q}()});J(p,"parts/ScrollbarAxis.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n){var y=n.addEvent,u=n.defined,C=n.pick;return function(){function h(){}h.compose=function(h,n){y(h,"afterInit",function(){var d=this;d.options&&d.options.scrollbar&&d.options.scrollbar.enabled&&(d.options.scrollbar.vertical=!d.horiz,d.options.startOnTick=d.options.endOnTick=!1,d.scrollbar=new n(d.chart.renderer,d.options.scrollbar,d.chart),y(d.scrollbar,"changed",function(h){var q=
C(d.options&&d.options.min,d.min),n=C(d.options&&d.options.max,d.max),x=u(d.dataMin)?Math.min(q,d.min,d.dataMin):q,v=(u(d.dataMax)?Math.max(n,d.max,d.dataMax):n)-x;u(q)&&u(n)&&(d.horiz&&!d.reversed||!d.horiz&&d.reversed?(q=x+v*this.to,x+=v*this.from):(q=x+v*(1-this.from),x+=v*(1-this.to)),C(this.options.liveRedraw,p.svg&&!p.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===h.DOMType||!u(h.DOMType)?d.setExtremes(x,q,!0,"mousemove"!==h.DOMType,h):this.setRange(this.from,this.to))}))});y(h,"afterRender",
function(){var d=Math.min(C(this.options.min,this.min),this.min,C(this.dataMin,this.min)),h=Math.max(C(this.options.max,this.max),this.max,C(this.dataMax,this.max)),q=this.scrollbar,n=this.axisTitleMargin+(this.titleOffset||0),x=this.chart.scrollbarsOffsets,v=this.options.margin||0;q&&(this.horiz?(this.opposite||(x[1]+=n),q.position(this.left,this.top+this.height+2+x[1]-(this.opposite?v:0),this.width,this.height),this.opposite||(x[1]+=v),n=1):(this.opposite&&(x[0]+=n),q.position(this.left+this.width+
2+x[0]-(this.opposite?0:v),this.top,this.width,this.height),this.opposite&&(x[0]+=v),n=0),x[n]+=q.size+q.options.margin,isNaN(d)||isNaN(h)||!u(this.min)||!u(this.max)||this.min===this.max?q.setRange(0,1):(x=(this.min-d)/(h-d),d=(this.max-d)/(h-d),this.horiz&&!this.reversed||!this.horiz&&this.reversed?q.setRange(x,d):q.setRange(1-d,1-x)))});y(h,"afterGetOffset",function(){var d=this.horiz?2:1,h=this.scrollbar;h&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[d]+=h.size+h.options.margin)})};
return h}()});J(p,"parts/Scrollbar.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/ScrollbarAxis.js"],p["parts/Utilities.js"]],function(p,n,y,u){var C=u.addEvent,h=u.correctFloat,q=u.defined,A=u.destroyObjectProperties,d=u.fireEvent,H=u.merge,I=u.pick,D=u.removeEvent;u=n.defaultOptions;var x=n.hasTouch,v=n.isTouchDevice,w=n.swapXY=function(l,e){e&&l.forEach(function(b){for(var a=b.length,e,f=0;f<a;f+=2)e=b[f+1],"number"===typeof e&&(b[f+1]=b[f+2],b[f+2]=e)});return l},r=function(){function l(e,
b,a){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=a;this.options=b;this.renderer=a.renderer;this.init(e,b,a)}l.prototype.addEvents=function(){var e=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,
a=this.scrollbarGroup.element,m=this.track.element,f=this.mouseDownHandler.bind(this),t=this.mouseMoveHandler.bind(this),c=this.mouseUpHandler.bind(this);e=[[b[e[0]].element,"click",this.buttonToMinClick.bind(this)],[b[e[1]].element,"click",this.buttonToMaxClick.bind(this)],[m,"click",this.trackClick.bind(this)],[a,"mousedown",f],[a.ownerDocument,"mousemove",t],[a.ownerDocument,"mouseup",c]];x&&e.push([a,"touchstart",f],[a.ownerDocument,"touchmove",t],[a.ownerDocument,"touchend",c]);e.forEach(function(a){C.apply(null,
a)});this._events=e};l.prototype.buttonToMaxClick=function(e){var b=(this.to-this.from)*I(this.options.step,.2);this.updatePosition(this.from+b,this.to+b);d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};l.prototype.buttonToMinClick=function(e){var b=h(this.to-this.from)*I(this.options.step,.2);this.updatePosition(h(this.from-b),h(this.to-b));d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};l.prototype.cursorToScrollbarPosition=function(e){var b=
this.options;b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(e.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(e.chartY-this.y-this.yOffset)/(this.barWidth-b)}};l.prototype.destroy=function(){var e=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(e){this[e]&&this[e].destroy&&(this[e]=this[e].destroy())},this);e&&this===e.scrollbar&&(e.scrollbar=null,A(e.scrollbarButtons))};l.prototype.drawScrollbarButton=
function(e){var b=this.renderer,a=this.scrollbarButtons,m=this.options,f=this.size;var t=b.g().add(this.group);a.push(t);t=b.rect().addClass("highcharts-scrollbar-button").add(t);this.chart.styledMode||t.attr({stroke:m.buttonBorderColor,"stroke-width":m.buttonBorderWidth,fill:m.buttonBackgroundColor});t.attr(t.crisp({x:-.5,y:-.5,width:f+1,height:f+1,r:m.buttonBorderRadius},t.strokeWidth()));t=b.path(w([["M",f/2+(e?-1:1),f/2-3],["L",f/2+(e?-1:1),f/2+3],["L",f/2+(e?2:-2),f/2]],m.vertical)).addClass("highcharts-scrollbar-arrow").add(a[e]);
this.chart.styledMode||t.attr({fill:m.buttonArrowColor})};l.prototype.init=function(e,b,a){this.scrollbarButtons=[];this.renderer=e;this.userOptions=b;this.options=H(l.defaultOptions,b);this.chart=a;this.size=I(this.options.size,this.options.height);b.enabled&&(this.render(),this.addEvents())};l.prototype.mouseDownHandler=function(e){e=this.chart.pointer.normalize(e);e=this.cursorToScrollbarPosition(e);this.chartX=e.chartX;this.chartY=e.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=
!0};l.prototype.mouseMoveHandler=function(e){var b=this.chart.pointer.normalize(e),a=this.options.vertical?"chartY":"chartX",m=this.initPositions||[];!this.grabbedCenter||e.touches&&0===e.touches[0][a]||(b=this.cursorToScrollbarPosition(b)[a],a=this[a],a=b-a,this.hasDragged=!0,this.updatePosition(m[0]+a,m[1]+a),this.hasDragged&&d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e}))};l.prototype.mouseUpHandler=function(e){this.hasDragged&&d(this,"changed",{from:this.from,
to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};l.prototype.position=function(e,b,a,m){var f=this.options.vertical,t=0,c=this.rendered?"animate":"attr";this.x=e;this.y=b+this.trackBorderWidth;this.width=a;this.xOffset=this.height=m;this.yOffset=t;f?(this.width=this.yOffset=a=t=this.size,this.xOffset=b=0,this.barWidth=m-2*a,this.x=e+=this.options.margin):(this.height=this.xOffset=m=b=this.size,this.barWidth=a-2*m,this.y+=this.options.margin);
this.group[c]({translateX:e,translateY:this.y});this.track[c]({width:a,height:m});this.scrollbarButtons[1][c]({translateX:f?0:a-b,translateY:f?m-t:0})};l.prototype.removeEvents=function(){this._events.forEach(function(e){D.apply(null,e)});this._events.length=0};l.prototype.render=function(){var e=this.renderer,b=this.options,a=this.size,m=this.chart.styledMode,f;this.group=f=e.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=e.rect().addClass("highcharts-scrollbar-track").attr({x:0,
r:b.trackBorderRadius||0,height:a,width:a}).add(f);m||this.track.attr({fill:b.trackBackgroundColor,stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=e.g().add(f);this.scrollbar=e.rect().addClass("highcharts-scrollbar-thumb").attr({height:a,width:a,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=e.path(w([["M",-3,a/4],["L",-3,2*a/3],["M",0,a/4],["L",
0,2*a/3],["M",3,a/4],["L",3,2*a/3]],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);m||(this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth}),this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};l.prototype.setRange=
function(e,b){var a=this.options,m=a.vertical,f=a.minWidth,t=this.barWidth,c,l=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(q(t)){e=Math.max(e,0);var F=Math.ceil(t*e);this.calculatedWidth=c=h(t*Math.min(b,1)-F);c<f&&(F=(t-f+c)*e,c=f);f=Math.floor(F+this.xOffset+this.yOffset);t=c/2-.5;this.from=e;this.to=b;m?(this.scrollbarGroup[l]({translateY:f}),this.scrollbar[l]({height:c}),this.scrollbarRifles[l]({translateY:t}),this.scrollbarTop=f,
this.scrollbarLeft=0):(this.scrollbarGroup[l]({translateX:f}),this.scrollbar[l]({width:c}),this.scrollbarRifles[l]({translateX:t}),this.scrollbarLeft=f,this.scrollbarTop=0);12>=c?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===a.showFull&&(0>=e&&1<=b?this.group.hide():this.group.show());this.rendered=!0}};l.prototype.trackClick=function(e){var b=this.chart.pointer.normalize(e),a=this.to-this.from,m=this.y+this.scrollbarTop,f=this.x+this.scrollbarLeft;this.options.vertical&&b.chartY>
m||!this.options.vertical&&b.chartX>f?this.updatePosition(this.from+a,this.to+a):this.updatePosition(this.from-a,this.to-a);d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};l.prototype.update=function(e){this.destroy();this.init(this.chart.renderer,H(!0,this.options,e),this.chart)};l.prototype.updatePosition=function(e,b){1<b&&(e=h(1-h(b-e)),b=1);0>e&&(b=h(b-e),e=0);this.from=e;this.to=b};l.defaultOptions={height:v?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,
margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return l}();n.Scrollbar||(u.scrollbar=H(!0,r.defaultOptions,u.scrollbar),n.Scrollbar=r,y.compose(p,r));return n.Scrollbar});J(p,"parts/Navigator.js",[p["parts/Axis.js"],p["parts/Color.js"],
p["parts/Globals.js"],p["parts/NavigatorAxis.js"],p["parts/Scrollbar.js"],p["parts/Utilities.js"]],function(p,n,y,u,C,h){n=n.parse;var q=h.addEvent,A=h.clamp,d=h.correctFloat,H=h.defined,I=h.destroyObjectProperties,D=h.erase,x=h.extend,v=h.find,w=h.isArray,r=h.isNumber,l=h.merge,e=h.pick,b=h.removeEvent,a=h.splat;h=y.Chart;var m=y.defaultOptions,f=y.hasTouch,t=y.isTouchDevice,c=y.Series,B=function(a){for(var k=[],z=1;z<arguments.length;z++)k[z-1]=arguments[z];k=[].filter.call(k,r);if(k.length)return Math[a].apply(0,
k)};var F="undefined"===typeof y.seriesTypes.areaspline?"line":"areaspline";x(m,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:n("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:F,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",
[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",
style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});y.Renderer.prototype.symbols["navigator-handle"]=function(a,k,z,f,c){a=c.width/2;k=Math.round(a/3)+.5;c=c.height||0;return[["M",-a-1,.5],["L",a,.5],["L",a,c+.5],["L",-a-1,c+.5],["L",-a-1,.5],["M",-k,4],["L",-k,c-3],["M",k-1,4],["L",k-1,c-3]]};var G=function(){function g(k){this.zoomedMin=
this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(k)}g.prototype.drawHandle=function(k,a,g,c){var z=this.navigatorOptions.handles.height;this.handles[a][c](g?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+
parseInt(k,10)+.5-z)}:{translateX:Math.round(this.left+parseInt(k,10)),translateY:Math.round(this.top+this.height/2-z/2-1)})};g.prototype.drawOutline=function(k,a,g,c){var z=this.navigatorOptions.maskInside,f=this.outline.strokeWidth(),e=f/2,E=f%2/2;f=this.outlineHeight;var t=this.scrollbarHeight||0,b=this.size,m=this.left-t,l=this.top;g?(m-=e,g=l+a+E,a=l+k+E,E=[["M",m+f,l-t-E],["L",m+f,g],["L",m,g],["L",m,a],["L",m+f,a],["L",m+f,l+b+t]],z&&E.push(["M",m+f,g-e],["L",m+f,a+e])):(k+=m+t-E,a+=m+t-E,
l+=e,E=[["M",m,l],["L",k,l],["L",k,l+f],["L",a,l+f],["L",a,l],["L",m+b+2*t,l]],z&&E.push(["M",k-e,l],["L",a+e,l]));this.outline[c]({d:E})};g.prototype.drawMasks=function(k,a,g,f){var z=this.left,c=this.top,E=this.height;if(g){var e=[z,z,z];var t=[c,c+k,c+a];var m=[E,E,E];var b=[k,a-k,this.size-a]}else e=[z,z+k,z+a],t=[c,c,c],m=[k,a-k,this.size-a],b=[E,E,E];this.shades.forEach(function(k,a){k[f]({x:e[a],y:t[a],width:m[a],height:b[a]})})};g.prototype.renderElements=function(){var k=this,a=k.navigatorOptions,
g=a.maskInside,f=k.chart,c=f.renderer,e,t={cursor:f.inverted?"ns-resize":"ew-resize"};k.navigatorGroup=e=c.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!g,g,!g].forEach(function(z,g){k.shades[g]=c.rect().addClass("highcharts-navigator-mask"+(1===g?"-inside":"-outside")).add(e);f.styledMode||k.shades[g].attr({fill:z?a.maskFill:"rgba(0,0,0,0)"}).css(1===g&&t)});k.outline=c.path().addClass("highcharts-navigator-outline").add(e);f.styledMode||k.outline.attr({"stroke-width":a.outlineWidth,
stroke:a.outlineColor});a.handles.enabled&&[0,1].forEach(function(z){a.handles.inverted=f.inverted;k.handles[z]=c.symbol(a.handles.symbols[z],-a.handles.width/2-1,0,a.handles.width,a.handles.height,a.handles);k.handles[z].attr({zIndex:7-z}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][z]).add(e);if(!f.styledMode){var g=a.handles;k.handles[z].attr({fill:g.backgroundColor,stroke:g.borderColor,"stroke-width":g.lineWidth}).css(t)}})};g.prototype.update=function(k){(this.series||
[]).forEach(function(k){k.baseSeries&&delete k.baseSeries.navigatorSeries});this.destroy();l(!0,this.chart.options.navigator,this.options,k);this.init(this.chart)};g.prototype.render=function(k,a,g,f){var z=this.chart,c=this.scrollbarHeight,t,m=this.xAxis,E=m.pointRange||0;var b=m.navigatorAxis.fake?z.xAxis[0]:m;var l=this.navigatorEnabled,B,K=this.rendered;var F=z.inverted;var v=z.xAxis[0].minRange,h=z.xAxis[0].options.maxRange;if(!this.hasDragged||H(g)){k=d(k-E/2);a=d(a+E/2);if(!r(k)||!r(a))if(K)g=
0,f=e(m.width,b.width);else return;this.left=e(m.left,z.plotLeft+c+(F?z.plotWidth:0));this.size=B=t=e(m.len,(F?z.plotHeight:z.plotWidth)-2*c);z=F?c:t+2*c;g=e(g,m.toPixels(k,!0));f=e(f,m.toPixels(a,!0));r(g)&&Infinity!==Math.abs(g)||(g=0,f=z);k=m.toValue(g,!0);a=m.toValue(f,!0);var w=Math.abs(d(a-k));w<v?this.grabbedLeft?g=m.toPixels(a-v-E,!0):this.grabbedRight&&(f=m.toPixels(k+v+E,!0)):H(h)&&d(w-E)>h&&(this.grabbedLeft?g=m.toPixels(a-h-E,!0):this.grabbedRight&&(f=m.toPixels(k+h+E,!0)));this.zoomedMax=
A(Math.max(g,f),0,B);this.zoomedMin=A(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(g,f),0,B);this.range=this.zoomedMax-this.zoomedMin;B=Math.round(this.zoomedMax);g=Math.round(this.zoomedMin);l&&(this.navigatorGroup.attr({visibility:"visible"}),K=K&&!this.hasDragged?"animate":"attr",this.drawMasks(g,B,F,K),this.drawOutline(g,B,F,K),this.navigatorOptions.handles.enabled&&(this.drawHandle(g,0,F,K),this.drawHandle(B,1,F,K)));this.scrollbar&&(F?(F=this.top-c,b=this.left-c+(l||!b.opposite?0:
(b.titleOffset||0)+b.axisTitleMargin),c=t+2*c):(F=this.top+(l?this.height:-c),b=this.left-c),this.scrollbar.position(b,F,z,c),this.scrollbar.setRange(this.zoomedMin/(t||1),this.zoomedMax/(t||1)));this.rendered=!0}};g.prototype.addMouseEvents=function(){var k=this,a=k.chart,g=a.container,c=[],m,e;k.mouseMoveHandler=m=function(a){k.onMouseMove(a)};k.mouseUpHandler=e=function(a){k.onMouseUp(a)};c=k.getPartsEvents("mousedown");c.push(q(a.renderTo,"mousemove",m),q(g.ownerDocument,"mouseup",e));f&&(c.push(q(a.renderTo,
"touchmove",m),q(g.ownerDocument,"touchend",e)),c.concat(k.getPartsEvents("touchstart")));k.eventsToUnbind=c;k.series&&k.series[0]&&c.push(q(k.series[0].xAxis,"foundExtremes",function(){a.navigator.modifyNavigatorAxisExtremes()}))};g.prototype.getPartsEvents=function(k){var a=this,g=[];["shades","handles"].forEach(function(z){a[z].forEach(function(c,f){g.push(q(c.element,k,function(k){a[z+"Mousedown"](k,f)}))})});return g};g.prototype.shadesMousedown=function(k,a){k=this.chart.pointer.normalize(k);
var g=this.chart,c=this.xAxis,f=this.zoomedMin,z=this.left,m=this.size,e=this.range,t=k.chartX;g.inverted&&(t=k.chartY,z=this.top);if(1===a)this.grabbedCenter=t,this.fixedWidth=e,this.dragOffset=t-f;else{k=t-z-e/2;if(0===a)k=Math.max(0,k);else if(2===a&&k+e>=m)if(k=m-e,this.reversedExtremes){k-=e;var b=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;k!==f&&(this.fixedWidth=e,a=c.navigatorAxis.toFixedRange(k,k+e,b,l),H(a.min)&&g.xAxis[0].setExtremes(Math.min(a.min,a.max),
Math.max(a.min,a.max),!0,null,{trigger:"navigator"}))}};g.prototype.handlesMousedown=function(k,a){this.chart.pointer.normalize(k);k=this.chart;var g=k.xAxis[0],c=this.reversedExtremes;0===a?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=c?g.min:g.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=c?g.max:g.min);k.fixedRange=null};g.prototype.onMouseMove=function(k){var a=this,g=a.chart,c=a.left,f=a.navigatorSize,m=a.range,b=a.dragOffset,l=g.inverted;
k.touches&&0===k.touches[0].pageX||(k=g.pointer.normalize(k),g=k.chartX,l&&(c=a.top,g=k.chartY),a.grabbedLeft?(a.hasDragged=!0,a.render(0,0,g-c,a.otherHandlePos)):a.grabbedRight?(a.hasDragged=!0,a.render(0,0,a.otherHandlePos,g-c)):a.grabbedCenter&&(a.hasDragged=!0,g<b?g=b:g>f+b-m&&(g=f+b-m),a.render(0,0,g-b,g-b+m)),a.hasDragged&&a.scrollbar&&e(a.scrollbar.options.liveRedraw,y.svg&&!t&&!this.chart.isBoosting)&&(k.DOMType=k.type,setTimeout(function(){a.onMouseUp(k)},0)))};g.prototype.onMouseUp=function(a){var k=
this.chart,g=this.xAxis,c=this.scrollbar,f=a.DOMEvent||a,m=k.inverted,e=this.rendered&&!this.hasDragged?"animate":"attr",t=Math.round(this.zoomedMax),b=Math.round(this.zoomedMin);if(this.hasDragged&&(!c||!c.hasDragged)||"scrollbar"===a.trigger){c=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var l=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var B=this.fixedExtreme;this.zoomedMax===this.size&&(B=this.reversedExtremes?c.dataMin:c.dataMax);0===this.zoomedMin&&(l=
this.reversedExtremes?c.dataMax:c.dataMin);g=g.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,l,B);H(g.min)&&k.xAxis[0].setExtremes(Math.min(g.min,g.max),Math.max(g.min,g.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:f})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&
this.drawMasks(b,t,m,e),this.outline&&this.drawOutline(b,t,m,e),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(b,0,m,e),this.drawHandle(t,1,m,e)))};g.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};g.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&
a.forEach(function(a){b(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&b(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};g.prototype.init=function(a){var k=a.options,g=k.navigator,c=g.enabled,f=k.scrollbar,m=f.enabled;k=c?g.height:0;var t=m?f.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=k;this.scrollbarHeight=t;this.scrollbarEnabled=m;this.navigatorEnabled=c;this.navigatorOptions=g;this.scrollbarOptions=f;this.outlineHeight=k+t;this.opposite=
e(g.opposite,!(c||!a.inverted));var b=this;c=b.baseSeries;f=a.xAxis.length;m=a.yAxis.length;var F=c&&c[0]&&c[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;b.navigatorEnabled?(b.xAxis=new p(a,l({breaks:F.options.breaks,ordinal:F.options.ordinal},g.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[t,0,-t,0],width:k}:{offsets:[0,
-t,0,t],height:k})),b.yAxis=new p(a,l(g.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:m,isInternal:!0,zoomEnabled:!1},a.inverted?{width:k}:{height:k})),c||g.series.data?b.updateNavigatorSeries(!1):0===a.series.length&&(b.unbindRedraw=q(a,"beforeRedraw",function(){0<a.series.length&&!b.series&&(b.setBaseSeries(),b.unbindRedraw())})),b.reversedExtremes=a.inverted&&!b.xAxis.reversed||!a.inverted&&b.xAxis.reversed,b.renderElements(),b.addMouseEvents()):(b.xAxis={chart:a,navigatorAxis:{fake:!0},
translate:function(k,g){var c=a.xAxis[0],f=c.getExtremes(),b=c.len-2*t,m=B("min",c.options.min,f.dataMin);c=B("max",c.options.max,f.dataMax)-m;return g?k*c/b+m:b*(k-m)/c},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},b.xAxis.navigatorAxis.axis=b.xAxis,b.xAxis.navigatorAxis.toFixedRange=u.AdditionsClass.prototype.toFixedRange.bind(b.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=b.scrollbar=new C(a.renderer,l(a.options.scrollbar,{margin:b.navigatorEnabled?
0:10,vertical:a.inverted}),a),q(b.scrollbar,"changed",function(k){var g=b.size,c=g*this.to;g*=this.from;b.hasDragged=b.scrollbar.hasDragged;b.render(0,0,g,c);(a.options.scrollbar.liveRedraw||"mousemove"!==k.DOMType&&"touchmove"!==k.DOMType)&&setTimeout(function(){b.onMouseUp(k)})}));b.addBaseSeriesEvents();b.addChartEvents()};g.prototype.getUnionExtremes=function(a){var k=this.chart.xAxis[0],g=this.xAxis,c=g.options,f=k.options,b;a&&null===k.dataMin||(b={dataMin:e(c&&c.min,B("min",f.min,k.dataMin,
g.dataMin,g.min)),dataMax:e(c&&c.max,B("max",f.max,k.dataMax,g.dataMax,g.max))});return b};g.prototype.setBaseSeries=function(a,g){var k=this.chart,c=this.baseSeries=[];a=a||k.options&&k.options.navigator.baseSeries||(k.series.length?v(k.series,function(a){return!a.options.isInternal}).index:0);(k.series||[]).forEach(function(k,g){k.options.isInternal||!k.options.showInNavigator&&(g!==a&&k.options.id!==a||!1===k.options.showInNavigator)||c.push(k)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,
g)};g.prototype.updateNavigatorSeries=function(k,g){var c=this,f=c.chart,t=c.baseSeries,z,B,F=c.navigatorOptions.series,d,v={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},r=c.series=(c.series||[]).filter(function(a){var k=a.baseSeries;return 0>t.indexOf(k)?(k&&(b(k,"updatedData",c.updatedDataHandler),delete k.navigatorSeries),a.chart&&a.destroy(),
!1):!0});t&&t.length&&t.forEach(function(a){var k=a.navigatorSeries,b=x({color:a.color,visible:a.visible},w(F)?m.navigator.series:F);k&&!1===c.navigatorOptions.adaptToUpdatedData||(v.name="Navigator "+t.length,z=a.options||{},d=z.navigatorOptions||{},B=l(z,v,b,d),B.pointRange=e(b.pointRange,d.pointRange,m.plotOptions[B.type||"line"].pointRange),b=d.data||b.data,c.hasNavigatorData=c.hasNavigatorData||!!b,B.data=b||z.data&&z.data.slice(0),k&&k.options?k.update(B,g):(a.navigatorSeries=f.initSeries(B),
a.navigatorSeries.baseSeries=a,r.push(a.navigatorSeries)))});if(F.data&&(!t||!t.length)||w(F))c.hasNavigatorData=!1,F=a(F),F.forEach(function(a,k){v.name="Navigator "+(r.length+1);B=l(m.navigator.series,{color:f.series[k]&&!f.series[k].options.isInternal&&f.series[k].color||f.options.colors[k]||f.options.colors[0]},v,a);B.data=a.data;B.data&&(c.hasNavigatorData=!0,r.push(f.initSeries(B)))});k&&this.addBaseSeriesEvents()};g.prototype.addBaseSeriesEvents=function(){var a=this,g=a.baseSeries||[];g[0]&&
g[0].xAxis&&q(g[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);g.forEach(function(k){q(k,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});q(k,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&k.xAxis&&q(k,"updatedData",this.updatedDataHandler);q(k,"remove",function(){this.navigatorSeries&&(D(a.series,this.navigatorSeries),H(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),
delete this.navigatorSeries)})},this)};g.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,k){return Math.min(a,k.xData?k.xData[0]:a)},a)};g.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,g;"undefined"!==typeof a.getExtremes&&(!(g=this.getUnionExtremes(!0))||g.dataMin===a.min&&g.dataMax===a.max||(a.min=g.dataMin,a.max=g.dataMax))};g.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,g=this.getExtremes(),c=g.dataMin,f=g.dataMax;g=
g.max-g.min;var b=a.stickToMin,m=a.stickToMax,t=e(this.options.overscroll,0),l=a.series&&a.series[0],B=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(b){var F=c;var d=F+g}m&&(d=f+t,b||(F=Math.max(c,d-g,a.getBaseSeriesMin(l&&l.xData?l.xData[0]:-Number.MAX_VALUE))));B&&(b||m)&&r(F)&&(this.min=this.userMin=F,this.max=this.userMax=d)}a.stickToMin=a.stickToMax=null};g.prototype.updatedDataHandler=function(){var a=this.chart.navigator,g=this.navigatorSeries,c=
a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=r(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);g&&!a.hasNavigatorData&&(g.options.pointStart=this.xData[0],g.setData(this.options.data,!1,null,!1))};g.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(q(this.chart,"redraw",function(){var a=this.navigator,g=a&&(a.baseSeries&&
a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);g&&a.render(g.min,g.max)}),q(this.chart,"getMargins",function(){var a=this.navigator,g=a.opposite?"plotTop":"marginBottom";this.inverted&&(g=a.opposite?"marginRight":"plotLeft");this[g]=(this[g]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};g.prototype.destroy=function(){this.removeEvents();this.xAxis&&(D(this.chart.xAxis,this.xAxis),D(this.chart.axes,this.xAxis));this.yAxis&&(D(this.chart.yAxis,this.yAxis),
D(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){I(a)},this)};return g}();y.Navigator||(y.Navigator=G,u.compose(p),q(h,"beforeShowResetZoom",function(){var a=this.options,k=a.navigator,c=a.rangeSelector;if((k&&
k.enabled||c&&c.enabled)&&(!t&&"x"===a.chart.zoomType||t&&"x"===a.chart.pinchType))return!1}),q(h,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new G(this)}),q(h,"afterSetChartSize",function(){var a=this.legend,k=this.navigator;if(k){var c=a&&a.options;var f=k.xAxis;var b=k.yAxis;var m=k.scrollbarHeight;this.inverted?(k.left=k.opposite?this.chartWidth-m-k.height:this.spacing[3]+m,k.top=this.plotTop+m):(k.left=this.plotLeft+m,
k.top=k.navigatorOptions.top||this.chartHeight-k.height-m-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+e(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));f&&b&&(this.inverted?f.options.left=b.options.left=k.left:f.options.top=b.options.top=k.top,f.setAxisSize(),b.setAxisSize())}}),q(h,"update",function(a){var g=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||
this.scroller||!g.enabled&&!c.enabled||(l(!0,this.options.navigator,g),l(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),q(h,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new G(this),e(a.redraw,!0)&&this.redraw(a.animation))}),q(h,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),q(c,"afterUpdate",function(){this.chart.navigator&&
!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),h.prototype.callbacks.push(function(a){var g=a.navigator;g&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),g.render(a.min,a.max))}));y.Navigator=G;return y.Navigator});J(p,"parts/OrdinalAxis.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n,y){var u=y.addEvent,C=y.css,h=y.defined,q=y.pick,A=y.timeUnits;y=n.Chart;var d=n.Series,H;(function(d){var p=function(){function d(d){this.index={};this.axis=d}d.prototype.beforeSetTickPositions=
function(){var d=this.axis,h=d.ordinal,r=[],l,e=!1,b=d.getExtremes(),a=b.min,m=b.max,f,t=d.isXAxis&&!!d.options.breaks;b=d.options.ordinal;var c=Number.MAX_VALUE,B=d.chart.options.chart.ignoreHiddenSeries,F;if(b||t){d.series.forEach(function(a,g){l=[];if(!(B&&!1===a.visible||!1===a.takeOrdinalPosition&&!t)&&(r=r.concat(a.processedXData),G=r.length,r.sort(function(a,g){return a-g}),c=Math.min(c,q(a.closestPointRange,c)),G)){for(g=0;g<G-1;)r[g]!==r[g+1]&&l.push(r[g+1]),g++;l[0]!==r[0]&&l.unshift(r[0]);
r=l}a.isSeriesBoosting&&(F=!0)});F&&(r.length=0);var G=r.length;if(2<G){var g=r[1]-r[0];for(f=G-1;f--&&!e;)r[f+1]-r[f]!==g&&(e=!0);!d.options.keepOrdinalPadding&&(r[0]-a>g||m-r[r.length-1]>g)&&(e=!0)}else d.options.overscroll&&(2===G?c=r[1]-r[0]:1===G?(c=d.options.overscroll,r=[r[0],r[0]+c]):c=h.overscrollPointsRange);e?(d.options.overscroll&&(h.overscrollPointsRange=c,r=r.concat(h.getOverscrollPositions())),h.positions=r,g=d.ordinal2lin(Math.max(a,r[0]),!0),f=Math.max(d.ordinal2lin(Math.min(m,r[r.length-
1]),!0),1),h.slope=m=(m-a)/(f-g),h.offset=a-g*m):(h.overscrollPointsRange=q(d.closestPointRange,h.overscrollPointsRange),h.positions=d.ordinal.slope=h.offset=void 0)}d.isOrdinal=b&&e;h.groupIntervalFactor=null};d.prototype.getExtendedPositions=function(){var d=this,h=d.axis,r=h.constructor.prototype,l=h.chart,e=h.series[0].currentDataGrouping,b=d.index,a=e?e.count+e.unitName:"raw",m=h.options.overscroll,f=h.getExtremes(),t;b||(b=d.index={});if(!b[a]){var c={series:[],chart:l,getExtremes:function(){return{min:f.dataMin,
max:f.dataMax+m}},options:{ordinal:!0},ordinal:{},ordinal2lin:r.ordinal2lin,val2lin:r.val2lin};c.ordinal.axis=c;h.series.forEach(function(a){t={xAxis:c,xData:a.xData.slice(),chart:l,destroyGroupedData:n.noop,getProcessedData:n.Series.prototype.getProcessedData};t.xData=t.xData.concat(d.getOverscrollPositions());t.options={dataGrouping:e?{enabled:!0,forced:!0,approximation:"open",units:[[e.unitName,[e.count]]]}:{enabled:!1}};a.processData.apply(t);c.series.push(t)});h.ordinal.beforeSetTickPositions.apply({axis:c});
b[a]=c.ordinal.positions}return b[a]};d.prototype.getGroupIntervalFactor=function(d,h,r){r=r.processedXData;var l=r.length,e=[];var b=this.groupIntervalFactor;if(!b){for(b=0;b<l-1;b++)e[b]=r[b+1]-r[b];e.sort(function(a,b){return a-b});e=e[Math.floor(l/2)];d=Math.max(d,r[0]);h=Math.min(h,r[l-1]);this.groupIntervalFactor=b=l*e/(h-d)}return b};d.prototype.getOverscrollPositions=function(){var d=this.axis,w=d.options.overscroll,r=this.overscrollPointsRange,l=[],e=d.dataMax;if(h(r))for(l.push(e);e<=d.dataMax+
w;)e+=r,l.push(e);return l};d.prototype.postProcessTickInterval=function(d){var h=this.axis,r=this.slope;return r?h.options.breaks?h.closestPointRange||d:d/(r/h.closestPointRange):d};return d}();d.Composition=p;d.compose=function(q,v,w){q.keepProps.push("ordinal");var r=q.prototype;q.prototype.getTimeTicks=function(l,e,b,a,m,f,t){void 0===m&&(m=[]);void 0===f&&(f=0);var c=0,B,d,r={},g=[],k=-Number.MAX_VALUE,z=this.options.tickPixelInterval,E=this.chart.time,K=[];if(!this.options.ordinal&&!this.options.breaks||
!m||3>m.length||"undefined"===typeof e)return E.getTimeTicks.apply(E,arguments);var v=m.length;for(B=0;B<v;B++){var q=B&&m[B-1]>b;m[B]<e&&(c=B);if(B===v-1||m[B+1]-m[B]>5*f||q){if(m[B]>k){for(d=E.getTimeTicks(l,m[c],m[B],a);d.length&&d[0]<=k;)d.shift();d.length&&(k=d[d.length-1]);K.push(g.length);g=g.concat(d)}c=B+1}if(q)break}d=d.info;if(t&&d.unitRange<=A.hour){B=g.length-1;for(c=1;c<B;c++)if(E.dateFormat("%d",g[c])!==E.dateFormat("%d",g[c-1])){r[g[c]]="day";var w=!0}w&&(r[g[0]]="day");d.higherRanks=
r}d.segmentStarts=K;g.info=d;if(t&&h(z)){c=K=g.length;w=[];var n;for(E=[];c--;)B=this.translate(g[c]),n&&(E[c]=n-B),w[c]=n=B;E.sort();E=E[Math.floor(E.length/2)];E<.6*z&&(E=null);c=g[K-1]>b?K-1:K;for(n=void 0;c--;)B=w[c],K=Math.abs(n-B),n&&K<.8*z&&(null===E||K<.8*E)?(r[g[c]]&&!r[g[c+1]]?(K=c+1,n=B):K=c,g.splice(K,1)):n=B}return g};r.lin2val=function(l,e){var b=this.ordinal,a=b.positions;if(a){var m=b.slope,f=b.offset;b=a.length-1;if(e)if(0>l)l=a[0];else if(l>b)l=a[b];else{b=Math.floor(l);var t=l-
b}else for(;b--;)if(e=m*b+f,l>=e){m=m*(b+1)+f;t=(l-e)/(m-e);break}return"undefined"!==typeof t&&"undefined"!==typeof a[b]?a[b]+(t?t*(a[b+1]-a[b]):0):l}return l};r.val2lin=function(l,e){var b=this.ordinal,a=b.positions;if(a){var m=a.length,f;for(f=m;f--;)if(a[f]===l){var t=f;break}for(f=m-1;f--;)if(l>a[f]||0===f){l=(l-a[f])/(a[f+1]-a[f]);t=f+l;break}e=e?t:b.slope*(t||0)+b.offset}else e=l;return e};r.ordinal2lin=r.val2lin;u(q,"afterInit",function(){this.ordinal||(this.ordinal=new d.Composition(this))});
u(q,"foundExtremes",function(){this.isXAxis&&h(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&h(this.userMin)&&(this.min+=this.options.overscroll))});u(q,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});u(q,"initialAxisTranslation",
function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});u(v,"pan",function(l){var e=this.xAxis[0],b=e.options.overscroll,a=l.originalEvent.chartX,m=this.options.chart&&this.options.chart.panning,f=!1;if(m&&"y"!==m.type&&e.options.ordinal&&e.series.length){var t=this.mouseDownX,c=e.getExtremes(),d=c.dataMax,h=c.min,r=c.max,g=this.hoverPoints,k=e.closestPointRange||e.ordinal&&e.ordinal.overscrollPointsRange;t=(t-a)/
(e.translationSlope*(e.ordinal.slope||k));var z={ordinal:{positions:e.ordinal.getExtendedPositions()}};k=e.lin2val;var E=e.val2lin;if(!z.ordinal.positions)f=!0;else if(1<Math.abs(t)){g&&g.forEach(function(a){a.setState()});if(0>t){g=z;var K=e.ordinal.positions?e:z}else g=e.ordinal.positions?e:z,K=z;z=K.ordinal.positions;d>z[z.length-1]&&z.push(d);this.fixedRange=r-h;t=e.navigatorAxis.toFixedRange(null,null,k.apply(g,[E.apply(g,[h,!0])+t,!0]),k.apply(K,[E.apply(K,[r,!0])+t,!0]));t.min>=Math.min(c.dataMin,
h)&&t.max<=Math.max(d,r)+b&&e.setExtremes(t.min,t.max,!0,!1,{trigger:"pan"});this.mouseDownX=a;C(this.container,{cursor:"move"})}}else f=!0;f||m&&/y/.test(m.type)?b&&(e.max=e.dataMax+b):l.preventDefault()});u(w,"updatedData",function(){var l=this.xAxis;l&&l.options.ordinal&&delete l.ordinal.index})}})(H||(H={}));H.compose(p,y,d);return H});J(p,"modules/broken-axis.src.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/Utilities.js"],p["parts/Stacking.js"]],function(p,n,y,u){var C=y.addEvent,h=
y.find,q=y.fireEvent,A=y.isArray,d=y.isNumber,H=y.pick,I=n.Series,D=function(){function d(d){this.hasBreaks=!1;this.axis=d}d.isInBreak=function(d,h){var r=d.repeat||Infinity,l=d.from,e=d.to-d.from;h=h>=l?(h-l)%r:r-(l-h)%r;return d.inclusive?h<=e:h<e&&0!==h};d.lin2Val=function(h){var q=this.brokenAxis;q=q&&q.breakArray;if(!q)return h;var r;for(r=0;r<q.length;r++){var l=q[r];if(l.from>=h)break;else l.to<h?h+=l.len:d.isInBreak(l,h)&&(h+=l.len)}return h};d.val2Lin=function(h){var q=this.brokenAxis;q=
q&&q.breakArray;if(!q)return h;var r=h,l;for(l=0;l<q.length;l++){var e=q[l];if(e.to<=h)r-=e.len;else if(e.from>=h)break;else if(d.isInBreak(e,h)){r-=h-e.from;break}}return r};d.prototype.findBreakAt=function(d,q){return h(q,function(h){return h.from<d&&d<h.to})};d.prototype.isInAnyBreak=function(h,q){var r=this.axis,l=r.options.breaks,e=l&&l.length,b;if(e){for(;e--;)if(d.isInBreak(l[e],h)){var a=!0;b||(b=H(l[e].showPoints,!r.isXAxis))}var m=a&&q?a&&!b:a}return m};d.prototype.setBreaks=function(h,
n){var r=this,l=r.axis,e=A(h)&&!!h.length;l.isDirty=r.hasBreaks!==e;r.hasBreaks=e;l.options.breaks=l.userOptions.breaks=h;l.forceRedraw=!0;l.series.forEach(function(b){b.isDirty=!0});e||l.val2lin!==d.val2Lin||(delete l.val2lin,delete l.lin2val);e&&(l.userOptions.ordinal=!1,l.lin2val=d.lin2Val,l.val2lin=d.val2Lin,l.setExtremes=function(b,a,m,f,t){if(r.hasBreaks){for(var c,e=this.options.breaks;c=r.findBreakAt(b,e);)b=c.to;for(;c=r.findBreakAt(a,e);)a=c.from;a<b&&(a=b)}p.prototype.setExtremes.call(this,
b,a,m,f,t)},l.setAxisTranslation=function(b){p.prototype.setAxisTranslation.call(this,b);r.unitLength=null;if(r.hasBreaks){b=l.options.breaks||[];var a=[],m=[],f=0,t,c=l.userMin||l.min,e=l.userMax||l.max,h=H(l.pointRangePadding,0),G;b.forEach(function(a){t=a.repeat||Infinity;d.isInBreak(a,c)&&(c+=a.to%t-c%t);d.isInBreak(a,e)&&(e-=e%t-a.from%t)});b.forEach(function(g){k=g.from;for(t=g.repeat||Infinity;k-t>c;)k-=t;for(;k<c;)k+=t;for(G=k;G<e;G+=t)a.push({value:G,move:"in"}),a.push({value:G+(g.to-g.from),
move:"out",size:g.breakSize})});a.sort(function(a,g){return a.value===g.value?("in"===a.move?0:1)-("in"===g.move?0:1):a.value-g.value});var g=0;var k=c;a.forEach(function(a){g+="in"===a.move?1:-1;1===g&&"in"===a.move&&(k=a.value);0===g&&(m.push({from:k,to:a.value,len:a.value-k-(a.size||0)}),f+=a.value-k-(a.size||0))});l.breakArray=r.breakArray=m;r.unitLength=e-c-f+h;q(l,"afterBreaks");l.staticScale?l.transA=l.staticScale:r.unitLength&&(l.transA*=(e-l.min+h)/r.unitLength);h&&(l.minPixelPadding=l.transA*
l.minPointOffset);l.min=c;l.max=e}});H(n,!0)&&l.chart.redraw()};return d}();n=function(){function h(){}h.compose=function(h,n){h.keepProps.push("brokenAxis");var r=I.prototype;r.drawBreaks=function(l,e){var b=this,a=b.points,m,f,t,c;if(l&&l.brokenAxis&&l.brokenAxis.hasBreaks){var h=l.brokenAxis;e.forEach(function(e){m=h&&h.breakArray||[];f=l.isXAxis?l.min:H(b.options.threshold,l.min);a.forEach(function(a){c=H(a["stack"+e.toUpperCase()],a[e]);m.forEach(function(g){if(d(f)&&d(c)){t=!1;if(f<g.from&&
c>g.to||f>g.from&&c<g.from)t="pointBreak";else if(f<g.from&&c>g.from&&c<g.to||f>g.from&&c>g.to&&c<g.from)t="pointInBreak";t&&q(l,t,{point:a,brk:g})}})})})}};r.gappedPath=function(){var d=this.currentDataGrouping,e=d&&d.gapSize;d=this.options.gapSize;var b=this.points.slice(),a=b.length-1,m=this.yAxis,f;if(d&&0<a)for("value"!==this.options.gapUnit&&(d*=this.basePointRange),e&&e>d&&e>=this.basePointRange&&(d=e),f=void 0;a--;)f&&!1!==f.visible||(f=b[a+1]),e=b[a],!1!==f.visible&&!1!==e.visible&&(f.x-
e.x>d&&(f=(e.x+f.x)/2,b.splice(a+1,0,{isNull:!0,x:f}),m.stacking&&this.options.stacking&&(f=m.stacking.stacks[this.stackKey][f]=new u(m,m.options.stackLabels,!1,f,this.stack),f.total=0)),f=e);return this.getGraphPath(b)};C(h,"init",function(){this.brokenAxis||(this.brokenAxis=new D(this))});C(h,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});C(h,"afterSetTickPositions",function(){var d=this.brokenAxis;if(d&&d.hasBreaks){var e=this.tickPositions,
b=this.tickPositions.info,a=[],m;for(m=0;m<e.length;m++)d.isInAnyBreak(e[m])||a.push(e[m]);this.tickPositions=a;this.tickPositions.info=b}});C(h,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});C(n,"afterGeneratePoints",function(){var d=this.options.connectNulls,e=this.points,b=this.xAxis,a=this.yAxis;if(this.isDirty)for(var m=e.length;m--;){var f=e[m],t=!(null===f.y&&!1===d)&&(b&&b.brokenAxis&&b.brokenAxis.isInAnyBreak(f.x,!0)||a&&a.brokenAxis&&
a.brokenAxis.isInAnyBreak(f.y,!0));f.visible=t?!1:!1!==f.options.visible}});C(n,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,H(this.pointArrayMap,["y"]))})};return h}();n.compose(p,I);return n});J(p,"masters/modules/broken-axis.src.js",[],function(){});J(p,"parts/DataGrouping.js",[p["parts/DateTimeAxis.js"],p["parts/Globals.js"],p["parts/Point.js"],p["parts/Tooltip.js"],p["parts/Utilities.js"]],function(p,n,y,u,C){"";var h=C.addEvent,q=C.arrayMax,A=C.arrayMin,
d=C.correctFloat,H=C.defined,I=C.error,D=C.extend,x=C.format,v=C.isNumber,w=C.merge,r=C.pick,l=n.Axis,e=n.defaultPlotOptions;C=n.Series;var b=n.approximations={sum:function(a){var g=a.length;if(!g&&a.hasNulls)var c=null;else if(g)for(c=0;g--;)c+=a[g];return c},average:function(a){var g=a.length;a=b.sum(a);v(a)&&g&&(a=d(a/g));return a},averages:function(){var a=[];[].forEach.call(arguments,function(g){a.push(b.average(g))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?
a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?q(a):a.hasNulls?null:void 0},low:function(a){return a.length?A(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,c,f,m){a=b.open(a);c=b.high(c);f=b.low(f);m=b.close(m);if(v(a)||v(c)||v(f)||v(m))return[a,c,f,m]},range:function(a,c){a=b.low(a);c=b.high(c);if(v(a)||v(c))return[a,c];if(null===a&&null===c)return null}},a=function(a,c,f,m){var g=this,k=g.data,e=g.options&&g.options.data,
t=[],d=[],h=[],l=a.length,B=!!c,z=[],r=g.pointArrayMap,F=r&&r.length,q=["x"].concat(r||["y"]),E=0,n=0,G;m="function"===typeof m?m:b[m]?b[m]:b[g.getDGApproximation&&g.getDGApproximation()||"average"];F?r.forEach(function(){z.push([])}):z.push([]);var p=F||1;for(G=0;G<=l&&!(a[G]>=f[0]);G++);for(G;G<=l;G++){for(;"undefined"!==typeof f[E+1]&&a[G]>=f[E+1]||G===l;){var A=f[E];g.dataGroupInfo={start:g.cropStart+n,length:z[0].length};var u=m.apply(g,z);g.pointClass&&!H(g.dataGroupInfo.options)&&(g.dataGroupInfo.options=
w(g.pointClass.prototype.optionsToObject.call({series:g},g.options.data[g.cropStart+n])),q.forEach(function(a){delete g.dataGroupInfo.options[a]}));"undefined"!==typeof u&&(t.push(A),d.push(u),h.push(g.dataGroupInfo));n=G;for(A=0;A<p;A++)z[A].length=0,z[A].hasNulls=!1;E+=1;if(G===l)break}if(G===l)break;if(r)for(A=g.cropStart+G,u=k&&k[A]||g.pointClass.prototype.applyOptions.apply({series:g},[e[A]]),A=0;A<F;A++){var C=u[r[A]];v(C)?z[A].push(C):null===C&&(z[A].hasNulls=!0)}else A=B?c[G]:null,v(A)?z[0].push(A):
null===A&&(z[0].hasNulls=!0)}return{groupedXData:t,groupedYData:d,groupMap:h}},m={approximations:b,groupData:a},f=C.prototype,t=f.processData,c=f.generatePoints,B={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],
week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},F={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},G=n.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",
null]];f.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};f.groupData=a;f.processData=function(){var a=this.chart,c=this.options.dataGrouping,b=!1!==this.allowDG&&c&&r(c.enabled,a.options.isStock),m=this.visible||!a.options.chart.ignoreHiddenSeries,e,d=this.currentDataGrouping,h=!1;this.forceCrop=b;this.groupPixelWidth=null;this.hasProcessed=!0;b&&!this.requireSorting&&(this.requireSorting=h=!0);b=!1===t.apply(this,arguments)||
!b;h&&(this.requireSorting=!1);if(!b){this.destroyGroupedData();b=c.groupAll?this.xData:this.processedXData;var l=c.groupAll?this.yData:this.processedYData,B=a.plotSizeX;a=this.xAxis;var F=a.options.ordinal,q=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(q){this.isDirty=e=!0;this.points=null;h=a.getExtremes();var n=h.min;h=h.max;F=F&&a.ordinal&&a.ordinal.getGroupIntervalFactor(n,h,this)||1;q=q*(h-n)/B*F;B=a.getTimeTicks(p.AdditionsClass.prototype.normalizeTimeTickInterval(q,
c.units||G),Math.min(n,b[0]),Math.max(h,b[b.length-1]),a.options.startOfWeek,b,this.closestPointRange);l=f.groupData.apply(this,[b,l,B,c.approximation]);b=l.groupedXData;F=l.groupedYData;var A=0;if(c.smoothed&&b.length){var u=b.length-1;for(b[u]=Math.min(b[u],h);u--&&0<u;)b[u]+=q/2;b[0]=Math.max(b[0],n)}for(u=1;u<B.length;u++)B.info.segmentStarts&&-1!==B.info.segmentStarts.indexOf(u)||(A=Math.max(B[u]-B[u-1],A));n=B.info;n.gapSize=A;this.closestPointRange=B.info.totalRange;this.groupMap=l.groupMap;
if(H(b[0])&&b[0]<a.min&&m){if(!H(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(b[0],a.min);a.dataMin=Math.min(b[0],a.dataMin)}c.groupAll&&(c=this.cropData(b,F,a.min,a.max,1),b=c.xData,F=c.yData);this.processedXData=b;this.processedYData=F}else this.groupMap=null;this.hasGroupedData=e;this.currentDataGrouping=n;this.preventGraphAnimation=(d&&d.totalRange)!==(n&&n.totalRange)}};f.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,c){a&&(this.groupedData[c]=
a.destroy?a.destroy():null)},this),this.groupedData.length=0)};f.generatePoints=function(){c.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};h(y,"update",function(){if(this.dataGroup)return I(24,!1,this.series.chart),!1});h(u,"headerFormatter",function(a){var c=this.chart,g=c.time,f=a.labelConfig,b=f.series,m=b.tooltipOptions,e=b.options.dataGrouping,t=m.xDateFormat,d=b.xAxis,h=m[(a.isFooter?"footer":"header")+"Format"];if(d&&"datetime"===d.options.type&&
e&&v(f.key)){var l=b.currentDataGrouping;e=e.dateTimeLabelFormats||B.dateTimeLabelFormats;if(l)if(m=e[l.unitName],1===l.count)t=m[0];else{t=m[1];var r=m[2]}else!t&&e&&(t=this.getXDateFormat(f,m,d));t=g.dateFormat(t,f.key);r&&(t+=g.dateFormat(r,f.key+l.totalRange-1));b.chart.styledMode&&(h=this.styledModeFormat(h));a.text=x(h,{point:D(f.point,{key:t}),series:b},c);a.preventDefault()}});h(C,"destroy",f.destroyGroupedData);h(C,"afterSetOptions",function(a){a=a.options;var c=this.type,g=this.chart.options.plotOptions,
f=e[c].dataGrouping,b=this.useCommonDataGrouping&&B;if(F[c]||b)f||(f=w(B,F[c])),a.dataGrouping=w(b,f,g.series&&g.series.dataGrouping,g[c].dataGrouping,this.userOptions.dataGrouping)});h(l,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});l.prototype.getGroupPixelWidth=function(){var a=this.series,c=a.length,f,b=0,m=!1,e;for(f=c;f--;)(e=a[f].options.dataGrouping)&&(b=Math.max(b,r(e.groupPixelWidth,B.groupPixelWidth)));for(f=c;f--;)(e=a[f].options.dataGrouping)&&a[f].hasProcessed&&
(c=(a[f].processedXData||a[f].data).length,a[f].groupPixelWidth||c>this.chart.plotSizeX/b||c&&e.forced)&&(m=!0);return m?b:0};l.prototype.setDataGrouping=function(a,c){var f;c=r(c,!0);a||(a={forced:!1,units:null});if(this instanceof l)for(f=this.series.length;f--;)this.series[f].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(c){c.dataGrouping=a},!1);this.ordinal&&(this.ordinal.slope=void 0);c&&this.chart.redraw()};n.dataGrouping=m;"";return m});J(p,"parts/OHLCSeries.js",
[p["parts/Globals.js"],p["parts/Point.js"],p["parts/Utilities.js"]],function(p,n,y){y=y.seriesType;var u=p.seriesTypes;y("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(n){return[n.open,n.high,
n.low,n.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){u.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},pointAttribs:function(n,h){h=u.column.prototype.pointAttribs.call(this,n,h);var q=this.options;delete h.fill;!n.options.color&&q.upColor&&n.open<n.close&&(h.stroke=q.upColor);return h},translate:function(){var n=this,h=n.yAxis,q=!!n.modifyValue,p=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];u.column.prototype.translate.apply(n);
n.points.forEach(function(d){[d.open,d.high,d.low,d.close,d.low].forEach(function(A,u){null!==A&&(q&&(A=n.modifyValue(A)),d[p[u]]=h.toPixels(A,!0))});d.tooltipPos[1]=d.plotHigh+h.pos-n.chart.plotTop})},drawPoints:function(){var n=this,h=n.chart,q=function(h,d,n){var q=h[0];h=h[1];"number"===typeof q[2]&&(q[2]=Math.max(n+d,q[2]));"number"===typeof h[2]&&(h[2]=Math.min(n-d,h[2]))};n.points.forEach(function(p){var d=p.graphic,u=!d;if("undefined"!==typeof p.plotY){d||(p.graphic=d=h.renderer.path().add(n.group));
h.styledMode||d.attr(n.pointAttribs(p,p.selected&&"select"));var A=d.strokeWidth();var y=A%2/2;var x=Math.round(p.plotX)-y;var v=Math.round(p.shapeArgs.width/2);var w=[["M",x,Math.round(p.yBottom)],["L",x,Math.round(p.plotHigh)]];if(null!==p.open){var r=Math.round(p.plotOpen)+y;w.push(["M",x,r],["L",x-v,r]);q(w,A/2,r)}null!==p.close&&(r=Math.round(p.plotClose)+y,w.push(["M",x,r],["L",x+v,r]),q(w,A/2,r));d[u?"attr":"animate"]({d:w}).addClass(p.getClassName(),!0)}})},animate:null},{getClassName:function(){return n.prototype.getClassName.call(this)+
(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});J(p,"parts/CandlestickSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n){var y=n.merge;n=n.seriesType;var u=p.defaultPlotOptions,C=p.seriesTypes;n("candlestick","ohlc",y(u.column,{states:{hover:{lineWidth:2}},tooltip:u.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(h,n){var q=C.column.prototype.pointAttribs.call(this,h,n),d=
this.options,p=h.open<h.close,u=d.lineColor||this.color;q["stroke-width"]=d.lineWidth;q.fill=h.options.color||(p?d.upColor||this.color:this.color);q.stroke=h.options.lineColor||(p?d.upLineColor||u:u);n&&(h=d.states[n],q.fill=h.color||q.fill,q.stroke=h.lineColor||q.stroke,q["stroke-width"]=h.lineWidth||q["stroke-width"]);return q},drawPoints:function(){var h=this,n=h.chart,p=h.yAxis.reversed;h.points.forEach(function(d){var q=d.graphic,u=!q;if("undefined"!==typeof d.plotY){q||(d.graphic=q=n.renderer.path().add(h.group));
h.chart.styledMode||q.attr(h.pointAttribs(d,d.selected&&"select")).shadow(h.options.shadow);var A=q.strokeWidth()%2/2;var x=Math.round(d.plotX)-A;var v=d.plotOpen;var w=d.plotClose;var r=Math.min(v,w);v=Math.max(v,w);var l=Math.round(d.shapeArgs.width/2);w=p?v!==d.yBottom:Math.round(r)!==Math.round(d.plotHigh);var e=p?Math.round(r)!==Math.round(d.plotHigh):v!==d.yBottom;r=Math.round(r)+A;v=Math.round(v)+A;A=[];A.push(["M",x-l,v],["L",x-l,r],["L",x+l,r],["L",x+l,v],["Z"],["M",x,r],["L",x,w?Math.round(p?
d.yBottom:d.plotHigh):r],["M",x,v],["L",x,e?Math.round(p?d.plotHigh:d.yBottom):v]);q[u?"attr":"animate"]({d:A}).addClass(d.getClassName(),!0)}})}});""});J(p,"mixins/on-series.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n){var y=n.defined,u=n.stableSort,C=p.seriesTypes;return{getPlotBox:function(){return p.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){C.column.prototype.translate.apply(this);var h=this,
q=h.options,n=h.chart,d=h.points,p=d.length-1,I,D=q.onSeries;D=D&&n.get(D);q=q.onKey||"y";var x=D&&D.options.step,v=D&&D.points,w=v&&v.length,r=n.inverted,l=h.xAxis,e=h.yAxis,b=0,a;if(D&&D.visible&&w){b=(D.pointXOffset||0)+(D.barW||0)/2;n=D.currentDataGrouping;var m=v[w-1].x+(n?n.totalRange:0);u(d,function(a,f){return a.x-f.x});for(q="plot"+q[0].toUpperCase()+q.substr(1);w--&&d[p];){var f=v[w];n=d[p];n.y=f.y;if(f.x<=n.x&&"undefined"!==typeof f[q]){if(n.x<=m&&(n.plotY=f[q],f.x<n.x&&!x&&(a=v[w+1])&&
"undefined"!==typeof a[q])){var t=(n.x-f.x)/(a.x-f.x);n.plotY+=t*(a[q]-f[q]);n.y+=t*(a.y-f.y)}p--;w++;if(0>p)break}}}d.forEach(function(a,f){a.plotX+=b;if("undefined"===typeof a.plotY||r)0<=a.plotX&&a.plotX<=l.len?r?(a.plotY=l.translate(a.x,0,1,0,1),a.plotX=y(a.y)?e.translate(a.y,0,0,0,1):0):a.plotY=(l.opposite?0:h.yAxis.len)+l.offset:a.shapeArgs={};if((I=d[f-1])&&I.plotX===a.plotX){"undefined"===typeof I.stackIndex&&(I.stackIndex=0);var c=I.stackIndex+1}a.stackIndex=c});this.onSeries=D}}});J(p,"parts/FlagsSeries.js",
[p["parts/Globals.js"],p["parts/SVGElement.js"],p["parts/SVGRenderer.js"],p["parts/Utilities.js"],p["mixins/on-series.js"]],function(p,n,y,u,C){function h(b){e[b+"pin"]=function(a,m,f,t,c){var d=c&&c.anchorX;c=c&&c.anchorY;"circle"===b&&t>f&&(a-=Math.round((t-f)/2),f=t);var h=e[b](a,m,f,t);if(d&&c){var l=d;"circle"===b?l=a+f/2:(a=h[0],f=h[1],"M"===a[0]&&"L"===f[0]&&(l=(a[1]+f[1])/2));h.push(["M",l,m>c?m:m+t],["L",d,c]);h=h.concat(e.circle(d-1,c-1,2,2))}return h}}var q=u.addEvent,A=u.defined,d=u.isNumber,
H=u.merge,I=u.objectEach,D=u.seriesType,x=u.wrap;u=p.noop;var v=p.Renderer,w=p.Series,r=p.TrackerMixin,l=p.VMLRenderer,e=y.prototype.symbols;D("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],
forceCrop:!0,init:w.prototype.init,pointAttribs:function(b,a){var m=this.options,f=b&&b.color||this.color,e=m.lineColor,c=b&&b.lineWidth;b=b&&b.fillColor||m.fillColor;a&&(b=m.states[a].fillColor,e=m.states[a].lineColor,c=m.states[a].lineWidth);return{fill:b||f,stroke:e||f,"stroke-width":c||m.lineWidth||0}},translate:C.translate,getPlotBox:C.getPlotBox,drawPoints:function(){var b=this.points,a=this.chart,m=a.renderer,f=a.inverted,e=this.options,c=e.y,d,h=this.yAxis,l={},g=[];for(d=b.length;d--;){var k=
b[d];var r=(f?k.plotY:k.plotX)>this.xAxis.len;var q=k.plotX;var u=k.stackIndex;var v=k.options.shape||e.shape;var w=k.plotY;"undefined"!==typeof w&&(w=k.plotY+c-("undefined"!==typeof u&&u*e.stackDistance));k.anchorX=u?void 0:k.plotX;var y=u?void 0:k.plotY;var C="flag"!==v;u=k.graphic;"undefined"!==typeof w&&0<=q&&!r?(u||(u=k.graphic=m.label("",null,null,v,null,null,e.useHTML),a.styledMode||u.attr(this.pointAttribs(k)).css(H(e.style,k.style)),u.attr({align:C?"center":"left",width:e.width,height:e.height,
"text-align":e.textAlign}).addClass("highcharts-point").add(this.markerGroup),k.graphic.div&&(k.graphic.div.point=k),a.styledMode||u.shadow(e.shadow),u.isNew=!0),0<q&&(q-=u.strokeWidth()%2),v={y:w,anchorY:y},e.allowOverlapX&&(v.x=q,v.anchorX=k.anchorX),u.attr({text:k.options.title||e.title||"A"})[u.isNew?"attr":"animate"](v),e.allowOverlapX||(l[k.plotX]?l[k.plotX].size=Math.max(l[k.plotX].size,u.width):l[k.plotX]={align:C?.5:0,size:u.width,target:q,anchorX:q}),k.tooltipPos=[q,w+h.pos-a.plotTop]):
u&&(k.graphic=u.destroy())}e.allowOverlapX||(I(l,function(a){a.plotX=a.anchorX;g.push(a)}),p.distribute(g,f?h.len:this.xAxis.len,100),b.forEach(function(a){var c=a.graphic&&l[a.plotX];c&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:c.pos+c.align*c.size,anchorX:a.anchorX}),A(c.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));e.useHTML&&x(this.markerGroup,"on",function(a){return n.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,
1))})},drawTracker:function(){var b=this.points;r.drawTrackerPoint.apply(this);b.forEach(function(a){var e=a.graphic;e&&q(e.element,"mouseover",function(){0<a.stackIndex&&!a.raised&&(a._y=e.y,e.attr({y:a._y-8}),a.raised=!0);b.forEach(function(f){f!==a&&f.raised&&f.graphic&&(f.graphic.attr({y:f._y}),f.raised=!1)})})})},animate:function(b){b&&this.setClip()},setClip:function(){w.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},
buildKDTree:u,invertGroups:u},{isValid:function(){return d(this.y)||"undefined"===typeof this.y}});e.flag=function(b,a,m,f,d){var c=d&&d.anchorX||b;d=d&&d.anchorY||a;var h=e.circle(c-1,d-1,2,2);h.push(["M",c,d],["L",b,a+f],["L",b,a],["L",b+m,a],["L",b+m,a+f],["L",b,a+f],["Z"]);return h};h("circle");h("square");v===l&&["circlepin","flag","squarepin"].forEach(function(b){l.prototype.symbols[b]=e[b]});""});J(p,"parts/RangeSelector.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,n){function y(a){this.init(a)}
var u=n.addEvent,C=n.createElement,h=n.css,q=n.defined,A=n.destroyObjectProperties,d=n.discardElement,H=n.extend,I=n.fireEvent,D=n.isNumber,x=n.merge,v=n.objectEach,w=n.pick,r=n.pInt,l=n.splat,e=p.Axis;n=p.Chart;var b=p.defaultOptions;H(b,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});b.lang=x(b.lang,{rangeSelectorZoom:"Zoom",
rangeSelectorFrom:"From",rangeSelectorTo:"To"});y.prototype={clickButton:function(a,b){var f=this.chart,m=this.buttonOptions[a],c=f.xAxis[0],d=f.scroller&&f.scroller.getUnionExtremes()||c||{},h=d.dataMin,n=d.dataMax,g=c&&Math.round(Math.min(c.max,w(n,c.max))),k=m.type;d=m._range;var r,q=m.dataGrouping;if(null!==h&&null!==n){f.fixedRange=d;q&&(this.forcedDataGrouping=!0,e.prototype.setDataGrouping.call(c||{chart:this.chart},q,!1),this.frozenStates=m.preserveDataGrouping);if("month"===k||"year"===k)if(c){k=
{range:m,max:g,chart:f,dataMin:h,dataMax:n};var p=c.minFromRange.call(k);D(k.newMax)&&(g=k.newMax)}else d=m;else if(d)p=Math.max(g-d,h),g=Math.min(p+d,n);else if("ytd"===k)if(c)"undefined"===typeof n&&(h=Number.MAX_VALUE,n=Number.MIN_VALUE,f.series.forEach(function(a){a=a.xData;h=Math.min(a[0],h);n=Math.max(a[a.length-1],n)}),b=!1),g=this.getYTDExtremes(n,h,f.time.useUTC),p=r=g.min,g=g.max;else{this.deferredYTDClick=a;return}else"all"===k&&c&&(p=h,g=n);p+=m._offsetMin;g+=m._offsetMax;this.setSelected(a);
if(c)c.setExtremes(p,g,w(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:m});else{var v=l(f.options.xAxis)[0];var y=v.range;v.range=d;var x=v.min;v.min=r;u(f,"load",function(){v.range=y;v.min=x})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,f=
a.options.rangeSelector,e=f.buttons||[].concat(b.defaultButtons),c=f.selected,d=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&I(a,"blur");c&&c.blur&&I(c,"blur")};b.chart=a;b.options=f;b.buttons=[];b.buttonOptions=e;this.unMouseDown=u(a.container,"mousedown",d);this.unResize=u(a,"resize",d);e.forEach(b.computeButtonRange);"undefined"!==typeof c&&e[c]&&this.clickButton(c,!1);u(a,"load",function(){a.xAxis&&a.xAxis[0]&&u(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==
c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,f=b.xAxis[0],e=Math.round(f.max-f.min),c=!f.hasVisibleSeries,d=b.scroller&&b.scroller.getUnionExtremes()||f,h=d.dataMin,l=d.dataMax;b=a.getYTDExtremes(l,h,b.time.useUTC);var g=b.min,k=b.max,n=a.selected,r=D(n),q=a.options.allButtonsEnabled,p=a.buttons;a.buttonOptions.forEach(function(b,d){var m=b._range,t=b.type,B=b.count||1,F=p[d],u=0,
z=b._offsetMax-b._offsetMin;b=d===n;var E=m>l-h,v=m<f.minRange,G=!1,w=!1;m=m===e;("month"===t||"year"===t)&&e+36E5>=864E5*{month:28,year:365}[t]*B-z&&e-36E5<=864E5*{month:31,year:366}[t]*B+z?m=!0:"ytd"===t?(m=k-g+z===e,G=!b):"all"===t&&(m=f.max-f.min>=l-h,w=!b&&r&&m);t=!q&&(E||v||w||c);B=b&&m||m&&!r&&!G||b&&a.frozenStates;t?u=3:B&&(r=!0,u=2);F.state!==u&&(F.setState(u),0===u&&n===d&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,f=a.count||1,e={millisecond:1,second:1E3,minute:6E4,
hour:36E5,day:864E5,week:6048E5};if(e[b])a._range=e[b]*f;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*f;a._offsetMin=w(a.offsetMin,0);a._offsetMax=w(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var f=this.chart.options.rangeSelector,e=this.chart.time,c=this[a+"Input"];q(b)&&(c.previousValue=c.HCTime,c.HCTime=b);c.value=e.dateFormat(f.inputEditDateFormat||"%Y-%m-%d",c.HCTime);this[a+"DateBox"].attr({text:e.dateFormat(f.inputDateFormat||"%b %e, %Y",
c.HCTime)})},showInput:function(a){var b=this.inputGroup,f=this[a+"DateBox"];h(this[a+"Input"],{left:b.translateX+f.x+"px",top:b.translateY+"px",width:f.width-2+"px",height:f.height-2+"px",border:"2px solid silver"})},hideInput:function(a){h(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function e(){var a=k.value,c=(n.inputDateParser||Date.parse)(a),b=d.xAxis[0],e=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:b,m=e.dataMin;e=e.dataMax;c!==k.previousValue&&
(k.previousValue=c,D(c)||(c=a.split("-"),c=Date.UTC(r(c[0]),r(c[1])-1,r(c[2]))),D(c)&&(d.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),g?c>f.maxInput.HCTime?c=void 0:c<m&&(c=m):c<f.minInput.HCTime?c=void 0:c>e&&(c=e),"undefined"!==typeof c&&b.setExtremes(g?c:b.min,g?b.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var f=this,d=f.chart,c=d.renderer.style||{},l=d.renderer,n=d.options.rangeSelector,q=f.div,g="min"===a,k,u,E=this.inputGroup;this[a+"Label"]=u=l.label(b.lang[g?"rangeSelectorFrom":
"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(E);E.offset+=u.width+5;this[a+"DateBox"]=l=l.label("",E.offset).addClass("highcharts-range-input").attr({padding:2,width:n.inputBoxWidth||90,height:n.inputBoxHeight||17,"text-align":"center"}).on("click",function(){f.showInput(a);f[a+"Input"].focus()});d.styledMode||l.attr({stroke:n.inputBoxBorderColor||"#cccccc","stroke-width":1});l.add(E);E.offset+=l.width+(g?10:0);this[a+"Input"]=k=C("input",{name:a,
className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},q);d.styledMode||(u.css(x(c,n.labelStyle)),l.css(x({color:"#333333"},c,n.inputStyle)),h(k,H({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:c.fontSize,fontFamily:c.fontFamily,top:"-9999em"},n.inputStyle)));k.onfocus=function(){f.showInput(a)};k.onblur=function(){k===p.doc.activeElement&&e();f.hideInput(a);k.blur()};k.onchange=e;k.onkeypress=function(a){13===a.keyCode&&e()}},getPosition:function(){var a=
this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,f){var e=this.chart.time,c=new e.Date(a),d=e.get("FullYear",c);f=f?e.Date.UTC(d,0,1):+new e.Date(d,0,1);b=Math.max(b||0,f);c=c.getTime();return{max:Math.min(a||c,c),min:b}},render:function(a,e){var f=this,d=f.chart,c=d.renderer,h=d.container,m=d.options,l=m.exporting&&!1!==m.exporting.enabled&&m.navigation&&m.navigation.buttonOptions,
g=b.lang,k=f.div,n=m.rangeSelector,r=w(m.chart.style&&m.chart.style.zIndex,0)+1;m=n.floating;var q=f.buttons;k=f.inputGroup;var p=n.buttonTheme,u=n.buttonPosition,v=n.inputPosition,y=n.inputEnabled,x=p&&p.states,A=d.plotLeft,D=f.buttonGroup,H,I=f.options.verticalAlign,J=d.legend,O=J&&J.options,P=u.y,N=v.y,Q=d.hasLoaded,R=Q?"animate":"attr",M=0,L=0;if(!1!==n.enabled){f.rendered||(f.group=H=c.g("range-selector-group").attr({zIndex:7}).add(),f.buttonGroup=D=c.g("range-selector-buttons").add(H),f.zoomText=
c.text(g.rangeSelectorZoom,0,15).add(D),d.styledMode||(f.zoomText.css(n.labelStyle),p["stroke-width"]=w(p["stroke-width"],0)),f.buttonOptions.forEach(function(a,b){q[b]=c.button(a.text,0,0,function(c){var d=a.events&&a.events.click,g;d&&(g=d.call(a,c));!1!==g&&f.clickButton(b);f.isActive=!0},p,x&&x.hover,x&&x.select,x&&x.disabled).attr({"text-align":"center"}).add(D)}),!1!==y&&(f.div=k=C("div",null,{position:"relative",height:0,zIndex:r}),h.parentNode.insertBefore(k,h),f.inputGroup=k=c.g("input-group").add(H),
k.offset=0,f.drawInput("min"),f.drawInput("max")));f.zoomText[R]({x:w(A+u.x,A)});var S=w(A+u.x,A)+f.zoomText.getBBox().width+5;f.buttonOptions.forEach(function(a,c){q[c][R]({x:S});S+=q[c].width+w(n.buttonSpacing,5)});A=d.plotLeft-d.spacing[3];f.updateButtonStates();l&&this.titleCollision(d)&&"top"===I&&"right"===u.align&&u.y+D.getBBox().height-12<(l.y||0)+l.height&&(M=-40);h=u.x-d.spacing[3];"right"===u.align?h+=M-A:"center"===u.align&&(h-=A/2);D.align({y:u.y,width:D.getBBox().width,align:u.align,
x:h},!0,d.spacingBox);f.group.placed=Q;f.buttonGroup.placed=Q;!1!==y&&(M=l&&this.titleCollision(d)&&"top"===I&&"right"===v.align&&v.y-k.getBBox().height-12<(l.y||0)+l.height+d.spacing[0]?-40:0,"left"===v.align?h=A:"right"===v.align&&(h=-Math.max(d.axisOffset[1],-M)),k.align({y:v.y,width:k.getBBox().width,align:v.align,x:v.x+h-2},!0,d.spacingBox),l=k.alignAttr.translateX+k.alignOptions.x-M+k.getBBox().x+2,h=k.alignOptions.width,g=D.alignAttr.translateX+D.getBBox().x,A=D.getBBox().width+20,(v.align===
u.align||g+A>l&&l+h>g&&P<N+k.getBBox().height)&&k.attr({translateX:k.alignAttr.translateX+(d.axisOffset[1]>=-M?0:-M),translateY:k.alignAttr.translateY+D.getBBox().height+10}),f.setInputValue("min",a),f.setInputValue("max",e),f.inputGroup.placed=Q);f.group.align({verticalAlign:I},!0,d.spacingBox);a=f.group.getBBox().height+20;e=f.group.alignAttr.translateY;"bottom"===I&&(J=O&&"bottom"===O.verticalAlign&&O.enabled&&!O.floating?J.legendHeight+w(O.margin,10):0,a=a+J-20,L=e-a-(m?0:n.y)-(d.titleOffset?
d.titleOffset[2]:0)-10);if("top"===I)m&&(L=0),d.titleOffset&&d.titleOffset[0]&&(L=d.titleOffset[0]),L+=d.margin[0]-d.spacing[0]||0;else if("middle"===I)if(N===P)L=0>N?e+void 0:e;else if(N||P)L=0>N||0>P?L-Math.min(N,P):e-a+NaN;f.group.translate(n.x,n.y+Math.floor(L));!1!==y&&(f.minInput.style.marginTop=f.group.translateY+"px",f.maxInput.style.marginTop=f.group.translateY+"px");f.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,f=a.y,d=a.buttonPosition.y,c=a.inputPosition.y;if(a.height)return a.height;
a=b?b.getBBox(!0).height+13+f:0;b=Math.min(c,d);if(0>c&&0>d||0<c&&0<d)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;x(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,f=a.maxInput;a.unMouseDown();a.unResize();A(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);f&&(f.onfocus=f.onblur=f.onchange=null);v(a,function(b,c){b&&"chart"!==
c&&(b.destroy?b.destroy():b.nodeType&&d(this[c]));b!==y.prototype[c]&&(a[c]=null)},this)}};e.prototype.minFromRange=function(){var a=this.range,b=a.type,f=this.max,d=this.chart.time,c=function(a,c){var f="year"===b?"FullYear":"Month",e=new d.Date(a),g=d.get(f,e);d.set(f,e,g+c);g===d.get(f,e)&&d.set("Date",e,0);return e.getTime()-a};if(D(a)){var e=f-a;var h=a}else e=f+c(f,-a.count),this.chart&&(this.chart.fixedRange=f-e);var l=w(this.dataMin,Number.MIN_VALUE);D(e)||(e=l);e<=l&&(e=l,"undefined"===typeof h&&
(h=c(e,a.count)),this.newMax=Math.min(e+h,this.dataMax));D(f)||(e=void 0);return e};p.RangeSelector||(u(n,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new y(this))}),u(n,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(D(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===
a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),u(n,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var f=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!q(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new y(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=
!0)),this.extraBottomMargin!==f||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)}),u(n,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),u(n,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),n.prototype.callbacks.push(function(a){function b(){f=a.xAxis[0].getExtremes();
c=a.legend;h=null===e||void 0===e?void 0:e.options.verticalAlign;D(f.min)&&e.render(f.min,f.max);e&&c.display&&"top"===h&&h===c.options.verticalAlign&&(d=x(a.spacingBox),d.y="vertical"===c.options.layout?a.plotTop:d.y+e.getHeight(),c.group.placed=!1,c.align(d))}var f,e=a.rangeSelector,c,d,h;if(e){var l=u(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var g=u(a,"redraw",b);b()}u(a,"destroy",function(){e&&(g(),l())})}),p.RangeSelector=y)});J(p,"parts/StockChart.js",[p["parts/Axis.js"],
p["parts/Chart.js"],p["parts/Globals.js"],p["parts/Point.js"],p["parts/SVGRenderer.js"],p["parts/Utilities.js"]],function(p,n,y,u,C,h){var q=h.addEvent,A=h.arrayMax,d=h.arrayMin,H=h.clamp,I=h.defined,D=h.extend,x=h.find,v=h.format,w=h.isNumber,r=h.isString,l=h.merge,e=h.pick,b=h.splat;h=y.Series;var a=h.prototype,m=a.init,f=a.processData,t=u.prototype.tooltipFormatter;y.StockChart=y.stockChart=function(a,f,d){var c=r(a)||a.nodeName,g=arguments[c?1:0],k=g,h=g.series,m=y.getOptions(),p,q=e(g.navigator&&
g.navigator.enabled,m.navigator.enabled,!0);g.xAxis=b(g.xAxis||{}).map(function(a,c){return l({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},m.xAxis,m.xAxis&&m.xAxis[c],a,{type:"datetime",categories:null},q?{startOnTick:!1,endOnTick:!1}:null)});g.yAxis=b(g.yAxis||{}).map(function(a,c){p=e(a.opposite,!0);return l({labels:{y:-2},opposite:p,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},m.yAxis,m.yAxis&&m.yAxis[c],
a)});g.series=null;g=l({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:q},scrollbar:{enabled:e(m.scrollbar.enabled,!0)},rangeSelector:{enabled:e(m.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:e(m.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});g.series=k.series=h;return c?new n(a,g,d):new n(g,f)};q(h,"setOptions",function(a){var c;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?c={borderWidth:0,shadow:!1}:this.is("scatter")||
this.is("sma")||(c={marker:{enabled:!1,radius:2}}),c&&(a.plotOptions[this.type]=l(a.plotOptions[this.type],c)))});q(p,"autoLabelAlign",function(a){var c=this.chart,b=this.options;c=c._labelPanes=c._labelPanes||{};var e=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(b=b.top+","+b.height,!c[b]&&e.enabled&&(15===e.x&&(e.x=0),"undefined"===typeof e.align&&(e.align="right"),c[b]=this,a.align="right",a.preventDefault()))});q(p,"destroy",function(){var a=this.chart,b=this.options&&
this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});q(p,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return w(a)?[d[b][a]]:r(a)?[d.get(a)]:f.map(function(a){return a[b]})}var c=this,f=this.isLinked&&!this.series?this.linkedParent.series:this.series,d=c.chart,k=d.renderer,h=c.left,l=c.top,m,n,p,q,t=[],u=[],v=a.translatedValue,y=a.value,A=a.force;if(d.options.isStock&&!1!==a.acrossPanes&&"xAxis"===
c.coll||"yAxis"===c.coll){a.preventDefault();u=b(c.coll);var D=c.isXAxis?d.yAxis:d.xAxis;D.forEach(function(a){if(I(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=I(a.options[b])?d[b][a.options[b]]:d[b][0];c===b&&u.push(a)}});var C=u.length?[]:[c.isXAxis?d.yAxis[0]:d.xAxis[0]];u.forEach(function(a){-1!==C.indexOf(a)||x(C,function(c){return c.pos===a.pos&&c.len===a.len})||C.push(a)});var J=e(v,c.translate(y,null,null,a.old));w(J)&&(c.horiz?C.forEach(function(a){var b;
n=a.pos;q=n+a.len;m=p=Math.round(J+c.transB);"pass"!==A&&(m<h||m>h+c.width)&&(A?m=p=H(m,h,h+c.width):b=!0);b||t.push(["M",m,n],["L",p,q])}):C.forEach(function(a){var b;m=a.pos;p=m+a.len;n=q=Math.round(l+c.height-J);"pass"!==A&&(n<l||n>l+c.height)&&(A?n=q=H(n,l,l+c.height):b=!0);b||t.push(["M",m,n],["L",p,q])}));a.path=0<t.length?k.crispPolyLine(t,a.lineWidth||1):null}});C.prototype.crispPolyLine=function(a,b){for(var c=0;c<a.length;c+=2){var e=a[c],d=a[c+1];e[1]===d[1]&&(e[1]=d[1]=Math.round(e[1])-
b%2/2);e[2]===d[2]&&(e[2]=d[2]=Math.round(e[2])+b%2/2)}return a};q(p,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});q(p,"afterDrawCrosshair",function(a){var b,c;if(I(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,f=this.logarithmic,k=this.options.crosshair.label,h=this.horiz,l=this.opposite,m=this.left,n=this.top,p=this.crossLabel,q=k.format,r="",t="inside"===this.options.tickPosition,u=!1!==this.crosshair.snap,w=0,x=
a.e||this.cross&&this.cross.e,y=a.point;a=this.min;var A=this.max;f&&(a=f.lin2log(a),A=f.lin2log(A));f=h?"center":l?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";p||(p=this.crossLabel=d.renderer.label(null,null,null,k.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:k.align||f,padding:e(k.padding,8),r:e(k.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||p.attr({fill:k.backgroundColor||
this.series[0]&&this.series[0].color||"#666666",stroke:k.borderColor||"","stroke-width":k.borderWidth||0}).css(D({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},k.style)));h?(f=u?y.plotX+m:x.chartX,n+=l?0:this.height):(f=l?this.width+m:0,n=u?y.plotY+n:x.chartY);q||k.formatter||(this.dateTime&&(r="%b %d, %Y"),q="{value"+(r?":"+r:"")+"}");r=u?y[this.isXAxis?"x":"y"]:this.toValue(h?x.chartX:x.chartY);p.attr({text:q?v(q,{value:r},d):k.formatter.call(this,r),x:f,y:n,visibility:r<
a||r>A?"hidden":"visible"});k=p.getBBox();if(h){if(t&&!l||!t&&l)n=p.y-k.height}else n=p.y-k.height/2;h?(b=m-k.x,c=m+this.width-k.x):(b="left"===this.labelAlign?m:0,c="right"===this.labelAlign?m+this.width:d.chartWidth);p.translateX<b&&(w=b-p.translateX);p.translateX+k.width>=c&&(w=-(p.translateX+k.width-c));p.attr({x:f+w,y:n,anchorX:h?f:this.opposite?0:d.chartWidth,anchorY:h?this.opposite?d.chartHeight:0:n+k.height/2})}});a.init=function(){m.apply(this,arguments);this.setCompare(this.options.compare)};
a.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};a.processData=function(a){var b,c=-1,d=!0===this.options.compareStart?0:1;f.apply(this,arguments);if(this.xAxis&&this.processedYData){var e=this.processedXData;var h=this.processedYData;
var l=h.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<l-d;b++){var m=h[b]&&-1<c?h[b][c]:h[b];if(w(m)&&e[b+d]>=this.xAxis.min&&0!==m){this.compareValue=m;break}}}};q(h,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];a.dataMin=d(b);a.dataMax=A(b)}});p.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),
e(b,!0)&&this.chart.redraw())};u.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,e(this.series.tooltipOptions.changeDecimals,2)));return t.apply(this,[a])};q(h,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var d=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,e=Math.floor(this.xAxis.axisLine.strokeWidth()/
2);0<=d&&(b-=Math.max(e-d,0))}!this.clipBox&&this.animate?(this.clipBox=l(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});q(n,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(l(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})});J(p,"masters/modules/stock.src.js",
[],function(){})});
//# sourceMappingURL=stock.js.map