/*
 Highstock JS v8.1.0 (2020-05-12)

 Advanced Highstock tools

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/stock-tools",["highcharts","highcharts/modules/stock"],function(r){e(r);e.Highcharts=r;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function r(e,d,l,h){e.hasOwnProperty(d)||(e[d]=h.apply(null,l))}e=e?e._modules:{};r(e,"annotations/eventEmitterMixin.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,d){var l=
d.addEvent,h=d.fireEvent,q=d.inArray,c=d.objectEach,m=d.pick,B=d.removeEvent;return{addEvents:function(){var b=this,g=function(g){l(g,"mousedown",function(a){b.onMouseDown(a)})};g(this.graphic.element);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&g(b.graphic.text.element)});c(b.options.events,function(g,a){var f=function(f){"click"===a&&b.cancelClick||g.call(b,b.chart.pointer.normalize(f),b.target)};if(-1===q(a,b.nonDOMEvents||[]))b.graphic.on(a,f);else l(b,a,f)});if(b.options.draggable&&
(l(b,"drag",b.onDrag),!b.graphic.renderer.styledMode)){var t={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[b.options.draggable]};b.graphic.css(t);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&b.graphic.text.css(t)})}b.isUpdating||h(b,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(b){var g=this,c=g.chart.pointer;b.preventDefault&&b.preventDefault();
if(2!==b.button){b=c.normalize(b);var k=b.chartX;var a=b.chartY;g.cancelClick=!1;g.chart.hasDraggedAnnotation=!0;g.removeDrag=l(e.doc,"mousemove",function(f){g.hasDragged=!0;f=c.normalize(f);f.prevChartX=k;f.prevChartY=a;h(g,"drag",f);k=f.chartX;a=f.chartY});g.removeMouseUp=l(e.doc,"mouseup",function(a){g.cancelClick=g.hasDragged;g.hasDragged=!1;g.chart.hasDraggedAnnotation=!1;h(m(g.target,g),"afterUpdate");g.onMouseUp(a)})}},onMouseUp:function(b){var g=this.chart;b=this.target||this;var c=g.options.annotations;
g=g.annotations.indexOf(b);this.removeDocEvents();c[g]=b.options},onDrag:function(b){if(this.chart.isInsidePlot(b.chartX-this.chart.plotLeft,b.chartY-this.chart.plotTop)){var g=this.mouseMoveToTranslation(b);"x"===this.options.draggable&&(g.y=0);"y"===this.options.draggable&&(g.x=0);this.points.length?this.translate(g.x,g.y):(this.shapes.forEach(function(b){b.translate(g.x,g.y)}),this.labels.forEach(function(b){b.translate(g.x,g.y)}));this.redraw(!1)}},mouseMoveToRadians:function(b,g,c){var k=b.prevChartY-
c,a=b.prevChartX-g;c=b.chartY-c;b=b.chartX-g;this.chart.inverted&&(g=a,a=k,k=g,g=b,b=c,c=g);return Math.atan2(c,b)-Math.atan2(k,a)},mouseMoveToTranslation:function(b){var g=b.chartX-b.prevChartX;b=b.chartY-b.prevChartY;if(this.chart.inverted){var c=b;b=g;g=c}return{x:g,y:b}},mouseMoveToScale:function(b,g,c){g=(b.chartX-g||1)/(b.prevChartX-g||1);b=(b.chartY-c||1)/(b.prevChartY-c||1);this.chart.inverted&&(c=b,b=g,g=c);return{x:g,y:b}},destroy:function(){this.removeDocEvents();B(this);this.hcEvents=
null}}});r(e,"annotations/ControlPoint.js",[e["parts/Utilities.js"],e["annotations/eventEmitterMixin.js"]],function(e,d){var l=e.merge,h=e.pick;return function(){function e(c,m,e,b){this.addEvents=d.addEvents;this.graphic=void 0;this.mouseMoveToRadians=d.mouseMoveToRadians;this.mouseMoveToScale=d.mouseMoveToScale;this.mouseMoveToTranslation=d.mouseMoveToTranslation;this.onDrag=d.onDrag;this.onMouseDown=d.onMouseDown;this.onMouseUp=d.onMouseUp;this.removeDocEvents=d.removeDocEvents;this.nonDOMEvents=
["drag"];this.chart=c;this.target=m;this.options=e;this.index=h(e.index,b)}e.prototype.setVisibility=function(c){this.graphic.attr("visibility",c?"visible":"hidden");this.options.visible=c};e.prototype.render=function(){var c=this.chart,e=this.options;this.graphic=c.renderer.symbol(e.symbol,0,0,e.width,e.height).add(c.controlPointsGroup).css(e.style);this.setVisibility(e.visible);this.addEvents()};e.prototype.redraw=function(c){this.graphic[c?"animate":"attr"](this.options.positioner.call(this,this.target))};
e.prototype.destroy=function(){d.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};e.prototype.update=function(c){var e=this.chart,d=this.target,b=this.index;c=l(!0,this.options,c);this.destroy();this.constructor(e,d,c,b);this.render(e.controlPointsGroup);this.redraw()};return e}()});r(e,"annotations/MockPoint.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,d){var l=d.defined,h=d.fireEvent;return function(){function d(c,
d,h){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=!0;this.series={visible:!0,chart:c,getPlotBox:e.Series.prototype.getPlotBox};this.target=d||null;this.options=h;this.applyOptions(this.getOptions())}d.fromPoint=function(c){return new d(c.series.chart,null,{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis})};d.pointToPixels=function(c,d){var e=c.series,b=e.chart,g=c.plotX,m=c.plotY;b.inverted&&(c.mock?(g=c.plotY,m=c.plotX):(g=b.plotWidth-c.plotY,m=b.plotHeight-c.plotX));
e&&!d&&(c=e.getPlotBox(),g+=c.translateX,m+=c.translateY);return{x:g,y:m}};d.pointToOptions=function(c){return{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis}};d.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};d.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};d.prototype.applyOptions=function(c){this.command=c.command;this.setAxis(c,"x");this.setAxis(c,"y");this.refresh()};d.prototype.setAxis=function(c,
d){d+="Axis";c=c[d];var m=this.series.chart;this.series[d]=c instanceof e.Axis?c:l(c)?m[d][c]||m.get(c):null};d.prototype.toAnchor=function(){var c=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(c[0]=this.plotY,c[1]=this.plotX);return c};d.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};d.prototype.isInsidePlot=function(){var c=this.plotX,d=this.plotY,e=this.series.xAxis,b=this.series.yAxis,g={x:c,y:d,isInsidePlot:!0};e&&(g.isInsidePlot=l(c)&&0<=c&&c<=e.len);b&&
(g.isInsidePlot=g.isInsidePlot&&l(d)&&0<=d&&d<=b.len);h(this.series.chart,"afterIsInsidePlot",g);return g.isInsidePlot};d.prototype.refresh=function(){var c=this.series,d=c.xAxis;c=c.yAxis;var e=this.getOptions();d?(this.x=e.x,this.plotX=d.toPixels(e.x,!0)):(this.x=null,this.plotX=e.x);c?(this.y=e.y,this.plotY=c.toPixels(e.y,!0)):(this.y=null,this.plotY=e.y);this.isInside=this.isInsidePlot()};d.prototype.translate=function(c,d,e,b){this.hasDynamicOptions()||(this.plotX+=e,this.plotY+=b,this.refreshOptions())};
d.prototype.scale=function(c,d,e,b){if(!this.hasDynamicOptions()){var g=this.plotY*b;this.plotX=(1-e)*c+this.plotX*e;this.plotY=(1-b)*d+g;this.refreshOptions()}};d.prototype.rotate=function(c,d,e){if(!this.hasDynamicOptions()){var b=Math.cos(e);e=Math.sin(e);var g=this.plotX,h=this.plotY;g-=c;h-=d;this.plotX=g*b-h*e+c;this.plotY=g*e+h*b+d;this.refreshOptions()}};d.prototype.refreshOptions=function(){var c=this.series,d=c.xAxis;c=c.yAxis;this.x=this.options.x=d?this.options.x=d.toValue(this.plotX,
!0):this.plotX;this.y=this.options.y=c?c.toValue(this.plotY,!0):this.plotY};return d}()});r(e,"annotations/controllable/controllableMixin.js",[e["annotations/ControlPoint.js"],e["annotations/MockPoint.js"],e["parts/Tooltip.js"],e["parts/Utilities.js"]],function(e,d,l,h){var q=h.isObject,c=h.isString,m=h.merge,x=h.splat;return{init:function(b,g,c){this.annotation=b;this.chart=b.chart;this.options=g;this.points=[];this.controlPoints=[];this.index=c;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,
arguments)},getPointsOptions:function(){var b=this.options;return b.points||b.point&&x(b.point)},attrsFromOptions:function(b){var g=this.constructor.attrsMap,c={},d,a=this.chart.styledMode;for(d in b){var f=g[d];!f||a&&-1!==["fill","stroke","stroke-width"].indexOf(f)||(c[f]=b[d])}return c},anchor:function(b){var g=b.series.getPlotBox();b=b.mock?b.toAnchor():l.prototype.getAnchor.call({chart:b.series.chart},b);b={x:b[0]+(this.options.x||0),y:b[1]+(this.options.y||0),height:b[2]||0,width:b[3]||0};return{relativePosition:b,
absolutePosition:m(b,{x:b.x+g.translateX,y:b.y+g.translateY})}},point:function(b,g){if(b&&b.series)return b;g&&null!==g.series||(q(b)?g=new d(this.chart,this,b):c(b)?g=this.chart.get(b)||null:"function"===typeof b&&(g=b.call(g,this),g=g.series?g:new d(this.chart,this,b)));return g},linkPoints:function(){var b=this.getPointsOptions(),g=this.points,c=b&&b.length||0,d;for(d=0;d<c;d++){var a=this.point(b[d],g[d]);if(!a){g.length=0;return}a.mock&&a.refresh();g[d]=a}return g},addControlPoints:function(){var b=
this.options.controlPoints;(b||[]).forEach(function(c,d){c=m(this.options.controlPointOptions,c);c.index||(c.index=d);b[d]=c;this.controlPoints.push(new e(this.chart,this,c))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(b){this.controlPoints.forEach(function(b){b.render()})},redraw:function(b){this.controlPoints.forEach(function(c){c.redraw(b)})},transform:function(b,c,d,e,a){if(this.chart.inverted){var f=c;c=d;d=f}this.points.forEach(function(f,u){this.transformPoint(b,
c,d,e,a,u)},this)},transformPoint:function(b,c,e,k,a,f){var n=this.points[f];n.mock||(n=this.points[f]=d.fromPoint(n));n[b](c,e,k,a)},translate:function(b,c){this.transform("translate",null,null,b,c)},translatePoint:function(b,c,d){this.transformPoint("translate",null,null,b,c,d)},translateShape:function(b,c){var d=this.annotation.chart,e=this.annotation.userOptions,a=d.annotations.indexOf(this.annotation);d=d.options.annotations[a];this.translatePoint(b,c,0);d[this.collection][this.index].point=
this.options.point;e[this.collection][this.index].point=this.options.point},rotate:function(b,c,d){this.transform("rotate",b,c,d)},scale:function(b,c,d,e){this.transform("scale",b,c,d,e)},setControlPointsVisibility:function(b){this.controlPoints.forEach(function(c){c.setVisibility(b)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.controlPoints.forEach(function(b){b.destroy()});this.options=this.controlPoints=this.points=
this.chart=null;this.annotation&&(this.annotation=null)},update:function(b){var c=this.annotation;b=m(!0,this.options,b);var d=this.graphic.parentGroup;this.destroy();this.constructor(c,b);this.render(d);this.redraw()}}});r(e,"annotations/controllable/markerMixin.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,d){var l=d.addEvent,h=d.defined,q=d.merge,c=d.objectEach,m=d.uniqueKey,x={arrow:{tagName:"marker",render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",
d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};e.SVGRenderer.prototype.addMarker=function(b,c){var d={id:b},e={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};d.children=c.children.map(function(a){return q(e,a)});c=this.definition(q(!0,{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},c,d));c.id=b;return c};
d=function(b){return function(c){this.attr(b,"url(#"+c+")")}};d={markerEndSetter:d("marker-end"),markerStartSetter:d("marker-start"),setItemMarkers:function(b){var c=b.options,d=b.chart,e=d.options.defs,a=c.fill,f=h(a)&&"none"!==a?a:c.stroke;["markerStart","markerEnd"].forEach(function(a){var n=c[a],k;if(n){for(k in e){var g=e[k];if(n===g.id&&"marker"===g.tagName){var p=g;break}}p&&(n=b[a]=d.renderer.addMarker((c.id||m())+"-"+p.id,q(p,{color:f})),b.attr(a,n.attr("id")))}})}};l(e.Chart,"afterGetContainer",
function(){this.options.defs=q(x,this.options.defs||{});c(this.options.defs,function(b){"marker"===b.tagName&&!1!==b.render&&this.renderer.addMarker(b.id,b)},this)});return d});r(e,"annotations/controllable/ControllablePath.js",[e["annotations/controllable/controllableMixin.js"],e["parts/Globals.js"],e["annotations/controllable/markerMixin.js"],e["parts/Utilities.js"]],function(e,d,l,h){var q=h.extend;h=h.merge;var c="rgba(192,192,192,"+(d.svg?.0001:.002)+")";d=function(c,d,b){this.init(c,d,b);this.collection=
"shapes"};d.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};h(!0,d.prototype,e,{type:"path",setMarkers:l.setItemMarkers,toD:function(){var c=this.options.d;if(c)return"function"===typeof c?c.call(this):c;c=this.points;var d=c.length,b=d,e=c[0],h=b&&this.anchor(e).absolutePosition,k=0,a=[];if(h)for(a.push(["M",h.x,h.y]);++k<d&&b;)e=c[k],b=e.command||"L",h=this.anchor(e).absolutePosition,"M"===b?a.push([b,h.x,h.y]):"L"===b?a.push([b,h.x,h.y]):
"Z"===b&&a.push([b]),b=e.series.visible;return b?this.chart.renderer.crispLine(a,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return e.shouldBeDrawn.call(this)||!!this.options.d},render:function(d){var h=this.options,b=this.attrsFromOptions(h);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(b).add(d);h.className&&this.graphic.addClass(h.className);this.tracker=this.annotation.chart.renderer.path([["M",0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(d);
this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:c,fill:c,"stroke-width":this.graphic.strokeWidth()+2*h.snap});e.render.call(this);q(this.graphic,{markerStartSetter:l.markerStartSetter,markerEndSetter:l.markerEndSetter});this.setMarkers(this)},redraw:function(c){var d=this.toD(),b=c?"animate":"attr";d?(this.graphic[b]({d:d}),this.tracker[b]({d:d})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=
!!d;e.redraw.call(this,c)}});return d});r(e,"annotations/controllable/ControllableRect.js",[e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllablePath.js"],e["parts/Utilities.js"]],function(e,d,l){l=l.merge;var h=function(d,c,e){this.init(d,c,e);this.collection="shapes"};h.attrsMap=l(d.attrsMap,{width:"width",height:"height"});l(!0,h.prototype,e,{type:"rect",translate:e.translateShape,render:function(d){var c=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,
-9E9,0,0).attr(c).add(d);e.render.call(this)},redraw:function(d){var c=this.anchor(this.points[0]).absolutePosition;if(c)this.graphic[d?"animate":"attr"]({x:c.x,y:c.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!c;e.redraw.call(this,d)}});return h});r(e,"annotations/controllable/ControllableCircle.js",[e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllablePath.js"],e["parts/Utilities.js"]],function(e,
d,l){l=l.merge;var h=function(d,c,e){this.init(d,c,e);this.collection="shapes"};h.attrsMap=l(d.attrsMap,{r:"r"});l(!0,h.prototype,e,{type:"circle",translate:e.translateShape,render:function(d){var c=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(c).add(d);e.render.call(this)},redraw:function(d){var c=this.anchor(this.points[0]).absolutePosition;if(c)this.graphic[d?"animate":"attr"]({x:c.x,y:c.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});
this.graphic.placed=!!c;e.redraw.call(this,d)},setRadius:function(d){this.options.r=d}});return h});r(e,"annotations/controllable/ControllableLabel.js",[e["annotations/controllable/controllableMixin.js"],e["parts/Globals.js"],e["annotations/MockPoint.js"],e["parts/Tooltip.js"],e["parts/Utilities.js"]],function(e,d,l,h,q){var c=q.extend,m=q.format,x=q.isNumber,b=q.merge,g=q.pick,t=function(b,a,f){this.init(b,a,f);this.collection="labels"};t.shapesWithoutBackground=["connector"];t.alignedPosition=function(b,
a){var f=b.align,c=b.verticalAlign,d=(a.x||0)+(b.x||0),e=(a.y||0)+(b.y||0),k,g;"right"===f?k=1:"center"===f&&(k=2);k&&(d+=(a.width-(b.width||0))/k);"bottom"===c?g=1:"middle"===c&&(g=2);g&&(e+=(a.height-(b.height||0))/g);return{x:Math.round(d),y:Math.round(e)}};t.justifiedOptions=function(b,a,f,c){var d=f.align,e=f.verticalAlign,n=a.box?0:a.padding||0,g=a.getBBox();a={align:d,verticalAlign:e,x:f.x,y:f.y,width:a.width,height:a.height};f=c.x-b.plotLeft;var k=c.y-b.plotTop;c=f+n;0>c&&("right"===d?a.align=
"left":a.x=-c);c=f+g.width-n;c>b.plotWidth&&("left"===d?a.align="right":a.x=b.plotWidth-c);c=k+n;0>c&&("bottom"===e?a.verticalAlign="top":a.y=-c);c=k+g.height-n;c>b.plotHeight&&("top"===e?a.verticalAlign="bottom":a.y=b.plotHeight-c);return a};t.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};b(!0,t.prototype,e,{translatePoint:function(b,a){e.translatePoint.call(this,b,a,0)},translate:function(b,a){var f=this.annotation.chart,
c=this.annotation.userOptions,d=f.annotations.indexOf(this.annotation);d=f.options.annotations[d];f.inverted&&(f=b,b=a,a=f);this.options.x+=b;this.options.y+=a;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=this.options.y},render:function(b){var a=this.options,f=this.attrsFromOptions(a),c=a.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,a.shape,null,
null,a.useHTML,null,"annotation-label").attr(f).add(b);this.annotation.chart.styledMode||("contrast"===c.color&&(c.color=this.annotation.chart.renderer.getContrast(-1<t.shapesWithoutBackground.indexOf(a.shape)?"#FFFFFF":a.backgroundColor)),this.graphic.css(a.style).shadow(a.shadow));a.className&&this.graphic.addClass(a.className);this.graphic.labelrank=a.labelrank;e.render.call(this)},redraw:function(b){var a=this.options,f=this.text||a.format||a.text,c=this.graphic,d=this.points[0];c.attr({text:f?
m(f,d.getLabelConfig(),this.annotation.chart):a.formatter.call(d,this)});a=this.anchor(d);(f=this.position(a))?(c.alignAttr=f,f.anchorX=a.absolutePosition.x,f.anchorY=a.absolutePosition.y,c[b?"animate":"attr"](f)):c.attr({x:0,y:-9999});c.placed=!!f;e.redraw.call(this,b)},anchor:function(){var b=e.anchor.apply(this,arguments),a=this.options.x||0,f=this.options.y||0;b.absolutePosition.x-=a;b.absolutePosition.y-=f;b.relativePosition.x-=a;b.relativePosition.y-=f;return b},position:function(b){var a=this.graphic,
f=this.annotation.chart,d=this.points[0],e=this.options,k=b.absolutePosition,v=b.relativePosition;if(b=d.series.visible&&l.prototype.isInsidePlot.call(d)){if(e.distance)var p=h.prototype.getPosition.call({chart:f,distance:g(e.distance,16)},a.width,a.height,{plotX:v.x,plotY:v.y,negative:d.negative,ttBelow:d.ttBelow,h:v.height||v.width});else e.positioner?p=e.positioner.call(this):(d={x:k.x,y:k.y,width:0,height:0},p=t.alignedPosition(c(e,{width:a.width,height:a.height}),d),"justify"===this.options.overflow&&
(p=t.alignedPosition(t.justifiedOptions(f,a,e,p),d)));e.crop&&(e=p.x-f.plotLeft,d=p.y-f.plotTop,b=f.isInsidePlot(e,d)&&f.isInsidePlot(e+a.width,d+a.height))}return b?p:null}});d.SVGRenderer.prototype.symbols.connector=function(b,a,f,c,d){var e=d&&d.anchorX;d=d&&d.anchorY;var n=f/2;if(x(e)&&x(d)){var g=[["M",e,d]];var u=a-d;0>u&&(u=-c-u);u<f&&(n=e<b+f/2?u:f-u);d>a+c?g.push(["L",b+n,a+c]):d<a?g.push(["L",b+n,a]):e<b?g.push(["L",b,a+c/2]):e>b+f&&g.push(["L",b+f,a+c/2])}return g||[]};return t});r(e,"annotations/controllable/ControllableImage.js",
[e["annotations/controllable/ControllableLabel.js"],e["annotations/controllable/controllableMixin.js"],e["parts/Utilities.js"]],function(e,d,l){l=l.merge;var h=function(d,c,e){this.init(d,c,e);this.collection="shapes"};h.attrsMap={width:"width",height:"height",zIndex:"zIndex"};l(!0,h.prototype,d,{type:"image",translate:d.translateShape,render:function(e){var c=this.attrsFromOptions(this.options),h=this.options;this.graphic=this.annotation.chart.renderer.image(h.src,0,-9E9,h.width,h.height).attr(c).add(e);
this.graphic.width=h.width;this.graphic.height=h.height;d.render.call(this)},redraw:function(h){var c=this.anchor(this.points[0]);if(c=e.prototype.position.call(this,c))this.graphic[h?"animate":"attr"]({x:c.x,y:c.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!c;d.redraw.call(this,h)}});return h});r(e,"annotations/annotations.src.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllableRect.js"],e["annotations/controllable/ControllableCircle.js"],
e["annotations/controllable/ControllablePath.js"],e["annotations/controllable/ControllableImage.js"],e["annotations/controllable/ControllableLabel.js"],e["annotations/eventEmitterMixin.js"],e["annotations/MockPoint.js"],e["annotations/ControlPoint.js"]],function(e,d,l,h,q,c,m,r,b,g,t){var k=d.addEvent,a=d.defined,f=d.destroyObjectProperties,n=d.erase,u=d.extend,A=d.find,v=d.fireEvent,p=d.merge,w=d.pick,C=d.splat;d=d.wrap;var z=e.Chart.prototype,y=function(){function a(a,b){this.annotation=void 0;
this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=p(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)}a.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();
this.addLabels();this.setLabelCollector()};a.prototype.getLabelsAndShapesOptions=function(a,b){var f={};["labels","shapes"].forEach(function(c){a[c]&&(f[c]=C(b[c]).map(function(b,f){return p(a[c][f],b)}))});return f};a.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);p(!0,this.options.shapes[b],a.options)},this)};a.prototype.addLabels=function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);p(!0,this.options.labels[b],a.options)},
this)};a.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};a.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,f=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(f,c){return[a[c&&c.point&&c.point.xAxis]||f[0],b[c&&c.point&&c.point.yAxis]||f[1]]},[]);this.clipXAxis=f[0];this.clipYAxis=f[1]};a.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,
y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};a.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};a.prototype.setOptions=function(a){this.options=p(this.defaultOptions,a)};a.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());
this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);l.redraw.call(this,a)};a.prototype.redrawItems=function(a,b){for(var f=a.length;f--;)this.redrawItem(a[f],b)};a.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};a.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);
this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();l.render.call(this)};a.prototype.setVisibility=function(a){var b=this.options;a=w(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};a.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};
l.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};a.prototype.destroy=function(){var a=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;n(a.labelCollectors,this.labelCollector);b.destroy.call(this);l.destroy.call(this);f(this,a)};a.prototype.remove=function(){return this.chart.removeAnnotation(this)};a.prototype.update=function(a,b){var f=this.chart,c=this.getLabelsAndShapesOptions(this.userOptions,
a),d=f.annotations.indexOf(this);a=p(!0,this.userOptions,a);a.labels=c.labels;a.shapes=c.shapes;this.destroy();this.constructor(f,a);f.options.annotations[d]=a;this.isUpdating=!0;w(b,!0)&&f.redraw();v(this,"afterUpdate");this.isUpdating=!1};a.prototype.initShape=function(b,f){b=p(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},b);f=new a.shapesMap[b.type](this,b,f);f.itemType="shape";this.shapes.push(f);return f};a.prototype.initLabel=function(a,b){a=p(this.options.labelOptions,
{controlPointOptions:this.options.controlPointOptions},a);b=new r(this,a,b);b.itemType="label";this.labels.push(b);return b};a.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(w(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};a.prototype.adjustVisibility=function(a){var b=!1,f=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===f.visibility&&f.show():
f.hide()};a.prototype.destroyItem=function(a){n(this[a.itemType+"s"],a);a.destroy()};a.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};a.ControlPoint=t;a.MockPoint=g;a.shapesMap={rect:h,circle:q,path:c,image:m};a.types={};return a}();p(!0,y.prototype,l,b,p(y.prototype,{nonDOMEvents:["add","afterUpdate","drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",
borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return a(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},
events:{},zIndex:6}}));e.extendAnnotation=function(a,b,f,c){b=b||y;p(!0,a.prototype,b.prototype,f);a.prototype.defaultOptions=p(a.prototype.defaultOptions,c||{})};u(z,{initAnnotation:function(a){a=new (y.types[a.type]||y)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);w(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,f="annotations"===a.coll?a:A(b,function(b){return b.options.id===
a});f&&(v(f,"remove"),n(this.options.annotations,f.options),n(b,f),f.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});z.collectionsWithUpdate.push("annotations");z.collectionsWithInit.annotations=[z.addAnnotation];z.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();
a.options.annotations.forEach(function(b,f){b=a.initAnnotation(b);a.options.annotations[f]=b.options});a.drawAnnotations();k(a,"redraw",a.drawAnnotations);k(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});d(e.Pointer.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))});return e.Annotation=y});r(e,"mixins/navigation.js",[],function(){return{initUpdate:function(e){e.navigation||(e.navigation=
{updates:[],update:function(d,e){this.updates.forEach(function(h){h.update.call(h.context,d,e)})}})},addUpdate:function(e,d){d.navigation||this.initUpdate(d);d.navigation.updates.push({update:e,context:d})}}});r(e,"annotations/navigationBindings.js",[e["annotations/annotations.src.js"],e["mixins/navigation.js"],e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,d,l,h){function q(a){var c=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;f(!0,a.prototype.defaultOptions.events,
{click:function(a){var f=this,d=f.chart.navigationBindings,e=d.activeAnnotation;c&&c.click.call(f,a);e!==f?(d.deselectAnnotation(),d.activeAnnotation=f,f.setControlPointsVisibility(!0),b(d,"showPopup",{annotation:f,formType:"annotation-toolbar",options:d.annotationToFields(f),onSubmit:function(a){var b={};"remove"===a.actionType?(d.activeAnnotation=!1,d.chart.removeAnnotation(f)):(d.fieldsToOptions(a.fields,b),d.deselectAnnotation(),a=b.typeOptions,"measure"===f.options.type&&(a.crosshairY.enabled=
0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),f.update(b))}})):(d.deselectAnnotation(),b(d,"closePopup"));a.activeAnnotation=!0}})}var c=h.addEvent,m=h.attr,r=h.format,b=h.fireEvent,g=h.isArray,t=h.isFunction,k=h.isNumber,a=h.isObject,f=h.merge,n=h.objectEach,u=h.pick,A=l.doc,v=l.win,p=function(){function e(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=A.getElementsByClassName(this.options.bindingsClassName||
"")}e.prototype.initEvents=function(){var a=this,b=a.chart,f=a.container,d=a.options;a.boundClassNames={};n(d.bindings||{},function(b){a.boundClassNames[b.className]=b});[].forEach.call(f,function(b){a.eventsToUnbind.push(c(b,"click",function(f){var c=a.getButtonEvents(b,f);c&&a.bindingsButtonClick(c.button,c.events,f)}))});n(d.events||{},function(b,f){t(b)&&a.eventsToUnbind.push(c(a,f,b))});a.eventsToUnbind.push(c(b.container,"click",function(f){!b.cancelClick&&b.isInsidePlot(f.chartX-b.plotLeft,
f.chartY-b.plotTop)&&a.bindingsChartClick(this,f)}));a.eventsToUnbind.push(c(b.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))};e.prototype.initUpdate=function(){var a=this;d.addUpdate(function(b){a.update(b)},this.chart)};e.prototype.bindingsButtonClick=function(a,f,c){var d=this.chart;this.selectedButtonElement&&(b(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),
this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=f;this.selectedButtonElement=a;b(this,"selectButton",{button:a});f.init&&f.init.call(this,a,c);(f.start||f.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")};e.prototype.bindingsChartClick=function(a,f){a=this.chart;var c=this.selectedButton;a=a.renderer.boxWrapper;var d;if(d=this.activeAnnotation&&!f.activeAnnotation&&f.target.parentNode){a:{d=f.target;var e=v.Element.prototype,n=e.matches||e.msMatchesSelector||e.webkitMatchesSelector,
g=null;if(e.closest)g=e.closest.call(d,".highcharts-popup");else{do{if(n.call(d,".highcharts-popup"))break a;d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType)}d=g}d=!d}d&&(b(this,"closePopup"),this.deselectAnnotation());c&&c.start&&(this.nextEvent?(this.nextEvent(f,this.currentUserDetails),this.steps&&(this.stepIndex++,c.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]:(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),
c.end&&c.end.call(this,f,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=c.start.call(this,f),c.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=c.steps[this.stepIndex]):(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,c.end&&c.end.call(this,f,this.currentUserDetails))))};e.prototype.bindingsContainerMouseMove=function(a,
b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};e.prototype.fieldsToOptions=function(a,b){n(a,function(a,f){var c=parseFloat(a),d=f.split("."),e=b,n=d.length-1;!k(c)||a.match(/px/g)||f.match(/format/g)||(a=c);""!==a&&"undefined"!==a&&d.forEach(function(b,f){var c=u(d[f+1],"");n===f?e[b]=a:(e[b]||(e[b]=c.match(/\d/g)?[]:{}),e=e[b])})});return b};e.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=
!1)};e.prototype.annotationToFields=function(b){function f(c,d,e,u){if(e&&-1===v.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(g(c))u[d]=[],c.forEach(function(b,c){a(b)?(u[d][c]={},n(b,function(a,b){f(a,b,h[d],u[d][c])})):f(b,0,h[d],u[d])});else if(a(c)){var k={};g(u)?(u.push(k),k[d]={},k=k[d]):u[d]=k;n(c,function(a,b){f(a,b,0===d?e:h[d],k)})}else"format"===d?u[d]=[r(c,b.labels[0].points[0]).toString(),"text"]:g(u)?u.push([c,p(c)]):u[d]=[c,p(c)]}var c=b.options,d=e.annotationsEditable,
h=d.nestedOptions,p=this.utils.getFieldType,k=u(c.type,c.shapes&&c.shapes[0]&&c.shapes[0].type,c.labels&&c.labels[0]&&c.labels[0].itemType,"label"),v=e.annotationsNonEditable[c.langKey]||[],w={langKey:c.langKey,type:k};n(c,function(a,b){"typeOptions"===b?(w[b]={},n(c[b],function(a,c){f(a,c,h,w[b],!0)})):f(a,b,d[k],w)});return w};e.prototype.getClickedClassNames=function(a,b){var f=b.target;b=[];for(var c;f&&((c=m(f,"class"))&&(b=b.concat(c.split(" ").map(function(a){return[a,f]}))),f=f.parentNode,
f!==a););return b};e.prototype.getButtonEvents=function(a,b){var f=this,c;this.getClickedClassNames(a,b).forEach(function(a){f.boundClassNames[a[0]]&&!c&&(c={events:f.boundClassNames[a[0]],button:a[1]})});return c};e.prototype.update=function(a){this.options=f(!0,this.options,a);this.removeEvents();this.initEvents()};e.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};e.prototype.destroy=function(){this.removeEvents()};e.annotationsEditable={nestedOptions:{labelOptions:["style",
"format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],
label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:[]};e.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};return e}();p.prototype.utils={updateRectSize:function(a,b){var f=b.chart,c=b.options.typeOptions,d=f.pointer.getCoordinates(a);a=d.xAxis[0].value-c.point.x;c=c.point.y-d.yAxis[0].value;b.update({typeOptions:{background:{width:f.inverted?
c:a,height:f.inverted?a:c}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};l.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new p(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};c(l.Chart,"load",function(){this.initNavigationBindings()});c(l.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});
c(p,"deselectButton",function(){this.selectedButtonElement=null});c(e,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});l.Annotation&&(q(e),n(e.types,function(a){q(a)}));l.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",
labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=
this.chart.options.navigation;return this.chart.addAnnotation(f({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5}]},b.annotationsOptions,b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var f=b.options.shapes[0].point,c=this.chart.xAxis[0].toPixels(f.x);f=this.chart.yAxis[0].toPixels(f.y);var d=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(d?f-a.chartX:c-a.chartX,2)+Math.pow(d?
c-a.chartY:f-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a);a=this.chart.options.navigation;var c=b.xAxis[0].value;b=b.yAxis[0].value;return this.chart.addAnnotation(f({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b}]}]},a.annotationsOptions,a.bindings.rectangleAnnotation.annotationsOptions))},
steps:[function(a,b){var f=b.options.shapes[0].points,c=this.chart.pointer.getCoordinates(a);a=c.xAxis[0].value;c=c.yAxis[0].value;f[1].x=a;f[2].x=a;f[2].y=c;f[3].y=c;b.update({shapes:[{points:f}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(f({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,
y:a.yAxis[0].value},overflow:"none",crop:!0}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return p});r(e,"modules/stock-tools-bindings.js",[e["parts/Globals.js"],e["annotations/navigationBindings.js"],e["parts/Utilities.js"]],function(e,d,l){var h=l.correctFloat,q=l.defined,c=l.extend,m=l.fireEvent,r=l.isNumber,b=l.merge,g=l.pick,t=l.uniqueKey,k=d.prototype.utils;k.addFlagFromForm=function(a){return function(b){var f=this,c=f.chart,d=
c.stockTools,e=k.getFieldType;b=k.attractToPoint(b,c);var g={type:"flags",onSeries:b.series.id,shape:a,data:[{x:b.x,y:b.y}],point:{events:{click:function(){var a=this,b=a.options;m(f,"showPopup",{point:a,formType:"annotation-toolbar",options:{langKey:"flags",type:"flags",title:[b.title,e(b.title)],name:[b.name,e(b.name)]},onSubmit:function(b){"remove"===b.actionType?a.remove():a.update(f.fieldsToOptions(b.fields,{}))}})}}}};d&&d.guiEnabled||c.addSeries(g);m(f,"showPopup",{formType:"flag",options:{langKey:"flags",
type:"flags",title:["A",e("A")],name:["Flag A",e("Flag A")]},onSubmit:function(a){f.fieldsToOptions(a.fields,g.data[0]);c.addSeries(g)}})}};k.manageIndicators=function(a){var b=this.chart,c={linkedTo:a.linkedTo,type:a.type},d=["ad","cmf","mfi","vbp","vwap"],e="ad atr cci cmf macd mfi roc rsi ao aroon aroonoscillator trix apo dpo ppo natr williamsr stochastic slowstochastic linearRegression linearRegressionSlope linearRegressionIntercept linearRegressionAngle".split(" ");if("edit"===a.actionType)this.fieldsToOptions(a.fields,
c),(a=b.get(a.seriesId))&&a.update(c,!1);else if("remove"===a.actionType){if(a=b.get(a.seriesId)){var g=a.yAxis;a.linkedSeries&&a.linkedSeries.forEach(function(a){a.remove(!1)});a.remove(!1);0<=e.indexOf(a.type)&&(g.remove(!1),this.resizeYAxes())}}else c.id=t(),this.fieldsToOptions(a.fields,c),0<=e.indexOf(a.type)?(g=b.addAxis({id:t(),offset:0,opposite:!0,title:{text:""},tickPixelInterval:40,showLastLabel:!1,labels:{align:"left",y:-2}},!1,!1),c.yAxis=g.options.id,this.resizeYAxes()):c.yAxis=b.get(a.linkedTo).options.yAxis,
0<=d.indexOf(a.type)&&(c.params.volumeSeriesID=b.series.filter(function(a){return"column"===a.options.type})[0].options.id),b.addSeries(c,!1);m(this,"deselectButton",{button:this.selectedButtonElement});b.redraw()};k.updateHeight=function(a,b){b.update({typeOptions:{height:this.chart.pointer.getCoordinates(a).yAxis[0].value-b.options.typeOptions.points[1].y}})};k.attractToPoint=function(a,b){a=b.pointer.getCoordinates(a);var f=a.xAxis[0].value;a=a.yAxis[0].value;var c=Number.MAX_VALUE,d;b.series.forEach(function(a){a.points.forEach(function(a){a&&
c>Math.abs(a.x-f)&&(c=Math.abs(a.x-f),d=a)})});return{x:d.x,y:d.y,below:a<d.y,series:d.series,xAxis:d.series.xAxis.index||0,yAxis:d.series.yAxis.index||0}};k.isNotNavigatorYAxis=function(a){return"highcharts-navigator-yaxis"!==a.userOptions.className};k.updateNthPoint=function(a){return function(b,c){var f=c.options.typeOptions;b=this.chart.pointer.getCoordinates(b);var d=b.xAxis[0].value,e=b.yAxis[0].value;f.points.forEach(function(b,f){f>=a&&(b.x=d,b.y=e)});c.update({typeOptions:{points:f.points}})}};
c(d.prototype,{getYAxisPositions:function(a,b,c){function f(a){return q(a)&&!r(a)&&a.match("%")}var d=0;a=a.map(function(a){var e=f(a.options.height)?parseFloat(a.options.height)/100:a.height/b;a=f(a.options.top)?parseFloat(a.options.top)/100:h(a.top-a.chart.plotTop)/b;r(e)||(e=c/100);d=h(d+e);return{height:100*e,top:100*a}});a.allAxesHeight=d;return a},getYAxisResizers:function(a){var b=[];a.forEach(function(f,c){f=a[c+1];b[c]=f?{enabled:!0,controlledAxis:{next:[g(f.options.id,f.options.index)]}}:
{enabled:!1}});return b},resizeYAxes:function(a){a=a||20;var b=this.chart,c=b.yAxis.filter(k.isNotNavigatorYAxis),d=c.length;b=this.getYAxisPositions(c,b.plotHeight,a);var e=this.getYAxisResizers(c),g=b.allAxesHeight,p=a;1<g?(6>d?(b[0].height=h(b[0].height-p),b=this.recalculateYAxisPositions(b,p)):(a=100/d,b=this.recalculateYAxisPositions(b,a/(d-1),!0,-1)),b[d-1]={top:h(100-a),height:a}):(p=100*h(1-g),5>d?(b[0].height=h(b[0].height+p),b=this.recalculateYAxisPositions(b,p)):b=this.recalculateYAxisPositions(b,
p/d,!0,1));b.forEach(function(a,b){c[b].update({height:a.height+"%",top:a.top+"%",resize:e[b]},!1)})},recalculateYAxisPositions:function(a,b,c,d){a.forEach(function(f,e){e=a[e-1];f.top=e?h(e.height+e.top):0;c&&(f.height=h(f.height+d*b))});return a}});l={segment:{className:"highcharts-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"segment",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,
y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.segment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},arrowSegment:{className:"highcharts-arrow-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowSegment",type:"crookedLine",typeOptions:{line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowSegment.annotationsOptions);
return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},ray:{className:"highcharts-ray",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"ray",type:"crookedLine",typeOptions:{type:"ray",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.ray.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},arrowRay:{className:"highcharts-arrow-ray",
start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowRay",type:"infinityLine",typeOptions:{type:"ray",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowRay.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},infinityLine:{className:"highcharts-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);
var c=this.chart.options.navigation;a=b({langKey:"infinityLine",type:"infinityLine",typeOptions:{type:"line",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.infinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},arrowInfinityLine:{className:"highcharts-arrow-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowInfinityLine",
type:"infinityLine",typeOptions:{type:"line",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowInfinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1)]},horizontalLine:{className:"highcharts-horizontal-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"horizontalLine",type:"infinityLine",draggable:"y",
typeOptions:{type:"horizontalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.horizontalLine.annotationsOptions);this.chart.addAnnotation(a)}},verticalLine:{className:"highcharts-vertical-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"verticalLine",type:"infinityLine",draggable:"x",typeOptions:{type:"verticalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.verticalLine.annotationsOptions);
this.chart.addAnnotation(a)}},crooked3:{className:"highcharts-crooked3",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"crooked3",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.crooked3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateNthPoint(2)]},crooked5:{className:"highcharts-crooked5",
start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"crookedLine",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.crooked5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateNthPoint(2),
k.updateNthPoint(3),k.updateNthPoint(4)]},elliott3:{className:"highcharts-elliott3",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"elliott3",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.elliott3.annotationsOptions);
return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateNthPoint(2),k.updateNthPoint(3)]},elliott5:{className:"highcharts-elliott5",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"elliott5",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},
{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.elliott5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateNthPoint(2),k.updateNthPoint(3),k.updateNthPoint(4),k.updateNthPoint(5)]},measureX:{className:"highcharts-measure-x",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"measure",type:"measure",typeOptions:{selectType:"x",point:{x:a.xAxis[0].value,
y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{enabled:!1,strokeWidth:0,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureX.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateRectSize]},measureY:{className:"highcharts-measure-y",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"measure",
type:"measure",typeOptions:{selectType:"y",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{enabled:!1,strokeWidth:0,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateRectSize]},measureXY:{className:"highcharts-measure-xy",start:function(a){a=this.chart.pointer.getCoordinates(a);
var c=this.chart.options.navigation;a=b({langKey:"measure",type:"measure",typeOptions:{selectType:"xy",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},background:{width:0,height:0,strokeWidth:10},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureXY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateRectSize]},fibonacci:{className:"highcharts-fibonacci",
start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"fibonacci",type:"fibonacci",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.fibonacci.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateHeight]},parallelChannel:{className:"highcharts-parallel-channel",start:function(a){a=this.chart.pointer.getCoordinates(a);
var c=this.chart.options.navigation;a=b({langKey:"parallelChannel",type:"tunnel",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.parallelChannel.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateHeight]},pitchfork:{className:"highcharts-pitchfork",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"pitchfork",type:"pitchfork",
typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value,controlPoint:{style:{fill:"red"}}},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}],innerBackground:{fill:"rgba(100, 170, 255, 0.8)"}},shapeOptions:{strokeWidth:2}},c.annotationsOptions,c.bindings.pitchfork.annotationsOptions);return this.chart.addAnnotation(a)},steps:[k.updateNthPoint(1),k.updateNthPoint(2)]},verticalCounter:{className:"highcharts-vertical-counter",start:function(a){a=k.attractToPoint(a,this.chart);
var c=this.chart.options.navigation,d=q(this.verticalCounter)?this.verticalCounter:0;a=b({langKey:"verticalCounter",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,text:d.toString()}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalCounter.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalLabel:{className:"highcharts-vertical-label",
start:function(a){a=k.attractToPoint(a,this.chart);var c=this.chart.options.navigation;a=b({langKey:"verticalLabel",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalLabel.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalArrow:{className:"highcharts-vertical-arrow",
start:function(a){a=k.attractToPoint(a,this.chart);var c=this.chart.options.navigation;a=b({langKey:"verticalArrow",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,format:" "},connector:{fill:"none",stroke:a.below?"red":"green"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalArrow.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},flagCirclepin:{className:"highcharts-flag-circlepin",
start:k.addFlagFromForm("circlepin")},flagDiamondpin:{className:"highcharts-flag-diamondpin",start:k.addFlagFromForm("flag")},flagSquarepin:{className:"highcharts-flag-squarepin",start:k.addFlagFromForm("squarepin")},flagSimplepin:{className:"highcharts-flag-simplepin",start:k.addFlagFromForm("nopin")},zoomX:{className:"highcharts-zoom-x",init:function(a){this.chart.update({chart:{zoomType:"x"}});m(this,"deselectButton",{button:a})}},zoomY:{className:"highcharts-zoom-y",init:function(a){this.chart.update({chart:{zoomType:"y"}});
m(this,"deselectButton",{button:a})}},zoomXY:{className:"highcharts-zoom-xy",init:function(a){this.chart.update({chart:{zoomType:"xy"}});m(this,"deselectButton",{button:a})}},seriesTypeLine:{className:"highcharts-series-type-line",init:function(a){this.chart.series[0].update({type:"line",useOhlcData:!0});m(this,"deselectButton",{button:a})}},seriesTypeOhlc:{className:"highcharts-series-type-ohlc",init:function(a){this.chart.series[0].update({type:"ohlc"});m(this,"deselectButton",{button:a})}},seriesTypeCandlestick:{className:"highcharts-series-type-candlestick",
init:function(a){this.chart.series[0].update({type:"candlestick"});m(this,"deselectButton",{button:a})}},fullScreen:{className:"highcharts-full-screen",init:function(a){this.chart.fullscreen.toggle();m(this,"deselectButton",{button:a})}},currentPriceIndicator:{className:"highcharts-current-price-indicator",init:function(a){var b=this.chart,c=b.series[0],d=c.options,e=d.lastVisiblePrice&&d.lastVisiblePrice.enabled;d=d.lastPrice&&d.lastPrice.enabled;b=b.stockTools;var g=b.getIconsURL();b&&b.guiEnabled&&
(a.firstChild.style["background-image"]=d?'url("'+g+'current-price-show.svg")':'url("'+g+'current-price-hide.svg")');c.update({lastPrice:{enabled:!d,color:"red"},lastVisiblePrice:{enabled:!e,label:{enabled:!0}}});m(this,"deselectButton",{button:a})}},indicators:{className:"highcharts-indicators",init:function(){var a=this;m(a,"showPopup",{formType:"indicators",options:{},onSubmit:function(b){a.utils.manageIndicators.call(a,b)}})}},toggleAnnotations:{className:"highcharts-toggle-annotations",init:function(a){var b=
this.chart,c=b.stockTools,d=c.getIconsURL();this.toggledAnnotations=!this.toggledAnnotations;(b.annotations||[]).forEach(function(a){a.setVisibility(!this.toggledAnnotations)},this);c&&c.guiEnabled&&(a.firstChild.style["background-image"]=this.toggledAnnotations?'url("'+d+'annotations-hidden.svg")':'url("'+d+'annotations-visible.svg")');m(this,"deselectButton",{button:a})}},saveChart:{className:"highcharts-save-chart",init:function(a){var b=this.chart,c=[],d=[],g=[],h=[];b.annotations.forEach(function(a,
b){c[b]=a.userOptions});b.series.forEach(function(a){a.is("sma")?d.push(a.userOptions):"flags"===a.type&&g.push(a.userOptions)});b.yAxis.forEach(function(a){k.isNotNavigatorYAxis(a)&&h.push(a.options)});e.win.localStorage.setItem("highcharts-chart",JSON.stringify({annotations:c,indicators:d,flags:g,yAxes:h}));m(this,"deselectButton",{button:a})}}};e.setOptions({navigation:{bindings:l}});d.prototype.utils=b(k,d.prototype.utils)});r(e,"modules/stock-tools-gui.js",[e["parts/Globals.js"],e["parts/Utilities.js"],
e["annotations/navigationBindings.js"]],function(e,d,l){var h=d.addEvent,q=d.createElement,c=d.css,m=d.extend,r=d.fireEvent,b=d.getStyle,g=d.isArray,t=d.merge,k=d.pick;e.setOptions({lang:{stockTools:{gui:{simpleShapes:"Simple shapes",lines:"Lines",crookedLines:"Crooked lines",measure:"Measure",advanced:"Advanced",toggleAnnotations:"Toggle annotations",verticalLabels:"Vertical labels",flags:"Flags",zoomChange:"Zoom change",typeChange:"Type change",saveChart:"Save chart",indicators:"Indicators",currentPriceIndicator:"Current Price Indicators",
zoomX:"Zoom X",zoomY:"Zoom Y",zoomXY:"Zooom XY",fullScreen:"Fullscreen",typeOHLC:"OHLC",typeLine:"Line",typeCandlestick:"Candlestick",circle:"Circle",label:"Label",rectangle:"Rectangle",flagCirclepin:"Flag circle",flagDiamondpin:"Flag diamond",flagSquarepin:"Flag square",flagSimplepin:"Flag simple",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",arrowLine:"Arrow line",horizontalLine:"Horizontal line",
verticalLine:"Vertical line",infinityLine:"Infinity line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel"}},navigation:{popup:{circle:"Circle",rectangle:"Rectangle",label:"Label",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",
arrowLine:"Arrow line",horizontalLine:"Horizontal line",verticalLine:"Vertical line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel",infinityLine:"Infinity line",measure:"Measure",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",flags:"Flags",addButton:"add",
saveButton:"save",editButton:"edit",removeButton:"remove",series:"Series",volume:"Volume",connector:"Connector",innerBackground:"Inner background",outerBackground:"Outer background",crosshairX:"Crosshair X",crosshairY:"Crosshair Y",tunnel:"Tunnel",background:"Background"}}},stockTools:{gui:{enabled:!0,className:"highcharts-bindings-wrapper",toolbarClassName:"stocktools-toolbar",buttons:"indicators separator simpleShapes lines crookedLines measure advanced toggleAnnotations separator verticalLabels flags separator zoomChange fullScreen typeChange separator currentPriceIndicator saveChart".split(" "),
definitions:{separator:{symbol:"separator.svg"},simpleShapes:{items:["label","circle","rectangle"],circle:{symbol:"circle.svg"},rectangle:{symbol:"rectangle.svg"},label:{symbol:"label.svg"}},flags:{items:["flagCirclepin","flagDiamondpin","flagSquarepin","flagSimplepin"],flagSimplepin:{symbol:"flag-basic.svg"},flagDiamondpin:{symbol:"flag-diamond.svg"},flagSquarepin:{symbol:"flag-trapeze.svg"},flagCirclepin:{symbol:"flag-elipse.svg"}},lines:{items:"segment arrowSegment ray arrowRay line arrowLine horizontalLine verticalLine".split(" "),
segment:{symbol:"segment.svg"},arrowSegment:{symbol:"arrow-segment.svg"},ray:{symbol:"ray.svg"},arrowRay:{symbol:"arrow-ray.svg"},line:{symbol:"line.svg"},arrowLine:{symbol:"arrow-line.svg"},verticalLine:{symbol:"vertical-line.svg"},horizontalLine:{symbol:"horizontal-line.svg"}},crookedLines:{items:["elliott3","elliott5","crooked3","crooked5"],crooked3:{symbol:"crooked-3.svg"},crooked5:{symbol:"crooked-5.svg"},elliott3:{symbol:"elliott-3.svg"},elliott5:{symbol:"elliott-5.svg"}},verticalLabels:{items:["verticalCounter",
"verticalLabel","verticalArrow"],verticalCounter:{symbol:"vertical-counter.svg"},verticalLabel:{symbol:"vertical-label.svg"},verticalArrow:{symbol:"vertical-arrow.svg"}},advanced:{items:["fibonacci","pitchfork","parallelChannel"],pitchfork:{symbol:"pitchfork.svg"},fibonacci:{symbol:"fibonacci.svg"},parallelChannel:{symbol:"parallel-channel.svg"}},measure:{items:["measureXY","measureX","measureY"],measureX:{symbol:"measure-x.svg"},measureY:{symbol:"measure-y.svg"},measureXY:{symbol:"measure-xy.svg"}},
toggleAnnotations:{symbol:"annotations-visible.svg"},currentPriceIndicator:{symbol:"current-price-show.svg"},indicators:{symbol:"indicators.svg"},zoomChange:{items:["zoomX","zoomY","zoomXY"],zoomX:{symbol:"zoom-x.svg"},zoomY:{symbol:"zoom-y.svg"},zoomXY:{symbol:"zoom-xy.svg"}},typeChange:{items:["typeOHLC","typeLine","typeCandlestick"],typeOHLC:{symbol:"series-ohlc.svg"},typeLine:{symbol:"series-line.svg"},typeCandlestick:{symbol:"series-candlestick.svg"}},fullScreen:{symbol:"fullscreen.svg"},saveChart:{symbol:"save-chart.svg"}}}}});
h(e.Chart,"afterGetContainer",function(){this.setStockTools()});h(e.Chart,"getMargins",function(){var a=this.stockTools&&this.stockTools.listWrapper;(a=a&&(a.startWidth+b(a,"padding-left")+b(a,"padding-right")||a.offsetWidth))&&a<this.plotWidth&&(this.plotLeft+=a)});h(e.Chart,"destroy",function(){this.stockTools&&this.stockTools.destroy()});h(e.Chart,"redraw",function(){this.stockTools&&this.stockTools.guiEnabled&&this.stockTools.redraw()});d=function(){function a(a,b,c){this.wrapper=this.toolbar=
this.submenu=this.showhideBtn=this.listWrapper=this.arrowWrapper=this.arrowUp=this.arrowDown=void 0;this.chart=c;this.options=a;this.lang=b;this.iconsURL=this.getIconsURL();this.guiEnabled=a.enabled;this.visible=k(a.visible,!0);this.placed=k(a.placed,!1);this.eventsToUnbind=[];this.guiEnabled&&(this.createHTML(),this.init(),this.showHideNavigatorion());r(this,"afterInit")}a.prototype.init=function(){var a=this,b=this.lang,c=this.options,d=this.toolbar,e=a.addSubmenu,k=c.definitions,l=d.childNodes,
m;c.buttons.forEach(function(c){m=a.addButton(d,k,c,b);a.eventsToUnbind.push(h(m.buttonWrapper,"click",function(){a.eraseActiveButtons(l,m.buttonWrapper)}));g(k[c].items)&&e.call(a,m,k[c])})};a.prototype.addSubmenu=function(a,d){var e=this,f=a.submenuArrow,g=a.buttonWrapper,k=b(g,"width"),n=this.wrapper,l=this.listWrapper,m=this.toolbar.childNodes,r=0,t;this.submenu=t=q("ul",{className:"highcharts-submenu-wrapper"},null,g);this.addSubmenuItems(g,d);e.eventsToUnbind.push(h(f,"click",function(a){a.stopPropagation();
e.eraseActiveButtons(m,g);0<=g.className.indexOf("highcharts-current")?(l.style.width=l.startWidth+"px",g.classList.remove("highcharts-current"),t.style.display="none"):(t.style.display="block",r=t.offsetHeight-g.offsetHeight-3,t.offsetHeight+g.offsetTop>n.offsetHeight&&g.offsetTop>r||(r=0),c(t,{top:-r+"px",left:k+3+"px"}),g.className+=" highcharts-current",l.startWidth=n.offsetWidth,l.style.width=l.startWidth+b(l,"padding-left")+t.offsetWidth+3+"px")}))};a.prototype.addSubmenuItems=function(a,b){var c=
this,d=this.submenu,e=this.lang,f=this.listWrapper,g;b.items.forEach(function(k){g=c.addButton(d,b,k,e);c.eventsToUnbind.push(h(g.mainButton,"click",function(){c.switchSymbol(this,a,!0);f.style.width=f.startWidth+"px";d.style.display="none"}))});var k=d.querySelectorAll("li > .highcharts-menu-item-btn")[0];c.switchSymbol(k,!1)};a.prototype.eraseActiveButtons=function(a,b,c){[].forEach.call(a,function(a){a!==b&&(a.classList.remove("highcharts-current"),a.classList.remove("highcharts-active"),c=a.querySelectorAll(".highcharts-submenu-wrapper"),
0<c.length&&(c[0].style.display="none"))})};a.prototype.addButton=function(b,c,d,e){void 0===e&&(e={});c=c[d];var f=c.items,g=c.className||"";d=q("li",{className:k(a.prototype.classMapping[d],"")+" "+g,title:e[d]||d},null,b);b=q("span",{className:"highcharts-menu-item-btn"},null,d);if(f&&f.length){var h=q("span",{className:"highcharts-submenu-item-arrow highcharts-arrow-right"},null,d);h.style["background-image"]="url("+this.iconsURL+"arrow-bottom.svg)"}else b.style["background-image"]="url("+this.iconsURL+
c.symbol+")";return{buttonWrapper:d,mainButton:b,submenuArrow:h}};a.prototype.addNavigation=function(){var a=this.wrapper;this.arrowWrapper=q("div",{className:"highcharts-arrow-wrapper"});this.arrowUp=q("div",{className:"highcharts-arrow-up"},null,this.arrowWrapper);this.arrowUp.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";this.arrowDown=q("div",{className:"highcharts-arrow-down"},null,this.arrowWrapper);this.arrowDown.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";
a.insertBefore(this.arrowWrapper,a.childNodes[0]);this.scrollButtons()};a.prototype.scrollButtons=function(){var a=0,b=this.wrapper,c=this.toolbar,d=.1*b.offsetHeight;this.eventsToUnbind.push(h(this.arrowUp,"click",function(){0<a&&(a-=d,c.style["margin-top"]=-a+"px")}));this.eventsToUnbind.push(h(this.arrowDown,"click",function(){b.offsetHeight+a<=c.offsetHeight+d&&(a+=d,c.style["margin-top"]=-a+"px")}))};a.prototype.createHTML=function(){var a=this.chart,b=this.options,c=a.container;a=a.options.navigation;
this.wrapper=a=q("div",{className:"highcharts-stocktools-wrapper "+b.className+" "+(a&&a.bindingsClassName)});c.parentNode.insertBefore(a,c);this.toolbar=c=q("ul",{className:"highcharts-stocktools-toolbar "+b.toolbarClassName});this.listWrapper=b=q("div",{className:"highcharts-menu-wrapper"});a.insertBefore(b,a.childNodes[0]);b.insertBefore(c,b.childNodes[0]);this.showHideToolbar();this.addNavigation()};a.prototype.showHideNavigatorion=function(){this.visible&&this.toolbar.offsetHeight>this.wrapper.offsetHeight-
50?this.arrowWrapper.style.display="block":(this.toolbar.style.marginTop="0px",this.arrowWrapper.style.display="none")};a.prototype.showHideToolbar=function(){var a=this.chart,c=this.wrapper,d=this.listWrapper,e=this.submenu,g=this.visible,k;this.showhideBtn=k=q("div",{className:"highcharts-toggle-toolbar highcharts-arrow-left"},null,c);k.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";g?(c.style.height="100%",k.style.top=b(d,"padding-top")+"px",k.style.left=c.offsetWidth+b(d,"padding-left")+
"px"):(e&&(e.style.display="none"),k.style.left="0px",this.visible=g=!1,d.classList.add("highcharts-hide"),k.classList.toggle("highcharts-arrow-right"),c.style.height=k.offsetHeight+"px");this.eventsToUnbind.push(h(k,"click",function(){a.update({stockTools:{gui:{visible:!g,placed:!0}}})}))};a.prototype.switchSymbol=function(a,b){var c=a.parentNode,d=c.classList.value;c=c.parentNode.parentNode;c.className="";d&&c.classList.add(d.trim());c.querySelectorAll(".highcharts-menu-item-btn")[0].style["background-image"]=
a.style["background-image"];b&&this.selectButton(c)};a.prototype.selectButton=function(a){0<=a.className.indexOf("highcharts-active")?a.classList.remove("highcharts-active"):a.classList.add("highcharts-active")};a.prototype.unselectAllButtons=function(a){var b=a.parentNode.querySelectorAll(".highcharts-active");[].forEach.call(b,function(b){b!==a&&b.classList.remove("highcharts-active")})};a.prototype.update=function(a){t(!0,this.chart.options.stockTools,a);this.destroy();this.chart.setStockTools(a);
this.chart.navigationBindings&&this.chart.navigationBindings.update()};a.prototype.destroy=function(){var a=this.wrapper,b=a&&a.parentNode;this.eventsToUnbind.forEach(function(a){a()});b&&b.removeChild(a);this.chart.isDirtyBox=!0;this.chart.redraw()};a.prototype.redraw=function(){this.showHideNavigatorion()};a.prototype.getIconsURL=function(){return this.chart.options.navigation.iconsURL||this.options.iconsURL||"https://code.highcharts.com/8.1.0/gfx/stock-icons/"};return a}();d.prototype.classMapping=
{circle:"highcharts-circle-annotation",rectangle:"highcharts-rectangle-annotation",label:"highcharts-label-annotation",segment:"highcharts-segment",arrowSegment:"highcharts-arrow-segment",ray:"highcharts-ray",arrowRay:"highcharts-arrow-ray",line:"highcharts-infinity-line",arrowLine:"highcharts-arrow-infinity-line",verticalLine:"highcharts-vertical-line",horizontalLine:"highcharts-horizontal-line",crooked3:"highcharts-crooked3",crooked5:"highcharts-crooked5",elliott3:"highcharts-elliott3",elliott5:"highcharts-elliott5",
pitchfork:"highcharts-pitchfork",fibonacci:"highcharts-fibonacci",parallelChannel:"highcharts-parallel-channel",measureX:"highcharts-measure-x",measureY:"highcharts-measure-y",measureXY:"highcharts-measure-xy",verticalCounter:"highcharts-vertical-counter",verticalLabel:"highcharts-vertical-label",verticalArrow:"highcharts-vertical-arrow",currentPriceIndicator:"highcharts-current-price-indicator",indicators:"highcharts-indicators",flagCirclepin:"highcharts-flag-circlepin",flagDiamondpin:"highcharts-flag-diamondpin",
flagSquarepin:"highcharts-flag-squarepin",flagSimplepin:"highcharts-flag-simplepin",zoomX:"highcharts-zoom-x",zoomY:"highcharts-zoom-y",zoomXY:"highcharts-zoom-xy",typeLine:"highcharts-series-type-line",typeOHLC:"highcharts-series-type-ohlc",typeCandlestick:"highcharts-series-type-candlestick",fullScreen:"highcharts-full-screen",toggleAnnotations:"highcharts-toggle-annotations",saveChart:"highcharts-save-chart",separator:"highcharts-separator"};m(e.Chart.prototype,{setStockTools:function(a){var b=
this.options,c=b.lang;a=t(b.stockTools&&b.stockTools.gui,a&&a.gui);this.stockTools=new e.Toolbar(a,c.stockTools&&c.stockTools.gui,this);this.stockTools.guiEnabled&&(this.isDirtyBox=!0)}});h(l,"selectButton",function(a){var b=a.button,c=this.chart.stockTools;c&&c.guiEnabled&&(c.unselectAllButtons(a.button),0<=b.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(b=b.parentNode.parentNode),c.selectButton(b))});h(l,"deselectButton",function(a){a=a.button;var b=this.chart.stockTools;b&&b.guiEnabled&&
(0<=a.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(a=a.parentNode.parentNode),b.selectButton(a))});e.Toolbar=d;return e.Toolbar});r(e,"masters/modules/stock-tools.src.js",[],function(){})});
//# sourceMappingURL=stock-tools.js.map