/*
 Highcharts JS v8.1.0 (2020-05-12)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(B){c(B);c.Highcharts=B;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function B(k,a,p,b){k.hasOwnProperty(a)||(k[a]=b.apply(null,p))}c=c?c._modules:{};B(c,"parts-more/Pane.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(k,a){function p(f,b,a){return Math.sqrt(Math.pow(f-
a[0],2)+Math.pow(b-a[1],2))<a[2]/2}var b=a.addEvent,g=a.extend,u=a.merge,v=a.pick,c=a.splat,C=k.CenteredSeriesMixin;k.Chart.prototype.collectionsWithUpdate.push("pane");a=function(){function f(f,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,
"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(f,a)}f.prototype.init=function(f,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(f)};f.prototype.setOptions=function(f){this.options=u(this.defaultOptions,this.chart.angular?{background:{}}:void 0,f)};f.prototype.render=function(){var f=this.options,a=this.options.background,b=this.chart.renderer;this.group||(this.group=b.g("pane-group").attr({zIndex:f.zIndex||0}).add());
this.updateCenter();if(a)for(a=c(a),f=Math.max(a.length,this.background.length||0),b=0;b<f;b++)a[b]&&this.axis?this.renderBackground(u(this.defaultBackgroundOptions,a[b]),b):this.background[b]&&(this.background[b]=this.background[b].destroy(),this.background.splice(b,1))};f.prototype.renderBackground=function(f,a){var b="animate",r={"class":"highcharts-pane "+(f.className||"")};this.chart.styledMode||g(r,{fill:f.backgroundColor,stroke:f.borderColor,"stroke-width":f.borderWidth});this.background[a]||
(this.background[a]=this.chart.renderer.path().add(this.group),b="attr");this.background[a][b]({d:this.axis.getPlotBandPath(f.from,f.to,f)}).attr(r)};f.prototype.updateCenter=function(f){this.center=(f||this.axis||{}).center=C.getCenter.call(this)};f.prototype.update=function(f,a){u(!0,this.options,f);u(!0,this.chart.options.pane,f);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(f){f.pane===this&&(f.pane=null,f.update({},a))},this)};return f}();k.Chart.prototype.getHoverPane=
function(f){var a=this,b;f&&a.pane.forEach(function(g){var h=f.chartX-a.plotLeft,w=f.chartY-a.plotTop;p(a.inverted?w:h,a.inverted?h:w,g.center)&&(b=g)});return b};b(k.Chart,"afterIsInsidePlot",function(f){this.polar&&(f.isInsidePlot=this.pane.some(function(a){return p(f.x,f.y,a.center)}))});b(k.Pointer,"beforeGetHoverData",function(f){var a=this.chart;a.polar&&(a.hoverPane=a.getHoverPane(f),f.filter=function(b){return b.visible&&!(!f.shared&&b.directTouch)&&v(b.options.enableMouseTracking,!0)&&(!a.hoverPane||
b.xAxis.pane===a.hoverPane)})});b(k.Pointer,"afterGetHoverData",function(f){var a=this.chart;f.hoverPoint&&f.hoverPoint.plotX&&f.hoverPoint.plotY&&a.hoverPane&&!p(f.hoverPoint.plotX,f.hoverPoint.plotY,a.hoverPane.center)&&(f.hoverPoint=void 0)});k.Pane=a;return k.Pane});B(c,"parts-more/HiddenAxis.js",[],function(){return function(){function k(){}k.init=function(a){a.getOffset=function(){};a.redraw=function(){this.isDirty=!1};a.render=function(){this.isDirty=!1};a.createLabelCollector=function(){return function(){}};
a.setScale=function(){};a.setCategories=function(){};a.setTitle=function(){};a.isHidden=!0};return k}()});B(c,"parts-more/RadialAxis.js",[c["parts/Axis.js"],c["parts/Tick.js"],c["parts-more/HiddenAxis.js"],c["parts/Utilities.js"]],function(k,a,p,b){var g=b.addEvent,u=b.correctFloat,v=b.defined,c=b.extend,C=b.fireEvent,f=b.merge,r=b.pick,w=b.pInt,z=b.relativeLength,h=b.wrap;b=function(){function a(){}a.init=function(a){var b=k.prototype;a.setOptions=function(l){l=this.options=f(a.constructor.defaultOptions,
this.defaultPolarOptions,l);l.plotBands||(l.plotBands=[]);C(this,"afterSetOptions")};a.getOffset=function(){b.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(l,e,d){l=this.pane.center;var m=this.chart,x=r(e,l[2]/2-this.offset);"undefined"===typeof d&&(d=this.horiz?0:this.center&&-this.center[3]/2);d&&(x+=d);this.isCircular||"undefined"!==typeof e?(e=this.chart.renderer.symbols.arc(this.left+l[0],this.top+l[1],x,x,{start:this.startAngleRad,end:this.endAngleRad,open:!0,
innerR:0}),e.xBounds=[this.left+l[0]],e.yBounds=[this.top+l[1]-x]):(e=this.postTranslate(this.angleRad,x),e=[["M",this.center[0]+m.plotLeft,this.center[1]+m.plotTop],["L",e.x,e.y]]);return e};a.setAxisTranslation=function(){b.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=
function(){this.autoConnect=this.isCircular&&"undefined"===typeof r(this.userMax,this.options.max)&&u(this.endAngleRad-this.startAngleRad)===u(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){b.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var l=this.center=c([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;
else{var e=this.postTranslate(this.angleRad,l[3]/2);l[0]=e.x-this.chart.plotLeft;l[1]=e.y-this.chart.plotTop}this.len=this.width=this.height=(l[2]-l[3])*r(this.sector,1)/2}};a.getPosition=function(l,e){l=this.translate(l);return this.postTranslate(this.isCircular?l:this.angleRad,r(this.isCircular?e:0>l?0:l,this.center[2]/2)-this.offset)};a.postTranslate=function(l,e){var d=this.chart,m=this.center;l=this.startAngleRad+l;return{x:d.plotLeft+m[0]+Math.cos(l)*e,y:d.plotTop+m[1]+Math.sin(l)*e}};a.getPlotBandPath=
function(l,e,d){var m=this.center,x=this.startAngleRad,t=m[2]/2,n=[r(d.outerRadius,"100%"),d.innerRadius,r(d.thickness,10)],f=Math.min(this.offset,0),a=/%$/;var b=this.isCircular;if("polygon"===this.options.gridLineInterpolation)n=this.getPlotLinePath({value:l}).concat(this.getPlotLinePath({value:e,reverse:!0}));else{l=Math.max(l,this.min);e=Math.min(e,this.max);b||(n[0]=this.translate(l),n[1]=this.translate(e));n=n.map(function(d){a.test(d)&&(d=w(d,10)*t/100);return d});if("circle"!==d.shape&&b)l=
x+this.translate(l),e=x+this.translate(e);else{l=-Math.PI/2;e=1.5*Math.PI;var g=!0}n[0]-=f;n[2]-=f;n=this.chart.renderer.symbols.arc(this.left+m[0],this.top+m[1],n[0],n[0],{start:Math.min(l,e),end:Math.max(l,e),innerR:r(n[1],n[0]-n[2]),open:g});b&&(b=(e+l)/2,f=this.left+m[0]+m[2]/2*Math.cos(b),n.xBounds=b>-Math.PI/2&&b<Math.PI/2?[f,this.chart.plotWidth]:[0,f],n.yBounds=[this.top+m[1]+m[2]/2*Math.sin(b)],n.yBounds[0]+=b>-Math.PI&&0>b||b>Math.PI?-10:10)}return n};a.getCrosshairPosition=function(l,e,
d){var m=l.value,x=this.pane.center;if(this.isCircular){if(v(m))l.point&&(t=l.point.shapeArgs||{},t.start&&(m=this.chart.inverted?this.translate(l.point.rectPlotY,!0):l.point.x));else{var t=l.chartX||0;var n=l.chartY||0;m=this.translate(Math.atan2(n-d,t-e)-this.startAngleRad,!0)}l=this.getPosition(m);t=l.x;n=l.y}else v(m)||(t=l.chartX,n=l.chartY),v(t)&&v(n)&&(d=x[1]+this.chart.plotTop,m=this.translate(Math.min(Math.sqrt(Math.pow(t-e,2)+Math.pow(n-d,2)),x[2]/2)-x[3]/2,!0));return[m,t||0,n||0]};a.getPlotLinePath=
function(l){var e=this,d=e.pane.center,m=e.chart,x=m.inverted,t=l.value,n=l.reverse,f=e.getPosition(t),a=e.pane.options.background?e.pane.options.background[0]||e.pane.options.background:{},b=a.innerRadius||"0%",g=a.outerRadius||"100%";a=d[0]+m.plotLeft;var h=d[1]+m.plotTop,q=f.x,w=f.y,p=e.height;f=d[3]/2;var r;l.isCrosshair&&(w=this.getCrosshairPosition(l,a,h),t=w[0],q=w[1],w=w[2]);if(e.isCircular)t=Math.sqrt(Math.pow(q-a,2)+Math.pow(w-h,2)),n="string"===typeof b?z(b,1):b/t,m="string"===typeof g?
z(g,1):g/t,d&&f&&(t=f/t,n<t&&(n=t),m<t&&(m=t)),d=[["M",a+n*(q-a),h-n*(h-w)],["L",q-(1-m)*(q-a),w+(1-m)*(h-w)]];else if((t=e.translate(t))&&(0>t||t>p)&&(t=0),"circle"===e.options.gridLineInterpolation)d=e.getLinePath(0,t,f);else if(d=[],m[x?"yAxis":"xAxis"].forEach(function(d){d.pane===e.pane&&(r=d)}),r)for(a=r.tickPositions,r.autoConnect&&(a=a.concat([a[0]])),n&&(a=a.slice().reverse()),t&&(t+=f),q=0;q<a.length;q++)h=r.getPosition(a[q],t),d.push(q?["L",h.x,h.y]:["M",h.x,h.y]);return d};a.getTitlePosition=
function(){var l=this.center,e=this.chart,d=this.options.title;return{x:e.plotLeft+l[0]+(d.x||0),y:e.plotTop+l[1]-{high:.5,middle:.25,low:0}[d.align]*l[2]+(d.y||0)}};a.createLabelCollector=function(){var l=this;return function(){if(l.isRadial&&l.tickPositions&&!0!==l.options.labels.allowOverlap)return l.tickPositions.map(function(e){return l.ticks[e]&&l.ticks[e].label}).filter(function(e){return!!e})}}};a.compose=function(b,q){g(b,"init",function(l){var e=this.chart,d=e.inverted,m=e.angular,x=e.polar,
t=this.isXAxis,n=this.coll,D=m&&t,h,g=e.options;l=l.userOptions.pane||0;l=this.pane=e.pane&&e.pane[l];if("colorAxis"===n)this.isRadial=!1;else{if(m){if(D?p.init(this):a.init(this),h=!t)this.defaultPolarOptions=a.defaultRadialGaugeOptions}else x&&(a.init(this),this.defaultPolarOptions=(h=this.horiz)?a.defaultCircularOptions:f("xAxis"===n?b.defaultOptions:b.defaultYAxisOptions,a.defaultRadialOptions),d&&"yAxis"===n&&(this.defaultPolarOptions.stackLabels=b.defaultYAxisOptions.stackLabels));m||x?(this.isRadial=
!0,g.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&e.labelCollectors.push(this.labelCollector)):this.isRadial=!1;l&&h&&(l.axis=this);this.isCircular=h}});g(b,"afterInit",function(){var l=this.chart,e=this.options,d=this.pane,m=d&&d.options;l.angular&&this.isXAxis||!d||!l.angular&&!l.polar||(this.angleRad=(e.angle||0)*Math.PI/180,this.startAngleRad=(m.startAngle-90)*Math.PI/180,this.endAngleRad=(r(m.endAngle,m.startAngle+360)-90)*Math.PI/
180,this.offset=e.offset||0)});g(b,"autoLabelAlign",function(l){this.isRadial&&(l.align=void 0,l.preventDefault())});g(b,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var l=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=l&&this.chart.labelCollectors.splice(l,1)}});g(b,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});g(q,"afterGetPosition",function(l){this.axis.getPosition&&c(l.pos,this.axis.getPosition(this.pos))});
g(q,"afterGetLabelPosition",function(l){var e=this.axis,d=this.label;if(d){var m=d.getBBox(),f=e.options.labels,t=f.y,n=20,a=f.align,b=(e.translate(this.pos)+e.startAngleRad+Math.PI/2)/Math.PI*180%360,h=Math.round(b),g="end",q=0>h?h+360:h,w=q,p=0,u=0,y=null===f.y?.3*-m.height:0;if(e.isRadial){var v=e.getPosition(this.pos,e.center[2]/2+z(r(f.distance,-25),e.center[2]/2,-e.center[2]/2));"auto"===f.rotation?d.attr({rotation:b}):null===t&&(t=e.chart.renderer.fontMetrics(d.styles&&d.styles.fontSize).b-
m.height/2);null===a&&(e.isCircular?(m.width>e.len*e.tickInterval/(e.max-e.min)&&(n=0),a=b>n&&b<180-n?"left":b>180+n&&b<360-n?"right":"center"):a="center",d.attr({align:a}));if("auto"===a&&2===e.tickPositions.length&&e.isCircular){90<q&&180>q?q=180-q:270<q&&360>=q&&(q=540-q);180<w&&360>=w&&(w=360-w);if(e.pane.options.startAngle===h||e.pane.options.startAngle===h+360||e.pane.options.startAngle===h-360)g="start";a=-90<=h&&90>=h||-360<=h&&-270>=h||270<=h&&360>=h?"start"===g?"right":"left":"start"===
g?"left":"right";70<w&&110>w&&(a="center");15>q||180<=q&&195>q?p=.3*m.height:15<=q&&35>=q?p="start"===g?0:.75*m.height:195<=q&&215>=q?p="start"===g?.75*m.height:0:35<q&&90>=q?p="start"===g?.25*-m.height:m.height:215<q&&270>=q&&(p="start"===g?m.height:.25*-m.height);15>w?u="start"===g?.15*-m.height:.15*m.height:165<w&&180>=w&&(u="start"===g?.15*m.height:.15*-m.height);d.attr({align:a});d.translate(u,p+y)}l.pos.x=v.x+f.x;l.pos.y=v.y+t}}});h(q.prototype,"getMarkPath",function(l,e,d,m,f,t,n){var a=this.axis;
a.isRadial?(l=a.getPosition(this.pos,a.center[2]/2+m),e=["M",e,d,"L",l.x,l.y]):e=l.call(this,e,d,m,f,t,n);return e})};a.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};a.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,
title:{rotation:0},zIndex:2};a.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return a}();b.compose(k,a);return b});B(c,"parts-more/AreaRangeSeries.js",[c["parts/Globals.js"],c["parts/Point.js"],c["parts/Utilities.js"]],function(k,a,p){var b=p.defined,g=p.extend,u=p.isArray,v=p.isNumber,c=p.pick;p=p.seriesType;var C=k.seriesTypes,f=k.Series.prototype,r=a.prototype;p("arearange","area",{lineWidth:1,
threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(f){return[f.low,f.high]},highToXY:function(f){var a=this.chart,b=this.xAxis.postTranslate(f.rectPlotX,this.yAxis.len-f.plotHigh);f.plotHighX=b.x-a.plotLeft;f.plotHigh=b.y-a.plotTop;
f.plotLowX=f.plotX},translate:function(){var f=this,a=f.yAxis,b=!!f.modifyValue;C.area.prototype.translate.apply(f);f.points.forEach(function(h){var g=h.high,q=h.plotY;h.isNull?h.plotY=null:(h.plotLow=q,h.plotHigh=a.translate(b?f.modifyValue(g,h):g,0,1,0,1),b&&(h.yBottom=h.plotHigh))});this.chart.polar&&this.points.forEach(function(a){f.highToXY(a);a.tooltipPos=[(a.plotHighX+a.plotLowX)/2,(a.plotHigh+a.plotLow)/2]})},getGraphPath:function(f){var a=[],b=[],g,p=C.area.prototype.getGraphPath;var q=this.options;
var l=this.chart.polar&&!1!==q.connectEnds,e=q.connectNulls,d=q.step;f=f||this.points;for(g=f.length;g--;){var m=f[g];m.isNull||l||e||f[g+1]&&!f[g+1].isNull||b.push({plotX:m.plotX,plotY:m.plotY,doCurve:!1});var x={polarPlotY:m.polarPlotY,rectPlotX:m.rectPlotX,yBottom:m.yBottom,plotX:c(m.plotHighX,m.plotX),plotY:m.plotHigh,isNull:m.isNull};b.push(x);a.push(x);m.isNull||l||e||f[g-1]&&!f[g-1].isNull||b.push({plotX:m.plotX,plotY:m.plotY,doCurve:!1})}f=p.call(this,f);d&&(!0===d&&(d="left"),q.step={left:"right",
center:"center",right:"left"}[d]);a=p.call(this,a);b=p.call(this,b);q.step=d;q=[].concat(f,a);!this.chart.polar&&b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.graphPath=q;this.areaPath=f.concat(b);q.isArea=!0;q.xMap=f.xMap;this.areaPath.xMap=f.xMap;return q},drawDataLabels:function(){var a=this.points,b=a.length,h,p=[],r=this.options.dataLabels,q,l=this.chart.inverted;if(u(r))if(1<r.length){var e=r[0];var d=r[1]}else e=r[0],d={enabled:!1};else e=g({},r),e.x=r.xHigh,e.y=r.yHigh,d=g({},r),
d.x=r.xLow,d.y=r.yLow;if(e.enabled||this._hasPointLabels){for(h=b;h--;)if(q=a[h]){var m=e.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow;q.y=q.high;q._plotY=q.plotY;q.plotY=q.plotHigh;p[h]=q.dataLabel;q.dataLabel=q.dataLabelUpper;q.below=m;l?e.align||(e.align=m?"right":"left"):e.verticalAlign||(e.verticalAlign=m?"top":"bottom")}this.options.dataLabels=e;f.drawDataLabels&&f.drawDataLabels.apply(this,arguments);for(h=b;h--;)if(q=a[h])q.dataLabelUpper=q.dataLabel,q.dataLabel=p[h],delete q.dataLabels,
q.y=q.low,q.plotY=q._plotY}if(d.enabled||this._hasPointLabels){for(h=b;h--;)if(q=a[h])m=d.inside?q.plotHigh<q.plotLow:q.plotHigh>q.plotLow,q.below=!m,l?d.align||(d.align=m?"left":"right"):d.verticalAlign||(d.verticalAlign=m?"bottom":"top");this.options.dataLabels=d;f.drawDataLabels&&f.drawDataLabels.apply(this,arguments)}if(e.enabled)for(h=b;h--;)if(q=a[h])q.dataLabels=[q.dataLabelUpper,q.dataLabel].filter(function(d){return!!d});this.options.dataLabels=r},alignDataLabel:function(){C.column.prototype.alignDataLabel.apply(this,
arguments)},drawPoints:function(){var a=this.points.length,r;f.drawPoints.apply(this,arguments);for(r=0;r<a;){var h=this.points[r];h.origProps={plotY:h.plotY,plotX:h.plotX,isInside:h.isInside,negative:h.negative,zone:h.zone,y:h.y};h.lowerGraphic=h.graphic;h.graphic=h.upperGraphic;h.plotY=h.plotHigh;b(h.plotHighX)&&(h.plotX=h.plotHighX);h.y=h.high;h.negative=h.high<(this.options.threshold||0);h.zone=this.zones.length&&h.getZone();this.chart.polar||(h.isInside=h.isTopInside="undefined"!==typeof h.plotY&&
0<=h.plotY&&h.plotY<=this.yAxis.len&&0<=h.plotX&&h.plotX<=this.xAxis.len);r++}f.drawPoints.apply(this,arguments);for(r=0;r<a;)h=this.points[r],h.upperGraphic=h.graphic,h.graphic=h.lowerGraphic,g(h,h.origProps),delete h.origProps,r++},setStackedPoints:k.noop},{setState:function(){var f=this.state,a=this.series,g=a.chart.polar;b(this.plotHigh)||(this.plotHigh=a.yAxis.toPixels(this.high,!0));b(this.plotLow)||(this.plotLow=this.plotY=a.yAxis.toPixels(this.low,!0));a.stateMarkerGraphic&&(a.lowerStateMarkerGraphic=
a.stateMarkerGraphic,a.stateMarkerGraphic=a.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;g&&(this.plotX=this.plotHighX);r.setState.apply(this,arguments);this.state=f;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;g&&(this.plotX=this.plotLowX);a.stateMarkerGraphic&&(a.upperStateMarkerGraphic=a.stateMarkerGraphic,a.stateMarkerGraphic=a.lowerStateMarkerGraphic,a.lowerStateMarkerGraphic=void 0);r.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,
f=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(f=r.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(f=f.concat(r.haloPath.apply(this,arguments)));return f},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return r.destroyElements.apply(this,arguments)},isValid:function(){return v(this.low)&&v(this.high)}});""});B(c,"parts-more/AreaSplineRangeSeries.js",
[c["parts/Globals.js"],c["parts/Utilities.js"]],function(k,a){a=a.seriesType;a("areasplinerange","arearange",null,{getPointSpline:k.seriesTypes.spline.prototype.getPointSpline});""});B(c,"parts-more/ColumnRangeSeries.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(k,a){var p=a.clamp,b=a.merge,g=a.pick;a=a.seriesType;var u=k.defaultPlotOptions,v=k.noop,c=k.seriesTypes.column.prototype;a("columnrange","arearange",b(u.column,u.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),
{translate:function(){var a=this,f=a.yAxis,b=a.xAxis,w=b.startAngleRad,u,h=a.chart,v=a.xAxis.isRadial,k=Math.max(h.chartWidth,h.chartHeight)+999,q;c.translate.apply(a);a.points.forEach(function(l){var e=l.shapeArgs,d=a.options.minPointLength;l.plotHigh=q=p(f.translate(l.high,0,1,0,1),-k,k);l.plotLow=p(l.plotY,-k,k);var m=q;var x=g(l.rectPlotY,l.plotY)-q;Math.abs(x)<d?(d-=x,x+=d,m-=d/2):0>x&&(x*=-1,m-=x);v?(u=l.barX+w,l.shapeType="arc",l.shapeArgs=a.polarArc(m+x,m,u,u+l.pointWidth)):(e.height=x,e.y=
m,l.tooltipPos=h.inverted?[f.len+f.pos-h.plotLeft-m-x/2,b.len+b.pos-h.plotTop-e.x-e.width/2,x]:[b.left-h.plotLeft+e.x+e.width/2,f.pos-h.plotTop+m+x/2,x])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:v,getSymbol:v,crispCol:function(){return c.crispCol.apply(this,arguments)},drawPoints:function(){return c.drawPoints.apply(this,arguments)},drawTracker:function(){return c.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return c.getColumnMetrics.apply(this,arguments)},
pointAttribs:function(){return c.pointAttribs.apply(this,arguments)},animate:function(){return c.animate.apply(this,arguments)},polarArc:function(){return c.polarArc.apply(this,arguments)},translate3dPoints:function(){return c.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return c.translate3dShapes.apply(this,arguments)}},{setState:c.pointClass.prototype.setState});""});B(c,"parts-more/ColumnPyramidSeries.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var p=
a.clamp,b=a.pick;a=a.seriesType;var g=c.seriesTypes.column.prototype;a("columnpyramid","column",{},{translate:function(){var a=this,v=a.chart,c=a.options,k=a.dense=2>a.closestPointRange*a.xAxis.transA;k=a.borderWidth=b(c.borderWidth,k?0:1);var f=a.yAxis,r=c.threshold,w=a.translatedThreshold=f.getThreshold(r),z=b(c.minPointLength,5),h=a.getColumnMetrics(),A=h.width,y=a.barW=Math.max(A,1+2*k),q=a.pointXOffset=h.offset;v.inverted&&(w-=.5);c.pointPadding&&(y=Math.ceil(y));g.translate.apply(a);a.points.forEach(function(l){var e=
b(l.yBottom,w),d=999+Math.abs(e),m=p(l.plotY,-d,f.len+d);d=l.plotX+q;var x=y/2,t=Math.min(m,e);e=Math.max(m,e)-t;var n;l.barX=d;l.pointWidth=A;l.tooltipPos=v.inverted?[f.len+f.pos-v.plotLeft-m,a.xAxis.len-d-x,e]:[d+x,m+f.pos-v.plotTop,e];m=r+(l.total||l.y);"percent"===c.stacking&&(m=r+(0>l.y)?-100:100);m=f.toPixels(m,!0);var D=(n=v.plotHeight-m-(v.plotHeight-w))?x*(t-m)/n:0;var g=n?x*(t+e-m)/n:0;n=d-D+x;D=d+D+x;var h=d+g+x;g=d-g+x;var u=t-z;var k=t+e;0>l.y&&(u=t,k=t+e+z);v.inverted&&(h=v.plotWidth-
t,n=m-(v.plotWidth-w),D=x*(m-h)/n,g=x*(m-(h-e))/n,n=d+x+D,D=n-2*D,h=d-g+x,g=d+g+x,u=t,k=t+e-z,0>l.y&&(k=t+e+z));l.shapeType="path";l.shapeArgs={x:n,y:u,width:D-n,height:e,d:[["M",n,u],["L",D,u],["L",h,k],["L",g,k],["Z"]]}})}});""});B(c,"parts-more/GaugeSeries.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var p=a.clamp,b=a.isNumber,g=a.merge,u=a.pick,v=a.pInt;a=a.seriesType;var k=c.Series,C=c.TrackerMixin;a("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,
crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:c.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,r=this.options,w=a.center;this.generatePoints();this.points.forEach(function(f){var h=g(r.dial,f.dial),c=v(u(h.radius,"80%"))*w[2]/200,k=v(u(h.baseLength,"70%"))*c/100,q=v(u(h.rearLength,"10%"))*c/100,l=h.baseWidth||
3,e=h.topWidth||1,d=r.overshoot,m=a.startAngleRad+a.translate(f.y,null,null,null,!0);if(b(d)||!1===r.wrap)d=b(d)?d/180*Math.PI:0,m=p(m,a.startAngleRad-d,a.endAngleRad+d);m=180*m/Math.PI;f.shapeType="path";f.shapeArgs={d:h.path||[["M",-q,-l/2],["L",k,-l/2],["L",c,-e/2],["L",c,e/2],["L",k,l/2],["L",-q,l/2],["Z"]],translateX:w[0],translateY:w[1],rotation:m};f.plotX=w[0];f.plotY=w[1]})},drawPoints:function(){var a=this,b=a.chart,p=a.yAxis.center,c=a.pivot,h=a.options,k=h.pivot,v=b.renderer;a.points.forEach(function(f){var l=
f.graphic,e=f.shapeArgs,d=e.d,m=g(h.dial,f.dial);l?(l.animate(e),e.d=d):f.graphic=v[f.shapeType](e).attr({rotation:e.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!b.styledMode)f.graphic[l?"animate":"attr"]({stroke:m.borderColor||"none","stroke-width":m.borderWidth||0,fill:m.backgroundColor||"#000000"})});c?c.animate({translateX:p[0],translateY:p[1]}):(a.pivot=v.circle(0,0,u(k.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(p[0],p[1]).add(a.group),b.styledMode||
a.pivot.attr({"stroke-width":k.borderWidth||0,stroke:k.borderColor||"#cccccc",fill:k.backgroundColor||"#000000"}))},animate:function(a){var f=this;a||f.points.forEach(function(a){var b=a.graphic;b&&(b.attr({rotation:180*f.yAxis.startAngleRad/Math.PI}),b.animate({rotation:a.shapeArgs.rotation},f.options.animation))})},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);k.prototype.render.call(this);this.group.clip(this.chart.clipRect)},
setData:function(a,b){k.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();u(b,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:C&&C.drawTrackerPoint},{setState:function(a){this.state=a}});""});B(c,"parts-more/BoxPlotSeries.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var p=a.pick;a=a.seriesType;var b=c.noop,g=c.seriesTypes;a("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:b,translate:function(){var a=this.yAxis,b=this.pointArrayMap;g.column.prototype.translate.apply(this);this.points.forEach(function(g){b.forEach(function(b){null!==g[b]&&(g[b+"Plot"]=a.translate(g[b],0,1,0,1))});g.plotHigh=g.highPlot})},drawPoints:function(){var a=
this,b=a.options,g=a.chart,c=g.renderer,f,r,w,k,h,A,y=0,q,l,e,d,m=!1!==a.doQuartiles,x,t=a.options.whiskerLength;a.points.forEach(function(n){var D=n.graphic,F=D?"animate":"attr",J=n.shapeArgs,u={},G={},H={},I={},v=n.color||a.color;"undefined"!==typeof n.plotY&&(q=Math.round(J.width),l=Math.floor(J.x),e=l+q,d=Math.round(q/2),f=Math.floor(m?n.q1Plot:n.lowPlot),r=Math.floor(m?n.q3Plot:n.lowPlot),w=Math.floor(n.highPlot),k=Math.floor(n.lowPlot),D||(n.graphic=D=c.g("point").add(a.group),n.stem=c.path().addClass("highcharts-boxplot-stem").add(D),
t&&(n.whiskers=c.path().addClass("highcharts-boxplot-whisker").add(D)),m&&(n.box=c.path(void 0).addClass("highcharts-boxplot-box").add(D)),n.medianShape=c.path(void 0).addClass("highcharts-boxplot-median").add(D)),g.styledMode||(G.stroke=n.stemColor||b.stemColor||v,G["stroke-width"]=p(n.stemWidth,b.stemWidth,b.lineWidth),G.dashstyle=n.stemDashStyle||b.stemDashStyle||b.dashStyle,n.stem.attr(G),t&&(H.stroke=n.whiskerColor||b.whiskerColor||v,H["stroke-width"]=p(n.whiskerWidth,b.whiskerWidth,b.lineWidth),
H.dashstyle=n.whiskerDashStyle||b.whiskerDashStyle||b.dashStyle,n.whiskers.attr(H)),m&&(u.fill=n.fillColor||b.fillColor||v,u.stroke=b.lineColor||v,u["stroke-width"]=b.lineWidth||0,u.dashstyle=n.boxDashStyle||b.boxDashStyle||b.dashStyle,n.box.attr(u)),I.stroke=n.medianColor||b.medianColor||v,I["stroke-width"]=p(n.medianWidth,b.medianWidth,b.lineWidth),I.dashstyle=n.medianDashStyle||b.medianDashStyle||b.dashStyle,n.medianShape.attr(I)),A=n.stem.strokeWidth()%2/2,y=l+d+A,D=[["M",y,r],["L",y,w],["M",
y,f],["L",y,k]],n.stem[F]({d:D}),m&&(A=n.box.strokeWidth()%2/2,f=Math.floor(f)+A,r=Math.floor(r)+A,l+=A,e+=A,D=[["M",l,r],["L",l,f],["L",e,f],["L",e,r],["L",l,r],["Z"]],n.box[F]({d:D})),t&&(A=n.whiskers.strokeWidth()%2/2,w+=A,k+=A,x=/%$/.test(t)?d*parseFloat(t)/100:t/2,D=[["M",y-x,w],["L",y+x,w],["M",y-x,k],["L",y+x,k]],n.whiskers[F]({d:D})),h=Math.round(n.medianPlot),A=n.medianShape.strokeWidth()%2/2,h+=A,D=[["M",l,h],["L",e,h]],n.medianShape[F]({d:D}))})},setStackedPoints:b});""});B(c,"parts-more/ErrorBarSeries.js",
[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){a=a.seriesType;var p=c.noop,b=c.seriesTypes;a("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:b.arearange?function(){var a=this.pointValKey;
b.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(b){b.y=b[a]})}:p,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||b.column.prototype.getColumnMetrics.call(this)}});""});B(c,"parts-more/WaterfallSeries.js",[c["parts/Axis.js"],c["parts/Globals.js"],c["parts/Point.js"],c["parts/Stacking.js"],c["parts/Utilities.js"]],function(c,a,p,b,g){var k=g.addEvent,v=g.arrayMax,E=g.arrayMin,C=g.correctFloat,f=g.isNumber,r=g.objectEach,w=g.pick;g=g.seriesType;
var z=a.Chart,h=a.Series,A=a.seriesTypes,y;(function(a){function f(){var d=this.waterfall.stacks;d&&(d.changed=!1,delete d.alreadyChanged)}function e(){var d=this.options.stackLabels;d&&d.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function d(){for(var d=this.axes,e=this.series,a=e.length;a--;)e[a].options.stacking&&(d.forEach(function(d){d.isXAxis||(d.waterfall.stacks.changed=!0)}),a=0)}function m(){this.waterfall||(this.waterfall=new x(this))}var x=function(){function d(d){this.axis=
d;this.stacks={changed:!1}}d.prototype.renderStackTotals=function(){var d=this.axis,e=d.waterfall.stacks,a=d.stacking&&d.stacking.stackTotalGroup,m=new b(d,d.options.stackLabels,!1,0,void 0);this.dummyStackItem=m;r(e,function(d){r(d,function(d){m.total=d.stackTotal;d.label&&(m.label=d.label);b.prototype.render.call(m,a);d.label=m.label;delete m.label})});m.total=null};return d}();a.Composition=x;a.compose=function(a,n){k(a,"init",m);k(a,"afterBuildStacks",f);k(a,"afterRender",e);k(n,"beforeRedraw",
d)}})(y||(y={}));g("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var a;A.column.prototype.generatePoints.apply(this);var f=0;for(a=this.points.length;f<a;f++){var e=this.points[f];var d=this.processedYData[f];if(e.isIntermediateSum||e.isSum)e.y=C(d)}},translate:function(){var a=this.options,f=this.yAxis,e,d=w(a.minPointLength,5),m=d/2,b=a.threshold,
t=a.stacking,n=f.waterfall.stacks[this.stackKey];A.column.prototype.translate.apply(this);var D=e=b;var g=this.points;var h=0;for(a=g.length;h<a;h++){var p=g[h];var r=this.processedYData[h];var c=p.shapeArgs;var k=[0,r];var u=p.y;if(t){if(n){k=n[h];if("overlap"===t){var v=k.stackState[k.stateIndex--];v=0<=u?v:v-u;Object.hasOwnProperty.call(k,"absolutePos")&&delete k.absolutePos;Object.hasOwnProperty.call(k,"absoluteNeg")&&delete k.absoluteNeg}else 0<=u?(v=k.threshold+k.posTotal,k.posTotal-=u):(v=
k.threshold+k.negTotal,k.negTotal-=u,v-=u),!k.posTotal&&Object.hasOwnProperty.call(k,"absolutePos")&&(k.posTotal=k.absolutePos,delete k.absolutePos),!k.negTotal&&Object.hasOwnProperty.call(k,"absoluteNeg")&&(k.negTotal=k.absoluteNeg,delete k.absoluteNeg);p.isSum||(k.connectorThreshold=k.threshold+k.stackTotal);f.reversed?(r=0<=u?v-u:v+u,u=v):(r=v,u=v-u);p.below=r<=w(b,0);c.y=f.translate(r,0,1,0,1);c.height=Math.abs(c.y-f.translate(u,0,1,0,1))}if(u=f.waterfall.dummyStackItem)u.x=h,u.label=n[h].label,
u.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[h],this.stackedYPos[h])}else v=Math.max(D,D+u)+k[0],c.y=f.translate(v,0,1,0,1),p.isSum?(c.y=f.translate(k[1],0,1,0,1),c.height=Math.min(f.translate(k[0],0,1,0,1),f.len)-c.y):p.isIntermediateSum?(0<=u?(r=k[1]+e,u=e):(r=e,u=k[1]+e),f.reversed&&(r^=u,u^=r,r^=u),c.y=f.translate(r,0,1,0,1),c.height=Math.abs(c.y-Math.min(f.translate(u,0,1,0,1),f.len)),e+=k[1]):(c.height=0<r?f.translate(D,0,1,0,1)-c.y:f.translate(D,0,1,0,1)-f.translate(D-r,0,
1,0,1),D+=r,p.below=D<w(b,0)),0>c.height&&(c.y+=c.height,c.height*=-1);p.plotY=c.y=Math.round(c.y)-this.borderWidth%2/2;c.height=Math.max(Math.round(c.height),.001);p.yBottom=c.y+c.height;c.height<=d&&!p.isNull?(c.height=d,c.y-=m,p.plotY=c.y,p.minPointLengthOffset=0>p.y?-m:m):(p.isNull&&(c.width=0),p.minPointLengthOffset=0);c=p.plotY+(p.negative?c.height:0);this.chart.inverted?p.tooltipPos[0]=f.len-c:p.tooltipPos[1]=c}},processData:function(a){var f=this.options,e=this.yData,d=f.data,m=e.length,b=
f.threshold||0,t,n,g,p,c;for(c=n=t=g=p=0;c<m;c++){var r=e[c];var q=d&&d[c]?d[c]:{};"sum"===r||q.isSum?e[c]=C(n):"intermediateSum"===r||q.isIntermediateSum?(e[c]=C(t),t=0):(n+=r,t+=r);g=Math.min(n,g);p=Math.max(n,p)}h.prototype.processData.call(this,a);f.stacking||(this.dataMin=g+b,this.dataMax=p)},toYData:function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y},updateParallelArrays:function(a,f){h.prototype.updateParallelArrays.call(this,a,f);if("sum"===this.yData[0]||"intermediateSum"===
this.yData[0])this.yData[0]=null},pointAttribs:function(a,f){var e=this.options.upColor;e&&!a.options.color&&(a.color=0<a.y?e:null);a=A.column.prototype.pointAttribs.call(this,a,f);delete a.dashstyle;return a},getGraphPath:function(){return[["M",0,0]]},getCrispPath:function(){var a=this.data,f=this.yAxis,e=a.length,d=Math.round(this.graph.strokeWidth())%2/2,m=Math.round(this.borderWidth)%2/2,b=this.xAxis.reversed,t=this.yAxis.reversed,n=this.options.stacking,g=[],h;for(h=1;h<e;h++){var p=a[h].shapeArgs;
var c=a[h-1];var r=a[h-1].shapeArgs;var k=f.waterfall.stacks[this.stackKey];var u=0<c.y?-r.height:0;k&&r&&p&&(k=k[h-1],n?(k=k.connectorThreshold,u=Math.round(f.translate(k,0,1,0,1)+(t?u:0))-d):u=r.y+c.minPointLengthOffset+m-d,g.push(["M",(r.x||0)+(b?0:r.width||0),u],["L",(p.x||0)+(b?p.width||0:0),u]));!n&&g.length&&r&&(0>c.y&&!t||0<c.y&&t)&&(g[g.length-2][2]+=r.height,g[g.length-1][2]+=r.height)}return g},drawGraph:function(){h.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},
setStackedPoints:function(){function a(d,a,e,m){if(C)for(e;e<C;e++)v.stackState[e]+=m;else v.stackState[0]=d,C=v.stackState.length;v.stackState.push(v.stackState[C-1]+a)}var f=this.options,e=this.yAxis.waterfall.stacks,d=f.threshold,m=d||0,b=m,t=this.stackKey,n=this.xData,g=n.length,h,p,c;this.yAxis.stacking.usePercentage=!1;var r=p=c=m;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var k=e.changed;(h=e.alreadyChanged)&&0>h.indexOf(t)&&(k=!0);e[t]||(e[t]={});h=e[t];for(var u=0;u<g;u++){var w=
n[u];if(!h[w]||k)h[w]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:k&&h[w]?h[w].label:void 0};var v=h[w];var y=this.yData[u];0<=y?v.posTotal+=y:v.negTotal+=y;var z=f.data[u];w=v.absolutePos=v.posTotal;var A=v.absoluteNeg=v.negTotal;v.stackTotal=w+A;var C=v.stackState.length;z&&z.isIntermediateSum?(a(c,p,0,c),c=p,p=d,m^=b,b^=m,m^=b):z&&z.isSum?(a(d,r,C),m=d):(a(m,y,0,r),z&&(r+=y,p+=y));v.stateIndex++;v.threshold=m;m+=v.stackTotal}e.changed=!1;e.alreadyChanged||(e.alreadyChanged=
[]);e.alreadyChanged.push(t)}},getExtremes:function(){var a=this.options.stacking;if(a){var f=this.yAxis;f=f.waterfall.stacks;var e=this.stackedYNeg=[];var d=this.stackedYPos=[];"overlap"===a?r(f[this.stackKey],function(a){e.push(E(a.stackState));d.push(v(a.stackState))}):r(f[this.stackKey],function(a){e.push(a.negTotal+a.threshold);d.push(a.posTotal+a.threshold)});return{dataMin:E(e),dataMax:v(d)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}},{getClassName:function(){var a=p.prototype.getClassName.call(this);
this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a},isValid:function(){return f(this.y)||this.isSum||!!this.isIntermediateSum}});"";y.compose(c,z);return y});B(c,"parts-more/PolygonSeries.js",[c["parts/Globals.js"],c["mixins/legend-symbol.js"],c["parts/Utilities.js"]],function(c,a,p){p=p.seriesType;var b=c.Series,g=c.seriesTypes;p("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},
trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=b.prototype.getGraphPath.call(this),g=a.length+1;g--;)(g===a.length||"M"===a[g][0])&&0<g&&a.splice(g,0,["Z"]);return this.areaPath=a},drawGraph:function(){this.options.fillColor=this.color;g.area.prototype.drawGraph.call(this)},drawLegendSymbol:a.drawRectangle,drawTracker:b.prototype.drawTracker,setStackedPoints:c.noop});""});B(c,"parts-more/BubbleLegend.js",[c["parts/Chart.js"],c["parts/Color.js"],c["parts/Globals.js"],c["parts/Legend.js"],
c["parts/Utilities.js"]],function(c,a,p,b,g){var k=a.parse;a=g.addEvent;var v=g.arrayMax,E=g.arrayMin,C=g.isNumber,f=g.merge,r=g.objectEach,w=g.pick,z=g.stableSort,h=g.wrap;"";var A=p.Series,y=p.noop,q=p.setOptions;q({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,
color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});q=function(){function a(a,d){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=y;this.init(a,d)}a.prototype.init=function(a,
d){this.options=a;this.visible=!0;this.chart=d.chart;this.legend=d};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var d=this.chart,e=this.options,f=w(a.options.itemDistance,20),b=e.ranges;var n=e.connectorDistance;this.fontMetrics=d.renderer.fontMetrics(e.labels.style.fontSize.toString()+"px");b&&b.length&&C(b[0].value)?(z(b,function(d,a){return a.value-d.value}),this.ranges=b,this.setOptions(),this.render(),d=this.getMaxLabelSize(),
b=this.ranges[0].radius,a=2*b,n=n-b+d.width,n=0<n?n:0,this.maxLabel=d,this.movementX="left"===e.labels.align?n:0,this.legendItemWidth=a+n+f,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,d=this.options,m=this.chart.series[d.seriesIndex],b=this.legend.baseline,t={"z-index":d.zIndex,"stroke-width":d.borderWidth},n={"z-index":d.zIndex,"stroke-width":d.connectorWidth},g=this.getLabelStyles(),l=m.options.marker.fillOpacity,
h=this.chart.styledMode;a.forEach(function(e,x){h||(t.stroke=w(e.borderColor,d.borderColor,m.color),t.fill=w(e.color,d.color,1!==l?k(m.color).setOpacity(l).get("rgba"):m.color),n.stroke=w(e.connectorColor,d.connectorColor,m.color));a[x].radius=this.getRangeRadius(e.value);a[x]=f(a[x],{center:a[0].radius-a[x].radius+b});h||f(!0,a[x],{bubbleStyle:f(!1,t),connectorStyle:f(!1,n),labelStyle:g})},this)};a.prototype.getLabelStyles=function(){var a=this.options,d={},m="left"===a.labels.align,b=this.legend.options.rtl;
r(a.labels.style,function(a,e){"color"!==e&&"fontSize"!==e&&"z-index"!==e&&(d[e]=a)});return f(!1,d,{"font-size":a.labels.style.fontSize,fill:w(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:b||m?"right":"left"})};a.prototype.getRangeRadius=function(a){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-1].value,d.ranges[0].value,d.minSize,d.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,d=this.options.zThreshold;
this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=d&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var d=this.options,e=d.labels,f=this.chart.renderer,b=this.symbols,n=b.labels,
g=a.center,l=Math.abs(a.radius),h=d.connectorDistance||0,c=e.align,p=e.style.fontSize;h=this.legend.options.rtl||"left"===c?-h:h;e=d.connectorWidth;var r=this.ranges[0].radius||0,k=g-l-d.borderWidth/2+e/2;p=p/2-(this.fontMetrics.h-p)/2;var q=f.styledMode;"center"===c&&(h=0,d.connectorDistance=0,a.labelStyle.align="center");c=k+d.labels.y;var u=r+h+d.labels.x;b.bubbleItems.push(f.circle(r,g+((k%1?1:.5)-(e%2?0:.5)),l).attr(q?{}:a.bubbleStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+
" ":"")+"highcharts-bubble-legend-symbol "+(d.className||"")).add(this.legendSymbol));b.connectors.push(f.path(f.crispLine([["M",r,k],["L",r+h,k]],d.connectorWidth)).attr(q?{}:a.connectorStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(d.connectorClassName||"")).add(this.legendSymbol));a=f.text(this.formatLabel(a),u,c+p).attr(q?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(d.labels.className||"")).add(this.legendSymbol);
n.push(a);a.placed=!0;a.alignAttr={x:u,y:c+p}};a.prototype.getMaxLabelSize=function(){var a,d;this.symbols.labels.forEach(function(e){d=e.getBBox(!0);a=a?d.width>a.width?d:a:d});return a||{}};a.prototype.formatLabel=function(a){var d=this.options,e=d.labels.formatter;d=d.labels.format;var f=this.chart.numberFormatter;return d?g.format(d,a):e?e.call(a):f(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(a.hideOverlappingLabels(d.labels),
d.labels.forEach(function(a,e){a.newOpacity?a.newOpacity!==a.oldOpacity&&d.connectors[e].show():d.connectors[e].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,d=a.options.ranges,m,b=Number.MAX_VALUE,t=-Number.MAX_VALUE;a.chart.series.forEach(function(d){d.isBubble&&!d.ignoreSeries&&(m=d.zData.filter(C),m.length&&(b=w(d.options.zMin,Math.min(b,Math.max(E(m),!1===d.options.displayNegative?d.options.zThreshold:-Number.MAX_VALUE))),t=w(d.options.zMax,Math.max(t,v(m)))))});
var n=b===t?[{value:t}]:[{value:b},{value:(b+t)/2},{value:t,autoRanges:!0}];d.length&&d[0].radius&&n.reverse();n.forEach(function(a,e){d&&d[e]&&(n[e]=f(!1,d[e],a))});return n};a.prototype.predictBubbleSizes=function(){var a=this.chart,d=this.fontMetrics,f=a.legend.options,b="horizontal"===f.layout,t=b?a.legend.lastLineHeight:0,n=a.plotSizeX,g=a.plotSizeY,l=a.series[this.options.seriesIndex];a=Math.ceil(l.minPxSize);var h=Math.ceil(l.maxPxSize);l=l.options.maxSize;var c=Math.min(g,n);if(f.floating||
!/%$/.test(l))d=h;else if(l=parseFloat(l),d=(c+t-d.h/2)*l/100/(l/100+1),b&&g-d>=n||!b&&n-d>=g)d=h;return[a,Math.ceil(d)]};a.prototype.updateRanges=function(a,d){var e=this.legend.options.bubbleLegend;e.minSize=a;e.maxSize=d;e.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,d=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(d.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,d.maxPxSize),a.render())};return a}();a(b,"afterGetAllItems",
function(a){var e=this.bubbleLegend,d=this.options,f=d.bubbleLegend,b=this.chart.getVisibleBubbleSeriesIndex();e&&e.ranges&&e.ranges.length&&(f.ranges.length&&(f.autoRanges=!!f.ranges[0].autoRanges),this.destroyItem(e));0<=b&&d.enabled&&f.enabled&&(f.seriesIndex=b,this.bubbleLegend=new p.BubbleLegend(f,this),this.bubbleLegend.addToLegend(a.allItems))});c.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,e=0;e<a.length;){if(a[e]&&a[e].isBubble&&a[e].visible&&a[e].zData.length)return e;
e++}return-1};b.prototype.getLinesHeights=function(){var a=this.allItems,e=[],d=a.length,f,b=0;for(f=0;f<d;f++)if(a[f].legendItemHeight&&(a[f].itemHeight=a[f].legendItemHeight),a[f]===a[d-1]||a[f+1]&&a[f]._legendItemPos[1]!==a[f+1]._legendItemPos[1]){e.push({height:0});var t=e[e.length-1];for(b;b<=f;b++)a[b].itemHeight>t.height&&(t.height=a[b].itemHeight);t.step=f}return e};b.prototype.retranslateItems=function(a){var f,d,b,g=this.options.rtl,t=0;this.allItems.forEach(function(e,m){f=e.legendGroup.translateX;
d=e._legendItemPos[1];if((b=e.movementX)||g&&e.ranges)b=g?f-e.options.maxSize/2:f+b,e.legendGroup.attr({translateX:b});m>a[t].step&&t++;e.legendGroup.attr({translateY:Math.round(d+a[t].height/2)});e._legendItemPos[1]=d+a[t].height/2})};a(A,"legendItemClick",function(){var a=this.chart,f=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=!f,this.ignoreSeries=f,a=0<=a.getVisibleBubbleSeriesIndex(),d.bubbleLegend.visible!==a&&(d.update({bubbleLegend:{enabled:a}}),d.bubbleLegend.visible=
a),this.visible=f)});h(c.prototype,"drawChartBox",function(a,f,d){var e=this.legend,b=0<=this.getVisibleBubbleSeriesIndex();if(e&&e.options.enabled&&e.bubbleLegend&&e.options.bubbleLegend.autoRanges&&b){var t=e.bubbleLegend.options;b=e.bubbleLegend.predictBubbleSizes();e.bubbleLegend.updateRanges(b[0],b[1]);t.placed||(e.group.placed=!1,e.allItems.forEach(function(d){d.legendGroup.translateY=null}));e.render();this.getMargins();this.axes.forEach(function(d){d.visible&&d.render();t.placed||(d.setScale(),
d.updateNames(),r(d.ticks,function(d){d.isNew=!0;d.isNewLabel=!0}))});t.placed=!0;this.getMargins();a.call(this,f,d);e.bubbleLegend.correctSizes();e.retranslateItems(e.getLinesHeights())}else a.call(this,f,d),e&&e.options.enabled&&e.bubbleLegend&&(e.render(),e.retranslateItems(e.getLinesHeights()))});p.BubbleLegend=q;return p.BubbleLegend});B(c,"parts-more/BubbleSeries.js",[c["parts/Globals.js"],c["parts/Color.js"],c["parts/Point.js"],c["parts/Utilities.js"]],function(c,a,p,b){var g=a.parse,k=b.arrayMax,
v=b.arrayMin,E=b.clamp,C=b.extend,f=b.isNumber,r=b.pick,w=b.pInt;a=b.seriesType;b=c.Axis;var z=c.noop,h=c.Series,A=c.seriesTypes;a("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},
turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,f){var b=this.options.marker.fillOpacity;a=h.prototype.pointAttribs.call(this,a,f);1!==b&&(a.fill=g(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,f,b){var e=this.zData,d=this.yData,m=b.minPxSize,g=b.maxPxSize,t=[];var n=0;for(b=e.length;n<b;n++){var h=
e[n];t.push(this.getRadius(a,f,m,g,h,d[n]))}this.radii=t},getRadius:function(a,b,g,e,d,m){var h=this.options,t="width"!==h.sizeBy,n=h.zThreshold,c=b-a,p=.5;if(null===m||null===d)return null;if(f(d)){h.sizeByAbsoluteValue&&(d=Math.abs(d-n),c=Math.max(b-n,Math.abs(a-n)),a=0);if(d<a)return g/2-1;0<c&&(p=(d-a)/c)}t&&0<=p&&(p=Math.sqrt(p));return Math.ceil(g+p*(e-g))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var f=a.graphic;if(f&&f.width){var e=
{x:f.x,y:f.y,width:f.width,height:f.height};f.attr({x:a.plotX,y:a.plotY,width:1,height:1});f.animate(e,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,b=this.data,g=this.radii;A.scatter.prototype.translate.call(this);for(a=b.length;a--;){var e=b[a];var d=g?g[a]:0;f(d)&&d>=this.minPxSize/2?(e.marker=C(e.marker,{radius:d,width:2*d,height:2*d}),e.dlBox={x:e.plotX-d,y:e.plotY-d,width:2*d,height:2*d}):e.shapeArgs=e.plotY=e.dlBox=void 0}},
alignDataLabel:A.column.prototype.alignDataLabel,buildKDTree:z,applyZones:z},{haloPath:function(a){return p.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});b.prototype.beforePadding=function(){var a=this,b=this.len,g=this.chart,e=0,d=b,m=this.isXAxis,h=m?"xData":"yData",t=this.min,n={},c=Math.min(g.plotWidth,g.plotHeight),p=Number.MAX_VALUE,u=-Number.MAX_VALUE,z=this.max-t,A=b/z,C=[];this.series.forEach(function(d){var e=d.options;!d.bubblePadding||!d.visible&&
g.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,C.push(d),m&&(["minSize","maxSize"].forEach(function(d){var a=e[d],f=/%$/.test(a);a=w(a);n[d]=f?c*a/100:a}),d.minPxSize=n.minSize,d.maxPxSize=Math.max(n.maxSize,n.minSize),d=d.zData.filter(f),d.length&&(p=r(e.zMin,E(v(d),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,p)),u=r(e.zMax,Math.max(u,k(d))))))});C.forEach(function(b){var n=b[h],g=n.length;m&&b.getRadii(p,u,b);if(0<z)for(;g--;)if(f(n[g])&&a.dataMin<=n[g]&&n[g]<=a.max){var c=
b.radii?b.radii[g]:0;e=Math.min((n[g]-t)*A-c,e);d=Math.max((n[g]-t)*A+c,d)}});C.length&&0<z&&!this.logarithmic&&(d-=b,A*=(b+Math.max(0,e)-Math.min(d,b))/b,[["min","userMin",e],["max","userMax",d]].forEach(function(d){"undefined"===typeof r(a.options[d[0]],a[d[1]])&&(a[d[0]]+=d[2]/A)}))};""});B(c,"modules/networkgraph/integrations.js",[c["parts/Globals.js"]],function(c){c.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,c){return(c-a)/a},repulsiveForceFunction:function(a,c){return(c-
a)/a*(c>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,b=this.barycenter.yFactor;c=(c-(this.box.left+this.box.width)/2)*a;b=(b-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=c/a.mass/a.degree,a.plotY-=b/a.mass/a.degree)})},repulsive:function(a,c,b){c=c*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=b.x*c,a.plotY+=b.y*c)},attractive:function(a,c,b){var g=a.getMass(),p=-b.x*c*this.diffTemperature;
c=-b.y*c*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=p*g.fromNode/a.fromNode.degree,a.fromNode.plotY-=c*g.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.plotX+=p*g.toNode/a.toNode.degree,a.toNode.plotY+=c*g.toNode/a.toNode.degree)},integrate:function(a,c){var b=-a.options.friction,g=a.options.maxSpeed,p=(c.plotX+c.dispX-c.prevX)*b;b*=c.plotY+c.dispY-c.prevY;var k=Math.abs,E=k(p)/(p||1);k=k(b)/(b||1);p=E*Math.min(g,Math.abs(p));b=k*Math.min(g,Math.abs(b));c.prevX=
c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=p;c.plotY+=b;c.temperature=a.vectorLength({x:p,y:b})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)}},euler:{attractiveForceFunction:function(a,c){return a*a/c},repulsiveForceFunction:function(a,c){return c*c/a},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,b=this.barycenter.yFactor;this.nodes.forEach(function(g){if(!g.fixedPosition){var p=g.getDegree();p*=1+p/2;g.dispX+=(c-g.plotX)*
a*p/g.degree;g.dispY+=(b-g.plotY)*a*p/g.degree}})},repulsive:function(a,c,b,g){a.dispX+=b.x/g*c/a.degree;a.dispY+=b.y/g*c/a.degree},attractive:function(a,c,b,g){var p=a.getMass(),k=b.x/g*c;c*=b.y/g;a.fromNode.fixedPosition||(a.fromNode.dispX-=k*p.fromNode/a.fromNode.degree,a.fromNode.dispY-=c*p.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=k*p.toNode/a.toNode.degree,a.toNode.dispY+=c*p.toNode/a.toNode.degree)},integrate:function(a,c){c.dispX+=c.dispX*a.options.friction;c.dispY+=
c.dispY*a.options.friction;var b=c.temperature=a.vectorLength({x:c.dispX,y:c.dispY});0!==b&&(c.plotX+=c.dispX/b*Math.min(Math.abs(c.dispX),a.temperature),c.plotY+=c.dispY/b*Math.min(Math.abs(c.dispY),a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.3)}}}});B(c,"modules/networkgraph/QuadTree.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){a=a.extend;var k=c.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=
[];this.body=this.isInternal=!1;this.isEmpty=!0};a(k.prototype,{insert:function(a,c){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,c-1):(this.isEmpty=!1,this.body?c?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,c-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,c-1)):(c=new k({top:a.plotX,left:a.plotY,width:.1,height:.1}),c.body=a,c.isInternal=!1,this.nodes.push(c)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=
0,c=0,k=0;this.isInternal?(this.nodes.forEach(function(b){b.isEmpty||(a+=b.mass,c+=b.plotX*b.mass,k+=b.plotY*b.mass)}),c/=a,k/=a):this.body&&(a=this.body.mass,c=this.body.plotX,k=this.body.plotY);this.mass=a;this.plotX=c;this.plotY=k},divideBox:function(){var a=this.box.width/2,c=this.box.height/2;this.nodes[0]=new k({left:this.box.left,top:this.box.top,width:a,height:c});this.nodes[1]=new k({left:this.box.left+a,top:this.box.top,width:a,height:c});this.nodes[2]=new k({left:this.box.left+a,top:this.box.top+
c,width:a,height:c});this.nodes[3]=new k({left:this.box.left,top:this.box.top+c,width:a,height:c})},getBoxPosition:function(a){var b=a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?b?0:3:b?1:2}});c=c.QuadTree=function(a,c,p,v){this.box={left:a,top:c,width:p,height:v};this.maxDepth=25;this.root=new k(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(c.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},
this)},visitNodeRecursive:function(a,c,k){var b;a||(a=this.root);a===this.root&&c&&(b=c(a));!1!==b&&(a.nodes.forEach(function(a){if(a.isInternal){c&&(b=c(a));if(!1===b)return;this.visitNodeRecursive(a,c,k)}else a.body&&c&&c(a.body);k&&k(a)},this),a===this.root&&k&&k(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});B(c,"modules/networkgraph/layouts.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var k=a.addEvent,b=
a.clamp,g=a.defined,u=a.extend,v=a.isFunction,E=a.pick,C=a.setAnimation;a=c.Chart;c.layouts={"reingold-fruchterman":function(){}};u(c.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=c.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=E(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=
E(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=E(a,this.options.enableSimulation)},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},step:function(){var a=
this,b=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(f){a[f+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?
(a.simulation&&c.win.cancelAnimationFrame(a.simulation),a.simulation=c.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&c.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,c,g){this.box={left:a,top:b,width:c,height:g}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);
-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=E(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/
(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new c.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;v(a)?(a.call(this),this.nodes.forEach(function(a){g(a.prevX)||(a.prevX=a.plotX);g(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},
setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(e){p[e.toNode.id]||(p[e.toNode.id]=!0,k.push(e.toNode),a(e.toNode))})}var b=this.box,c=this.nodes,g=2*Math.PI/(c.length+1),h=c.filter(function(a){return 0===a.linksTo.length}),k=[],p={},q=this.options.initialPositionRadius;h.forEach(function(b){k.push(b);a(b)});k.length?c.forEach(function(a){-1===k.indexOf(a)&&k.push(a)}):k=c;k.forEach(function(a,e){a.plotX=a.prevX=E(a.plotX,b.width/2+q*Math.cos(e*g));a.plotY=a.prevY=E(a.plotY,
b.height/2+q*Math.sin(e*g));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,c=this.nodes,g=c.length+1;c.forEach(function(f,c){f.plotX=f.prevX=E(f.plotX,b.width*a(c));f.plotY=f.prevY=E(f.plotY,b.height*a(g+c));f.dispX=0;f.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=
0,b=0,c=0;this.nodes.forEach(function(f){b+=f.plotX*f.mass;c+=f.plotY*f.mass;a+=f.mass});return this.barycenter={x:b,y:c,xFactor:b/a,yFactor:c/a}},barnesHutApproximation:function(a,b){var f=this.getDistXY(a,b),c=this.vectorLength(f);if(a!==b&&0!==c)if(b.isInternal)if(b.boxSize/c<this.options.theta&&0!==c){var g=this.repulsiveForce(c,this.k);this.force("repulsive",a,g*b.mass,f,c);var k=!1}else k=!0;else g=this.repulsiveForce(c,this.k),this.force("repulsive",a,g*b.mass,f,c);return k},repulsiveForces:function(){var a=
this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){if(b!==c&&!b.fixedPosition){var f=a.getDistXY(b,c);var g=a.vectorLength(f);if(0!==g){var k=a.repulsiveForce(g,a.k);a.force("repulsive",b,k*c.mass,f,g)}}})})},attractiveForces:function(){var a=this,b,c,g;a.links.forEach(function(f){f.fromNode&&f.toNode&&(b=a.getDistXY(f.fromNode,f.toNode),c=a.vectorLength(b),
0!==c&&(g=a.attractiveForce(c,a.k),a.force("attractive",f,g,b,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,c){var f=a.radius;a.plotX=b(a.plotX,c.left+f,c.width-f);a.plotY=b(a.plotY,c.top+f,c.height-f)},coolDown:function(a,b,c){return a-b*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},
getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});k(a,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});k(a,"render",function(){function a(a){a.maxIterations--&&
isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),c=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){C(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!c;){var c=!0;this.graphLayoutsLookup.forEach(a)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});k(a,"beforePrint",function(){this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)});this.redraw()});k(a,"afterPrint",function(){this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});
this.redraw()})});B(c,"modules/networkgraph/draggable-nodes.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var k=a.addEvent;a=c.Chart;c.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,c){if(a.fixedPosition&&a.inDragMode){var b=this.chart,g=b.pointer.normalize(c);c=a.fixedPosition.chartX-g.chartX;g=a.fixedPosition.chartY-g.chartY;if(5<
Math.abs(c)||5<Math.abs(g))c=a.fixedPosition.plotX-c,g=a.fixedPosition.plotY-g,b.isInsidePlot(c,g)&&(a.plotX=c,a.plotY=g,a.hasDragged=!0,this.redrawHalo(a),this.layout.simulation?this.layout.resetSimulation():(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(a,c){a.fixedPosition&&a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw(),
a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};k(a,"load",function(){var a=this,c,p,v;a.container&&(c=k(a.container,"mousedown",function(c){var b=a.hoverPoint;b&&b.series&&b.series.hasDraggableNodes&&b.series.options.draggable&&(b.series.onMouseDown(b,c),p=k(a.container,"mousemove",function(a){return b&&b.series&&b.series.onMouseMove(b,a)}),v=k(a.container.ownerDocument,
"mouseup",function(a){p();v();return b&&b.series&&b.series.onMouseUp(b,a)}))}));k(a,"destroy",function(){c()})})});B(c,"parts-more/PackedBubbleSeries.js",[c["parts/Globals.js"],c["parts/Color.js"],c["parts/Point.js"],c["parts/Utilities.js"]],function(c,a,p,b){var g=a.parse,k=b.addEvent,v=b.clamp,E=b.defined,C=b.extend;a=b.extendClass;var f=b.fireEvent,r=b.isArray,w=b.isNumber,z=b.merge,h=b.pick;b=b.seriesType;var A=c.Series,y=c.Chart,q=c.layouts["reingold-fruchterman"],l=c.seriesTypes.bubble.prototype.pointClass,
e=c.dragNodesMixin;c.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,c,b,e){return Math.min(a,(b.marker.radius+e.marker.radius)/2)},barycenter:function(){var a=this,c=a.options.gravitationalConstant,b=a.box,e=a.nodes,f,g;e.forEach(function(d){a.options.splitSeries&&!d.isParentNode?(f=d.series.parentNode.plotX,g=d.series.parentNode.plotY):(f=b.width/2,g=b.height/2);d.fixedPosition||(d.plotX-=(d.plotX-f)*c/(d.mass*Math.sqrt(e.length)),d.plotY-=(d.plotY-g)*c/(d.mass*Math.sqrt(e.length)))})},
repulsive:function(a,c,b,e){var d=c*this.diffTemperature/a.mass/a.degree;c=b.x*d;b=b.y*d;a.fixedPosition||(a.plotX+=c,a.plotY+=b);e.fixedPosition||(e.plotX-=c,e.plotY-=b)},integrate:c.networkgraphIntegrations.verlet.integrate,getK:c.noop};c.layouts.packedbubble=a(q,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,c=a.box,b=a.nodes,e=2*Math.PI/(b.length+1),f,g,k=a.options.initialPositionRadius;b.forEach(function(d,
b){a.options.splitSeries&&!d.isParentNode?(f=d.series.parentNode.plotX,g=d.series.parentNode.plotY):(f=c.width/2,g=c.height/2);d.plotX=d.prevX=h(d.plotX,f+k*Math.cos(d.index||b*e));d.plotY=d.prevY=h(d.plotY,g+k*Math.sin(d.index||b*e));d.dispX=0;d.dispY=0})},repulsiveForces:function(){var a=this,c,b,e,f=a.options.bubblePadding;a.nodes.forEach(function(d){d.degree=d.mass;d.neighbours=0;a.nodes.forEach(function(m){c=0;d===m||d.fixedPosition||!a.options.seriesInteraction&&d.series!==m.series||(e=a.getDistXY(d,
m),b=a.vectorLength(e)-(d.marker.radius+m.marker.radius+f),0>b&&(d.degree+=.01,d.neighbours++,c=a.repulsiveForce(-b/Math.sqrt(d.neighbours),a.k,d,m)),a.force("repulsive",d,c*m.mass,e,m,b))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var d=this.getDistXY(a,a.series.parentNode);var b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(d);0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*d.x,a.plotY-=.01*d.y)}q.prototype.applyLimitBox.apply(this,
arguments)}});b("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,
parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,requireSorting:!1,directTouch:!0,
axisTypes:[],noSharedTooltip:!0,searchPoint:c.noop,accumulateAllPoints:function(a){var d=a.chart,b=[],c,e;for(c=0;c<d.series.length;c++)if(a=d.series[c],a.visible||!d.options.chart.ignoreHiddenSeries)for(e=0;e<a.yData.length;e++)b.push([null,null,a.yData[e],a.index,e,{id:e,marker:{radius:0}}]);return b},init:function(){A.prototype.init.apply(this,arguments);k(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},render:function(){var a=
[];A.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(d){r(d.dataLabels)&&d.dataLabels.forEach(function(d){a.push(d)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;A.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,
a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(d){a.layout.removeElementFromCollection(d,a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;A.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,
A.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,c=Math.min,e,f=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){E(a.plotX)&&E(a.plotY)&&a.marker.radius&&(e=a.marker.radius,f[0]=c(f[0],a.plotX-e),f[1]=b(f[1],a.plotX+e),f[2]=c(f[2],a.plotY-e),f[3]=b(f[3],a.plotY+e))});return w(f.width/f.height)?f:null},calculateParentRadius:function(){var a=this.seriesBox();
this.parentNodeRadius=v(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||g(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||
this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=z({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));
this.parentNode.graphic.attr(c)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,e,f=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(d){a.parentNodeMass+=Math.PI*Math.pow(d.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(d){d.seriesIndex===a.index&&(e=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);e||(f||(f=(new l).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,
isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(f.plotX=a.parentNode.plotX,f.plotY=a.parentNode.plotY),a.parentNode=f,c.addElementsToCollection([a],c.series),c.addElementsToCollection([f],c.nodes))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,e=this.chart.graphLayoutsLookup,f=z(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var n=b[a.type+"-series"];n||(b[a.type+"-series"]=n=new c.layouts[a.type],n.init(f),e.splice(n.index,
0,n));this.parentNodeLayout=n;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,e=this.chart.graphLayoutsLookup,f=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=e=[]);var n=b[a.type];n||(a.enableSimulation=E(f.forExport)?!f.forExport:a.enableSimulation,b[a.type]=n=new c.layouts[a.type],n.init(a),e.splice(n.index,0,n));this.layout=n;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=
1});n.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);n.addElementsToCollection([this],n.series);n.addElementsToCollection(this.points,n.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,c=this.index,e,n=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();E(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());
if(n)var g=a.allDataPoints;else g=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(e=0;e<g.length;e++)if(g[e][3]===c){var h=b[g[e][4]];var k=g[e][2];n||(h.plotX=g[e][0]-a.plotLeft+a.diffX,h.plotY=g[e][1]-a.plotTop+a.diffY);h.marker=C(h.marker,{radius:k,width:2*k,height:2*k});h.radius=k}n&&this.deferLayout();f(this,"afterTranslate")},checkOverlap:function(a,b){var d=a[0]-b[0],c=a[1]-b[1];return-.001>Math.sqrt(d*d+c*c)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,c){var d=Math.sqrt,
e=Math.asin,f=Math.acos,m=Math.pow,g=Math.abs;d=d(m(a[0]-b[0],2)+m(a[1]-b[1],2));f=f((m(d,2)+m(c[2]+b[2],2)-m(c[2]+a[2],2))/(2*(c[2]+b[2])*d));e=e(g(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+f+e*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var d=this.checkOverlap,b=this.positionBubble,c=[],e=1,f=0,g=0;var h=[];var k;a=a.sort(function(a,d){return d[2]-a[2]});if(a.length){c.push([[0,0,a[0][2],a[0][3],a[0][4]]]);
if(1<a.length)for(c.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=a[k][2]||1,h=b(c[e][f],c[e-1][g],a[k]),d(h,c[e][0])?(c.push([]),g=0,c[e+1].push(b(c[e][f],c[e][0],a[k])),e++,f=0):1<e&&c[e-1][g+1]&&d(h,c[e-1][g+1])?(g++,c[e].push(b(c[e][f],c[e-1][g],a[k])),f++):(f++,c[e].push(h));this.chart.stages=c;this.chart.rawPositions=[].concat.apply([],c);this.resizeRadius();h=this.chart.rawPositions}return h},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,
e=Math.max,f=a.plotLeft,g=a.plotTop,h=a.plotHeight,k=a.plotWidth,l,p,q;var r=l=Number.POSITIVE_INFINITY;var v=p=Number.NEGATIVE_INFINITY;for(q=0;q<b.length;q++){var u=b[q][2];r=c(r,b[q][0]-u);v=e(v,b[q][0]+u);l=c(l,b[q][1]-u);p=e(p,b[q][1]+u)}q=[v-r,p-l];c=c.apply([],[(k-f)/q[0],(h-g)/q[1]]);if(1e-10<Math.abs(c-1)){for(q=0;q<b.length;q++)b[q][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+g-l-(p-l)/2,a.diffX=k/2+f-r-(v-r)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,c=
Infinity,e=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){E(a)&&(a>e&&(e=a),a<c&&(c=a))})});a=h(a,c);b=h(b,e);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,e=c.useSimulation,f=Math.min(b.plotWidth,b.plotHeight),g={},h=[],k=b.allDataPoints,l,p,q,r;["minSize","maxSize"].forEach(function(a){var d=parseInt(c[a],10),b=/%$/.test(c[a]);g[a]=b?f*d/100:d*Math.sqrt(k.length)});b.minRadius=l=g.minSize/Math.sqrt(k.length);b.maxRadius=
p=g.maxSize/Math.sqrt(k.length);var u=e?a.calculateZExtremes():[l,p];(k||[]).forEach(function(d,b){q=e?v(d[2],u[0],u[1]):d[2];r=a.getRadius(u[0],u[1],l,p,q);0===r&&(r=null);k[b][2]=r;h.push(r)});a.radii=h},redrawHalo:e.redrawHalo,onMouseDown:e.onMouseDown,onMouseMove:e.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var d,b,c=this.layout,f=this.parentNodeLayout;f&&c.options.dragBetweenSeries&&f.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(d=c.getDistXY(a,e),b=
c.vectorLength(d)-e.marker.radius-a.marker.radius,0>b&&(e.series.addPoint(z(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),c.removeElementFromCollection(a,c.nodes),a.remove()))});e.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&
(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));c.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:c.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return p.prototype.destroy.apply(this,arguments)}});k(y,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});B(c,"parts-more/Polar.js",[c["parts/Globals.js"],c["parts-more/Pane.js"],c["parts/Pointer.js"],
c["parts/SVGRenderer.js"],c["parts/Utilities.js"]],function(c,a,p,b,g){var k=g.addEvent,v=g.animObject,E=g.defined,C=g.find,f=g.isNumber,r=g.pick,w=g.splat,z=g.uniqueKey,h=g.wrap,A=c.Series,y=c.seriesTypes,q=A.prototype;p=p.prototype;q.searchPointByAngle=function(a){var d=this.chart,b=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-b[0]-d.plotLeft,a.chartY-b[1]-d.plotTop)})};q.getConnectors=function(a,b,c,f){var d=f?1:0;var e=0<=b&&b<=a.length-1?b:0>b?
a.length-1+b:0;b=0>e-1?a.length-(1+d):e-1;d=e+1>a.length-1?d:e+1;var g=a[b];d=a[d];var m=g.plotX;g=g.plotY;var h=d.plotX;var k=d.plotY;d=a[e].plotX;e=a[e].plotY;m=(1.5*d+m)/2.5;g=(1.5*e+g)/2.5;h=(1.5*d+h)/2.5;var l=(1.5*e+k)/2.5;k=Math.sqrt(Math.pow(m-d,2)+Math.pow(g-e,2));var p=Math.sqrt(Math.pow(h-d,2)+Math.pow(l-e,2));m=Math.atan2(g-e,m-d);l=Math.PI/2+(m+Math.atan2(l-e,h-d))/2;Math.abs(m-l)>Math.PI/2&&(l-=Math.PI);m=d+Math.cos(l)*k;g=e+Math.sin(l)*k;h=d+Math.cos(Math.PI+l)*p;l=e+Math.sin(Math.PI+
l)*p;d={rightContX:h,rightContY:l,leftContX:m,leftContY:g,plotX:d,plotY:e};c&&(d.prevPointCont=this.getConnectors(a,b,!1,f));return d};q.toXY=function(a){var d=this.chart,b=this.xAxis;var c=this.yAxis;var e=a.plotX,f=a.plotY,g=a.series,h=d.inverted,k=a.y,l=h?e:c.len-f;h&&g&&!g.isRadialBar&&(a.plotY=f="number"===typeof k?c.translate(k)||0:0);a.rectPlotX=e;a.rectPlotY=f;c.center&&(l+=c.center[3]/2);c=h?c.postTranslate(f,l):b.postTranslate(e,l);a.plotX=a.polarPlotX=c.x-d.plotLeft;a.plotY=a.polarPlotY=
c.y-d.plotTop;this.kdByAngle?(d=(e/Math.PI*180+b.pane.options.startAngle)%360,0>d&&(d+=360),a.clientX=d):a.clientX=a.plotX};y.spline&&(h(y.spline.prototype,"getPointSpline",function(a,b,c,f){this.chart.polar?f?(a=this.getConnectors(b,f,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,f);return a}),y.areasplinerange&&(y.areasplinerange.prototype.getPointSpline=y.spline.prototype.getPointSpline));
k(A,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var b=this.points,f=b.length;f--;)this.toXY(b[f]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&b[f].y<this.yAxis.min&&(b[f].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(k(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;
this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=c.noop}})))}},{order:2});h(q,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var f=!0}b.forEach(function(a){"undefined"===
typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));f&&b.pop();return d});var l=function(a,b){var d=this,e=this.chart,f=this.options.animation,g=this.group,h=this.markerGroup,k=this.xAxis.center,l=e.plotLeft,p=e.plotTop,q,u,w,y;if(e.polar)if(d.isRadialBar)b||(d.startAngleRad=r(d.translatedThreshold,d.xAxis.startAngleRad),c.seriesTypes.pie.prototype.animate.call(d,b));else{if(e.renderer.isSVG)if(f=v(f),d.is("column")){if(!b){var A=k[3]/2;d.points.forEach(function(a){q=a.graphic;
w=(u=a.shapeArgs)&&u.r;y=u&&u.innerR;q&&u&&(q.attr({r:A,innerR:A}),q.animate({r:w,innerR:y},d.options.animation))})}}else b?(a={translateX:k[0]+l,translateY:k[1]+p,scaleX:.001,scaleY:.001},g.attr(a),h&&h.attr(a)):(a={translateX:l,translateY:p,scaleX:1,scaleY:1},g.animate(a,f),h&&h.animate(a,f))}else a.call(this,b)};h(q,"animate",l);y.column&&(A=y.arearange.prototype,y=y.column.prototype,y.polarArc=function(a,b,c,f){var d=this.xAxis.center,e=this.yAxis.len,g=d[3]/2;b=e-b+g;a=e-r(a,e)+g;this.yAxis.reversed&&
(0>b&&(b=g),0>a&&(a=g));return{x:d[0],y:d[1],r:b,innerR:a,start:c,end:f}},h(y,"animate",l),h(y,"translate",function(a){var b=this.options,c=b.stacking,e=this.chart,h=this.xAxis,k=this.yAxis,l=k.reversed,p=k.center,q=h.startAngleRad,r=h.endAngleRad-q;this.preventPostTranslate=!0;a.call(this);if(h.isRadial){a=this.points;h=a.length;var u=k.translate(k.min);var v=k.translate(k.max);b=b.threshold||0;if(e.inverted&&f(b)){var w=k.translate(b);E(w)&&(0>w?w=0:w>r&&(w=r),this.translatedThreshold=w+q)}for(;h--;){b=
a[h];var y=b.barX;var A=b.x;var C=b.y;b.shapeType="arc";if(e.inverted){b.plotY=k.translate(C);if(c&&k.stacking){if(C=k.stacking.stacks[(0>C?"-":"")+this.stackKey],this.visible&&C&&C[A]&&!b.isNull){var z=C[A].points[this.getStackIndicator(void 0,A,this.index).key];var B=k.translate(z[0]);z=k.translate(z[1]);E(B)&&(B=g.clamp(B,0,r))}}else B=w,z=b.plotY;B>z&&(z=[B,B=z][0]);if(!l)if(B<u)B=u;else if(z>v)z=v;else{if(z<u||B>v)B=z=0}else if(z>u)z=u;else if(B<v)B=v;else if(B>u||z<v)B=z=r;k.min>k.max&&(B=z=
l?r:0);B+=q;z+=q;p&&(b.barX=y+=p[3]/2);A=Math.max(y,0);C=Math.max(y+b.pointWidth,0);b.shapeArgs={x:p&&p[0],y:p&&p[1],r:C,innerR:A,start:B,end:z};b.opacity=B===z?0:void 0;b.plotY=(E(this.translatedThreshold)&&(B<this.translatedThreshold?B:z))-q}else B=y+q,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,B,B+b.pointWidth);this.toXY(b);e.inverted?(y=k.postTranslate(b.rectPlotY,y+b.pointWidth/2),b.tooltipPos=[y.x-e.plotLeft,y.y-e.plotTop]):b.tooltipPos=[b.plotX,b.plotY];p&&(b.ttBelow=b.plotY>p[1])}}}),y.findAlignments=
function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b},A&&(A.findAlignments=y.findAlignments),h(y,"alignDataLabel",function(a,b,c,f,g,h){var d=this.chart,e=r(f.inside,!!this.options.stacking);d.polar?(a=b.rectPlotX/Math.PI*180,d.inverted?(this.forceDL=d.isInsidePlot(b.plotX,Math.round(b.plotY),!1),e&&b.shapeArgs?(g=b.shapeArgs,g=this.yAxis.postTranslate((g.start+g.end)/
2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),g={x:g.x-d.plotLeft,y:g.y-d.plotTop}):b.tooltipPos&&(g={x:b.tooltipPos[0],y:b.tooltipPos[1]}),f.align=r(f.align,"center"),f.verticalAlign=r(f.verticalAlign,"middle")):this.findAlignments&&(f=this.findAlignments(a,f)),q.alignDataLabel.call(this,b,c,f,g,h),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,f,g,h)}));h(p,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=
a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});b.prototype.clipCircle=function(a,b,c,f){var d=z(),e=this.createElement("clipPath").attr({id:d}).add(this.defs);a=f?this.arc(a,b,c,f,0,2*Math.PI).add(e):this.circle(a,b,c).add(e);a.id=d;a.clipPath=e;return a};k(c.Chart,"getAxes",function(){this.pane||
(this.pane=[]);w(this.options.pane).forEach(function(b){new a(b,this)},this)});k(c.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});k(c.Series,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});h(c.Chart.prototype,"get",function(a,b){return C(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});B(c,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map