/*
 Highcharts JS v8.1.0 (2020-05-12)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(C){b(C);b.Highcharts=C;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function C(b,e,d,v){b.hasOwnProperty(e)||(b[e]=v.apply(null,d))}b=b?b._modules:{};C(b,"parts-3d/Math.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,e){var d=e.pick,v=b.deg2rad;b.perspective3D=function(d,
w,m){w=0<m&&m<Number.POSITIVE_INFINITY?m/(d.z+w.z+m):1;return{x:d.x*w,y:d.y*w}};b.perspective=function(u,w,m,e){var q=w.options.chart.options3d,t=d(e,m?w.inverted:!1),p={x:w.plotWidth/2,y:w.plotHeight/2,z:q.depth/2,vd:d(q.depth,1)*d(q.viewDistance,0)},y=w.scale3d||1;e=v*q.beta*(t?-1:1);q=v*q.alpha*(t?-1:1);var x=Math.cos(q),B=Math.cos(-e),c=Math.sin(q),n=Math.sin(-e);m||(p.x+=w.plotLeft,p.y+=w.plotTop);return u.map(function(a){var f=(t?a.y:a.x)-p.x;var h=(t?a.x:a.y)-p.y;a=(a.z||0)-p.z;f={x:B*f-n*
a,y:-c*n*f+x*h-B*c*a,z:x*n*f+c*h+x*B*a};h=b.perspective3D(f,p,p.vd);h.x=h.x*y+p.x;h.y=h.y*y+p.y;h.z=f.z*y+p.z;return{x:t?h.y:h.x,y:t?h.x:h.y,z:h.z}})};b.pointCameraDistance=function(u,w){var m=w.options.chart.options3d,b=w.plotWidth/2;w=w.plotHeight/2;m=d(m.depth,1)*d(m.viewDistance,0)+m.depth;return Math.sqrt(Math.pow(b-d(u.plotX,u.x),2)+Math.pow(w-d(u.plotY,u.y),2)+Math.pow(m-d(u.plotZ,u.z),2))};b.shapeArea=function(d){var u=0,m;for(m=0;m<d.length;m++){var b=(m+1)%d.length;u+=d[m].x*d[b].y-d[b].x*
d[m].y}return u/2};b.shapeArea3d=function(d,e,m){return b.shapeArea(b.perspective(d,e,m))}});C(b,"parts-3d/SVGRenderer.js",[b["parts/Color.js"],b["parts/Globals.js"],b["parts/SVGElement.js"],b["parts/SVGRenderer.js"],b["parts/Utilities.js"]],function(b,e,d,v,u){function w(a,c,g,f,n,r,h,l){var k=[],E=r-n;return r>n&&r-n>Math.PI/2+.0001?(k=k.concat(w(a,c,g,f,n,n+Math.PI/2,h,l)),k=k.concat(w(a,c,g,f,n+Math.PI/2,r,h,l))):r<n&&n-r>Math.PI/2+.0001?(k=k.concat(w(a,c,g,f,n,n-Math.PI/2,h,l)),k=k.concat(w(a,
c,g,f,n-Math.PI/2,r,h,l))):[["C",a+g*Math.cos(n)-g*z*E*Math.sin(n)+h,c+f*Math.sin(n)+f*z*E*Math.cos(n)+l,a+g*Math.cos(r)+g*z*E*Math.sin(r)+h,c+f*Math.sin(r)-f*z*E*Math.cos(r)+l,a+g*Math.cos(r)+h,c+f*Math.sin(r)+l]]}var m=b.parse,A=u.animObject,q=u.defined,t=u.extend,p=u.merge,y=u.objectEach,x=u.pick,B=Math.cos,c=Math.PI,n=Math.sin,a=e.charts,f=e.deg2rad,h=e.perspective;var z=4*(Math.sqrt(2)-1)/3/(c/2);v.prototype.toLinePath=function(a,c){var g=[];a.forEach(function(a){g.push(["L",a.x,a.y])});a.length&&
(g[0][0]="M",c&&g.push(["Z"]));return g};v.prototype.toLineSegments=function(a){var c=[],g=!0;a.forEach(function(a){c.push(g?["M",a.x,a.y]:["L",a.x,a.y]);g=!g});return c};v.prototype.face3d=function(c){var f=this,g=this.createElement("path");g.vertexes=[];g.insidePlotArea=!1;g.enabled=!0;g.attr=function(c){if("object"===typeof c&&(q(c.enabled)||q(c.vertexes)||q(c.insidePlotArea))){this.enabled=x(c.enabled,this.enabled);this.vertexes=x(c.vertexes,this.vertexes);this.insidePlotArea=x(c.insidePlotArea,
this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var g=h(this.vertexes,a[f.chartIndex],this.insidePlotArea),k=f.toLinePath(g,!0);g=e.shapeArea(g);g=this.enabled&&0<g?"visible":"hidden";c.d=k;c.visibility=g}return d.prototype.attr.apply(this,arguments)};g.animate=function(c){if("object"===typeof c&&(q(c.enabled)||q(c.vertexes)||q(c.insidePlotArea))){this.enabled=x(c.enabled,this.enabled);this.vertexes=x(c.vertexes,this.vertexes);this.insidePlotArea=x(c.insidePlotArea,
this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var g=h(this.vertexes,a[f.chartIndex],this.insidePlotArea),k=f.toLinePath(g,!0);g=e.shapeArea(g);g=this.enabled&&0<g?"visible":"hidden";c.d=k;this.attr("visibility",g)}return d.prototype.animate.apply(this,arguments)};return g.attr(c)};v.prototype.polyhedron=function(a){var c=this,g=this.g(),f=g.destroy;this.styledMode||g.attr({"stroke-linejoin":"round"});g.faces=[];g.destroy=function(){for(var a=0;a<g.faces.length;a++)g.faces[a].destroy();
return f.call(this)};g.attr=function(a,f,k,n){if("object"===typeof a&&q(a.faces)){for(;g.faces.length>a.faces.length;)g.faces.pop().destroy();for(;g.faces.length<a.faces.length;)g.faces.push(c.face3d().add(g));for(var r=0;r<a.faces.length;r++)c.styledMode&&delete a.faces[r].fill,g.faces[r].attr(a.faces[r],null,k,n);delete a.faces}return d.prototype.attr.apply(this,arguments)};g.animate=function(a,f,k){if(a&&a.faces){for(;g.faces.length>a.faces.length;)g.faces.pop().destroy();for(;g.faces.length<a.faces.length;)g.faces.push(c.face3d().add(g));
for(var n=0;n<a.faces.length;n++)g.faces[n].animate(a.faces[n],f,k);delete a.faces}return d.prototype.animate.apply(this,arguments)};return g.attr(a)};b={initArgs:function(a){var c=this,g=c.renderer,f=g[c.pathType+"Path"](a),k=f.zIndexes;c.parts.forEach(function(a){c[a]=g.path(f[a]).attr({"class":"highcharts-3d-"+a,zIndex:k[a]||0}).add(c)});c.attr({"stroke-linejoin":"round",zIndex:k.group});c.originalDestroy=c.destroy;c.destroy=c.destroyParts;c.forcedSides=f.forcedSides},singleSetterForParts:function(a,
c,g,f,n,r){var k={};f=[null,null,f||"attr",n,r];var h=g&&g.zIndexes;g?(h&&h.group&&this.attr({zIndex:h.group}),y(g,function(c,f){k[f]={};k[f][a]=c;h&&(k[f].zIndex=g.zIndexes[f]||0)}),f[1]=k):(k[a]=c,f[0]=k);return this.processParts.apply(this,f)},processParts:function(a,c,f,n,h){var g=this;g.parts.forEach(function(k){c&&(a=x(c[k],!1));if(!1!==a)g[k][f](a,n,h)});return g},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};var l=p(b,{parts:["front","top",
"side"],pathType:"cuboid",attr:function(a,c,f,n){if("string"===typeof a&&"undefined"!==typeof c){var g=a;a={};a[g]=c}return a.shapeArgs||q(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):d.prototype.attr.call(this,a,void 0,f,n)},animate:function(a,c,f){if(q(a.x)&&q(a.y)){a=this.renderer[this.pathType+"Path"](a);var g=a.forcedSides;this.singleSetterForParts("d",null,a,"animate",c,f);this.attr({zIndex:a.zIndexes.group});g!==this.forcedSides&&(this.forcedSides=
g,l.fillSetter.call(this,this.fill))}else d.prototype.animate.call(this,a,c,f);return this},fillSetter:function(a){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:a,top:m(a).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:m(a).brighten(0<=this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=a;return this}});v.prototype.elements3d={base:b,cuboid:l};v.prototype.element3d=function(a,c){var f=this.g();t(f,this.elements3d[a]);f.initArgs(c);
return f};v.prototype.cuboid=function(a){return this.element3d("cuboid",a)};v.prototype.cuboidPath=function(c){function f(a){return 0===l&&1<a&&6>a?{x:b[a].x,y:b[a].y+10,z:b[a].z}:b[0].x===b[7].x&&4<=a?{x:b[a].x+10,y:b[a].y,z:b[a].z}:0===B&&2>a||5<a?{x:b[a].x,y:b[a].y,z:b[a].z+10}:b[a]}function g(a){return b[a]}var n=c.x,k=c.y,r=c.z||0,l=c.height,z=c.width,B=c.depth,d=a[this.chartIndex],p=d.options.chart.options3d.alpha,m=0,b=[{x:n,y:k,z:r},{x:n+z,y:k,z:r},{x:n+z,y:k+l,z:r},{x:n,y:k+l,z:r},{x:n,y:k+
l,z:r+B},{x:n+z,y:k+l,z:r+B},{x:n+z,y:k,z:r+B},{x:n,y:k,z:r+B}],y=[];b=h(b,d,c.insidePlotArea);var u=function(a,c,n){var k=[[],-1],r=a.map(g),h=c.map(g);a=a.map(f);c=c.map(f);0>e.shapeArea(r)?k=[r,0]:0>e.shapeArea(h)?k=[h,1]:n&&(y.push(n),k=0>e.shapeArea(a)?[r,0]:0>e.shapeArea(c)?[h,1]:[r,0]);return k};var x=u([3,2,1,0],[7,6,5,4],"front");c=x[0];var t=x[1];x=u([1,6,7,0],[4,5,2,3],"top");z=x[0];var q=x[1];x=u([1,2,5,6],[0,7,4,3],"side");u=x[0];x=x[1];1===x?m+=1E6*(d.plotWidth-n):x||(m+=1E6*n);m+=10*
(!q||0<=p&&180>=p||360>p&&357.5<p?d.plotHeight-k:10+k);1===t?m+=100*r:t||(m+=100*(1E3-r));return{front:this.toLinePath(c,!0),top:this.toLinePath(z,!0),side:this.toLinePath(u,!0),zIndexes:{group:Math.round(m)},forcedSides:y,isFront:t,isTop:q}};v.prototype.arc3d=function(a){function c(a){var c=!1,f={},g;a=p(a);for(g in a)-1!==k.indexOf(g)&&(f[g]=a[g],delete a[g],c=!0);return c?f:!1}var g=this.g(),n=g.renderer,k="x y r innerR start end depth".split(" ");a=p(a);a.alpha=(a.alpha||0)*f;a.beta=(a.beta||
0)*f;g.top=n.path();g.side1=n.path();g.side2=n.path();g.inn=n.path();g.out=n.path();g.onAdd=function(){var a=g.parentGroup,c=g.attr("class");g.top.add(g);["out","inn","side1","side2"].forEach(function(f){g[f].attr({"class":c+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){g[a]=function(){var c=arguments;["top","out","inn","side1","side2"].forEach(function(f){g[f][a].apply(g[f],c)})}});g.setPaths=function(a){var c=g.renderer.arc3dPath(a),f=100*c.zTop;g.attribs=a;g.top.attr({d:c.top,
zIndex:c.zTop});g.inn.attr({d:c.inn,zIndex:c.zInn});g.out.attr({d:c.out,zIndex:c.zOut});g.side1.attr({d:c.side1,zIndex:c.zSide1});g.side2.attr({d:c.side2,zIndex:c.zSide2});g.zIndex=f;g.attr({zIndex:f});a.center&&(g.top.setRadialReference(a.center),delete a.center)};g.setPaths(a);g.fillSetter=function(a){var c=m(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:c});this.side2.attr({fill:c});this.inn.attr({fill:c});this.out.attr({fill:c});this.top.attr({fill:a});return this};["opacity","translateX",
"translateY","visibility"].forEach(function(a){g[a+"Setter"]=function(a,c){g[c]=a;["out","inn","side1","side2","top"].forEach(function(f){g[f].attr(c,a)})}});g.attr=function(a){var f;"object"===typeof a&&(f=c(a))&&(t(g.attribs,f),g.setPaths(g.attribs));return d.prototype.attr.apply(g,arguments)};g.animate=function(a,f,n){var k=this.attribs,h="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var l=A(x(f,this.renderer.globalAnimation));if(l.duration){var r=
c(a);g[h]=0;a[h]=1;g[h+"Setter"]=e.noop;r&&(l.step=function(a,c){function f(a){return k[a]+(x(r[a],k[a])-k[a])*c.pos}c.prop===h&&c.elem.setPaths(p(k,{x:f("x"),y:f("y"),r:f("r"),innerR:f("innerR"),start:f("start"),end:f("end"),depth:f("depth")}))});f=l}return d.prototype.animate.call(this,a,f,n)};g.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return d.prototype.destroy.call(this)};g.hide=function(){this.top.hide();this.out.hide();
this.inn.hide();this.side1.hide();this.side2.hide()};g.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return g};v.prototype.arc3dPath=function(a){function f(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var g=a.x,h=a.y,k=a.start,l=a.end-.00001,z=a.r,d=a.innerR||0,p=a.depth||0,b=a.alpha,m=a.beta,x=Math.cos(k),u=Math.sin(k);a=Math.cos(l);var y=Math.sin(l),t=z*Math.cos(m);z*=Math.cos(b);var e=d*Math.cos(m),q=d*Math.cos(b);d=p*Math.sin(m);
var v=p*Math.sin(b);p=[["M",g+t*x,h+z*u]];p=p.concat(w(g,h,t,z,k,l,0,0));p.push(["L",g+e*a,h+q*y]);p=p.concat(w(g,h,e,q,l,k,0,0));p.push(["Z"]);var A=0<m?Math.PI/2:0;m=0<b?0:Math.PI/2;A=k>-A?k:l>-A?-A:k;var D=l<c-m?l:k<c-m?c-m:l,C=2*c-m;b=[["M",g+t*B(A),h+z*n(A)]];b=b.concat(w(g,h,t,z,A,D,0,0));l>C&&k<C?(b.push(["L",g+t*B(D)+d,h+z*n(D)+v]),b=b.concat(w(g,h,t,z,D,C,d,v)),b.push(["L",g+t*B(C),h+z*n(C)]),b=b.concat(w(g,h,t,z,C,l,0,0)),b.push(["L",g+t*B(l)+d,h+z*n(l)+v]),b=b.concat(w(g,h,t,z,l,C,d,v)),
b.push(["L",g+t*B(C),h+z*n(C)]),b=b.concat(w(g,h,t,z,C,D,0,0))):l>c-m&&k<c-m&&(b.push(["L",g+t*Math.cos(D)+d,h+z*Math.sin(D)+v]),b=b.concat(w(g,h,t,z,D,l,d,v)),b.push(["L",g+t*Math.cos(l),h+z*Math.sin(l)]),b=b.concat(w(g,h,t,z,l,D,0,0)));b.push(["L",g+t*Math.cos(D)+d,h+z*Math.sin(D)+v]);b=b.concat(w(g,h,t,z,D,A,d,v));b.push(["Z"]);m=[["M",g+e*x,h+q*u]];m=m.concat(w(g,h,e,q,k,l,0,0));m.push(["L",g+e*Math.cos(l)+d,h+q*Math.sin(l)+v]);m=m.concat(w(g,h,e,q,l,k,d,v));m.push(["Z"]);x=[["M",g+t*x,h+z*u],
["L",g+t*x+d,h+z*u+v],["L",g+e*x+d,h+q*u+v],["L",g+e*x,h+q*u],["Z"]];g=[["M",g+t*a,h+z*y],["L",g+t*a+d,h+z*y+v],["L",g+e*a+d,h+q*y+v],["L",g+e*a,h+q*y],["Z"]];y=Math.atan2(v,-d);h=Math.abs(l+y);a=Math.abs(k+y);k=Math.abs((k+l)/2+y);h=f(h);a=f(a);k=f(k);k*=1E5;l=1E5*a;h*=1E5;return{top:p,zTop:1E5*Math.PI+1,out:b,zOut:Math.max(k,l,h),inn:m,zInn:Math.max(k,l,h),side1:x,zSide1:.99*h,side2:g,zSide2:.99*l}}});C(b,"parts-3d/Tick3D.js",[b["parts/Utilities.js"]],function(b){var e=b.addEvent,d=b.extend,v=b.wrap;
return function(){function b(){}b.compose=function(d){e(d,"afterGetLabelPosition",b.onAfterGetLabelPosition);v(d.prototype,"getMarkPath",b.wrapGetMarkPath)};b.onAfterGetLabelPosition=function(b){var m=this.axis.axis3D;m&&d(b.pos,m.fix3dPosition(b.pos))};b.wrapGetMarkPath=function(b){var d=this.axis.axis3D,e=b.apply(this,[].slice.call(arguments,1));if(d){var q=e[0],t=e[1];if("M"===q[0]&&"L"===t[0])return d=[d.fix3dPosition({x:q[1],y:q[2],z:0}),d.fix3dPosition({x:t[1],y:t[2],z:0})],this.axis.chart.renderer.toLineSegments(d)}return e};
return b}()});C(b,"parts-3d/Axis3D.js",[b["parts/Globals.js"],b["parts/Tick.js"],b["parts-3d/Tick3D.js"],b["parts/Utilities.js"]],function(b,e,d,v){var u=v.addEvent,w=v.merge,m=v.pick,A=v.wrap,q=b.deg2rad,t=b.perspective,p=b.perspective3D,y=b.shapeArea,x=function(){function b(c){this.axis=c}b.prototype.fix3dPosition=function(c,n){var a=this.axis,f=a.chart;if("colorAxis"===a.coll||!f.is3d())return c;var h=q*f.options.chart.options3d.alpha,b=q*f.options.chart.options3d.beta,l=m(n&&a.options.title.position3d,
a.options.labels.position3d);n=m(n&&a.options.title.skew3d,a.options.labels.skew3d);var k=f.frame3d,d=f.plotLeft,g=f.plotWidth+d,B=f.plotTop,p=f.plotHeight+B;f=!1;var r=0,x=0,e={x:0,y:1,z:0};c=a.axis3D.swapZ({x:c.x,y:c.y,z:0});if(a.isZAxis)if(a.opposite){if(null===k.axes.z.top)return{};x=c.y-B;c.x=k.axes.z.top.x;c.y=k.axes.z.top.y;d=k.axes.z.top.xDir;f=!k.top.frontFacing}else{if(null===k.axes.z.bottom)return{};x=c.y-p;c.x=k.axes.z.bottom.x;c.y=k.axes.z.bottom.y;d=k.axes.z.bottom.xDir;f=!k.bottom.frontFacing}else if(a.horiz)if(a.opposite){if(null===
k.axes.x.top)return{};x=c.y-B;c.y=k.axes.x.top.y;c.z=k.axes.x.top.z;d=k.axes.x.top.xDir;f=!k.top.frontFacing}else{if(null===k.axes.x.bottom)return{};x=c.y-p;c.y=k.axes.x.bottom.y;c.z=k.axes.x.bottom.z;d=k.axes.x.bottom.xDir;f=!k.bottom.frontFacing}else if(a.opposite){if(null===k.axes.y.right)return{};r=c.x-g;c.x=k.axes.y.right.x;c.z=k.axes.y.right.z;d=k.axes.y.right.xDir;d={x:d.z,y:d.y,z:-d.x}}else{if(null===k.axes.y.left)return{};r=c.x-d;c.x=k.axes.y.left.x;c.z=k.axes.y.left.z;d=k.axes.y.left.xDir}"chart"!==
l&&("flap"===l?a.horiz?(b=Math.sin(h),h=Math.cos(h),a.opposite&&(b=-b),f&&(b=-b),e={x:d.z*b,y:h,z:-d.x*b}):d={x:Math.cos(b),y:0,z:Math.sin(b)}:"ortho"===l?a.horiz?(e=Math.cos(h),l=Math.sin(b)*e,h=-Math.sin(h),b=-e*Math.cos(b),e={x:d.y*b-d.z*h,y:d.z*l-d.x*b,z:d.x*h-d.y*l},h=1/Math.sqrt(e.x*e.x+e.y*e.y+e.z*e.z),f&&(h=-h),e={x:h*e.x,y:h*e.y,z:h*e.z}):d={x:Math.cos(b),y:0,z:Math.sin(b)}:a.horiz?e={x:Math.sin(b)*Math.sin(h),y:Math.cos(h),z:-Math.cos(b)*Math.sin(h)}:d={x:Math.cos(b),y:0,z:Math.sin(b)});
c.x+=r*d.x+x*e.x;c.y+=r*d.y+x*e.y;c.z+=r*d.z+x*e.z;f=t([c],a.chart)[0];n&&(0>y(t([c,{x:c.x+d.x,y:c.y+d.y,z:c.z+d.z},{x:c.x+e.x,y:c.y+e.y,z:c.z+e.z}],a.chart))&&(d={x:-d.x,y:-d.y,z:-d.z}),c=t([{x:c.x,y:c.y,z:c.z},{x:c.x+d.x,y:c.y+d.y,z:c.z+d.z},{x:c.x+e.x,y:c.y+e.y,z:c.z+e.z}],a.chart),f.matrix=[c[1].x-c[0].x,c[1].y-c[0].y,c[2].x-c[0].x,c[2].y-c[0].y,f.x,f.y],f.matrix[4]-=f.x*f.matrix[0]+f.y*f.matrix[2],f.matrix[5]-=f.x*f.matrix[1]+f.y*f.matrix[3]);return f};b.prototype.swapZ=function(c,n){var a=this.axis;
return a.isZAxis?(n=n?0:a.chart.plotLeft,{x:n+c.z,y:c.y,z:c.x-n}):c};return b}();return function(){function b(){}b.compose=function(c){w(!0,c.defaultOptions,b.defaultOptions);c.keepProps.push("axis3D");u(c,"init",b.onInit);u(c,"afterSetOptions",b.onAfterSetOptions);u(c,"drawCrosshair",b.onDrawCrosshair);u(c,"destroy",b.onDestroy);c=c.prototype;A(c,"getLinePath",b.wrapGetLinePath);A(c,"getPlotBandPath",b.wrapGetPlotBandPath);A(c,"getPlotLinePath",b.wrapGetPlotLinePath);A(c,"getSlotWidth",b.wrapGetSlotWidth);
A(c,"getTitlePosition",b.wrapGetTitlePosition);d.compose(e)};b.onAfterSetOptions=function(){var c=this.chart,n=this.options;c.is3d&&c.is3d()&&"colorAxis"!==this.coll&&(n.tickWidth=m(n.tickWidth,0),n.gridLineWidth=m(n.gridLineWidth,1))};b.onDestroy=function(){["backFrame","bottomFrame","sideFrame"].forEach(function(c){this[c]&&(this[c]=this[c].destroy())},this)};b.onDrawCrosshair=function(c){this.chart.is3d()&&"colorAxis"!==this.coll&&c.point&&(c.point.crosshairPos=this.isXAxis?c.point.axisXpos:this.len-
c.point.axisYpos)};b.onInit=function(){this.axis3D||(this.axis3D=new x(this))};b.wrapGetLinePath=function(c){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:c.apply(this,[].slice.call(arguments,1))};b.wrapGetPlotBandPath=function(c){if(!this.chart.is3d()||"colorAxis"===this.coll)return c.apply(this,[].slice.call(arguments,1));var n=arguments,a=n[2],f=[];n=this.getPlotLinePath({value:n[1]});a=this.getPlotLinePath({value:a});if(n&&a)for(var h=0;h<n.length;h+=2){var b=n[h],d=n[h+1],k=a[h],e=a[h+
1];"M"===b[0]&&"L"===d[0]&&"M"===k[0]&&"L"===e[0]&&f.push(b,d,e,["L",k[1],k[2]],["Z"])}return f};b.wrapGetPlotLinePath=function(c){var n=this.axis3D,a=this.chart,f=c.apply(this,[].slice.call(arguments,1));if(!a.is3d()||"colorAxis"===this.coll||null===f)return f;var h=a.options.chart.options3d,b=this.isZAxis?a.plotWidth:h.depth;h=a.frame3d;var d=f[0],k=f[1];f=[];"M"===d[0]&&"L"===k[0]&&(n=[n.swapZ({x:d[1],y:d[2],z:0}),n.swapZ({x:d[1],y:d[2],z:b}),n.swapZ({x:k[1],y:k[2],z:0}),n.swapZ({x:k[1],y:k[2],
z:b})],this.horiz?(this.isZAxis?(h.left.visible&&f.push(n[0],n[2]),h.right.visible&&f.push(n[1],n[3])):(h.front.visible&&f.push(n[0],n[2]),h.back.visible&&f.push(n[1],n[3])),h.top.visible&&f.push(n[0],n[1]),h.bottom.visible&&f.push(n[2],n[3])):(h.front.visible&&f.push(n[0],n[2]),h.back.visible&&f.push(n[1],n[3]),h.left.visible&&f.push(n[0],n[1]),h.right.visible&&f.push(n[2],n[3])),f=t(f,this.chart,!1));return a.renderer.toLineSegments(f)};b.wrapGetSlotWidth=function(c,n){var a=this.chart,f=this.ticks,
h=this.gridGroup;if(this.categories&&a.frameShapes&&a.is3d()&&h&&n&&n.label){h=h.element.childNodes[0].getBBox();var b=a.frameShapes.left.getBBox(),d=a.options.chart.options3d;a={x:a.plotWidth/2,y:a.plotHeight/2,z:d.depth/2,vd:m(d.depth,1)*m(d.viewDistance,0)};var k,e;d=n.pos;var g=f[d-1];f=f[d+1];0!==d&&g&&g.label.xy&&(k=p({x:g.label.xy.x,y:g.label.xy.y,z:null},a,a.vd));f&&f.label.xy&&(e=p({x:f.label.xy.x,y:f.label.xy.y,z:null},a,a.vd));f={x:n.label.xy.x,y:n.label.xy.y,z:null};f=p(f,a,a.vd);return Math.abs(k?
f.x-k.x:e?e.x-f.x:h.x-b.x)}return c.apply(this,[].slice.call(arguments,1))};b.wrapGetTitlePosition=function(c){var n=c.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(n,!0):n};b.defaultOptions={labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}};return b}()});C(b,"parts-3d/ZAxis.js",[b["parts/Axis.js"],b["parts/Utilities.js"]],function(b,e){var d=this&&this.__extends||function(){var b=function(d,e){b=Object.setPrototypeOf||{__proto__:[]}instanceof
Array&&function(b,d){b.__proto__=d}||function(b,d){for(var c in d)d.hasOwnProperty(c)&&(b[c]=d[c])};return b(d,e)};return function(d,e){function p(){this.constructor=d}b(d,e);d.prototype=null===e?Object.create(e):(p.prototype=e.prototype,new p)}}(),v=e.addEvent,u=e.merge,w=e.pick,m=e.splat,A=function(){function b(){}b.compose=function(d){v(d,"afterGetAxes",b.onAfterGetAxes);d=d.prototype;d.addZAxis=b.wrapAddZAxis;d.collectionsWithInit.zAxis=[d.addZAxis];d.collectionsWithUpdate.push("zAxis")};b.onAfterGetAxes=
function(){var b=this,d=this.options;d=d.zAxis=m(d.zAxis||{});b.is3d()&&(b.zAxis=[],d.forEach(function(d,e){d.index=e;d.isX=!0;b.addZAxis(d).setScale()}))};b.wrapAddZAxis=function(b){return new q(this,b)};return b}(),q=function(b){function e(d,e){d=b.call(this,d,e)||this;d.isZAxis=!0;return d}d(e,b);e.prototype.getSeriesExtremes=function(){var b=this,d=b.chart;b.hasVisibleSeries=!1;b.dataMin=b.dataMax=b.ignoreMinPadding=b.ignoreMaxPadding=void 0;b.stacking&&b.stacking.buildStacks();b.series.forEach(function(e){!e.visible&&
d.options.chart&&d.options.chart.ignoreHiddenSeries||(b.hasVisibleSeries=!0,e=e.zData,e.length&&(b.dataMin=Math.min(w(b.dataMin,e[0]),Math.min.apply(null,e)),b.dataMax=Math.max(w(b.dataMax,e[0]),Math.max.apply(null,e))))})};e.prototype.setAxisSize=function(){var d=this.chart;b.prototype.setAxisSize.call(this);this.width=this.len=d.options.chart&&d.options.chart.options3d&&d.options.chart.options3d.depth||0;this.right=d.chartWidth-this.width-this.left};e.prototype.setOptions=function(d){d=u({offset:0,
lineWidth:0},d);b.prototype.setOptions.call(this,d);this.coll="zAxis"};e.ZChartComposition=A;return e}(b);return q});C(b,"parts-3d/Chart.js",[b["parts/Axis.js"],b["parts-3d/Axis3D.js"],b["parts/Globals.js"],b["parts/Utilities.js"],b["parts-3d/ZAxis.js"]],function(b,e,d,v,u){function w(c,b){var a=c.plotLeft,f=c.plotWidth+a,d=c.plotTop,n=c.plotHeight+d,l=a+c.plotWidth/2,k=d+c.plotHeight/2,e=Number.MAX_VALUE,g=-Number.MAX_VALUE,m=Number.MAX_VALUE,p=-Number.MAX_VALUE,r=1;var q=[{x:a,y:d,z:0},{x:a,y:d,
z:b}];[0,1].forEach(function(a){q.push({x:f,y:q[a].y,z:q[a].z})});[0,1,2,3].forEach(function(a){q.push({x:q[a].x,y:n,z:q[a].z})});q=x(q,c,!1);q.forEach(function(a){e=Math.min(e,a.x);g=Math.max(g,a.x);m=Math.min(m,a.y);p=Math.max(p,a.y)});a>e&&(r=Math.min(r,1-Math.abs((a+l)/(e+l))%1));f<g&&(r=Math.min(r,(f-l)/(g-l)));d>m&&(r=0>m?Math.min(r,(d+k)/(-m+d+k)):Math.min(r,1-(d+k)/(m+k)%1));n<p&&(r=Math.min(r,Math.abs((n-k)/(p-k))));return r}var m=v.addEvent,A=v.Fx,q=v.isArray,t=v.merge,p=v.pick;v=v.wrap;
var y=d.Chart,x=d.perspective;y.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};y.prototype.propsRequireDirtyBox.push("chart.options3d");y.prototype.propsRequireUpdateSeries.push("chart.options3d");m(y,"afterInit",function(){var c=this.options;this.is3d()&&(c.series||[]).forEach(function(b){"scatter"===(b.type||c.chart.type||c.chart.defaultSeriesType)&&(b.type="scatter3d")})});m(y,"addSeries",function(c){this.is3d()&&"scatter"===c.options.type&&
(c.options.type="scatter3d")});v(d.Chart.prototype,"isInsidePlot",function(c){return this.is3d()||c.apply(this,[].slice.call(arguments,1))});var B=d.getOptions();t(!0,B,{chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});m(y,"afterGetContainer",function(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),
[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(c){this.renderer.definition({tagName:"filter",id:"highcharts-"+c.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",slope:c.slope},{tagName:"feFuncG",type:"linear",slope:c.slope},{tagName:"feFuncB",type:"linear",slope:c.slope}]}]})},this))});v(y.prototype,"setClassName",function(c){c.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")});m(d.Chart,
"afterSetChartSize",function(){var c=this.options.chart.options3d;if(this.is3d()){c&&(c.alpha=c.alpha%360+(0<=c.alpha?0:360),c.beta=c.beta%360+(0<=c.beta?0:360));var b=this.inverted,a=this.clipBox,f=this.margin;a[b?"y":"x"]=-(f[3]||0);a[b?"x":"y"]=-(f[0]||0);a[b?"height":"width"]=this.chartWidth+(f[3]||0)+(f[1]||0);a[b?"width":"height"]=this.chartHeight+(f[0]||0)+(f[2]||0);this.scale3d=1;!0===c.fitToPlot&&(this.scale3d=w(this,c.depth));this.frame3d=this.get3dFrame()}});m(y,"beforeRedraw",function(){this.is3d()&&
(this.isDirtyBox=!0)});m(y,"beforeRender",function(){this.is3d()&&(this.frame3d=this.get3dFrame())});v(y.prototype,"renderSeries",function(c){var b=this.series.length;if(this.is3d())for(;b--;)c=this.series[b],c.translate(),c.render();else c.call(this)});m(y,"afterDrawChartBox",function(){if(this.is3d()){var c=this.renderer,b=this.options.chart.options3d,a=this.get3dFrame(),f=this.plotLeft,h=this.plotLeft+this.plotWidth,e=this.plotTop,l=this.plotTop+this.plotHeight;b=b.depth;var k=f-(a.left.visible?
a.left.size:0),m=h+(a.right.visible?a.right.size:0),g=e-(a.top.visible?a.top.size:0),q=l+(a.bottom.visible?a.bottom.size:0),p=0-(a.front.visible?a.front.size:0),r=b+(a.back.visible?a.back.size:0),x=this.hasRendered?"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:c.polyhedron().add(),top:c.polyhedron().add(),left:c.polyhedron().add(),right:c.polyhedron().add(),back:c.polyhedron().add(),front:c.polyhedron().add()});this.frameShapes.bottom[x]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",
zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:d.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:k,y:q,z:p},{x:m,y:q,z:p},{x:m,y:q,z:r},{x:k,y:q,z:r}],enabled:a.bottom.visible},{fill:d.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:f,y:l,z:b},{x:h,y:l,z:b},{x:h,y:l,z:0},{x:f,y:l,z:0}],enabled:a.bottom.visible},{fill:d.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:k,y:q,z:p},{x:k,y:q,z:r},{x:f,y:l,z:b},{x:f,y:l,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:d.color(a.bottom.color).brighten(-.1).get(),
vertexes:[{x:m,y:q,z:r},{x:m,y:q,z:p},{x:h,y:l,z:0},{x:h,y:l,z:b}],enabled:a.bottom.visible&&!a.right.visible},{fill:d.color(a.bottom.color).get(),vertexes:[{x:m,y:q,z:p},{x:k,y:q,z:p},{x:f,y:l,z:0},{x:h,y:l,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:d.color(a.bottom.color).get(),vertexes:[{x:k,y:q,z:r},{x:m,y:q,z:r},{x:h,y:l,z:b},{x:f,y:l,z:b}],enabled:a.bottom.visible&&!a.back.visible}]});this.frameShapes.top[x]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?
-1E3:1E3,faces:[{fill:d.color(a.top.color).brighten(.1).get(),vertexes:[{x:k,y:g,z:r},{x:m,y:g,z:r},{x:m,y:g,z:p},{x:k,y:g,z:p}],enabled:a.top.visible},{fill:d.color(a.top.color).brighten(.1).get(),vertexes:[{x:f,y:e,z:0},{x:h,y:e,z:0},{x:h,y:e,z:b},{x:f,y:e,z:b}],enabled:a.top.visible},{fill:d.color(a.top.color).brighten(-.1).get(),vertexes:[{x:k,y:g,z:r},{x:k,y:g,z:p},{x:f,y:e,z:0},{x:f,y:e,z:b}],enabled:a.top.visible&&!a.left.visible},{fill:d.color(a.top.color).brighten(-.1).get(),vertexes:[{x:m,
y:g,z:p},{x:m,y:g,z:r},{x:h,y:e,z:b},{x:h,y:e,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:d.color(a.top.color).get(),vertexes:[{x:k,y:g,z:p},{x:m,y:g,z:p},{x:h,y:e,z:0},{x:f,y:e,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:d.color(a.top.color).get(),vertexes:[{x:m,y:g,z:r},{x:k,y:g,z:r},{x:f,y:e,z:b},{x:h,y:e,z:b}],enabled:a.top.visible&&!a.back.visible}]});this.frameShapes.left[x]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:d.color(a.left.color).brighten(.1).get(),
vertexes:[{x:k,y:q,z:p},{x:f,y:l,z:0},{x:f,y:l,z:b},{x:k,y:q,z:r}],enabled:a.left.visible&&!a.bottom.visible},{fill:d.color(a.left.color).brighten(.1).get(),vertexes:[{x:k,y:g,z:r},{x:f,y:e,z:b},{x:f,y:e,z:0},{x:k,y:g,z:p}],enabled:a.left.visible&&!a.top.visible},{fill:d.color(a.left.color).brighten(-.1).get(),vertexes:[{x:k,y:q,z:r},{x:k,y:g,z:r},{x:k,y:g,z:p},{x:k,y:q,z:p}],enabled:a.left.visible},{fill:d.color(a.left.color).brighten(-.1).get(),vertexes:[{x:f,y:e,z:b},{x:f,y:l,z:b},{x:f,y:l,z:0},
{x:f,y:e,z:0}],enabled:a.left.visible},{fill:d.color(a.left.color).get(),vertexes:[{x:k,y:q,z:p},{x:k,y:g,z:p},{x:f,y:e,z:0},{x:f,y:l,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:d.color(a.left.color).get(),vertexes:[{x:k,y:g,z:r},{x:k,y:q,z:r},{x:f,y:l,z:b},{x:f,y:e,z:b}],enabled:a.left.visible&&!a.back.visible}]});this.frameShapes.right[x]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:d.color(a.right.color).brighten(.1).get(),
vertexes:[{x:m,y:q,z:r},{x:h,y:l,z:b},{x:h,y:l,z:0},{x:m,y:q,z:p}],enabled:a.right.visible&&!a.bottom.visible},{fill:d.color(a.right.color).brighten(.1).get(),vertexes:[{x:m,y:g,z:p},{x:h,y:e,z:0},{x:h,y:e,z:b},{x:m,y:g,z:r}],enabled:a.right.visible&&!a.top.visible},{fill:d.color(a.right.color).brighten(-.1).get(),vertexes:[{x:h,y:e,z:0},{x:h,y:l,z:0},{x:h,y:l,z:b},{x:h,y:e,z:b}],enabled:a.right.visible},{fill:d.color(a.right.color).brighten(-.1).get(),vertexes:[{x:m,y:q,z:p},{x:m,y:g,z:p},{x:m,y:g,
z:r},{x:m,y:q,z:r}],enabled:a.right.visible},{fill:d.color(a.right.color).get(),vertexes:[{x:m,y:g,z:p},{x:m,y:q,z:p},{x:h,y:l,z:0},{x:h,y:e,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:d.color(a.right.color).get(),vertexes:[{x:m,y:q,z:r},{x:m,y:g,z:r},{x:h,y:e,z:b},{x:h,y:l,z:b}],enabled:a.right.visible&&!a.back.visible}]});this.frameShapes.back[x]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:d.color(a.back.color).brighten(.1).get(),
vertexes:[{x:m,y:q,z:r},{x:k,y:q,z:r},{x:f,y:l,z:b},{x:h,y:l,z:b}],enabled:a.back.visible&&!a.bottom.visible},{fill:d.color(a.back.color).brighten(.1).get(),vertexes:[{x:k,y:g,z:r},{x:m,y:g,z:r},{x:h,y:e,z:b},{x:f,y:e,z:b}],enabled:a.back.visible&&!a.top.visible},{fill:d.color(a.back.color).brighten(-.1).get(),vertexes:[{x:k,y:q,z:r},{x:k,y:g,z:r},{x:f,y:e,z:b},{x:f,y:l,z:b}],enabled:a.back.visible&&!a.left.visible},{fill:d.color(a.back.color).brighten(-.1).get(),vertexes:[{x:m,y:g,z:r},{x:m,y:q,
z:r},{x:h,y:l,z:b},{x:h,y:e,z:b}],enabled:a.back.visible&&!a.right.visible},{fill:d.color(a.back.color).get(),vertexes:[{x:f,y:e,z:b},{x:h,y:e,z:b},{x:h,y:l,z:b},{x:f,y:l,z:b}],enabled:a.back.visible},{fill:d.color(a.back.color).get(),vertexes:[{x:k,y:q,z:r},{x:m,y:q,z:r},{x:m,y:g,z:r},{x:k,y:g,z:r}],enabled:a.back.visible}]});this.frameShapes.front[x]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:d.color(a.front.color).brighten(.1).get(),
vertexes:[{x:k,y:q,z:p},{x:m,y:q,z:p},{x:h,y:l,z:0},{x:f,y:l,z:0}],enabled:a.front.visible&&!a.bottom.visible},{fill:d.color(a.front.color).brighten(.1).get(),vertexes:[{x:m,y:g,z:p},{x:k,y:g,z:p},{x:f,y:e,z:0},{x:h,y:e,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:d.color(a.front.color).brighten(-.1).get(),vertexes:[{x:k,y:g,z:p},{x:k,y:q,z:p},{x:f,y:l,z:0},{x:f,y:e,z:0}],enabled:a.front.visible&&!a.left.visible},{fill:d.color(a.front.color).brighten(-.1).get(),vertexes:[{x:m,y:q,z:p},{x:m,
y:g,z:p},{x:h,y:e,z:0},{x:h,y:l,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:d.color(a.front.color).get(),vertexes:[{x:h,y:e,z:0},{x:f,y:e,z:0},{x:f,y:l,z:0},{x:h,y:l,z:0}],enabled:a.front.visible},{fill:d.color(a.front.color).get(),vertexes:[{x:m,y:q,z:p},{x:k,y:q,z:p},{x:k,y:g,z:p},{x:m,y:g,z:p}],enabled:a.front.visible}]})}});y.prototype.retrieveStacks=function(c){var b=this.series,a={},f,d=1;this.series.forEach(function(h){f=p(h.options.stack,c?0:b.length-1-h.index);a[f]?a[f].series.push(h):
(a[f]={series:[h],position:d},d++)});a.totalStacks=d+1;return a};y.prototype.get3dFrame=function(){var c=this,b=c.options.chart.options3d,a=b.frame,f=c.plotLeft,h=c.plotLeft+c.plotWidth,e=c.plotTop,l=c.plotTop+c.plotHeight,k=b.depth,m=function(a){a=d.shapeArea3d(a,c);return.5<a?1:-.5>a?-1:0},g=m([{x:f,y:l,z:k},{x:h,y:l,z:k},{x:h,y:l,z:0},{x:f,y:l,z:0}]),q=m([{x:f,y:e,z:0},{x:h,y:e,z:0},{x:h,y:e,z:k},{x:f,y:e,z:k}]),t=m([{x:f,y:e,z:0},{x:f,y:e,z:k},{x:f,y:l,z:k},{x:f,y:l,z:0}]),r=m([{x:h,y:e,z:k},
{x:h,y:e,z:0},{x:h,y:l,z:0},{x:h,y:l,z:k}]),u=m([{x:f,y:l,z:0},{x:h,y:l,z:0},{x:h,y:e,z:0},{x:f,y:e,z:0}]);m=m([{x:f,y:e,z:k},{x:h,y:e,z:k},{x:h,y:l,z:k},{x:f,y:l,z:k}]);var B=!1,v=!1,w=!1,A=!1;[].concat(c.xAxis,c.yAxis,c.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?v=!0:B=!0:a.opposite?A=!0:w=!0)});var y=function(a,c,b){for(var f=["size","color","visible"],d={},g=0;g<f.length;g++)for(var e=f[g],h=0;h<a.length;h++)if("object"===typeof a[h]){var k=a[h][e];if("undefined"!==typeof k&&null!==k){d[e]=
k;break}}a=b;!0===d.visible||!1===d.visible?a=d.visible:"auto"===d.visible&&(a=0<c);return{size:p(d.size,1),color:p(d.color,"none"),frontFacing:0<c,visible:a}};a={axes:{},bottom:y([a.bottom,a.top,a],g,B),top:y([a.top,a.bottom,a],q,v),left:y([a.left,a.right,a.side,a],t,w),right:y([a.right,a.left,a.side,a],r,A),back:y([a.back,a.front,a],m,!0),front:y([a.front,a.back,a],u,!1)};"auto"===b.axisLabelPosition?(r=function(a,c){return a.visible!==c.visible||a.visible&&c.visible&&a.frontFacing!==c.frontFacing},
b=[],r(a.left,a.front)&&b.push({y:(e+l)/2,x:f,z:0,xDir:{x:1,y:0,z:0}}),r(a.left,a.back)&&b.push({y:(e+l)/2,x:f,z:k,xDir:{x:0,y:0,z:-1}}),r(a.right,a.front)&&b.push({y:(e+l)/2,x:h,z:0,xDir:{x:0,y:0,z:1}}),r(a.right,a.back)&&b.push({y:(e+l)/2,x:h,z:k,xDir:{x:-1,y:0,z:0}}),g=[],r(a.bottom,a.front)&&g.push({x:(f+h)/2,y:l,z:0,xDir:{x:1,y:0,z:0}}),r(a.bottom,a.back)&&g.push({x:(f+h)/2,y:l,z:k,xDir:{x:-1,y:0,z:0}}),q=[],r(a.top,a.front)&&q.push({x:(f+h)/2,y:e,z:0,xDir:{x:1,y:0,z:0}}),r(a.top,a.back)&&q.push({x:(f+
h)/2,y:e,z:k,xDir:{x:-1,y:0,z:0}}),t=[],r(a.bottom,a.left)&&t.push({z:(0+k)/2,y:l,x:f,xDir:{x:0,y:0,z:-1}}),r(a.bottom,a.right)&&t.push({z:(0+k)/2,y:l,x:h,xDir:{x:0,y:0,z:1}}),l=[],r(a.top,a.left)&&l.push({z:(0+k)/2,y:e,x:f,xDir:{x:0,y:0,z:-1}}),r(a.top,a.right)&&l.push({z:(0+k)/2,y:e,x:h,xDir:{x:0,y:0,z:1}}),f=function(a,b,f){if(0===a.length)return null;if(1===a.length)return a[0];for(var d=0,g=x(a,c,!1),e=1;e<g.length;e++)f*g[e][b]>f*g[d][b]?d=e:f*g[e][b]===f*g[d][b]&&g[e].z<g[d].z&&(d=e);return a[d]},
a.axes={y:{left:f(b,"x",-1),right:f(b,"x",1)},x:{top:f(q,"y",-1),bottom:f(g,"y",1)},z:{top:f(l,"y",-1),bottom:f(t,"y",1)}}):a.axes={y:{left:{x:f,z:0,xDir:{x:1,y:0,z:0}},right:{x:h,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:e,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:l,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:w?h:f,y:e,xDir:w?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:w?h:f,y:l,xDir:w?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return a};A.prototype.matrixSetter=function(){if(1>this.pos&&(q(this.start)||q(this.end))){var c=this.start||
[1,0,0,1,0,0],b=this.end||[1,0,0,1,0,0];var a=[];for(var f=0;6>f;f++)a.push(this.pos*b[f]+(1-this.pos)*c[f])}else a=this.end;this.elem.attr(this.prop,a,null,!0)};u.ZChartComposition.compose(y);e.compose(b);""});C(b,"parts-3d/Series.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,e){var d=e.addEvent,v=e.pick,u=b.perspective;d(b.Series,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});b.Series.prototype.translate3dPoints=function(){var b=this.chart,d=v(this.zAxis,
b.options.zAxis[0]),e=[],q;for(q=0;q<this.data.length;q++){var t=this.data[q];if(d&&d.translate){var p=d.logarithmic&&d.val2lin?d.val2lin(t.z):t.z;t.plotZ=d.translate(p);t.isInside=t.isInside?p>=d.min&&p<=d.max:!1}else t.plotZ=0;t.axisXpos=t.plotX;t.axisYpos=t.plotY;t.axisZpos=t.plotZ;e.push({x:t.plotX,y:t.plotY,z:t.plotZ})}b=u(e,b,!0);for(q=0;q<this.data.length;q++)t=this.data[q],d=b[q],t.plotX=d.x,t.plotY=d.y,t.plotZ=d.z}});C(b,"parts-3d/Column.js",[b["parts/Globals.js"],b["parts/Utilities.js"],
b["parts/Stacking.js"]],function(b,e,d){function v(b){var d=b.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(d.stroke=this.options.edgeColor||d.fill,d["stroke-width"]=A(this.options.edgeWidth,1));return d}function u(b,d,c){var e=this.chart.is3d&&this.chart.is3d();e&&(this.options.inactiveOtherPoints=!0);b.call(this,d,c);e&&(this.options.inactiveOtherPoints=!1)}function w(b){for(var d=[],c=1;c<arguments.length;c++)d[c-1]=arguments[c];return this.series.chart.is3d()?this.graphic&&
"g"!==this.graphic.element.nodeName:b.apply(this,d)}var m=e.addEvent,A=e.pick;e=e.wrap;var q=b.perspective,t=b.Series,p=b.seriesTypes,y=b.svg;e(p.column.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});e(b.Series.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,1))});p.column.prototype.translate3dPoints=function(){};p.column.prototype.translate3dShapes=function(){var b=
this,d=b.chart,c=b.options,e=c.depth,a=(c.stacking?c.stack||0:b.index)*(e+(c.groupZPadding||1)),f=b.borderWidth%2?.5:0,h;d.inverted&&!b.yAxis.reversed&&(f*=-1);!1!==c.grouping&&(a=0);a+=c.groupZPadding||1;b.data.forEach(function(c){c.outside3dPlot=null;if(null!==c.y){var l=c.shapeArgs,k=c.tooltipPos,n;[["x","width"],["y","height"]].forEach(function(a){n=l[a[0]]-f;0>n&&(l[a[1]]+=l[a[0]]+f,l[a[0]]=-f,n=0);n+l[a[1]]>b[a[0]+"Axis"].len&&0!==l[a[1]]&&(l[a[1]]=b[a[0]+"Axis"].len-l[a[0]]);if(0!==l[a[1]]&&
(l[a[0]]>=b[a[0]+"Axis"].len||l[a[0]]+l[a[1]]<=f)){for(var d in l)l[d]=0;c.outside3dPlot=!0}});"rect"===c.shapeType&&(c.shapeType="cuboid");l.z=a;l.depth=e;l.insidePlotArea=!0;h={x:l.x+l.width/2,y:l.y,z:a+e/2};d.inverted&&(h.x=l.height,h.y=c.clientX);c.plot3d=q([h],d,!0,!1)[0];k=q([{x:k[0],y:k[1],z:a+e/2}],d,!0,!1)[0];c.tooltipPos=[k.x,k.y]}});b.z=a};e(p.column.prototype,"animate",function(b){if(this.chart.is3d()){var d=arguments[1],c=this.yAxis,e=this,a=this.yAxis.reversed;y&&(d?e.data.forEach(function(b){null!==
b.y&&(b.height=b.shapeArgs.height,b.shapey=b.shapeArgs.y,b.shapeArgs.height=1,a||(b.shapeArgs.y=b.stackY?b.plotY+c.translate(b.stackY):b.plotY+(b.negative?-b.height:b.height)))}):(e.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,e.options.animation))}),this.drawDataLabels()))}else b.apply(this,[].slice.call(arguments,1))});e(p.column.prototype,"plotGroup",function(b,d,c,e,a,f){"dataLabelsGroup"!==d&&this.chart.is3d()&&
(this[d]&&delete this[d],f&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(f)),this[d]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[d].survive=!0,"group"===d||"markerGroup"===d))&&(arguments[3]="visible");return b.apply(this,Array.prototype.slice.call(arguments,1))});e(p.column.prototype,"setVisible",function(b,d){var c=this,e;c.chart.is3d()&&c.data.forEach(function(a){e=(a.visible=a.options.visible=d="undefined"===typeof d?
!A(c.visible,a.visible):d)?"visible":"hidden";c.options.data[c.data.indexOf(a)]=a.options;a.graphic&&a.graphic.attr({visibility:e})});b.apply(this,Array.prototype.slice.call(arguments,1))});p.column.prototype.handle3dGrouping=!0;m(t,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,d=b.grouping,c=b.stacking,e=A(this.yAxis.options.reversedStacks,!0),a=0;if("undefined"===typeof d||d){d=this.chart.retrieveStacks(c);a=b.stack||0;for(c=0;c<d[a].series.length&&d[a].series[c]!==
this;c++);a=10*(d.totalStacks-d[a].position)+(e?c:-c);this.xAxis.reversed||(a=10*d.totalStacks-a)}b.depth=b.depth||25;this.z=this.z||0;b.zIndex=a}});e(p.column.prototype,"pointAttribs",v);e(p.column.prototype,"setState",u);e(p.column.prototype.pointClass.prototype,"hasNewShapeType",w);p.columnrange&&(e(p.columnrange.prototype,"pointAttribs",v),e(p.columnrange.prototype,"setState",u),e(p.columnrange.prototype.pointClass.prototype,"hasNewShapeType",w),p.columnrange.prototype.plotGroup=p.column.prototype.plotGroup,
p.columnrange.prototype.setVisible=p.column.prototype.setVisible);e(t.prototype,"alignDataLabel",function(b,d,c,e,a){var f=this.chart;e.outside3dPlot=d.outside3dPlot;if(f.is3d()&&this.is("column")){var h=this.options,m=A(e.inside,!!this.options.stacking),l=f.options.chart.options3d,k=d.pointWidth/2||0;h={x:a.x+k,y:a.y,z:this.z+h.depth/2};f.inverted&&(m&&(a.width=0,h.x+=d.shapeArgs.height/2),90<=l.alpha&&270>=l.alpha&&(h.y+=d.shapeArgs.width));h=q([h],f,!0,!1)[0];a.x=h.x-k;a.y=d.outside3dPlot?-9E9:
h.y}b.apply(this,[].slice.call(arguments,1))});e(d.prototype,"getStackBox",function(b,d,c,e,a,f,h,m){var l=b.apply(this,[].slice.call(arguments,1));if(d.is3d()&&c.base){var k=+c.base.split(",")[0],n=d.series[k];k=d.options.chart.options3d;n&&n instanceof p.column&&(n={x:l.x+(d.inverted?h:f/2),y:l.y,z:n.options.depth/2},d.inverted&&(l.width=0,90<=k.alpha&&270>=k.alpha&&(n.y+=f)),n=q([n],d,!0,!1)[0],l.x=n.x-f/2,l.y=n.y)}return l})});C(b,"parts-3d/Pie.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],
function(b,e){var d=e.pick;e=e.wrap;var v=b.deg2rad,u=b.seriesTypes,w=b.svg;e(u.pie.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var d=this,e=d.options,m=e.depth||0,p=d.chart.options.chart.options3d,u=p.alpha,w=p.beta,B=e.stacking?(e.stack||0)*m:d._i*m;B+=m/2;!1!==e.grouping&&(B=0);d.data.forEach(function(b){var c=b.shapeArgs;b.shapeType="arc3d";c.z=B;c.depth=.75*m;c.alpha=u;c.beta=w;c.center=d.center;c=(c.end+c.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(c)*
e.slicedOffset*Math.cos(u*v)),translateY:Math.round(Math.sin(c)*e.slicedOffset*Math.cos(u*v))}})}});e(u.pie.prototype.pointClass.prototype,"haloPath",function(b){var d=arguments;return this.series.chart.is3d()?[]:b.call(this,d[1])});e(u.pie.prototype,"pointAttribs",function(b,e,q){b=b.call(this,e,q);q=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=q.edgeColor||e.color||this.color,b["stroke-width"]=d(q.edgeWidth,1));return b});e(u.pie.prototype,"drawDataLabels",function(b){if(this.chart.is3d()){var d=
this.chart.options.chart.options3d;this.data.forEach(function(b){var e=b.shapeArgs,m=e.r,q=(e.start+e.end)/2;b=b.labelPosition;var u=b.connectorPosition,w=-m*(1-Math.cos((e.alpha||d.alpha)*v))*Math.sin(q),c=m*(Math.cos((e.beta||d.beta)*v)-1)*Math.cos(q);[b.natural,u.breakAt,u.touchingSliceAt].forEach(function(b){b.x+=c;b.y+=w})})}b.apply(this,[].slice.call(arguments,1))});e(u.pie.prototype,"addPoint",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,
!0)});e(u.pie.prototype,"animate",function(b){if(this.chart.is3d()){var e=arguments[1],m=this.options.animation,u=this.center,p=this.group,v=this.markerGroup;w&&(!0===m&&(m={}),e?(p.oldtranslateX=d(p.oldtranslateX,p.translateX),p.oldtranslateY=d(p.oldtranslateY,p.translateY),e={translateX:u[0],translateY:u[1],scaleX:.001,scaleY:.001},p.attr(e),v&&(v.attrSetters=p.attrSetters,v.attr(e))):(e={translateX:p.oldtranslateX,translateY:p.oldtranslateY,scaleX:1,scaleY:1},p.animate(e,m),v&&v.animate(e,m)))}else b.apply(this,
[].slice.call(arguments,1))})});C(b,"parts-3d/Scatter.js",[b["parts/Globals.js"],b["parts/Point.js"],b["parts/Utilities.js"]],function(b,e,d){d=d.seriesType;var v=b.seriesTypes;d("scatter3d","scatter",{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}},{pointAttribs:function(d){var e=v.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&d&&(e.zIndex=b.pointCameraDistance(d,this.chart));return e},axisTypes:["xAxis","yAxis","zAxis"],
pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],directTouch:!0},{applyOptions:function(){e.prototype.applyOptions.apply(this,arguments);"undefined"===typeof this.z&&(this.z=0);return this}});""});C(b,"parts-3d/VMLAxis3D.js",[b["parts/Utilities.js"]],function(b){var e=b.addEvent,d=function(){return function(b){this.axis=b}}();return function(){function b(){}b.compose=function(d){d.keepProps.push("vml");e(d,"init",b.onInit);e(d,"render",b.onRender)};b.onInit=function(){this.vml||(this.vml=
new d(this))};b.onRender=function(){var b=this.vml;b.sideFrame&&(b.sideFrame.css({zIndex:0}),b.sideFrame.front.attr({fill:b.sideFrame.color}));b.bottomFrame&&(b.bottomFrame.css({zIndex:1}),b.bottomFrame.front.attr({fill:b.bottomFrame.color}));b.backFrame&&(b.backFrame.css({zIndex:0}),b.backFrame.front.attr({fill:b.backFrame.color}))};return b}()});C(b,"parts-3d/VMLRenderer.js",[b["parts/Axis.js"],b["parts/Globals.js"],b["parts/SVGRenderer.js"],b["parts-3d/VMLAxis3D.js"]],function(b,e,d,v){var u=e.VMLRenderer;
u&&(e.setOptions({animate:!1}),u.prototype.face3d=d.prototype.face3d,u.prototype.polyhedron=d.prototype.polyhedron,u.prototype.elements3d=d.prototype.elements3d,u.prototype.element3d=d.prototype.element3d,u.prototype.cuboid=d.prototype.cuboid,u.prototype.cuboidPath=d.prototype.cuboidPath,u.prototype.toLinePath=d.prototype.toLinePath,u.prototype.toLineSegments=d.prototype.toLineSegments,u.prototype.arc3d=function(b){b=d.prototype.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b},e.VMLRenderer.prototype.arc3dPath=
d.prototype.arc3dPath,v.compose(b))});C(b,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map